### ISSUE TITLE
"Touching mouse pointer" always returns false when the sprite is hidden

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-vm#1003]
### Expected Behavior

In Scratch 2.0 it returns true if it's over the sprite, even if the sprite is hidden.

To test, add and run these blocks:
![image](https://user-images.githubusercontent.com/13686399/38056608-c02a3ea6-3291-11e8-81fe-7e21df18ff54.png)

Then hide the sprite, mouseover it, and show it again.  It should have moved.

**Comment by thisandagain** [comment]
The problem appears to be that hidden sprites return dimensions of `0,0`.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#284
