### ISSUE TITLE
Change language on "mouse-pointer" blocks

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#1015]
## Overview
Scratch 3.0 will work on a wide variety of devices including Chromebooks, Windows Surface, iPads, and Android tablets. Many of these devices either exclusively support touch or support a mixture of touch and mouse interaction. Because of this, we would like to retire use of the terms "mouse-pointer" and "clicked" and use the more generic terms "pointer" and "tapped". This will impact a large number of blocks, but feels important in order to properly support touch platforms moving forward.

#### Move
- `go to (pointer)`
- `glide (1) secs to (pointer)`
- `point towards (pointer)`

#### Events
- `when this sprite tapped`
- `when stage tapped`

#### Sensing
- `<pointer down?>`
- `(pointer x)`
- `(pointer y)`
- `(distance to (pointer))`

#### Details
- The `(distance to (pointer))` block should be moved down to below the `(pointer y)` block. It's current positioning in the "Sensing" category doesn't make much sense (particularly for a block that isn't used very heavily).

**Comment by Kenny2github** [comment]
Question: What does the "needs-triage" label mean?

**Comment by thisandagain** [comment]
@Kenny2github It means I need to schedule it.

**Comment by ntlrsk** [comment]
@SpeakkVisually this is the issue for tracking the change in block wordings, including **when sprite tapped**

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1472
