### ISSUE TITLE
Say block doesn't run as long as it should

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-vm#1035]
When a Second "say block for x seconds" interrupts a first "say block for y seconds", the second say block only stays on the screen until the first one would have been done.  (seems to inherit the remaining time on screen of the interrupted first say block and ignores its own "for x seconds")

### Steps to Reproduce

Create these blocks (not connected):
![image](https://user-images.githubusercontent.com/13686399/38513292-92ca9bd6-3be2-11e8-86c0-a73edc891fe6.png)

- Click on the "Say hello" block.
- Notice that the cat says "Hello"
- Notice that the "Say hello" block is glowing.
- Click on the "Say goodbye" block (within 4 seconds of clicking on the "say hello" block)
- Notice that the cat says "Goodbye"
- Notice that the "Say goodbye" and "Say hello" blocks are both glowing.
- Wait
- Notice that the speech bubble disappears early, and the "Say goodbye" block is still glowing as though it were running.

### Operating System and Browser

Chrome on linux.

**Comment by paulkaplan** [comment]
Ack yeah the block promise resolves no matter what with clearing the targets bubble. We need to add a flag or something to indicate that the resolve timeout should not clear the bubble if it has been overwritten.
