### ISSUE TITLE
web bluetooth error

### ISSUE THREAD

**Issue by wwj718** [LLK/scratch-vm#1037]
Hi， I make a extension to control BB8（with web bluetooth）

my code in extension:

```
navigator.bluetooth.requestDevice({
    'filters': [{ 'namePrefix': ['BB'] }],
    'optionalServices': [
      serviceA,
      serviceB
    ]
  })
```

## Expected behavior:

I can get the bluetooth device info lists

## Actual behavior:

The following message is dumped:

`DOMException: Must be handling a user gesture to show a permission request.`

I notice that the extension thread is a worker.   I don't konw if it has the permission to use  web bluetooth
 
when I copy the code and run it on the console，it is ok

**Comment by wwj718** [comment]
I solve it

must use a button to run the code

**Comment by xiaolongchengithub** [comment]
connectBluetooth () {
        try {
            navigator.bluetooth.requestDevice({
                filters: [{ namePrefix: "BBC micro:bit" }],
                optionalServices: [UART_SERVICE_UUID]
                }).connect();

            return "success"
        } catch (e) {
          return 'eroor!';
        }

      }

      pair(){
        this.server =  this.uBitDevice.gatt.connect();
      }


hello ,can you help me. i can find the devices.but can not connect(). 
it report:
index.js:207 Uncaught TypeError: Cannot read property 'connect' of undefined
    at BalanceCar.pair (index.js:207)
    at Scratch3BalanceCarBlocks.move (index.js:623)
    at execute (execute.js:492).

thanks
