### ISSUE TITLE
Broadcast shadow import issue

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#1044]
This bug is best described with it's repro.

1) In Scratch 2.0, create a new project
2) Drag out a broadcast block
3) Plug something into the broadcast block and unplug it so that it creates an empty string message name
4) Plug something back into the broadcast block
5) Make sure this project is saved and import it into 3.0
6) Unplug the input from the broadcast block
7) Observe that the field reads `i` but it should read `message1`

This is an issue with sb2 import, and creates a problem with save and load because a variable is not created for the underlying broadcast shadow until the shadow is obscured. So if we saved the project before step 6 above, the project would not be able to load.

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-vm/pull/1045
