### ISSUE TITLE
There has an error in package.json,I hava solve it,you should fix it。

### ISSUE THREAD

**Issue by kickTec** [LLK/scratch-vm#1048]
ajv-keywords@1.5.1 requires a peer of ajv@>=4.10.0,but [scratch-vm\node_modules\scratch-parser\package.json] set it to "ajv": "4.7.0"。

**Comment by thisandagain** [comment]
Please use the issue template when creating an issue. There is not enough information in this issue to understand your issue, question, and/or suggestion.
