### ISSUE TITLE
Adjust wording on "go to" Looks block to avoid confusion with "go to" Motion blocks

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-vm#1051]
The revised "go to front" block in Looks has a pull-down menu with the options:
go to [front/back] 
This may lead to confusion between the **go to** Motion blocks.

Suggestion to change to:
**go to [front | back] layer**

![image](https://user-images.githubusercontent.com/4721032/38700605-a23c8d84-3e69-11e8-8695-11b910c737ec.png)

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1450
