### ISSUE TITLE
Some stacks unexpectedly run way too fast. Should more blocks yield?

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1063]
### Expected Behavior

Generally, a forever loop is expected to repeat at 30fps, unless we're in turbo mode or a custom block with "run without screen refresh".

### Actual Behavior

Some stacks, like the one shown below, can run tens of thousands of times per second, which feels unexpected (during the recording, I'm just tapping the space bar once). This is because this stack contains no blocks that trigger a yield due to a screen refresh:

![counting-too-fast](https://user-images.githubusercontent.com/567844/38754064-63f09000-3f2e-11e8-8841-0bf8fdaf450d.gif)

The same loop with a "change pitch effect" block in it unexpectedly updates the pitch ridiculously fast.

We should consider making more blocks yield. My guess is that all motion and looks block currently cause a yield. Perhaps the only change needed is to make the sound effect and volume blocks also trigger a yield.

**Comment by mrjacobbloom** [comment]
I believe this matches 2.0:
![turbo](https://user-images.githubusercontent.com/2879020/38757206-65589140-3f29-11e8-8ef8-283352e9a096.gif)

see this forum post that talks about this: https://scratch.mit.edu/discuss/topic/249719/?page=1#post-2559693 (h/t @TheLogFather)

That said, I vote yes on sound-related blocks yielding
