### ISSUE TITLE
"go to [back]" and "go [backward] (1) layers" can cause sprites to go behind the pen layer

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#1066]
### Expected Behavior

- Sprites should never render behind the pen layer

### Actual Behavior

- The "go to [back]" block can cause sprites to go behind the pen layer

### Steps to Reproduce

https://scratch.mit.edu/projects/217041627 (Run in Turbo Mode)
https://llk.github.io/scratch-gui/develop/#217041627 (Run in Turbo Mode)

**Comment by ZenithRogue** [comment]
I didn't realize the bug was already documented here at the time, but [I made an issue showing some possible solutions](https://github.com/LLK/scratch-gui/issues/1809)

**Comment by ZenithRogue** [comment]
(moving this from my duplicate topic)

There are three ways I think this can be resolved:
 
1. You keep the pen canvas behind all sprites

2. You add a block that allows you to move a sprite above or below another. IE: "move above [sprite1]" "move above [pen layer]"

3. You implement a more extensive pen system as detailed [here](https://scratch.mit.edu/discuss/topic/234935/)
