### ISSUE TITLE
"Stop other scripts" does not stop sound 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1068]
### Expected Behavior

In Scratch 2.0, the "stop other scripts in sprite" block stops a sound that is currently playing in another stack (_only_ if it is being played by a "play sound until done" block).

### Actual Behavior

In Scratch 3.0, "stop other scripts in sprite" block does not stop sounds being played in another stack by a "play sound until done" block.

### Steps to Reproduce

Here's an example. Press 1, then press 2. When you press 2, the first sound should stop, but it does not.

![image](https://user-images.githubusercontent.com/567844/39019919-efb25f6e-43f8-11e8-83f1-11750a8ec758.png)

Thanks to an anonymous feedback form contributor for finding this one!

**Comment by Heath123** [comment]
This affects https://scratch.mit.edu/projects/189158317/

**Comment by kchadha** [comment]
Closing because it seems like this issue is fixed now.
