### ISSUE TITLE
Stop other scripts in sprite doesn't stop ask blocks

### ISSUE THREAD

**Issue by 77Tigers** [LLK/scratch-vm#1076]
### Expected Behavior

Like Scratch 2, ask blocks should be stopped by an stop other scripts in sprite block.

### Actual Behavior

Opposite of above

### Steps to Reproduce

Click an ask and wait block, then click a stop other scripts in sprite block.

**Comment by mzgoddard** [comment]
<del>I can't confirm this bug. It seems to work for me.</del>
