### ISSUE TITLE
[win] [make] On windows, commands with slash don't working

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#108]
example:

``` batch
./node_modules/.bin/webpack
```

didn't working because of `/` is not `\`

**Comment by tmickel** [comment]
Hmmm, @thisandagain, any experience with this? I imagine if we switch it to `\`, it would break on OS X/Linux...

**Comment by dekrain** [comment]
It can be generated automatically, easy be replaced with regexp

**Comment by thisandagain** [comment]
@tmickel I've run into this a number of times (particularly at Mozilla). Here is a good overview:
https://gist.github.com/domenic/2790533

TL;DR: We may want to move much of what is in our `Makefile` into `npm` scripts.

**Comment by tmickel** [comment]
@dekrain Feels like this has been resolved by the new script and README updates. Please feel free to reopen if you think this is still a problem!
