### ISSUE TITLE
Inputs not loading

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#109]
When I click any category, "warning" in console apears:

```
blockly_compressed_vertical.js:1045: Ignoring non-existent input SOUND_MENU in block sound_play
```

screen:
![block bug](https://cloud.githubusercontent.com/assets/19158291/17941597/5a38422c-6a34-11e6-874a-d3327bb678d5.png)

**Comment by tmickel** [comment]
I think your copy of scratch-blocks is on the "master" branch (500+ commits behind the "develop" branch). If you go to node_modules/scratch-blocks and `git checkout develop`, you will probably have a better time :)

**Comment by dekrain** [comment]
no, I downloaded `scratch-vm-develop.zip` and I used `npm install`

**Comment by tmickel** [comment]
your copy of scratch-blocks (not scratch-vm) is definitely out of date. I think `npm install` installs master by default (not sure why) @thisandagain

**Comment by tmickel** [comment]
yep - but that was installing master, not develop. your screenshot above is definitely showing an out-of-date copy of scratch-blocks.

I think I fixed it in our `package.json`: https://github.com/LLK/scratch-vm/commit/6d773076c517cd8a29fdea900892f07636bb363f

So you can fix this by either switching branches, or redownload and run `npm install` again.

**Comment by dekrain** [comment]
Yes, It's fine :)
