### ISSUE TITLE
Mouse x,y stops updating after about three seconds on touch device

### ISSUE THREAD

**Issue by Mr-Dave2** [LLK/scratch-vm#1095]
### Expected Behavior

In scratch 2.0 mouse x,y sensing will constantly be updated for touch devices in full screen mode

### Actual Behavior

In Scratch 3.0, the updating of mouse x,y sensing stops after about three seconds. 

### Steps to Reproduce

Please see these projects:

https://llk.github.io/scratch-gui/develop/#218854775
 https://llk.github.io/scratch-gui/develop/#10859244 (a starter program)

### Operating System and Browser

iPad iOS 11.3 safari.

Scratch 3.0
![f464686c-a096-4aee-8641-3ad9fcad01ee](https://user-images.githubusercontent.com/35544966/39365412-b2cdf53c-49f6-11e8-919d-874f226c311b.gif) 

Scratch 2.0
![dc9d90b6-c134-42ee-b9fe-46ab988445a8](https://user-images.githubusercontent.com/35544966/39380985-22d5a7b0-4a26-11e8-9b7f-50123b2e3b79.gif)

**Comment by picklesrus** [comment]
This is working for me on an iPad now. It isn't fast, but the the fish follows my finger for a while.
