### ISSUE TITLE
International keys not detected in key-pressed block

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-vm#1116]
### Expected Behavior

After switching to an international keyboard, pressing keys on that keyboard should be able to be sensed.

### Actual Behavior

Key is not detected.

### Steps to Reproduce
1. Install an international keyboard (I chose French)
2. Program:
<img width="351" alt="screen shot 2018-05-04 at 1 59 19 pm" src="https://user-images.githubusercontent.com/399209/39643739-be834780-4fa3-11e8-9f6c-9cefe5d0a517.png">

3. Enter è from the keyboard (key `7`)
4. Nothing happens

### Operating System and Browser
Seen on Mac 10.13.3 Chrome 66 and Chromebook chromeOS 64

**Comment by thisandagain** [comment]
@ericrosenbaum Do you mind taking a look at this? Perhaps a few edge cases fell through on your last PR?

**Comment by ericrosenbaum** [comment]
I'm guessing this was filed just before my keypress changes landed on develop? I just tested this specific scenario using the è key on the French keyboard and it worked great. @chrisgarrity please confirm.

**Comment by chrisgarrity** [comment]
Did your keypress changes not make it into develop for the smoketest? It was during smoketest that I ran into it.

**Comment by chrisgarrity** [comment]
Looks like the changes just didn't get merged to develop prior to smoketest. International keys work on develop now.
