### ISSUE TITLE
User suggested adding panning to Scratch audio

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-vm#112]
/cc @ericrosenbaum 

Reported via freshdesk no. 54970:

> Dear Scratch Team,
> I would like to suggest something :P If it would be possible, could you maybe add that?
> When you add some sounds/music and those have more sound on the right/left and then you hear those sounds on the right/left.
> If you understand that, can you maybe add that :D

This could be limited to just playback of sounds with panning, but it could also be a customizable effect! : )

**Comment by towerofnix** [comment]
Stereo sound is pretty important to most games today, especially for atmosphere. Combine dynamic panning and volume changing and you'll be able to get some really nice sounds!

**Comment by tmickel** [comment]
We have an experiment for this, tracking in #293.

**Comment by Sigton** [comment]
Awesome! Panning would be a great feature :)

Sigton
