### ISSUE TITLE
(x position) is more precise than in 2.0

### ISSUE THREAD

**Issue by mrjacobbloom** [LLK/scratch-vm#1150]
### Expected Behavior

For perfect compatibility, `(x position)` should round to 8 decimal places

### Actual Behavior

It looks like `(x position)`  is rounding to 16 decimal places

### Steps to Reproduce

https://llk.github.io/scratch-gui/develop/compatibility-testing.html#223591096

This project breaks in 3.0: https://llk.github.io/scratch-gui/develop/#117386152/

### Operating System and Browser

MacOS 10.12.4, Chrome 66.0.3359.139 (64-bit)

**Comment by mrjacobbloom** [comment]
Note: I'm all for more precision in 3.0, but I thought I'd report the incompatibility

**Comment by mrjacobbloom** [comment]
There aren't a lot of great uses for fractional coordinates at all, I can only really think of one: pen transparency. This is less important now that pen colors can have alpha, and would only be useful for challenges like the one above. Either way, I don't think you need more than a digits or two of precision for that.

In fact, in many cases it's probably more confusing than beneficial to have fractional coordinates at all. Consider the following script:
![image](https://user-images.githubusercontent.com/2879020/40154608-589d8fe0-594c-11e8-8490-770d76e2f184.png)
the sprite will head toward the mouse pointer, but once it's reached the mouse the script won't terminate as expected because it's still a fractional distance away.

**Comment by MsBlockCat** [comment]
Maybe something could be mentioned in the help section for the coordinate blocks about using the round block to round the coordinates in the code?

**Comment by apple502j** [comment]
LLK/scratch-gui#1372

Similar problem

**Comment by thisandagain** [comment]
Wow. Great catch. Thanks @mrjacobbloom

**Comment by thisandagain** [comment]
I'm marking this as "help wanted". It should be fairly simple to resolve by looking at the block implementation.

**Comment by mrjacobbloom** [comment]
confirmed the project works correctly in the VM playground! 🙌
