### ISSUE TITLE
Extensions should also allow for icons per block

### ISSUE THREAD

**Issue by vincentbriglia** [LLK/scratch-vm#1152]
### Expected Behavior

Specifying a blockIconURI per block should show a different icon

### Actual Behavior

There is no option to add an icon per block, only currently on the category level

### Steps to Reproduce

Api is missing, this is default behavior at the moment, this is a feature request

### Operating System and Browser

Mac OS 10.13.3, Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by joker314** [comment]
Perhaps this issue should be closed due to PR #1154 being merged. Also to be closed: #1151 (per #1153)
