### ISSUE TITLE
Variable monitors do not import correctly if they are initially hidden

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#1165]
### Expected Behavior

All variable monitors should import in their correct position and mode (normal/large/slider). The example project (after the "show 4-6" button is clicked) should look like this:

![Screenshot of project in 2.0](https://user-images.githubusercontent.com/9948030/40461272-eb8208c4-5ee0-11e8-916b-60864192b4dd.png)

### Actual Behavior

Variable monitors which are hidden when the 2.0 project is saved do not import with their position or mode. When shown (via the palette checkbox or a "show variable" block), they all line up at the top left, the default position for variable monitors, and are in normal-readout mode (with the min/max values for the slider the default 0-100). The example project (again, after "show 4-6" is pressed) looks like this:

![Screenshot of project in 3.0](https://user-images.githubusercontent.com/9948030/40461343-4a2aeabc-5ee1-11e8-900f-0b18e30a7d6a.png)

### Steps to Reproduce

Create a Scratch 2.0 project and place a variable in any position or mode, then hide the variable. Save the project and open it in Scratch 3.0, then show the variable. Note that the variable is in the top left of the stage and the default/normal mode instead of however it was positioned/set.

My example project: https://scratch.mit.edu/projects/225201357/ ([3.0](https://llk.github.io/scratch-gui/develop/#225201357))

Many projects which use variables as part of the user interface are affected by this issue. I stumbled across this issue [here (warning, this project has many assets)](https://scratch.mit.edu/projects/172355986/).

### Operating System and Browser

Issue exists on both Firefox 61.0b7 and Chromium 62.0.3202.89, running Debian (testing).

**Comment by hyperobject** [comment]
Related issue: llk/scratch-gui#2033
