### ISSUE TITLE
Remove list limits

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#1174]
### Expected Behavior
No limits. Scratch 2.0 can have as many as it won't crash.
### Actual Behavior
200,000.
Some projects have more than that, so they will be broken.
### Steps to Reproduce
Add 200,000 things
Add more, but it won't add.
### Operating System and Browser
Windows 10 64bit, Firefox 60.0.1
Windows 7 64bit SP1 HomePremium, Firefox 60.0.1

**Comment by towerofnix** [comment]
See https://github.com/LLK/scratch-vm/pull/1031#issuecomment-379755753:

>@towerofnix That's a good question! In 3.0, we are changing the way we store projects on the server to allow bigger projects. There are currently some projects in 2.0 that have very long lists (some for games, but others just to test the limits of a project's size). We want to continue to support these projects, but given that we'll be able to save and load much bigger projects in the future, we don't want to also allow even bigger lists because this will increase browser memory usage while attempting to run one of these projects (or display a monitor for these lists, or scroll through the blocks flyout, etc.). Ultimately, this would cause more browser crashes, which we want to avoid. We're hoping that a 200k limit is a good balance where most projects that currently use large lists (games, etc.) still run well, but we're not actively giving way to crashing more user's browsers.

(Ping @kchadha)

**Comment by thisandagain** [comment]
This was an explicit decision to avoid issues for users on lower-powered hardware (phones, Raspberry PI, etc.).
