### ISSUE TITLE
Switching to other browser's tabs should not stop

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#1175]
### Expected Behavior
Projects should be running after switching tabs
### Actual Behavior
They stopped
### Steps to Reproduce
1. Open a project (it should not stop itself)
2. Switch browser's tab
### Operating System and Browser
Windows 7 Home Premium 64bit, 
Firefox 60.0.1

**Comment by kyleplo** [comment]
Can't reproduce on Windows 10 Chrome 67

**Comment by Kenny2github** [comment]
Can't reproduce on Windows 10 Chrome 67

**Comment by apple502j** [comment]
seems fixed :smiley_cat:
