### ISSUE TITLE
Add import/export xml like scratch-blocks to playground?

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#118]
It would allow a temporary way to save and load and I don't think it would be too hard to implement seeing as it's based on scratch-blocks and scratch-blocks has one.

**Comment by tmickel** [comment]
Could, although why not wait until we can import/export full projects?

**Comment by TheBrokenRail** [comment]
Just so we could have something temporarily, and I made a pull request adding it (I copied some code from scratch-blocks)

**Comment by tmickel** [comment]
Thanks again @TheBrokenRail for the implementation!
