### ISSUE TITLE
Consider how translate extension lets you select the viewer's language

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1190]
We should consider the wording on the reporter block currently labeled "viewer language." Some other options include:

- "language" (h/t @paulkaplan) 
- "viewer's language" (h/t correct use of possessive apostrophe)
- "user's language" (inspired by the username block, which is the only other thing with a similar behavior)

We should also consider adding the same option as an item in the language menu on the translate block, to make it easier to use (i.e. so you don't have to drop the reporter in). It could go just before or after the "random language" option, if we add that (https://github.com/LLK/scratch-vm/issues/1189).

**Comment by kyleplo** [comment]
What about "current language"?

**Comment by thisandagain** [comment]
From discussion I believe we arrived at simply "language" as to match the "username" reporter.
