### ISSUE TITLE
"Say (nothing)" then "say (something)" does not work in a loop

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#1195]
### Expected Behavior

The final say/think block executed in the tick should determine what text is shown on the screen; in the example script, "Hello!" should show up because it was ran after "say (nothing)".

### Actual Behavior

The speech bubble only shows up once the loop stops.

### Steps to Reproduce

Create a script like this:

![Forever: say (empty input), say (Hello!).](https://user-images.githubusercontent.com/9948030/40923019-18bf59a6-67ea-11e8-8746-fbdc9b942f4b.png)

I noticed this issue while testing [this](https://scratch.mit.edu/projects/116852216/) project, which is supposed to show a help bubble by using "think" when you hover over particular regions of the on-screen scripts.

### Operating System and Browser

Firefox 61.0b10, Debian (testing).

**Comment by adroitwhiz** [comment]
@towerofnix Is this fixed in https://llk.github.io/scratch-gui/develop/?

**Comment by towerofnix** [comment]
@adroitwhiz It does seem to be! Thanks!
