### ISSUE TITLE
should there be a benchmarkMode?

### ISSUE THREAD

**Issue by mzgoddard** [LLK/scratch-vm#1197]
### Expected Behavior

#1184 in effect disables turbo mode for projects that use sound blocks. Instead of going as fast as it can, it goes at the rate the system/VirtualMachine can render frames.

### Actual Behavior

Goes as fast as it can so we can measure block and engine performance.

### Steps to Reproduce

compare http://localhost:8073/playground/index.html#155128646,5000,5000 versus https://llk.github.io/scratch-vm/index.html#155128646,5000,5000

-----

With the intent of sound blocks providing some volume change safety, should we remove projects like 155128646 from the performance suite? Or should we have a for internal use benchmarkMode?

**Comment by mzgoddard** [comment]
I think this would be a good add along with something like `BlockUtility.yieldUntilNextFrame()` to support this feature.

**Comment by mzgoddard** [comment]
Related: #1196

**Comment by rschamp** [comment]
It seems like it could be confusing if we have slightly different running behavior while benchmarking vs normal runs. I think it might be better to adjust the benchmark suite with the behavior of the blocks in each project taken into account.

**Comment by towerofnix** [comment]
Note #1184 uses `return new Promise(r => resolve())` to force a yield, and this miiiiight be broken / related to #688. Something like a `yieldUntilNextFrame` util function like @mzgoddard mentioned would probably help.

**Comment by mzgoddard** [comment]
Thinking on it more I think https://github.com/LLK/scratch-vm/pull/1211 actually solves this issue from a benchmarking perspective. (I don't think this helps #688.) Even if some threads are blocked and run once a tick, they'll still be useful to the benchmark suite because the suite tracks time as well as blocks executed. So projects that can't run 100% of the time can still run for example 20% of the time of its benchmark run and give us useful data.

(Also I found an existing `yieldUntilNextFrame` that the `Sequencer` already supports.)

**Comment by rschamp** [comment]
Closing for #1211
