### ISSUE TITLE
Fix Speech Extension in Safari

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-vm#1202]
For now, I'm only testing browsers on my mac laptop since those are easy
**Chrome Mac**: Okay so far
**Firefox Mac**: Okay so far

**Safari on a mac:** throws this error:
[Info] [react-ga] – "with trackers: undefined" (lib.min.js, line 46451)
[Log] vm (3) (lib.min.js, line 184265)
"warn"
"Primitive rejected promise: "
ReferenceError: Can't find variable: AudioContext
_initializeMicrophone — index.js:549
_initListening — index.js:539
_startListening — index.js:518
(anonymous function) — index.js:734
initializePromise
Promise
(anonymous function) — index.js:730
promiseReactionJob

**Comment by picklesrus** [comment]
Update: works on chrome on Android and on an old Surface running Edge so I think safari is the main problem. 

For Safari, I think I just need to use webkitAudioContext instead of AudioContext so fix should be easy.

Since enough browsers work(!), I'll change the title of the bug and file anything else browser specific that comes up separately.

**Comment by picklesrus** [comment]
Update: While #1215 fixed the js error, safari still doesn't work.  Audio data seems to be all arrays of 0s. Continuing to investigate.

**Comment by picklesrus** [comment]
#1297 will fix the *first* listen and wait block we encounter to not have all 0s. 

For fixing subsequent ones, I'm still weeding through information from https://kaliatech.github.io/web-audio-recording-tests/dist/#/test1 to figure out how to re-initialize the pieces that Safari wants properly.

**Comment by picklesrus** [comment]
After reading the code for the examples in https://kaliatech.github.io/web-audio-recording-tests/dist/#/test1 and the discussions on the bugs on that page, I figured out the main problem here is that I was reusing the mediaStream.  If I call getUserMedia for every listenAndWait block, it works fine in desktop Safari (don't currently have an ipad to test with).  Tab switching is still problematic at times, but that seems to be a larger problem.

Just a note for any future readers.  This Safari thing becomes really frustrating to debug because once you get it into a "stuck" state, you have to restart the browser to "unstick" it. Subsequent code changes go unnoticed until you remember :-/.  

PR coming soon.

**Comment by ericrosenbaum** [comment]
Fixed by https://github.com/LLK/scratch-vm/pull/1467
