### ISSUE TITLE
Use lower-case in text displayed in speech recognition extension blocks

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1219]
### Expected Behavior

Default text displayed on scratch blocks is always lower case. 

### Actual Behavior

Some blocks in the speech recognition extension have upper case letters ("Listen and Wait" and "When I hear").

**Comment by picklesrus** [comment]
I also noticed this when I went to convert the block text to messages.  Will be fixed in #1224.
