### ISSUE TITLE
Speech Extension: Pick default text for When I hear block

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-vm#1223]
This is currently set to "cat".  What should it be?

**Comment by thisandagain** [comment]
From discussion: use "let's go" as the default text

**Comment by kyleplo** [comment]
What about "Scratch on!"?

**Comment by towerofnix** [comment]
@kyleplo "Scratch on" is usually something people say at the end of whatever they're writing, like a goodbye, as far as I've seen. But "let's go" (as @thisandagain mentioned) really means to start doing something, which I think makes sense for this.

**Comment by kyleplo** [comment]
@towerofnix Good point.

**Comment by picklesrus** [comment]
Fixed in #1224
