### ISSUE TITLE
Add "Create Variable" button to playground

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#123]
It would allow you to name your variable and not create one every time you opened the data tab. It's already in scratch-blocks why isn't it in scratch-vm?

**Comment by dekrain** [comment]
Variables are not yet supported

**Comment by TheBrokenRail** [comment]
I know but the variable blocks and reporter are there. I know there not implemented. I'm just asking why the create one letter name variable on open data tab is there and not the scratch-blocks method of create variable button

**Comment by dekrain** [comment]
Maybe if this done, anybody fix it

**Comment by thisandagain** [comment]
@TheBrokenRail It takes work to implement these things and we simply haven't gotten to this yet. While we appreciate suggestions, please try to have a productive tone and realize that this is a very large project. If you'd like to contribute, please consider sending along a PR.

**Comment by TheBrokenRail** [comment]
I know but it's already on scratch-blocks a dependency for scratch-vm so it's probally easier to add because you just disable the current variable creation system and enable the one on scratch-blocks

**Comment by TheBrokenRail** [comment]
Made a Pull Request! (Again code copied from scratch-blocks)

**Comment by dekrain** [comment]
Pull for clear data category :/
