### ISSUE TITLE
Comments with `<` interrupt project processing

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-vm#1234]
### Expected Behavior

When loading a project that contains comments, the comment should be able to have the `<` character inside of it.

### Actual Behavior

When loading a project that does contain a comment with a `<` character, it appears to stop processing of the project data at that point.

### Steps to Reproduce

Demonstration of comment loaded in project:
https://scratch.mit.edu/projects/229156463/#editor

The same project showing how the project stops loading at the `<`
https://preview.scratch.mit.edu/#229156463

### Operating System and Browser

macOS 10.13.4, Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by kchadha** [comment]
Looks like `<` and possibly `>` need to be escaped in the comment xml being sent to scratch-blocks.
