### ISSUE TITLE
Why isn't Scratch 3.0 going to save to XML?

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#124]
It's Already supported so I don't see a need to use json of something.

**Comment by dekrain** [comment]
2.0 loader not yet merged

**Comment by tmickel** [comment]
Blockly-style XML really only represents one workspace: the blocks for one sprite, for example. We need a format that supports multiple programmable objects (not to mention other metadata, like costumes, sounds, etc.). The 3.0 format may (or may not be) different from the SB2 JSON format, including maybe switching the block format for each sprite to XML. We haven't figured that out yet.
