### ISSUE TITLE
“when this sprite clicked” does not trigger until after the mouse button has been released

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#1249]
### Expected Behavior
The "when this sprite clicked" hat block should trigger on mouse down (as per Scratch 2.0)

### Actual Behavior
The "when this sprite clicked" hat block triggers on mouse up

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/747641/41597371-4b73cd20-739b-11e8-8a3b-1c3a85461eba.png)

### Credit
HT to multiple users in the forums (including Mr-Dave, RaefWorks_Animations, and videogames102) for noticing this and providing repro cases.

**Comment by thisandagain** [comment]
Note: this will be a little hard to address until sprite dragging is disabled in player (project page + fullscreen) mode.

**Comment by fsih** [comment]
@paulkaplan @kchadha can I get help understanding the repro steps? I built the stack of blocks, and it seems to do nothing when I click the sprite in either 2.0 or beta.

**Comment by Mr-Dave2** [comment]
@fsih Are you clicking and holding the mouse down?  My test case is here: [Scratch 2 link](https://scratch.mit.edu/projects/227085207) and [Scratch 3.0 link](https://beta.scratch.mit.edu/#227085207) .  

The post in the forum that mentions problems with actual projects is [here](https://scratch.mit.edu/discuss/topic/299791/?page=157#post-3129081) . 

And [this project](https://beta.scratch.mit.edu/compatibility-testing.html#215189208) also has the problem  but you'll have to play the game for a little while until a power-up is dropped by an ant and then you can notice that you can't drag it over to a tower.  And I should mention that this project is also affected by the issue where a sprite cannot sense the mouse pointer until it has executed a move block.

**Comment by fsih** [comment]
@Mr-Dave2 thanks! I see, you have to be in player mode (as opposed to editor mode)
