### ISSUE TITLE
A Way To Broadcast messages to clones WHEN broadcasts are implemented?

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#125]
Maybe You could hopefully add a "When message [message1] is received and am clone" hat block. It would make interacting with clones a lot easier. (I don't think it would be that hard, just instead of the main sprite receiving the message make the clones receive it)

**Comment by tmickel** [comment]
Here is the workaround in 2.0:
<img width="237" alt="screen shot 2016-09-02 at 11 38 55 am" src="https://cloud.githubusercontent.com/assets/120403/18209486/e6e3fef4-7101-11e6-816a-69be9fab1935.png">
Considering it's not many blocks to accomplish this now, I would guess we probably won't be adding this :)
