### ISSUE TITLE
Speech Extension: Replace start/stop recording sounds with visual indicator

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-vm#1250]
Whenever we start executing a listen and wait block, we play a start sound to indicate that the microphone is listening. When listening stops, we play an indicator sound as well. 

Replace this sound with a visual indicator.

**Comment by kyleplo** [comment]
What about a little microphone icon next to the green flag?

**Comment by ericrosenbaum** [comment]
Closed by https://github.com/LLK/scratch-gui/pull/3205
