### ISSUE TITLE
Project loaders: SB/1.4

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#128]
We need to support the 1.4 format. Possibly even 1.4-formatted data could come from the website? But especially for any offline scenario.

**Comment by tmickel** [comment]
Reference:

https://github.com/LLK/scratch-flash/blob/5cff62b909856b7d7b3d116a5dcc2b4f03de8482/src/util/ObjReader.as

**Comment by tmickel** [comment]
This, too:
https://github.com/LLK/scratch-flash/blob/5cff62b909856b7d7b3d116a5dcc2b4f03de8482/src/util/OldProjectReader.as

**Comment by TheBrokenRail** [comment]
I found a javascript GitHub project that might help https://github.com/trumank/sb.js

**Comment by TheBrokenRail** [comment]
And from what I see with this library the names are pretty much the same as 2.0 so I think if the licence is compatible if it is detected as a 1.4 file you could use this library and give parseScratchObject the stage object of the return value

**Comment by towerofnix** [comment]
This is definitely an important feature - why was this issue closed? I don't see any other issue (more recent or otherwise) for the general implementation of parsing 1.4 `sb` files.

**Comment by rschamp** [comment]
Good catch @towerofnix — we had closed it because it was being tracked here https://github.com/LLK/scratch-gui/issues/972, but this is the original issue.  We're implementing 1.4 imports imminently.
