### ISSUE TITLE
EV3 Extension: have motor position reporter block only return 0-360?

### ISSUE THREAD

**Issue by evhan55** [LLK/scratch-vm#1287]
Right now, the block reports - (high number) to + (high number)

**Comment by evhan55** [comment]
Done

**Comment by nekketsuuu** [comment]
@evhan55 Hello! Would you explain why this design is adopted? I think this feature makes it harder to implement "turn motor [A] by [some] degrees/rotations" block on Scratch.

**Comment by evhan55** [comment]
Hi!  Oh hmm, how does it make it harder?

**Comment by nekketsuuu** [comment]
Thanks for your quick reply! I'm thinking this kind of implementation (which contains some bugs).

![default](https://user-images.githubusercontent.com/4374702/43643206-77ae0200-9765-11e8-9586-a2f2b2f006fb.PNG)

But this fails because `motor [A] position` is from 0 to 360.

**Comment by evhan55** [comment]
Hi, Oh I think I see it.  The design was adopted when taking into consideration the simplicity of the numbers and ranges for younger users to think about.  I think that for your implementation, you might have to adapt to the `0-360` range if you can.

**Comment by nekketsuuu** [comment]
Nice. I agree with the design choice :) Then, is there a plan to implement a extension block of "Motor [A] turn this way by [some] degrees" or "Motor [A] turn this way by [some] rotations"? LEGO EV3 Software has them as fundamental blocks, and I think they are used many times. If it's OK to add these blocks, I can write an issue or a PR.

**Comment by nekketsuuu** [comment]
@evhan55 I'm sorry for starting a new discussion in this closed issue. I opened a new issue above, so let's continue the discussion there.
