### ISSUE TITLE
EV3 extension: Refactor

### ISSUE THREAD

**Issue by evhan55** [LLK/scratch-vm#1292]
Needs re-factoring to clean up enums, static vars, and generation of command byte-codes.

**Comment by ericrosenbaum** [comment]
Just a note for the cleanup: @chrisgarrity noticed that there is a copy-paste error. not a functional problem, just a misnamed block arg [here](https://github.com/LLK/scratch-vm/blob/f9814a5f884df836da4da8f249a27e5ea9861460/src/extensions/scratch3_ev3/index.js#L970-L983) and [here](https://github.com/LLK/scratch-vm/blob/f9814a5f884df836da4da8f249a27e5ea9861460/src/extensions/scratch3_ev3/index.js#L1151).

**Comment by evhan55** [comment]
@ericrosenbaum @chrisgarrity thanks for the catch!
