### ISSUE TITLE
What should happen when a local variable is shared with the stage?

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#1304]
Users can share blocks between sprites or between sprites and the stage. If the set of blocks being shared from a sprite to a stage contain a reference to a local variable on the sprite, what should happen? Below are some possible options discussing the response to the following scenario.

Scenario:
1. Create a project with a sprite `Sprite1`
2. Create a local variable `foo` on `Sprite1`
3. Drag a `change [foo] by 1` block onto `Sprite1`'s workspace.
4. Create a new sprite `Sprite2`
5. Create a local variable `foo` on `Sprite2`
6. Drag a `change [foo] by 1` block onto `Sprite2`'s workspace.
7. Share the `change [foo] by 1` block from `Sprite1`'s workspace to the stage.
8. Share the `change [foo] by 1` block from `Sprite2`'s workspace to the stage.
9. Repeat steps 7 and 8.

#### Option # 1 - Local variable gets renamed on the stage  (creating a new global variable with a name that does not conflict with any local variables); local vars of the same name from the same sprites get the same name, local vars of the same name from a different sprite get a different name.

In this option, two global variables are created. One is created by step 7 and one is created by step 8. These global variables have new names: `Stage: foo` and `Stage: foo2` respectively. `Sprite1` and `Sprite2` still have their own local variables named `foo`.

Step 9 does not create any more new variables, instead we have one more `change [...] by 1` block for each of the new variables.

#### Option # 2 - Local variable gets renamed on the stage (creating a new global variable with a name that does not conflict with any local variables); all local variables of the same name (regardless of the sprite sharing them) get mapped to the same new global variable.

In this option, one new global variable is created: `Stage: foo`. After step 9 in the scenario, the stage has four `change [Stage: foo] by 1` blocks. `Sprite1` and `Sprite2` still have their own local variables named `foo`.

#### Option # 4 - Local variables are converted to global variables.

In this option, step 7 of the scenario converts the `foo` variable on both `Sprite1` and `Sprite2` to a global variable. The global variable's value is set to 0. No local variables named `foo` exist anymore and any blocks referencing them are converted to use the new global variable.

#### Additional Notes on the Options Above
- Option # 1 has already been implemented.
- Option # 2 would require a runtime map of original local variable name to new global variable name.

**Comment by kyleplo** [comment]
I like option 4 except that the new global variable should take the value of the old local variable.

**Comment by Micircle** [comment]
When copy a local variable by keyboard, this issue is still existing
