### ISSUE TITLE
Why is there no Micro:bit "button [] pressed?" block

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#1308]
### Expected Behavior

There should be a "button [a/b/any] pressed?" block for micro:bit.

### Actual Behavior

There isn't one.

### Steps to Reproduce

Look at the blocks of the micro:bit extension.

### Operating System and Browser

All.

---
Moved from LLK/scratch-blocks#1632
/cc @kyleplo

**Comment by evhan55** [comment]
@ericrosenbaum @khanning Was there a design decision that left this out for any reason?

**Comment by khanning** [comment]
This block is added in PR #1314
