### ISSUE TITLE
Project won't load: Error: Cannot create monitor for target...

### ISSUE THREAD

**Issue by gnarf** [LLK/scratch-vm#1322]
http://llk.github.io/scratch-vm/index.html#187694931

### Expected Behavior

Project loads and runs

### Actual Behavior

http://llk.github.io/scratch-vm/index.html#187694931 which is used in the vm benchmark suite will not longer load / execute due to this monitor error:

```
sb2.js:262 Uncaught (in promise) Error: Cannot create monitor for target that cannot be found by name
    at parseMonitorObject (sb2.js:262)
    at sb2.js:648
```

### Steps to Reproduce

Load the URL, look at console

### Operating System and Browser

Mac / Chrome - but probably everywhere.

**Comment by paulkaplan** [comment]
@kchadha Looks like it is because we are renaming the stage object to "Stage" even if it has a different name, which messes with the monitor processing. Should we just let the object retain its name?
