### ISSUE TITLE
EV3 motor reporters sometimes report NaN while motor is moving

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1324]
### Expected Behavior

EV3 motor reporters should not report NaN

### Actual Behavior

If you run a motor using a motor command block, and at the same time you monitor its position, the position is sometimes reported as NaN.

![ev3-motor-nan](https://user-images.githubusercontent.com/567844/42580039-958e42ce-84f7-11e8-8bcb-03ed55024cac.gif)

### Steps to Reproduce

See gif

**Comment by evhan55** [comment]
I think this is fixed
