### ISSUE TITLE
The Stage is a Sprite (It can move and turn) SB2 Importer [FEATURE or BUG]

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#133]
It would be pretty cool as a feature

**Comment by tmickel** [comment]
Not a feature - definitely a missing piece. We're not distinguishing in the code yet between the stage, sprites, and clones, but we need to.

**Comment by TheBrokenRail** [comment]
It would be cool though to allow it to move on the x axis to allow side scrolling, or maybe on y and x just only if when it moves and there's no blank area like it can move until the next move would create white area or black basically not stage visible

**Comment by tmickel** [comment]
Addressed in #149.
