### ISSUE TITLE
Prevent EV3 motor command race condition

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1334]
### Expected Behavior

When you send a sequence of motor commands for the same motor, the newest command should always take effect.

### Actual Behavior

Each motor command starts the motor, stops it in "brake" mode, waits for a short interval, then puts the motor in "coast" mode. If, during the interval between brake and coast, another motor command to the same motor begins, the original coast command is sent shortly after that, and the second motor command does not complete.

For example, this stack (as a baseline) should run the motor for 1 second one way, then 1 second the other way: 

![image](https://user-images.githubusercontent.com/567844/42659618-d1773160-85f6-11e8-8886-f85debf6713d.png)

This stack is logically the same, and should have the same behavior:

![image](https://user-images.githubusercontent.com/567844/42659665-f60fbbbe-85f6-11e8-926a-1288068501c5.png)

Instead, the motor runs for 1 second way, then starts moving the other way but immediately stops.

@paulkaplan suggested that a way to resolve this (inspired by the current implementation of the say bubble blocks, which similarly have to deal with overlapping sequences of commands for single output). Basically, for each motor, we would store the id of the motor command that is currently running. When a motor command starts, it sets a new id. When a motor command runs its ‘deferred’ part (e.g. the coast command that happens at the end), it checks the id of the current motor command, and bails out if it doesn’t match (because a newer command has started).

**Comment by evhan55** [comment]
Another option is to try checking for motor busy flag status

**Comment by ericrosenbaum** [comment]
Resolved by https://github.com/LLK/scratch-vm/pull/1381
