### ISSUE TITLE
microbit, missing option 'A+B' for when button pressed

### ISSUE THREAD

**Issue by fortuik** [LLK/scratch-vm#1336]
### Expected Behavior

'whenButtonPressed' should include an option 'A+B', current ['A', 'B', 'any'].
This will allow current MicroBit guides for MakeCode and Python to be easily adopted for Scratch.

### Actual Behavior

There is no option for 'whenButtonPressed'  'A+B'

### Steps to Reproduce
1. open url https://llk.github.io/scratch-gui/microbit/
2. add extension MicroBit
3. check the options of the 'whenButtonPressed'

### Operating System and Browser

all

**Comment by khanning** [comment]
This can somewhat be achieved with the boolean button block introduced in #1314.

<img width="295" alt="screen shot 2018-07-13 at 8 48 46 am" src="https://user-images.githubusercontent.com/1169507/42692424-a9d0d2aa-8679-11e8-90a7-d964d2e3c155.png">

We should consider adding "both" or "A + B" to the dropdown for the button blocks so the options would be  
`[A, B, any, both]`  
-or-  
`[any, A, B, any, A + B]`  

The problem with "both" is that the block would read "when [both] button pressed"

The other question this would raise is should we include a slight delay to try to isolate a 2 button vs. 1 button press. My sense would be to not introduce a delay and allow the events to overlap to maximize responsiveness.

**Comment by fortuik** [comment]
Hello,
the [A, B, A+B, any] would be the most logical for me.
'Any' is for 'A or B' and I would rather see 'A+B' and 'any' or neither as an option.
If the boolean button block is the way to go then IMHO 'any' should be also removed from the options.

Regarding the responsiveness, the https://llk.github.io/scratch-gui/microbit/ does not have yet the new boolean button block. My feeling says a very slight delay would be required :)

**Comment by ericrosenbaum** [comment]
After discussion, we decided that we should not add the 'A + B' option because we do not have a good way to make a hat block work that detects both buttons being pressed without also triggering the hats for individual buttons. There would be a way to do this a firmware change, using a short time window to detect it, but this would introduce other problems (especially the behavior of the corresponding boolean reporter).
