### ISSUE TITLE
microbit, proposal to add predefined images for the led matrix

### ISSUE THREAD

**Issue by fortuik** [LLK/scratch-vm#1337]
### Expected Behavior

List of predefined images like https://bbcmicrobitmicropython.readthedocs.io/en/latest/tutorials/images.html and MakeCode's ShowIcon for the Microbit LEDs.

### Actual Behavior

No predefined images to choose from in the Scratch MicroBit extension, e.g. displayMatrix has only a predefined heart image.

### Steps to Reproduce
1. open url https://llk.github.io/scratch-gui/microbit/
2. add extension MicroBit
3. check the Display posibilities

### Operating System and Browser

all

**Comment by khanning** [comment]
This is something that's been discussed. One option would be to extend the FieldMatrix to include a carousel of predefined images.

@carljbowman do you have any thoughts?

**Comment by ericrosenbaum** [comment]
After discussion, we decided to close for now. We may revisit this idea in the future.
