### ISSUE TITLE
micro:bit display text block wait until finished

### ISSUE THREAD

**Issue by khanning** [LLK/scratch-vm#1340]
### Expected Behavior

The micro:bit extension `display [Hello!]` block should wait until the text is done printing on the micro:bit display.

The MicroBitDisplay driver has an [event notification](https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitDisplay.cpp#L316) for when the print command has finished so we could easily make the block wait until it's done printing.

On the other hand, it is nice to be able to interrupt the display text block and you can implement your own wait after it.

<img width="140" alt="screen shot 2018-07-13 at 9 42 15 am" src="https://user-images.githubusercontent.com/1169507/42694621-0c7c9734-8681-11e8-9843-469c8d4cbf5b.png">

### Actual Behavior

`display [Hello!]` will wait for 1 second regardless of the input length.

### Steps to Reproduce

1. Load the micro:bit extension
2. Drag out a forever loop and drop in a `display [Hello!]` block
3. Run the loop
4. The display text block executes every seconds, restarting the micro:bit print function.

### Operating System and Browser

all

**Comment by ericrosenbaum** [comment]
@khanning will proceed with this one. It will require a new microbit firmware version, so to maintain backward compatibility, we may need to introduce a new opcode for a new version of this block with the new behavior? Or! Maybe! the VM can actually predict the exact timing of the text scrolling and just yield for that amount of time.

**Comment by khanning** [comment]
Closed with #1599
