### ISSUE TITLE
2.0 projects where variables and lists share a name are not imported correctly

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#1349]
### Expected Behavior

2.0 projects should get imported without errors.

### Actual Behavior

In Scratch 2.0, it is possible to create a project where a variable and a list share a name (e.g. via adding sprites from different projects into the backpack and adding those from the backpack into a new project and sharing the love).

Projects created in this way (e.g. #236537105) do not import correctly, and switching between sprites results in weird behavior with the block toolbox (e.g. new variables named i, j, k, ... popping up, variables missing, etc.).

### Steps to Reproduce

Import #236537105 and switch between sprites.
Observe errors in the console and weird behavior in the data category of the toolbox.

**Comment by kchadha** [comment]
It should be noted that the project mentioned in this issue has two problems:
1) As the issue states, a variable in the project and a list in the project share a name in the same scope (the global scope). While this is okay in Scratch 3.0 projects, this was assumed to not be allowed in Scratch 2.0 projects.
2) This project has an instance of a local variable sharing a name with a global variable and a local list sharing a name with a global list. This is being tracked in #1379

**Comment by picklesrus** [comment]
Resolved in #1586. Note that number 2 in the comment above is being tracked in #1379
