### ISSUE TITLE
EV3 and Microbit: shouldn't send requests if not connected?

### ISSUE THREAD

**Issue by evhan55** [LLK/scratch-vm#1358]
The EV3 and Microbit extensions shouldn't try to send data requests to the devices if they aren't connected.  I thought this was correctly implemented in the Microbit but it seems to be gone now.

Might be good enhancements for both EV3 and Microbit so the console doesn't fill up with vm error statements.

**Comment by ericrosenbaum** [comment]
The change we made for microbit to check if we're connected before sending is [here](https://github.com/LLK/scratch-vm/blob/0776845a94a7fdf11b0fd875a8ac2cad1bf59866/src/extensions/scratch3_microbit/index.js#L246). Maybe this is not working correctly, or makes an incorrect assumption?

**Comment by evhan55** [comment]
Oh!  I see.  Okay, this might be a good check to add to the EV3 extension then.  It looks like it should work there where it is in the Microbit, and maybe also in whatever 'read' functions there may be in both extensions.

**Comment by evhan55** [comment]
I think I may have fixed this in commit https://github.com/LLK/scratch-vm/pull/1354/commits/d3631576e57431eebdf2c8d02c84d001e570e13b

**Comment by thisandagain** [comment]
This was the cause of some crashes we saw from testing over the past couple days. We have made Scratch Link stable when this occurs, but the VM should try to prevent this behavior.
