### ISSUE TITLE
Microbit "button pressed?" block should return true/false

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1364]
### Expected Behavior

The microbit extension's boolean block `A button pressed?` should report true or false.

### Actual Behavior

It reports numbers.

**Comment by ericrosenbaum** [comment]
In a recent test we noticed that when pressing the microbit "B" button repeatedly, the reported value actually changed from 1 to 2, so we should make sure that the fix for this bug handles that situation as well.

**Comment by evhan55** [comment]
Sounds good!

**Comment by evhan55** [comment]
Closed via #1611
