### ISSUE TITLE
Turning micro bit power off doesn't disconnect microbit

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1366]
### Expected Behavior

If you remove power from the micro bit, Scratch should disconnect from it.

### Actual Behavior

It does not disconnect from the microbit and still shows that they are connected.  When you disconnect from the microbit (that is unplugged) in Scratch it throws a console error:

`vm BLESession error: "ws onclose"`

### Steps to Reproduce

Add the micro bit extension to a project
Plug in and connect a micro bit
unplug the microbit
Note: there is no disconnection error of any kind and the microbit looks like it is still connected
Click the connection status dot
Note: it still says the micro bit is connected
Disconnect the microbit
Note: An error appears in the console

### Operating System and Browser

Chrome on Windows

**Comment by BryceLTaylor** [comment]
It seems you get the `vm BLESession error: "ws onclose"` error every time you disconnect the microbit, not only when you turn it off first.

**Comment by ericrosenbaum** [comment]
Fixed by https://github.com/LLK/scratch-vm/pull/1383
