### ISSUE TITLE
Microbit failed to connect and gave error

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1371]
### Expected Behavior

Connecting a microbit should result in a connected micro bit

### Actual Behavior

After clicking connect on a micro bit and waiting for it to load it gave an oops message and an error appeared in the console:

`vm BLESession error: {"code":-32500, "message":"Application Error","data":"failied to enumerate GATT services: Unreachable"}`

### Steps to Reproduce

Add the microbit extension
Connect to a micro bit
Note: it shows an error message in the modal and an error appears int he console

### Operating System and Browser

Chrome on Windows

**Comment by evhan55** [comment]
@BryceLTaylor is this still happening for you?

**Comment by BryceLTaylor** [comment]
I was unable to reproduce this today.  Closing this issue.
