### ISSUE TITLE
Microbit display blocks run very slowly on Windows

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1380]
### Expected Behavior

A stack of display blocks on the microbit should run through at 30fps.

### Actual Behavior

Each block takes about half a second to a second to run.  They don't all run at the same speed.

### Steps to Reproduce

Build this stack:
![screen shot 2018-07-19 at 11 34 30 am](https://user-images.githubusercontent.com/1088291/42953647-e7b372fc-8b48-11e8-8335-1591d0bae370.png)
Run the stack (click the button on the microbit)
Note: It takes a long time for each block to run.

### Operating System and Browser

Chrome on Windows
I don't see this on chrome on mac

**Comment by BryceLTaylor** [comment]
Putting that stack in a forever loop like this:
![screen shot 2018-07-19 at 1 40 33 pm](https://user-images.githubusercontent.com/1088291/42960300-6297cfbc-8b59-11e8-866c-78e817dc37eb.png)
and then running it for 1 second (approximately) and then stopping all, causes the display to animate for an additional ~14 seconds.

Also in the forever it skips frames as it animates and still changes slowly.

**Comment by evhan55** [comment]
@ericrosenbaum should we consider this resolved?

**Comment by evhan55** [comment]
Is this related to rate limiting?

**Comment by evhan55** [comment]
We believe this is resolved
