### ISSUE TITLE
Project #98255879 breaks when not in full screen mode

### ISSUE THREAD

**Issue by RoboErikG** [LLK/scratch-vm#1382]
Sample project that breaks in 3.0 https://preview.scratch.mit.edu/#98255879

After scoring a goal if it's not in fullscreen the game gets stuck and keyboard commands start scrolling the page.

### Expected Behavior

Can score points and keep playing.

Wow, much fun! Win! Sport!

### Actual Behavior

Game stops responding and sprite icons start shaking.

Wow, much fail! Shake! Lose.

### Steps to Reproduce

Open https://preview.scratch.mit.edu/#98255879
Score a goal while playing in the small window (not fullscreen)

### Operating System and Browser

Chrome on Ubuntu

**Comment by BryceLTaylor** [comment]
I can not reproduce this issue.
