### ISSUE TITLE
Speech recognition hats trigger again when you press green flag

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1395]
### Expected Behavior

Pressing the green flag should not cause a "when I hear" block to run.

### Actual Behavior

If the most recent speech recognition result matches what is in a "when I hear" hat, when you press the green flag, it triggers the hat.

![when-i-hear-bug](https://user-images.githubusercontent.com/567844/43222641-a9f23c52-901e-11e8-918f-ea60dc067bc6.gif)

**Comment by picklesrus** [comment]
I'll take this one. We need to reset the text we're looking for in the hat's edge trigger on the green flag event.  We are currently only resetting it at the beginning of a listenAndWait block.
