### ISSUE TITLE
Microbit: Rename "clear display" to go with pen extension

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-vm#1396]
### Expected Behavior

"clear display" block should be renamed "erase display", "erase entire display" or "erase all display" to go with pen extension.

### Actual Behavior

It is named "clear display"

### Steps to Reproduce

Look at the "clear display" microbit block

### Operating System and Browser

All

**Comment by ericrosenbaum** [comment]
After discussion we decided to leave as is (noting my objection that, under normal circumstances you can't "erase" pen)
