### ISSUE TITLE
Duplicating a sprite with local variables should not duplicate variable IDs

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#1403]
### Expected Behavior

No two distinct variables in a given project should have the same ID.

### Actual Behavior

Duplicating a sprite with local variables also duplicates variable IDs. This causes problems with variable monitors, where duplicating `Sprite1` with variable `foo` creates a new sprite `Sprite2` with variable `foo` and the variable block referring to foo in the toolbox is shared by both sprites. E.g. you can only have the monitor for one of the local variables up at any time.

**Comment by picklesrus** [comment]
Resolved by #1434
