### ISSUE TITLE
Stack glow starts after first block in stack finishes

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1404]
### Expected Behavior

The stack glow should turn on when the stack starts, and turn off when the stack finishes.

### Actual Behavior

The stack glow appears to turn on only after the first command block in the stack finishes running.

![stack-glow-bug2](https://user-images.githubusercontent.com/567844/43477845-4439c7ee-94ca-11e8-8c4b-6f9b0ae6aa5c.gif)

The gif shows: 

```
when green flag clicked
glide 1 sec to random position
```

When you click the green flag, the stack runs, and highlights briefly after it finishes. 

The gif also shows:

```
when green flag clicked
glide 1 sec to random position
wait 1 sec
```

When you click the green flag, the glide block runs, and then the stack highlights while the wait block is running.

Note that when you click the stack to run it (instead of clicking the green flag), the highlighting behaves as expected.

**Comment by thisandagain** [comment]
@kchadha Do you mind taking a look at this? Happy to help if you'd like.

/cc @cwillisf @rschamp
