### ISSUE TITLE
Stopping scripts in sprite/clone doesn't stop sounds that are playing "until done"

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-vm#1410]
### Expected Behavior

In Scratch 2.0, stopping the scripts of a sprite/clone will stop a sound that is currently being played by a scripts that's still running a "play sound until done" block.

Note this is also the case for a clone that gets deleted and is currently running a "play sound until done" block (since, in Scratch 2, its scripts get stopped when the clone is deleted).

### Actual Behavior

In Scratch 3.0 the sounds continue playing even though the script running a "play sound until done" block has been terminated (either by "stop other scripts in sprite" or by deleting the clone).

### Steps to Reproduce

Click on a "play sound until done" block (for a sound that lasts several seconds).
While the sound is playing, click on a "stop other scripts in sprite" block.

(Alternatively, have two "when I start as a clone" scripts. One of them starts the long sound playing 'until done', the other waits for a second or so and then deletes the clone. Then create a clone by clicking on a "create clone of myself" block...)

In Scratch 2 the sound will stop playing.
In Scratch 3 it won't stop playing.

### Operating System and Browser

N/A

**Comment by TheLogFather** [comment]
Forgot to reference https://github.com/LLK/scratch-vm/issues/949, which is related (since its resolution led to this happening).

**Comment by BryceLTaylor** [comment]
This can be seen in [this project:](https://llk.github.io/scratch-gui/develop/compatibility-testing.html#238938875)
As well as this one: 228613336

**Comment by Robomandude** [comment]
It should be noted that this issue also affects note blocks from the music extension.
