### ISSUE TITLE
Current block menu imports from sb2 as "year" no matter what

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-vm#1414]
![image](https://user-images.githubusercontent.com/654102/43600568-ee9fbbbe-9658-11e8-9490-811b9ca5d7f8.png)

This is the project I'm importing

[current-menu.sb2.zip](https://github.com/LLK/scratch-vm/files/2254562/current-menu.sb2.zip)

Saw this being discussed here https://scratch.mit.edu/discuss/topic/299791/?page=270#post-3200539

**Comment by paulkaplan** [comment]
Woah, but in a crazy turn, the project actually runs correctly...

**Comment by traincrisis** [comment]
Ow, that is bad bug
