### ISSUE TITLE
Projects with old 1.4 drum block are mangled

### ISSUE THREAD

**Issue by as-com** [LLK/scratch-vm#1424]
### Expected Behavior

This project (and any other project using the old 1.4 drum block) opens without ~~crashing~~ being mangled: https://scratch.mit.edu/projects/115797375/

### Actual Behavior

Scratch ~~crashes~~ makes the blocks disappear:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/3819625/46045277-3c850c00-c0eb-11e8-94af-6a64fca3177e.png">
<img width="653" alt="image" src="https://user-images.githubusercontent.com/3819625/46045284-41e25680-c0eb-11e8-8151-dcf567b5e3c1.png">

Project in picture: https://scratch.mit.edu/projects/76004096/

### Operating System and Browser

~~macOS Mojave 10.14 Beta (18A347e), Safari 12.0 (14606.1.30)~~
macOS High Sierra 10.13.6 (17G2307), Firefox Nightly 64.0a1 (2018-09-25) (64-bit)

Related: #861

**Comment by towerofnix** [comment]
I don't have much experience with that block - IIRC it's exactly equivalent to the other "play drum" block, but has an ordinary number input instead of one with a dropdown? If so, fixing this is as easy as adding an entry to [sb2_specmap.js](https://github.com/LLK/scratch-vm/blob/develop/src/serialization/sb2_specmap.js).

**Comment by as-com** [comment]
They actually make different sounds. There’s another hard coded array of parameters buried somewhere within the old ActionScript codebase for this old block.

**Comment by as-com** [comment]
Since https://github.com/LLK/scratch-vm/pull/1329 was merged, the project now opens without crashing, but the drum block disappears. See the updated issue description...

**Comment by towerofnix** [comment]
Looks like the relevant code is [here](https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/sound/SoundBank.as#L103-L118). It doesn't look too complicated to implement in 3.0. (Edit - specifically, the algorithm is "Is it the play MIDI (1.4) drum block? If so, subtract 35 from the index.") (I'm working on this atm.)

Double edit: oops, yes, [there's a mapping for drums too.](https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/sound/SoundBank.as#L339-L388)

**Comment by towerofnix** [comment]
I created a project to demonstrate some examples of how Scratch 2.0 approximates MIDI sounds: https://scratch.mit.edu/projects/248475643/

**Comment by picklesrus** [comment]
I'm actually still seeing this as a problem with a simple set of blocks
<img width="270" alt="screen shot 2019-01-02 at 10 49 27 am" src="https://user-images.githubusercontent.com/15675877/50599444-2326f500-0e7c-11e9-893e-bdbaae567b95.png">

Attached is the SB1
[testdrum.zip](https://github.com/LLK/scratch-vm/files/2721187/testdrum.zip)

The drum block disappears
