### ISSUE TITLE
Checked local variables will be recreated，after their sprite deleted

### ISSUE THREAD

**Issue by Micircle** [LLK/scratch-vm#1430]
### Expected Behavior

Local variables should be deleted after their sprite deleted

### Actual Behavior

Local variables were recreated.

### Steps to Reproduce

1. Add more than one sprite.
2. Create one or more local variables for a sprite.
3. Keep variables being checked and delete the sprite.
4. Toggle stage and other sprites.
5. Local variables were recreated.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
@BryceLTaylor Can you please attempt a repro?

/cc @kchadha

**Comment by kchadha** [comment]
@ascii, @BryceLTaylor I just submitted a fix for this in #1486 which should have landed on beta on Friday
