### ISSUE TITLE
Loading a project from 2.0 that ever checked the video motion monitor turns on video motion extension

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1433]
### Expected Behavior

If a project doesn't use video motion blocks it should not turn on the video motion extension.

### Actual Behavior

If at any point ever you have checked the video motion sensing block in 2.0 and saved it, then even if you turn off the monitor it will be saved in the project json.  Opening the project in 3.0 then imports the extension and turns on the webcam.

Can be seen in this project: https://scratch.mit.edu/projects/238455324/#editor
As well as these:
50182430
196398611
71789076

### Steps to Reproduce

Create a project in 2.0
Choose Sensing in the category menu
Check the checkbox next to Video Motion for this sprite
Make sure the project is saved
Uncheck the video motion checkbox
Open the project in 3.0
Note: the video motion extension is added and the webcam turns on

### Operating System and Browser

Chrome on Mac

**Comment by LiFaytheGoblin** [comment]
Another one: 216897461

**Comment by ktbee** [comment]
Fixed in #1643

**Comment by fsih** [comment]
Reopening since #1643 was reverted

**Comment by kchadha** [comment]
Fixed with #1688.
