### ISSUE TITLE
"The project file that was selected failed to load"

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#1439]
A project I was working on failed to load.

Here's the project file which fails to open (renamed .zip so that GitHub lets me upload it): [Tilt to Live.zip](https://github.com/LLK/scratch-vm/files/2275280/Tilt.to.Live.zip)

It's based on https://scratch.mit.edu/projects/15933695/ - It's an updated version of that project.

The error I get in the console reads:

```json
{
  "validationError": "Could not parse as a valid SB2 or SB3 project.",
  "sb2Errors": [
    {
      "keyword": "required",
      "dataPath": "",
      "schemaPath": "#/required",
      "params": {
        "missingProperty": "objName"
      },
      "message": "should have required property 'objName'"
    }
  ],
  "sb3Errors": [
    {
      "keyword": "enum",
      "dataPath": ".targets[7].blocks['Abh0i;C4yIjO-LNA4fS*'].mutation.warp",
      "schemaPath": "#/definitions/boolOrBoolString/oneOf/0/enum",
      "params": {
        "allowedValues": [
          "true",
          "false"
        ]
      },
      "message": "should be equal to one of the allowed values"
    },
    {
      "keyword": "type",
      "dataPath": ".targets[7].blocks['Abh0i;C4yIjO-LNA4fS*'].mutation.warp",
      "schemaPath": "#/definitions/boolOrBoolString/oneOf/1/type",
      "params": {
        "type": "boolean"
      },
      "message": "should be boolean"
    },
    {
      "keyword": "oneOf",
      "dataPath": ".targets[7].blocks['Abh0i;C4yIjO-LNA4fS*'].mutation.warp",
      "schemaPath": "#/definitions/boolOrBoolString/oneOf",
      "params": {
        "passingSchemas": null
      },
      "message": "should match exactly one schema in oneOf"
    },
    {
      "keyword": "type",
      "dataPath": ".targets[7].blocks['Abh0i;C4yIjO-LNA4fS*']",
      "schemaPath": "#/definitions/variable_primitive/type",
      "params": {
        "type": "array"
      },
      "message": "should be array"
    },
    {
      "keyword": "type",
      "dataPath": ".targets[7].blocks['Abh0i;C4yIjO-LNA4fS*']",
      "schemaPath": "#/definitions/list_primitive/type",
      "params": {
        "type": "array"
      },
      "message": "should be array"
    },
    {
      "keyword": "oneOf",
      "dataPath": ".targets[7].blocks['Abh0i;C4yIjO-LNA4fS*']",
      "schemaPath": "#/oneOf",
      "params": {
        "passingSchemas": null
      },
      "message": "should match exactly one schema in oneOf"
    },
    {
      "keyword": "oneOf",
      "dataPath": ".targets[7].blocks['Abh0i;C4yIjO-LNA4fS*']",
      "schemaPath": "#/properties/blocks/additionalProperties/oneOf",
      "params": {
        "passingSchemas": null
      },
      "message": "should match exactly one schema in oneOf"
    }
  ]
}
```

This is the latest version of the project which *does* open: 
[untitled-project-8_4_2018-12_12_56 PM.zip](https://github.com/LLK/scratch-vm/files/2275291/untitled-project-8_4_2018-12_12_56.PM.zip)

There are four versions since that which do not open (the latest of which is attached above).

That version does include several updates since importing the 2.0 project.

### Operating System and Browser

Firefox 62.0b15, Debian (testing).

**Comment by towerofnix** [comment]
Looks like all the (SB3) issues are related to a particular procedure call block, "kill scripts". Here's the excerpt from the project.json:

![The JSON code for project.targets[7].blocks['Abh0i;C4yIjO-LNA4fS*']](https://user-images.githubusercontent.com/9948030/43916423-eb83b134-9be3-11e8-9899-cf374037dcbb.png)

**Comment by kchadha** [comment]
@towerofnix, thanks for reporting this issue. I just submitted a PR to fix this issue on scratch-parser. Once that's landed (and the update propagates through scratch-vm to scratch-gui), you should be able to load that project again. As a temporary fix, you might be able to manually patch your project by replacing all the instances of `warp: "null"` with `warp: "false"`
