### ISSUE TITLE
EV3: Set power after turning a motor doesn't change the current motor speed

### ISSUE THREAD

**Issue by nekketsuuu** [LLK/scratch-vm#1448]
### Expected Behavior

The following program rotates a motor at power 50% at first, and then rotates it at power 100%.

![set_speed_after_turn](https://user-images.githubusercontent.com/4374702/44000919-7c49126e-9e63-11e8-8592-1711de04b3b9.png)

### Actual Behavior

That rotates the motor at power 50% to the end.

I know why this happens, but this is counterintuitive, isn't it?

Here is a list of choices I came up:

* Leave them as it is. This behavior is as specified.
* Merge the power block and the turning block (as the EV3 Software does).
* Implicitly execute a turning operation when the power block is executed and the motor is already turning.

### Steps to Reproduce

1. Connect a motor to a EV3
2. Connect the EV3 to a computer by Bluetooth and Scratch Link in <https://beta.scratch.mit.edu/>.
3. Try to change power after turning a motor.

### Operating System and Browser

Windows 10 Home 1803, Google Chrome 68.0.3440.106 (Official build) (64 bit), LEGO MINDSTORMS Education EV3 Core Set
I tested on https://beta.scratch.mit.edu/, on Aug 12, 2018.

**Comment by thisandagain** [comment]
This is actually a bit of confusion / lack of clarity of how the motor and power blocks work using the EV3. Essentially "set power" will only affect subsequent motor commands due to limitations within the EV3's firmware. I'm going to close this, but this is certainly something we will continue to discuss.
