### ISSUE TITLE
You don't die when you fall into pits

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1451]
Many projects use the position of a sprite on the edge of the stage to determine events, such as if you are on the bottom edge, you die.  In 3.0 the position of the sprite when it stops moving (so you don't lose the sprite) is different than it is in 2.0.

For example, in [this project](https://beta.scratch.mit.edu/#236930544):  When the player sprite falls off the edge it stops at y = -181.  In the code the `check edges` function starts with an `if y < -187` block.  In 2.0 the sprite can go below -187 and it works.  By adjusting the numbers you can make it work properly.

3.0 calculates the position that a sprite can go to differently.

This project is another example of this.
56534898

**Comment by kchadha** [comment]
@thisandagain, @BryceLTaylor, and I discussed and investigated this issue.

It looks like there are two problems here,

1) There seems to be some sort of rounding issue with the cat costume when calculating where to stop falling down... Scratch 3.0 is not rounding the y position of the cat, but Scratch 2.0 seems to be.

2) The larger issue seems to be that if the costume of a sprite is very small (regardless of bitmap or vector), there seems to be a larger difference between 2.0 and 3.0 in how far the sprite can fall down. In Scratch 2.0, very small sprites can fall down ~3 coordinate units further than in Scratch 3.0. 

We made this minimal repro project that helps to showcase this difference.
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#246060082

**Comment by ktbee** [comment]
Here is an example project that shows you can successfully fall into pits at -187 `y position` (the user changed the original project to accommodate the bug): https://scratch.mit.edu/projects/279811694/

This is with the fix from https://github.com/LLK/scratch-render/pull/400

**Comment by ktbee** [comment]
Fixed by https://github.com/LLK/scratch-render/pull/400 !
