### ISSUE TITLE
Gradients point in wrong direction in 2.0

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1462]
When loading projects from 2.0 that use gradients in vector drawings, sometimes the gradients are drawn the in the wrong direction.

For example in the project 118805754 ( [3.0 version](https://beta.scratch.mit.edu/#118805754) [2.0 version](https://scratch.mit.edu/projects/118805754/#editor)  [Comparison](https://llk.github.io/scratch-gui/develop/compatibility-testing.html#118805754)  ) if you set the Brush to 4 and then set the direction to the different numbers you'll see that some orientations of the gradient appear more than once.  For example 4 and 6.  Most of them don't match the direction they face in 2.0.

![screen shot 2018-08-13 at 2 14 30 pm](https://user-images.githubusercontent.com/1088291/44059273-d0db2c5c-9f1e-11e8-9b1a-b3f0cadfb80b.png)

![screen shot 2018-08-13 at 5 32 50 pm](https://user-images.githubusercontent.com/1088291/44059317-f3995a5c-9f1e-11e8-9357-f0fb3bcd6db5.png)

![screen shot 2018-08-13 at 5 32 50 pm](https://user-images.githubusercontent.com/1088291/44059317-f3995a5c-9f1e-11e8-9357-f0fb3bcd6db5.png)

This doesn't happen in 2.0.

Other examples of the gradient direction wrong can be found here:
56534898 (Look at the volcano in the opening)
![screen shot 2018-08-13 at 5 36 31 pm](https://user-images.githubusercontent.com/1088291/44059470-80861fae-9f1f-11e8-83a1-89d5e7951f08.png)
139625909 (Look at the sky in the second shot (entering code 202 at the beginning))
![screen shot 2018-08-13 at 5 31 07 pm](https://user-images.githubusercontent.com/1088291/44059247-c071a634-9f1e-11e8-88df-4f98f4f206fd.png)

**Comment by fsih** [comment]
I think I've seen this before in https://github.com/LLK/scratch-render/issues/236

**Comment by thisandagain** [comment]
Thanks @fsih. Tracking in https://github.com/LLK/scratch-render/issues/236
