### ISSUE TITLE
Several projects are missing text when imported into 3.0

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1474]
Text in costumes of some sprites is missing in 3.0

235389000
![screen shot 2018-08-14 at 5 23 26 pm](https://user-images.githubusercontent.com/1088291/44119284-cac8862a-9fe6-11e8-9a09-21bce1d3f371.png)

237991516
![screen shot 2018-08-14 at 5 24 06 pm](https://user-images.githubusercontent.com/1088291/44119303-dde82346-9fe6-11e8-9500-71bbe41ed781.png)

93279933
![screen shot 2018-08-14 at 5 26 02 pm](https://user-images.githubusercontent.com/1088291/44119447-37704470-9fe7-11e8-85ee-f9d661296f1b.png)

**Comment by towerofnix** [comment]
This may have to do with #672 - it looks like these projects were originally created in Scratch 1.4.

**Comment by thisandagain** [comment]
Confirmed. Tracking in https://github.com/LLK/scratch-vm/issues/672
