### ISSUE TITLE
Text in costumes gets cut off sometimes in 3.0

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1477]
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#138935858
![screen shot 2018-08-14 at 5 32 55 pm](https://user-images.githubusercontent.com/1088291/44119766-2577aa96-9fe8-11e8-80ed-d9d3888082a5.png)
The text in the end screen of the animation is cut off where it says "Comment Ideas down below..."

This project:
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#203392290
The first time you load it the word "Time" is cut off on the title screen.  However if you refresh the page it is not cut off.  @rschamp suggested that it might have something to do with caching and not knowing how big the text box needs to be the first time it loads.

First time it loads:
<img width="992" alt="screen shot 2018-08-14 at 11 08 08 pm" src="https://user-images.githubusercontent.com/1088291/44129595-231e6954-a017-11e8-8414-1aeddabc50c3.png">

After reloading it:
<img width="998" alt="screen shot 2018-08-14 at 11 08 27 pm" src="https://user-images.githubusercontent.com/1088291/44129602-2b794e20-a017-11e8-9496-4b675b8bc80c.png">

**Comment by thisandagain** [comment]
This is a pretty common complaint we are seeing in the forums. Flagging for discussion.

**Comment by thisandagain** [comment]
@fsih Would you mind scheduling a meeting for us all to discuss this? It would be nice to get this issue rolling. :-)

**Comment by fsih** [comment]
Possibly related issues
https://github.com/LLK/scratch-paint/issues/434
https://github.com/LLK/scratch-paint/issues/648
https://github.com/LLK/scratch-paint/issues/481

**Comment by fsih** [comment]
Remaining bugs https://github.com/LLK/scratch-paint/issues/481 and https://github.com/LLK/scratch-paint/issues/736 appear to be limited to less common browsers and have been backlogged for now.
