### ISSUE TITLE
Some images are blurry on the stage in 3.0

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1480]
This project
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#226561187
has one sprite with a vector image that is made of a series of squares.  In the paint editor and in Scratch 2.0 the lines are clear, but on the stage in 3.0 they blur together.

![screen shot 2018-08-15 at 1 39 32 pm](https://user-images.githubusercontent.com/1088291/44163265-e6a35a00-a090-11e8-8587-7cebee2facb4.png)

<img width="982" alt="screen shot 2018-08-15 at 9 15 58 am" src="https://user-images.githubusercontent.com/1088291/44149946-e1dc1a36-a06b-11e8-82dd-b72ec29e5a46.png">

Here's an example of a project that uses a bunch of vector squares in a costume where I can blurring:
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#238776718
<img width="984" alt="screen shot 2018-08-15 at 9 24 18 am" src="https://user-images.githubusercontent.com/1088291/44150305-04f0412c-a06d-11e8-8535-d6845c16f568.png">

**Comment by thisandagain** [comment]
@ktbee Let's discuss this one at our next check-in.
