### ISSUE TITLE
Putting a reporter block in another block then reloading workspace causes crash

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1496]
### Expected Behavior

It should be safe to make copies of my mathematicses.

### Actual Behavior

If you nest a reporter inside of another reporter (e.g. using operator blocks), then duplicate it, and switch to the costumes tab and back, it crashes with `Shadow block cannot be a top-level block.`

### Steps to Reproduce

- Drag out a `+` block and nest another `+` block inside it
- Duplicate it
- Switch to costumes tab and back

![shadow-dupl-bug](https://user-images.githubusercontent.com/567844/44281990-8eeb2700-a227-11e8-8616-8ed53725930a.gif)

**Comment by AmazingMech2418** [comment]
I'm pretty sure that would be in scratch-gui or scratch-blocks...

**Comment by AmazingMech2418** [comment]
https://github.com/LLK/scratch-blocks/blob/698af3fcbb5e18a0e32cc2ead7713b77e20c809b/core/xml.js#L467

**Comment by AmazingMech2418** [comment]
It's also not just if it is duplicated. I think the problem is that shadows for the blocks are appearing above the block it is nested into. Even reporters inside of stacks throw the error.

**Comment by ericrosenbaum** [comment]
thanks @amazinigmech2418 - I think you're right that it is not related to duplication, so it's even more severe (i.e. more likely or more frequent). The crash exists on beta. all you have to do is put a reporter into a command block, and switch to costumes and back:

![reporter-crash](https://user-images.githubusercontent.com/567844/44411270-1ee4e580-a534-11e8-948d-fa37a4c79d24.gif)

**Comment by rachel-fenichel** [comment]
Loading the same stack in the vertical playground (create it, export to xml, clear or refresh, import from XML) doesn't have this problem, so I'm guessing there's a fun interaction with how the vm tracks shadow blocks when blockly is ignoring them.

**Comment by kchadha** [comment]
@rachel-fenichel, you're right. The VM is definitely doing something weird with shadow blocks. The XML that's being emitted for a `move (x position) steps` stack has two shadow blocks, one in the right place (consistent with the XML for the same stack in the vertical playground) and one shadow block at the same level as the move steps block... I will file a separate issue for this...
