### ISSUE TITLE
Inconsistent behavior with "touching (mouse-pointer)" block

### ISSUE THREAD

**Issue by amylh** [LLK/scratch-vm#1500]
### Expected Behavior

In the example project below, each of the buttons should 'pop' (i.e. grow to a certain size) when touching the mouse-pointer, and shrink (back to a certain size) otherwise.
See https://scratch.mit.edu/projects/165201011/ for an example.

### Actual Behavior

In 3.0, unless extra blocks are included in the script, the buttons do not react to the mouse-pointer.
In the example, the green buttons are those with the extra blocks, and the red buttons are the ones without.

The "extra blocks" I'm referring to tend to be blocks that update the sprite's position (e.g. set x to [], go to x [] y [], etc.). But most graphics ('Looks') blocks seem to have no effect. (See inside the project for a more extensive list of which blocks work and which don't.)

### Steps to Reproduce

See 2.0 version: https://scratch.mit.edu/projects/165201011/
3.0 preview: https://beta.scratch.mit.edu/#165201011

### Operating System and Browser

Linux Mint 18.1
Mozilla Firefox, Google Chrome

Windows 10
Microsoft Edge, Google Chrome

**Comment by thisandagain** [comment]
@BryceLTaylor Do you mind creating a minimal repro of this?

/cc @kchadha @rschamp

**Comment by BryceLTaylor** [comment]
This appears to be unrelated to clones entirely.  It seems to be a problem only with the touching mouse pointer block, but only if it's on the mouse-pointer option.  I repeated it with just the cat in this project:
https://beta.scratch.mit.edu/#239837384

The green cat has a `move 0 steps` block after it runs and you can mouse over it.  The red cat (which is another sprite) does not. However, if you click the stage the `touching mouse-pointer` block works.  It does not matter whether you click the stage before or after the green flag.

It doesn't appear to be a problem with the forever and if.  Here is an example those working. 
https://beta.scratch.mit.edu/#239838189
 It also uses the `touching [ ]` block but it's touching a sprite
