### ISSUE TITLE
Hacked Block: A variable reporter dropped into a non-droppable block doesn't run like in 2.0

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1520]
In Scratch 2.0 you could drop a variable into a non-droppable block, such as in the list name in the `item _ of [list name]`  and `length of [list name]` blocks.
![hackedblocklengthof2](https://user-images.githubusercontent.com/1088291/44487640-c7727280-a624-11e8-953b-90c1013e01d3.png)
![hackedblockitem_of2](https://user-images.githubusercontent.com/1088291/44489029-5634be80-a628-11e8-9106-92cc280bacf1.png)

In 3.0 these are replaced with `readVariable,[variable name]` in the drop down.  That is also now the name of a list in the project.

![hackedblocklenghthof3](https://user-images.githubusercontent.com/1088291/44487659-ce00ea00-a624-11e8-9a6b-9ad2efb034c8.png)
![hackedblockitemof3](https://user-images.githubusercontent.com/1088291/44489046-5d5bcc80-a628-11e8-861e-cfc3efd0cedb.png)

This can be seen in this project:
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#204009022

They can be found in the Blocks sprite, under the custom procedure called `start`.  (See above screenshots.)

**Comment by BryceLTaylor** [comment]
Thanks to @mr-dave2 for helping track this one down.

**Comment by joker314** [comment]
This might be tracked in #1030

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1030
