### ISSUE TITLE
Two issues with "toggle script": any hat block should activate its stack when clicked

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#153]
- [ ] Scripts that start with edge-activated hats can't currently be started by clicking. This is because the hat is evaluated, and the predicate fails. I think we should just skip the hat block when a user explicitly clicks on a stack starting with an edge-activated hat.
- [ ] "Untoggle" is based on the top-block of the thread, instead of the "script-block" of the thread. If the thread moves onto a different script, this can lead to weird behavior.

**Comment by rschamp** [comment]
For July: clicking hats should run their scripts without evaluating the hat first

**Comment by fsih** [comment]
@tmickel I don't understand what the second check box means, can you give repro steps?

**Comment by tmickel** [comment]
Sure! I don't remember precisely all the weird behavior that happens because of this. But one such repro... Start with this:
<img width="330" alt="screen shot 2017-07-11 at 5 16 43 pm" src="https://user-images.githubusercontent.com/120403/28091096-b92ccc10-665c-11e7-9685-83ae2e0da689.png">
The left forever is running (i.e. cat is spinning).

Drag the left blocks into the right forever. The glow snaps to the outer loop:
<img width="214" alt="screen shot 2017-07-11 at 5 17 37 pm" src="https://user-images.githubusercontent.com/120403/28091121-d5e5ef12-665c-11e7-9280-d46fe8e710e1.png">

Now, click on any block in the stack to untoggle it. Notice that the cat spins twice as fast - i.e., that you spawned a second thread - instead of stopping the stack.

This is basically because the toggle/untoggle for a stack is currently related to the first block that ran in the thread, rather than the first block of the *current* stack of the thread.


I think Scratch 2.0 also has some weird weird behavior with this sort of thing, but I think it should be fundamentally solvable...

**Comment by fsih** [comment]
For the first issue, this seems to be working already. I tried every hat block and the only one that didn't work was "when timer > 10", which must be a different bug, because timer is much greater than 10.

<img width="477" alt="screen shot 2017-07-11 at 17 51 57" src="https://user-images.githubusercontent.com/2855464/28092534-c0c5604a-6661-11e7-8bd0-5d2e7f66cfd0.png">

(So I guess https://github.com/LLK/scratch-blocks/issues/845 was not a dupe)

**Comment by fsih** [comment]
Thanks Tim!

In Scratch 2.0 when you add the outer forever, the inner one stays glowing, and you can toggle the glow on the outer one, so that's cool

**Comment by fsih** [comment]
Moved second issue to its own issue: https://github.com/LLK/scratch-vm/issues/654
This issue is now just about bullet 1.
