### ISSUE TITLE
wedo2 "set motor direction" block sometimes stops the motor

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1538]
### Expected Behavior

The WeDo 2.0 "set motor direction" block should never stop the motor.

### Actual Behavior

Sometimes you can get the extension into a state where the "set motor direction" block stops the motor.

### Steps to Reproduce

Click these three blocks in order:
- turn motor on for 1 sec
- (wait for this block to finish)
- turn motor on
- set motor direction to reverse

The motor will stop (instead of reversing directions)

**Comment by ericrosenbaum** [comment]
I think the problem is that, when the "reverse" block runs, the motor object still has a value set for _pendingTimeoutDelay (which should have been cleared earlier). It tries to calculate the remaining time in the delay, but it ends up being negative, so it stops the motor.

**Comment by evhan55** [comment]
Closed via #1611
