### ISSUE TITLE
Vector text helvetica not appearing

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-vm#1541]
### Expected Behavior

In a 2.0 project (shared 6 Oct 2016, making use of vector editor), there are costumes with numbers in vector format. Most are in helvetica, the nine is in gloria. I would expect any costume to appear in 3.0 the way it appeared in 2.0.

### Actual Behavior

The helvetica numbers don't appear. The gloria number does. The issue #672 also has disappearing text, but for pixel graphics and 1.x projects.

### Steps to Reproduce

124310159

### Operating System and Browser

MacOS, Chrome

**Comment by fsih** [comment]
The numbers 0 through 8 are opening in the bitmap editor

**Comment by LiFaytheGoblin** [comment]
Interesting. In 3.0 they open in the bitmap editor but empty, in 2.0 they open in the vector editor, editable (for me)

**Comment by fsih** [comment]
The costumes are showing in the bitmap editor because the SB2 file has costumes with MD5s that end in .png, which causes us to interpret it as a bitmap.


```
	{
		"costumeName": "four",
		"baseLayerID": 1,
		"baseLayerMD5": "5a209e8d611967ee50a6c39e30b2f3c2.png",
		"bitmapResolution": 1,
		"rotationCenterX": 16,
		"rotationCenterY": 19,
		"text": "4",
		"textRect": [0, 0, 29, 31],
		"textColor": -16777216,
		"fontName": "Apple LiGothic Medium",
		"fontSize": 24,
		"textLayerID": 6,
		"textLayerMD5": "f21f12493cbb8103f3fab54bd7b207cc.png"
	},

```

The issue seems to be the mysterious text layer. In addition to a PNG, the costume defines everything needed to display a text element, which is interpreted in Scratch 2 as a vector costume with text, apparently. @kchadha says we are not doing anything with the text layer information in the sb2.

Oddly, the 9 is stored as an SVG, so it shows up fine
```
	{
		"costumeName": "nine",
		"baseLayerID": 11,
		"baseLayerMD5": "72c6ac9a30f6e098d763b91673a5b664.svg",
		"bitmapResolution": 1,
		"rotationCenterX": 16,
		"rotationCenterY": 27
	},
```

**Comment by fsih** [comment]
We also found a possibly unrelated issue with the IDs changing: https://github.com/LLK/scratch-vm/issues/1713

**Comment by kchadha** [comment]
> Oddly, the 9 is stored as an SVG, so it shows up fine
> 
> ```
> 	{
> 		"costumeName": "nine",
> 		"baseLayerID": 11,
> 		"baseLayerMD5": "72c6ac9a30f6e098d763b91673a5b664.svg",
> 		"bitmapResolution": 1,
> 		"rotationCenterX": 16,
> 		"rotationCenterY": 27
> 	},
> ```

😂😅🤔

**Comment by fsih** [comment]
Maybe whenever sb2 files contain more arguments that we don't parse, we should log that somehow? I wonder if there are other things.

**Comment by thisandagain** [comment]
Next steps are to investigate exactly how 2.0 is interpreting the text layer and make modifications to 3.0 to convert / handle this situation in the same way.

**Comment by towerofnix** [comment]
BTW, this is a duplicate of my old issue #672, which has a lot more information.

**Comment by fsih** [comment]
That's great @towerofnix, thanks for all the info!
