### ISSUE TITLE
Use token bucket style rate limiting in the micro:bit extension

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1547]
We should try replacing the current simple rate limiting approach in the micro:bit extension (while sending, drop other messages) with one based on the token bucket strategy, as we did for the WeDo [here](https://github.com/LLK/scratch-vm/pull/1540).

I expect this to improve the behavior of the LED display blocks, especially when rapidly sending them.

**Comment by thisandagain** [comment]
@ericrosenbaum @evhan55 When did you folks want to give this a go?

**Comment by evhan55** [comment]
@thisandagain : @ericrosenbaum and I did some minor triaging today and decided to go for this in November: https://github.com/LLK/scratch-vm/issues/1508.  Let us know if you prefer us to try earlier!

**Comment by evhan55** [comment]
This is duplicated here: https://github.com/LLK/scratch-vm/issues/1508
