### ISSUE TITLE
How can i get a png from the canvas

### ISSUE THREAD

**Issue by iburning** [LLK/scratch-vm#1553]
### Expected Behavior

I want to get the blob by using canvas.toBlob()

### Actual Behavior

But i got different size of blob every time. Sometime the blob is right size and can be convert to an image.

### Steps to Reproduce

I think, the canvas is rendering frequently, so i can not get the correct blob.

### Operating System and Browser

I use firefox 61.0.1 @ ubuntu 18

**Comment by apple502j** [comment]
Not related to Scratch?
