### ISSUE TITLE
EV3 "button pressed?" block should return true/false

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1557]
### Expected Behavior

The EV3 extension's boolean block `button 1 pressed?` should report true or false.

### Actual Behavior

It reports numbers.

This is the same as the corresponding issue for microbit: https://github.com/LLK/scratch-vm/issues/1364

**Comment by evhan55** [comment]
I just re-tested this, and it's already working as expected.
Seems to have been addressed in https://github.com/LLK/scratch-vm/pull/1555/, for some reason.
Closing this issue.
