### ISSUE TITLE
EV3 motor position reporter gets inverted

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1567]
### Expected Behavior

When you continuously turn an EV3 motor with your hand a certain direction (e.g. clockwise), the motor position reporter values should always change in the same direction (e.g. increasing).

### Actual Behavior

Sometimes that position reporter values invert, so that as you turn the motor, the reported values first go down, then start going up.

This seems to be an error in the code that converts the internal representation of the motor's position to 0-360. The internal representation is in degrees, but represents continuous rotation and can range from a large negative to a large positive value. Specifically, the inversion happens when the internal value crosses from a positive to a negative value. 

While recording the gif below, I'm turning the motor counter-clockwise. the cat intially turns counter-clockwise, but then starts turning clockwise. This happens when the internal value (in the log, the first of the two values printed out) goes from positive to negative.
 
![motor-direction-bug](https://user-images.githubusercontent.com/567844/45243555-440e7d80-b2c2-11e8-8e5d-dfb041714750.gif)

The fix probably involves using our wrapClamp util. The motor class has a position getter which should probably report the "raw" value instead, and the opcode function called by the reporter block should handle the wrapClamping.

**Comment by evhan55** [comment]
Closed via #1611
