### ISSUE TITLE
(Sppech to Text) "Do not translate Google" is unnecessary 

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#1603]
Since the extension name is "Speech to Text", we needn't add that sentence to https://github.com/LLK/scratch-vm/blob/64a1d3e02b6aaaac9d6ec5e7299fc13e8199e136/src/extensions/scratch3_speech2text/index.js#L605

**Comment by thisandagain** [comment]
Happy to accept a PR for this.
