### ISSUE TITLE
Prevent multiple hardware disconnect alerts

### ISSUE THREAD

**Issue by evhan55** [LLK/scratch-vm#1615]
### Expected Behavior

One alert is shown when hardware peripheral disconnects.

### Actual Behavior

In some cases, two, redundant alerts display.

### Cases to Consider:

- Preventing the VM from requesting the alert twice- it should only be when the socket closes
- Preventing the alert from getting sent if we were not already connected
- What about if you connect, disconnect, connect, disconnect. Okay to see two alerts? Lets ask Carl and Kathy

**Comment by thisandagain** [comment]
I was able to get this to occur in my testing environment.

### Environment
Scratch Link 1.1.2 1b61617
macOS Version 10.14 (Build 18A391)
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

### Repro Steps
- Connect LEGO WeDo 2.0
- Execute the "set light color to ()" block
- Press and hold the power button on the LEGO WeDo 2.0 to turn off the hub
- Execute the "turn (motor) on" block

### Reference
![image](https://user-images.githubusercontent.com/747641/46888689-330bdb80-ce2f-11e8-9fbb-219fa0fc1bc3.png)

**Comment by evhan55** [comment]
I believe the issue @thisandagain is seeing would be resolved when these are resolved and merged in:

- https://github.com/LLK/scratch-link/issues/87: WeDo 2.0 can "go away" without causing any error
- https://github.com/LLK/scratch-vm/pull/1654: Differentiate peripheral errors: request vs. disconnect

Right now, two alerts are showing because of the issue resolved by PR #1654.
However, the alert should happen much earlier, when the WeDo2 disconnects, and that would be resolved by #87.  So, I am going to leave this issue open, but not work on it until those issues are addressed.

**Comment by kaaaaathy** [comment]
Chatted with @evhan55 about this... looks like we are also getting stacked alerts in these cases:

(I don't have any hardware extensions connected, and Scratch Link was not running at the time)

1. When I open microbit from the extensions library:
![redundant alerts 2](https://user-images.githubusercontent.com/8203939/47027785-1674e980-d136-11e8-999c-c55a5c268794.gif)


2. When I click the orange alert in the blocks panel:
![redundant alerts](https://user-images.githubusercontent.com/8203939/47027589-b120f880-d135-11e8-83f3-23a4b0c4f451.gif)

**Environment**
Scratch Link 1.18.827.1749
macOS 10.13.4 (17E199)
Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by evhan55** [comment]
Both of these cases seen by @thisandagain and @kathymakes have been resolved with https://github.com/LLK/scratch-vm/pull/1654.  There is a new issue to be opened about no alerts showing when the LEGO WeDo2 is powered down, which I will open.

**Comment by evhan55** [comment]
@thisandagain 's test case is something to consider in https://github.com/LLK/scratch-vm/issues/1590
