### ISSUE TITLE
Extraneous local variable created via Hide/Show

### ISSUE THREAD

**Issue by Mr-Dave2** [LLK/scratch-vm#1623]
### Expected Behavior

Local variables that are not defined or referenced in a sprite should not be dynamically created for that sprite.

### Actual Behavior

It's possible for stacks in a sprite to create local variables in another sprite.

### Steps to Reproduce

Add a new sprite (such as "Ben") to a new project.
Create a local variable in Ben (such as "Local").
Create this stack in Ben:  When GF Clicked; Hide variable "Local"; Show variable "Local".
Switch to Sprite1 (there should be no stacks and the only variable is the default "my variable".
Click the GF twice.

Notice that the monitor for "Local" now says "Sprite1: Local".  

Switch to Ben and then switch back to Sprite1.

Notice that "Local" now appears in the list of variables for Sprite1.

### Operating System and Browser

Windows 7 / Chrome Version 69.0.3497.100 (Official Build) (64-bit)

Here's a small [test case.](https://beta.scratch.mit.edu/compatibility-testing.html#249245634)  [Scratch 2 link](https://scratch.mit.edu/projects/249245634) and [Scratch 3 link](https://beta.scratch.mit.edu#249245634).

and the problem was reported in the forums [here:](https://scratch.mit.edu/discuss/topic/308114/?page=12#post-3263867)

**Comment by Kenny2github** [comment]
Reproduced on Windows 10 Chrome 69, Scratch 3. On Scratch 3, after clicking the mouse, the "Tera1: Button 1" monitor briefly shows up before being hijacked by "Sprite1: Button 1".

**Comment by kchadha** [comment]
@thisandagain I think this is probably critical as it can mess up project state pretty badly
