### ISSUE TITLE
Compatibility wiki page does not mention new limit on list size

### ISSUE THREAD

**Issue by Mr-Dave2** [LLK/scratch-vm#1633]
### Expected Behavior

The [Scratch 3 compatibility page ](https://github.com/LLK/scratch-vm/wiki/Compatibility) should describe the new limit for the size of a list.

### Actual Behavior

Nothing about the new limit is mentioned.  Users have noticed the limit and in the forums mention this difference as an issue.  One user even read the compatibility wiki page [and pointed out the new limit as a glitch](https://scratch.mit.edu/discuss/topic/316966/) since it was not mentioned in the wiki.

### Steps to Reproduce

visit https://github.com/LLK/scratch-vm/wiki/Compatibility

Windows 7; Firefox 62.0.2

**Comment by thisandagain** [comment]
Good catch! Thanks @Mr-Dave2

/cc @kchadha

**Comment by kchadha** [comment]
Documented here: https://github.com/LLK/scratch-vm/wiki/Compatibility#list-item-limit
