### ISSUE TITLE
Hardware disconnection alerts appear when no device was connected

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1638]
### Expected Behavior

The disconnection alert should only show when a hardware device was connected and becomes disconnected.

### Actual Behavior

If you attempt to connect to a hardware device but Scratch Link is not running, or bluetooth is not enabled, alerts are displayed.

Note that If you have switched languages before doing this, you get two additional alerts for each time you have switched languages. 

### Steps to Reproduce

- Close Scratch Link or disable bluetooth
- Initiate the device connection process, e.g. by adding the microbit extension

**Comment by evhan55** [comment]
Thanks @ericrosenbaum , I think this will need splitting up of hardware extension error types.
I propose this for now:

- **PERIPHERAL_DISCONNECT_ERROR**: for disconnect/read/write/send errors when we are already connected but can't talk to peripheral -> _triggers a disconnection alert in the GUI_
- **PERIPHERAL_REQUEST_ERROR**: for request/connect errors when we cannot connect to the peripheral at all -> _triggers connection modal error pane (no alert)_

What do you think?

**Comment by ericrosenbaum** [comment]
@evhan55 That looks good to me!

**Comment by evhan55** [comment]
@ericrosenbaum
For your reference, there is a WebSocket connection red console error that can never be hidden from users:
https://stackoverflow.com/questions/31002592/javascript-doesnt-catch-error-in-websocket-instantiation

It is a case we will not be able to prevent from showing up in the console, I think.

**Comment by evhan55** [comment]
Target Scratch Link no.: `1.1.2`

**Comment by evhan55** [comment]
Language switching still an issue.  Filed GUI issue here:
https://github.com/LLK/scratch-gui/issues/3336

**Comment by cwillisf** [comment]
Target Scratch Link version 1.1.2 or newer on Mac / 1.1.3 or newer on Windows

Note that the difference between 1.1.2 and 1.1.3 is the way that the Windows build calculates the version number -- the change doesn't affect Mac builds :)
