### ISSUE TITLE
Renaming clone?

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#164]
I've found it a little confusing to think about the name "clone" when we will have "actual" clones and "not-actual" sprite "clones." Maybe we should actually be calling this something like "rendered target"?

**Comment by towerofnix** [comment]
Is this an internal change, or will it actually affect the editor? Because when I think of "clones", I think of [this](https://d1o51r9qdgnnlz.cloudfront.net/animated_image/fb353f57-8441-4bbd-9543-3776de8ba698/giphy.gif).. basically what a clone is, in Scratch 2.0 anyways.

**Comment by tmickel** [comment]
It's an internal change only. As far as the UI goes, we'll continue calling things "sprites" and "clones." In the VM, even the first "sprite" and the stage are "clone" objects since they all share the same basic properties. In Scratch 2.0 I think this was called ScratchObject.

**Comment by thisandagain** [comment]
I think I agree. "Rendered target" is a little clunky but is nice and descriptive (certainly more descriptive than `ScratchObject`).
