### ISSUE TITLE
vendor.js too large, how to compress it?

### ISSUE THREAD

**Issue by wooden1985** [LLK/scratch-vm#1646]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
Please fill out issue templates and provide sufficient information for us to help identify and resolve your issues.
