### ISSUE TITLE
Close web socket before making a new one for hardware extensions

### ISSUE THREAD

**Issue by evhan55** [LLK/scratch-vm#1671]
From a test:

"I was connected to the EV3, then shut it down, restarted it, went to reconnect, and the scan never found the EV3 at all. Scratch Link showed 4 active sessions (seems to be the number of times I clicked “refresh” on the scanning step). Restarting bluetooth on the EV3 did not help. Restarting Chrome did not help. I was able to detect the same EV3 from a mac with Link 1.1.2. Restarting Scratch Link did not help."

**Comment by evhan55** [comment]
Also to fix with this issue: don't disconnect from socket if it wasn't connected to in the first place.

**Comment by evhan55** [comment]
Currently working on these two issues and have made this progress:

- **micro:bit [BLE]**: Scan for peripheral multiple times, uses same web socket now and doesn't create multiple web sockets
- **WeDo2 [BLE]**: Closing the connection modal if you don't initially scan for the peripheral doesn't give a console error.  Scanning for a peripheral once connects to the one first found, no multiple web sockets are ever created. (Using this branch on scratch-gui: https://github.com/LLK/scratch-gui/pull/3459)
- **EV3 [BT]**: Scan for peripheral the first time returns the first one found.  If 'refresh' is pressed and a scan is attempted again, an error is now returned: `{"code":-32601,"message":"Method Not Found","data":"Cannot call discover in discovery state"}`.  This means the web socket might need to be completely closed, reopened and rebound to handlers again every time an EV3 (or all BT peripherals?) don't show up on the first scan and more scans are needed. (However, per this StackOverflow it seems like possibly bad practice? Not sure: https://stackoverflow.com/questions/13797262/how-to-reconnect-to-websocket-after-close-connection)

cc: @ericrosenbaum 
cc: @cwillisf thoughts?

**Comment by cwillisf** [comment]
If it's not too difficult to implement, I would suggest:

- Every time you send a `discover` request, it happens on a `new Websocket(...)`
- If the user closes the connection modal before you `connect`, close and "forget" the Websocket (with `{ mySocket.close(); mySocket = null; }` or similar)

Continuing to use the same Websocket for future discover requests means reusing the same Scratch Link session object for multiple discover requests. A strict reading of the [Scratch Link docs](https://github.com/LLK/scratch-link/blob/master/Documentation/NetworkProtocol.md#discovery-state) indicates that this isn't allowed (only the `connect` request is supported), so technically the fact that `BLESession` allows it is a minor bug.

In more practical terms, closing the socket between (potentially) unrelated requests helps guarantee that there isn't any state accidentally retained from one request to the next. Closing the Websocket also lets Scratch Link know that it can turn off Bluetooth scanning, possibly saving battery on a laptop.

**Comment by evhan55** [comment]
Thank you @cwillisf , makes sense, sorry about not noticing the docs, I will try it!

**Comment by cwillisf** [comment]
@evhan55 no worry about the docs -- that particular point is pretty subtle. I was actually going to write something like "the docs are ambiguous on this point" at first, but when I went to grab a link for the relevant section I happened to re-read it and noticed that the docs imply (but don't explicitly state) that `discover` isn't allowed in the "discovery" state.
