### ISSUE TITLE
micro:bit hardware update

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#1674]
See [this](https://support.microbit.org/support/solutions/articles/19000087020-micro-bit-motion-sensor-change)

TL;DR
Motion sensor has changed and Scratch Link might need update.

**Comment by ericrosenbaum** [comment]
Thanks @apple502j !

@khanning can you please look into this when you have a chance?

**Comment by khanning** [comment]
I'm on it! We should just have to recompile the firmware with the latest micro:bit DAL. I'm getting some samples of the new hardware so we can test this before releasing.

**Comment by mraerino** [comment]
@khanning is there any way to get the sources for compiling the microbit hex?
we are trying to use hardware similar to the microbit
