### ISSUE TITLE
Pen Extension doesn't load when importing projects, No blocks load in Sprite

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1676]
### Expected Behavior

If a project uses pen blocks the pen extension should load and the blocks should appear in the sprites that use the pen blocks

### Actual Behavior

When a 2.0 project loads that uses the pen blocks the Pen extension doesn't load.  Any sprite that uses pen blocks shows no blocks in the workspace.

### Steps to Reproduce

Load dolphins 3d https://llk.github.io/scratch-gui/develop/#115870836
Look at the Pen sprite
Note: It has no blocks and the Pen Extension is not loaded (strangely it does have a workspace comment)

3d Solar System v1.6.1 https://llk.github.io/scratch-gui/develop/#89811578
Look at the OrbitDraw sprite
Note: It has no blocks and the Pen Extension is not loaded

Load Bouncy Heroes https://llk.github.io/scratch-gui/develop/#173918262
Look a the Loop sprite
Note: It has no blocks and the Pen Extension is not loaded

### Operating System and Browser

Mac Chrome
Safari Chrome

**Comment by BryceLTaylor** [comment]
The PR #1643 is being reverted for now in this pr https://github.com/LLK/scratch-vm/pull/1675.

**Comment by ktbee** [comment]
The original issue that broke the pen extension is fixed in #1693 and we now have tests for catching when the pen extension breaks as well in #1700
