### ISSUE TITLE
Translate languages for Set language block (TTS Extension)

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#1678]
### Expected Behavior
Language names should be in Japanese when I use Scratch in Japanese.

### Actual Behavior
It says "Japanese" instead of "日本語".

### Steps to Reproduce
1. Load TTS Extension
2. Set the language to japanese

### Operating System and Browser
On Windows 10 Firefox 62

**Comment by chrisgarrity** [comment]
Note: this should use the languages names module used by the translation extension for consistency.

**Comment by apple502j** [comment]
@chrisgarrity Then how do we handle Spanish (Europian) and Spanish (Latin America)?
