### ISSUE TITLE
no keyboard events after a sprite has been cloned

### ISSUE THREAD

**Issue by aoloe** [LLK/scratch-vm#1684]
i have a script that:

- sets the "running" variable to "no"
- starts a clone
- uses the space key to switch the value of running between "yes" and "no"

### Expected Behavior

when i press space the value should switch between "yes" and "no" 

### Actual Behavior

the value does not change

### Steps to Reproduce

as soon as "create a clone of myself" is added to the green flag block, and the program restarted, scratch stops capturing the space bar.

the mouse click on the sprite does work and gives me the same result as i would expect from the space bar.

### Operating System and Browser

Debian Testing with Chromium

![clone-space](https://user-images.githubusercontent.com/1857016/47266651-d9e02e00-d539-11e8-92c7-a0cb5f57970c.png)

[clone-space.zip](https://github.com/LLK/scratch-vm/files/2499090/clone-space.zip)

**Comment by Mr-Dave2** [comment]
I tried this under Scratch 2 and got the same behavior.  The stack with 'When SPACE key is pressed' is executed by both the original sprite and its clone.  One of them sets the variable to yes and the other setting it back to  no. I added some different wait times to your program so the effect could be seen.
![space with wait](https://user-images.githubusercontent.com/35544966/47267325-c3b97a00-d507-11e8-8dac-2f3280fcbead.png)

**Comment by aoloe** [comment]
yes, i also did try it in scratch 2.0 and got the same result

with your explanation i now understand well why this happens.
(and why it works when i use the "click on sprite")

i have to think a bit about it (and how to solve this), but i fear that there is nothing that can be changed in scratch to implement my idea "this way".
the behavior is "surprising" for the programmer (which is not so good), but very likely correct!

thanks for looking at it!
