### ISSUE TITLE
Scratch-vm and scratch-gui run the same .sb3 files with different results？

### ISSUE THREAD

**Issue by weijiahui1** [LLK/scratch-vm#1690]
### Expected Behavior

Same operation effect

### Actual Behavior

Operation results are different.

### Steps to Reproduce

1. Scratch-vm the file running target file after packaging.
![image](https://user-images.githubusercontent.com/25278544/47353312-87943e00-d6ee-11e8-9843-3213afda77d3.png)

2. scratch-gui the file running target file after packaging.
![image](https://user-images.githubusercontent.com/25278544/47353337-98dd4a80-d6ee-11e8-964b-064fa5e10dd0.png)

### Operating System and Browser
window10 google

**Comment by thisandagain** [comment]
See comments in https://github.com/LLK/scratch-gui/issues/3464
