### ISSUE TITLE
Touching color does not work with the default purple color

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-vm#1695]
### Expected Behavior

_Please describe what should happen_

On this project, when you press "a" and the cat moves over the purple, it should "say <true>" but it says false. Note how the other touching color stacks work fine, just not the paint editors default purple color... Very bizarre.

![image](https://user-images.githubusercontent.com/654102/47457246-9c330d80-d7a4-11e8-9f9c-46792fd28a5d.png)

/cc @kchadha you mentioned there was a touching color change recently that could have caused this?

### Operating System and Browser

Mac/Chrome

[touching color bug.sb3.zip](https://github.com/LLK/scratch-vm/files/2512086/touching.color.bug.sb3.zip)

**Comment by kchadha** [comment]
@paulkaplan, I don't think the changes I mentioned are related to this issue =/

**Comment by thisandagain** [comment]
@ktbee Could you prioritize this issue?

**Comment by ktbee** [comment]
@thisandagain sure thing!

**Comment by ktbee** [comment]
@paulkaplan, do you remember how you chose the color value for the touching color block? I found the behavior you described, but noticed the color values were very slightly different between the fill color of the block and the touching color block value:

![backdrop-fill-color](https://user-images.githubusercontent.com/7991694/49311113-337b3700-f4ae-11e8-8112-a422684aa4c1.png)

![touching-boolean-color](https://user-images.githubusercontent.com/7991694/49311121-38d88180-f4ae-11e8-94d1-a398768b0b8b.png)

When I used the color dropper option when choosing my touching color value, it worked well enough with the default paint color and the other colors on your project. Here is an example project I made to test this: 
[touching color bug - working touching color.sb3.zip](https://github.com/LLK/scratch-vm/files/2634786/touching.color.bug.-.working.touching.color.sb3.zip)

For me in Chrome and on a Mac, all of the scenarios say "true", as you'd expect. I'm wondering if you chose the touching color or the fill color in a different way that somehow made that color value slightly different? I'm wondering your steps, as I haven't been able to reproduce the incorrect false value yet. 

![screen shot 2018-11-30 at 2 52 39 pm](https://user-images.githubusercontent.com/7991694/49311632-a3d68800-f4af-11e8-8f32-a2d735b2fbf5.png)

**Comment by paulkaplan** [comment]
@ktbee my steps to repro are the following:
1. Switch to the stage
2. Open the costumes tab
3. Click the rectangle tool
4. Make a big rectangle around the middle of the project
5. Switch to the cat
6. Drag out the "touching color" block
7. Use the eyedropper tool to choose the purple value from the stage
8. Click the block, it says "false"

The color in the "fill" dropdown is 72
![image](https://user-images.githubusercontent.com/654102/49394667-8816f000-f702-11e8-8299-83e2233e81ea.png)


The color in the "touching color" dropdown is 71 after using the eyedropper
![image](https://user-images.githubusercontent.com/654102/49394688-936a1b80-f702-11e8-9389-72cb4e0c16d9.png)

Maybe the eyedropper is rounding the color in a certain way?

**Comment by ktbee** [comment]
@paulkaplan that's a good question, I had initially thought eye dropper rounding was the issue as well. However, I think I've traced the discrepancies to being something in scratch-blocks. I found that the `change` event was firing on the color picking block even when I just clicked on the color and didn't change any values in the UI. 

I demoed the issue in the gif below. I have [a console statement above this line](https://github.com/LLK/scratch-vm/blob/develop/src/engine/blocks.js#L322) in the Blocky event listener that prints out the data for the change event. I'm finding it's periodically fired when I click the color, but don't intentionally change it. This seems to happen more often for colors in the blue or purple spectrum. It seems like the block is returning different hexcodes even without a change from the user. 

This gif is a little small in the comment, you may want to click it to see it in full size. One thing to notice is when a new change is logged to the console. For these color values, it seems to change almost every time I click the color input.

![color-picker-changing](https://user-images.githubusercontent.com/7991694/49606610-d83fbd80-f961-11e8-87bc-f022b9424f7c.gif)
