### ISSUE TITLE
Project with hacked blocks fails to load - #55574144

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#1704]
### Expected Behavior

2.0 projects should load in Scratch 3.0. 

### Actual Behavior

This project does not load, immediately gets an oops page:
55574144

Errors in the console:
```
raven.js:55 Error: Error in Scratch GUI [location=https://llk.github.io/scratch-gui/develop/#55574144]: TypeError: Cannot create property 'message' on string 'Connection checks failed. Input "CONDITION" connection on "control_wait_until" block (id="pqOX%(v+Vc)(Ot,VE`ee") expected Boolean, found String'
```

This error is suspiciously similar to one that was previously fixed in #1562

### Steps to Reproduce

Try loading the project above.

cc/ @thisandagain, @BryceLTaylor, @ktbee, @mzgoddard

**Comment by Mr-Dave2** [comment]
I was wondering if it would help to carry forward the comment from the original issue that this is just a collection of hacked blocks.  Maybe even change the title "Project with hacked blocks fails to load - 55574144".
![hacked block project](https://user-images.githubusercontent.com/35544966/47687111-a726dd00-dbac-11e8-8aa1-e945b5bcc60e.png)

**Comment by joker314** [comment]
We're tracking hacked blocks in #1030, I believe.

**Comment by TheLogFather** [comment]
Might be worth noting that https://scratch.mit.edu/projects/148155722/ also fails to load.

It's a very simple project, so should be easy to debug.

It contains something which *looks* as though it was 'hacked' (the variable in a custom block boolean slot), but actually was not (–it's possible to do that within the Scratch editor itself, as explained in the project, though it's probably not by an expected/intended route).

**Comment by kchadha** [comment]
Fixed with https://github.com/LLK/scratch-gui/pull/3961

**Comment by TheLogFather** [comment]
Was just wondering if this was meant to have now regressed so that projects with certain 'hacked'(/undefined) blocks no longer load again?

For example:
https://scratch.mit.edu/projects/83967960/ ('hacked' "attribute of sprite" sensor block)
https://scratch.mit.edu/projects/10085324/ (red "undefined" block)

**Comment by TheLogFather** [comment]
Also looks like the project I referenced above (https://scratch.mit.edu/projects/148155722/) is broken again too – it loads in this case, and it even runs correctly, but the script with 'hacked' block is invisible (sound like as mentioned in #3579).
