### ISSUE TITLE
Assets are getting IDs renamed

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-vm#1713]
### Expected Behavior
Asset MD5s should stay the same

### Actual Behavior
Something is changing asset IDs when loading SB2s in scratch 3.

### Steps to Reproduce
1. I downloaded the project https://scratch.mit.edu/projects/124310159/#editor
2. I uploaded it to Scratch 3
3. I downloaded the SB3
The SB3 contains files named
797b03bdb8cf6ccfc30c0692d533d998.png
a8da90eb371d3fe456046a1e0cc71b54.png
Those IDs appear nowhere in the SB2's project.json

### Operating System and Browser
Any

**Comment by rschamp** [comment]
This is expected since we convert SVGs and bitmaps in the VM and then re-hash the contents to get the new MD5.

/cc @paulkaplan @kchadha @thisandagain
