### ISSUE TITLE
Save the Minifigs project does not load

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1714]
This version does not load in 3.0:
https://llk.github.io/scratch-gui/develop/#10118726

This version does load- the only change was to add a shape to the background:
https://llk.github.io/scratch-gui/develop/#258472899

cc @kchadha

**Comment by Mr-Dave2** [comment]
I was wondering, even though you wrote this project, if you had remembered that this was a Scratch 1.4 project.

 $ grep scratch-version project.json
                "scratch-version": "1.4 of 30-Jun-09",

**Comment by kchadha** [comment]
This issue is one I investigated a while ago. In Scratch 1.4, it was possible to have an empty background and this gets saved in the sb2 json when the project gets converted.

The sb2 json has values/formats for values that Scratch 3.0 import code does not expect e.g.

```
baseLayerID: -1,
baseLayerMD5: 510da64cf172d53750dffd23fbf73563 // note the missing .fileExtension here
```

**Comment by kchadha** [comment]
@mzgoddard, just wanted to make sure you're aware of this issue
