### ISSUE TITLE
Numbers: float vs int

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#172]
Scratch 2.0 and the current VM are handling this case differently:

<img width="148" alt="screen shot 2016-09-12 at 5 20 48 pm" src="https://cloud.githubusercontent.com/assets/120403/18453442/56316298-790d-11e6-8ca2-ca977d2c9a16.png">

In 2.0, the presence of any decimal point - "1.", "1.0", ".0", etc.- will cause the interpreter to label the number as a non-integer. "Pick random" then picks floats or rounded ints accordingly.

The current VM implementation is based on if there's an actual value, so:
<img width="179" alt="screen shot 2016-09-12 at 5 22 39 pm" src="https://cloud.githubusercontent.com/assets/120403/18453500/8fd0340c-790d-11e6-8ff0-8db086b541c0.png">
is treated as "give me an int from 1 to 10."

The sane way to deal with this case is probably to provide a method in `Cast` that's something like `Cast.isInt` that checks the string for a decimal point. That would replace this (too basic) check here: https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_operators.js#L84

**Comment by mrjacobbloom** [comment]
The same decimal point check is used in variable watcher sliders' min and max

**Comment by tmickel** [comment]
Thanks @Airhogs777 - we'll have to remember that!
