### ISSUE TITLE
Translate "Scratch lost connection to..."

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#1725]
This message is used for alerts.

**Comment by benjiwheeler** [comment]
And keep in mind right-to-left considerations.

**Comment by apple502j** [comment]
https://github.com/LLK/scratch-vm/blob/develop/src/io/ble.js#L177
Maybe formatMessage with values is fine here.

Also
https://github.com/LLK/scratch-vm/blob/develop/src/io/bt.js#L120

**Comment by apple502j** [comment]
fixed.
