### ISSUE TITLE
With BLE device, cannot access unadvertised services

### ISSUE THREAD

**Issue by beakutis** [LLK/scratch-vm#1751]
### Expected Behavior

When connection to a BLE device is discovered and established, access to any GATT service named in "service" or "optionalServices" should be allowed.

### Actual Behavior

Unable to access any characteristic listed under "optionalServices" unless the service is explicitly part of the advertising packet/advertisement data. In need of a way to access services listed as "optionalServices" that are not explicitly being advertised. 

### Operating System and Browser

Mac OS 10.13.6 Google Chrome 69.0.3497.100

**Comment by thisandagain** [comment]
Moved to LLK/scratch-link#99
