### ISSUE TITLE
Monitors (and monitored variables) from old projects are kept around across project loads

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#1758]
### Expected Behavior

Loading a new project should not keep around variables from an old project.

### Actual Behavior

Loading a new project (via file upload) after having a project with monitors checked previously, 
keeps around the variables from the old project in the new project. This is because the monitorBlocks container is not getting cleared out when clearing the VM runtime.

### Steps to Reproduce

1. Create a new project
2. Create some variables and monitor them
3. Load a new project from the filesystem
4. Switch sprites and switch back or switch between the costume tab and the code tab
5. Observe that the variables from your old project are in the toolbox

### Proposed Solution
Remove knowledge of previous monitors when clearing the runtime

Thanks to @summerscar for finding this issue!

**Comment by benjiwheeler** [comment]
Also see related issue: https://github.com/LLK/scratch-gui/issues/3427

Seems to me this is likely the same issue
