### ISSUE TITLE
Sensing of block will evaluate a list in the first menu.

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-vm#1762]
This isn't quite an issue yet, but it is about to be once #1425 and https://github.com/LLK/scratch-gui/issues/2389 are fixed.

The problem is this code doesn't check the variable types and it probably should:
https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_sensing.js#L316

### Expected Behavior

Variables should show up in the first menu of the sensing of block (they don't yet, but I'm working on it #1425). Once I add them, you can get a list in there and it will also evaluate:
![screen shot 2018-11-14 at 7 11 14 pm](https://user-images.githubusercontent.com/15675877/48521340-173a9180-e842-11e8-8ec7-fe4e64da5e53.png)

### Steps to Reproduce

Getting the list in their is slightly convoluted:
1. make a project with 2 sprites
2. in sprite one add variable 'pizza'
3. in sprite 2, drag out a sensing of block to the workspace
4. select sprite 1 in the right menu
5. select the variable 'pizza' in the first sensing block menu
6. Go back to sprite 1 and add a list 'pizza'. Add some items to the list.
7. Remove the variable 'pizza'
8. Go back to Sprite 2 and click on the sensing block. (which should still have pizza selected)

In scratch 2 this evaluates to 0 (though the steps to get the list selected are slightly different)

**Comment by towerofnix** [comment]
BTW, should it be joined by space instead of `,`? I.e, shouldn't it be evaluated [the same way](https://github.com/LLK/scratch-vm/blob/26ced0dd5806b68d47008a4dd44964717e19714c/src/blocks/scratch3_data.js#L93-L124) as clicking that corresponding list block?

**Comment by picklesrus** [comment]
@towerofnix I think the intent was to disallow lists in this menu. It isn't easy to do so (you can't just pick one from the menu), but it is possible.  In scratch 2.0, if you do manage to get a list selected in that menu, it evaluates to 0 and I think that's behavior we want to keep in 3.0.
