### ISSUE TITLE
How to register a event on the scratch-block-select-component to my business?

### ISSUE THREAD

**Issue by TongDaDa** [LLK/scratch-vm#1777]
Hi 😊, I very favor scratch! 

Summary 🔥:

I'm a green hand, but now I encounter a question that maybe change the codes in the `scratch-vm`, I want to listen to the keyboard event on the block that has keyboard listing function in my application, but I don't know how to modify and where to modify this `scratch-vm` right?

What do I want to do? 😢

We need to be compatible with wireless users. The use of scratch monitor keyboard events requires an event to be selected, but the ipad does not have a keyboard, so I want to display a virtual keyboard on the screen. Every time I choose an operation that carries the keyboard, it will be on the ipad screen. Display a virtual keyboard corresponding to the selected keyboard value

My English is not good,  don't make fun of me. 😊

Thanks. 😁

**Comment by TongDaDa** [comment]
I solve the above question although you don't reply to me...

**Comment by benjiwheeler** [comment]
Glad that you found a solution!

We would never make fun of you -- Scratch users and contributors speak many different languages. What matters is that we try to understand and help each other!

If you can, I would love to know what your solution was. It might help someone else.

**Comment by TongDaDa** [comment]
Thanks, I use the blockListen function in `scratch-vm` project. it may be a hook for scratch-blocks. @benjiwheeler

**Comment by TongDaDa** [comment]
So, I intend to register a hook to my business modules from the `scratch-vm` module so that I can listen to the blocks all event, I can judge the event type to do something.  @benjiwheeler
