### ISSUE TITLE
Implement variables and lists

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#180]
Here are some notes about how variables work in Scratch 2.0:
- Variable can be _per-clone_ ("for this sprite only") or _global_.
- Variable can be list-type or primitive-type.
- _global_ variables only can be cloud/persistent variables. List-type variables cannot be cloud variables.
- A "for this sprite only" variable's data is copied on the instantiation of a clone.
- Variables are created on-the-fly if not previously known (e.g., `lookupOrCreateVar`, `lookupOrCreateList`).
- Cloud vars currently seem to work with the `persistenceManager` overrides for online. For now to me it seems good to ignore the persistence/cloud property until we implement the equivalent.
- Procedure parameters are handled separately (see #79).

Based on this I think it would be best to wait until merging #150 to work on variables.

**Comment by tmickel** [comment]
- Variables are looked up first locally, then globally: https://github.com/LLK/scratch-flash/blob/master/src/scratch/ScratchObj.as#L461. If not found, they are only created locally.
- Scratch 2.0 stores global variables as variables on the stage. Not sure if I love this.

**Comment by tmickel** [comment]
- Variable names are case-sensitive.

**Comment by towerofnix** [comment]
> Scratch 2.0 stores global variables as variables on the stage. Not sure if I love this.

Something I also don't really like - if they could be stored elsewhere, one could make stage-local variables.. (would have to keep that in mind for sb2->sb3!)

**Comment by jeandrek** [comment]
The sprites are children of the stage
