### ISSUE TITLE
Switching languages causes Loaded projects to vanish

### ISSUE THREAD

**Issue by gabrielcbe** [LLK/scratch-vm#1806]
### Expected Behavior

Switching languages should keep the loaded project and only translate the blocks used.

### Actual Behavior

Switching languages after loading a project causes the UI to give back a blank project, not the one you had open.

### Steps to Reproduce

Open Scratch > Load a project form your computer > Switch language from english to any other language (e.g. Portuguese) 

after switching, scratch returns to a blank project.

### Operating System and Browser

Windows 10 & Chrome 70.0.3538.110

**Comment by thisandagain** [comment]
@BryceLTaylor Can you reproduce this?

**Comment by BryceLTaylor** [comment]
I sure can!  On mac chrome as well.  It has to be a project that you load with File>upload from your computer.
If the project is loaded from a 2.0 project from production it changes languages normally.

**Comment by benjiwheeler** [comment]
FYI tracking this in https://github.com/LLK/scratch-gui/issues/3892 , should we close this issue in favor of that?

**Comment by thisandagain** [comment]
@benjiwheeler Yup! That's a better description. Thanks.
