### ISSUE TITLE
Add play note to Lego Wedo

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-vm#1813]
### Expected Behavior

There should be a play note block, like in Scratch 2.0

### Actual Behavior

There isn't

### Steps to Reproduce

Look in the Wedo toolbox

### Operating System and Browser

All

**Comment by ericrosenbaum** [comment]
We decided to make the existing WeDo 2.0 "play note" block into a legacy block which is hidden from the palette. This was mainly because the WeDo speaker is so quiet that the sound from this block is often inaudible.
