### ISSUE TITLE
Move some event handlers to the VM

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#183]
I think it may make sense to provide some hooks for users of the VM to easily do these:
https://github.com/LLK/scratch-vm/blob/develop/playground/playground.js#L163

and maybe some of the other event handlers in the playground currently.

**Comment by tmickel** [comment]
@rschamp I'm hoping it can be a little simpler than it is now. Maybe like `vm.attachKeyboard(canvas, document)`, `vm.attachMouse(canvas, document)`, `vm.attachBlocks(blocklyWorkspace)`?

**Comment by rschamp** [comment]
Since these are for interactions between the VM and a specific platform, I think it would make the most sense to encapsulate these in the GUI that links the vm to the blocks and the environment.

**Comment by tmickel** [comment]
Yep - talked about this with Ray, decided we'll hold off on this for now to keep the VM fairly encapsulated.
