### ISSUE TITLE
Ghost effect not clamped to 0 or 100

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1875]
### Expected Behavior

The actual value of the ghost effect should never be less than 0 or greater than 100 as is the case in 2.0.  Any attempt to set it to a number > 100 should set it to 100.  Similarly, any attempt to set it to a number < 0 should set it to 0.

### Actual Behavior

If you run "Change Ghost Effect by 10" repeatedly, the ghost effect can go above 100.  Similarly you can reduce the ghost effect below 0 by using a negative number.  You can also set the ghost effect directly to a number out of the range with the "Set ghost effect to [ ]" block

### Steps to Reproduce

Create a new project
On the cat build these stacks:
![screen shot 2018-12-27 at 9 55 49 am](https://user-images.githubusercontent.com/1088291/50484289-9f719200-09bd-11e9-936c-a17071367e4d.png)
Press space
Note: the cat fades away
Press b
note: the cat returns
press space twice
Note: the cat fades away
Press b
Note: the cat does not return
press b again
Note: the cat returns.  The value for the ghost effect was 200 so you had to reduce it by 100 twice to get it to appear again.
Drag out and run the block "Set ghost effect to [300]"
Note: the cat disappears
Press space
Note: the cat does not return
Press space twice more
Note: the cat returns.  You successfully set the ghost effect to 300. 

Here's a useful project to test it with: https://scratch.mit.edu/projects/274813682/

### Operating System and Browser

Mac Chrome

**Comment by picklesrus** [comment]
I'm pretty sure this project is an example of this too: https://scratch.mit.edu/projects/270818825
Notice how once you've clicked true/false, the question shrinks but never quite disappears (see screenshot), but in scratch 2.0 it does.  
![screen shot 2018-12-27 at 10 06 20 am](https://user-images.githubusercontent.com/15675877/50484573-2115ef80-09bf-11e9-9ed5-f56c72030e35.png)
