### ISSUE TITLE
Multi-line say block with RTL text is incorrectly ordered

### ISSUE THREAD

**Issue by guyhed** [LLK/scratch-vm#1887]
When you write a text in Say or Think block that occupy more than one line on the stage, that text appears on the stage with the words and **lines** in reverse order.

**This happens in all the old scratch project after the transition to scratch 3.0**

For example the block
![image](https://user-images.githubusercontent.com/1233716/50638675-509c9d00-0f67-11e9-8f89-7e4b12192245.png)
produces this on the stage
![image](https://user-images.githubusercontent.com/1233716/50638759-9fe2cd80-0f67-11e9-956a-f700425edad4.png)

**Comment by chrisgarrity** [comment]
I created a test project: https://scratch.mit.edu/projects/276896027/

**Comment by chrisgarrity** [comment]
@thisandagain I don't think this is fixed. From my test project:
![Screen Shot 2019-04-26 at 11 01 23 AM](https://user-images.githubusercontent.com/399209/56817033-b52f8080-6812-11e9-803f-b82f9a567689.png)

**Comment by paulkaplan** [comment]
Just a note, I updated the title to be more specific about the problem. I believe the fixes for the say bubble will be different from the one for backdrops/costumes (https://github.com/LLK/scratch-vm/issues/2152) so lets leave these as two separate issues. 

From testing locally, it looks like https://github.com/LLK/scratch-render/pull/451 fixes the say bubble problem (by totally reimplementing say bubbles, so not helpful for solving the costume problem probably). I'll make sure to put this issue on the testing list for when scratch-render#451 is merged.
