### ISSUE TITLE
Duplicated sprite's codes don't work with click to run

### ISSUE THREAD

**Issue by qramo** [LLK/scratch-vm#1890]
### Expected Behavior

Both scripts can start and continue with click to run.

### Actual Behavior

Duplicated sprite's codes don't work with click to run. And stop other sprite running codes.

### Steps to Reproduce

I put a project made by this way, here:
[https://scratch.mit.edu/projects/277133456/](https://scratch.mit.edu/projects/277133456/)

1. Build some code with "forever" and moving things on "Sprite 1". (e.g. forever walk around, forever turn..etc)
2. Start this script with click to run.
3. Duplicate "Sprite 1" (will be made "Sprite 2")
4. Start the script on "Sprite 2" with click to run.
 
### Operating System and Browser
Mac OS 10.14.2 Chrome 71.0.3578.98

**Comment by thisandagain** [comment]
@BryceLTaylor Would you mind doing a repro on this?

**Comment by qramo** [comment]
_Thank you for your arrange._

I did not know well inside of code in scratch-vm. So I can only see by DevTools on Chrome. 
Each code blocks have unique "data-id" hashes. But it seems same "data-id" hash is in <g> tag of those blocks made by duplicated sprits. I thought it maybe cause of this.

<img width="956" alt="2019-01-05 0 31 00" src="https://user-images.githubusercontent.com/1835068/50695867-440c6780-1081-11e9-8c62-41543601836f.png">

**Comment by BryceLTaylor** [comment]
This appears to have been fixed.  I seem to recall @kchadha doing some work to make sure duplicated blocks have unique ids a while ago.  Closing this issue.
