### ISSUE TITLE
Text to Speech incorrectly censors common words

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1891]
### Expected Behavior

The Text to Speech extension should speak common (non-bad-word) phrases in any language.

### Actual Behavior

In English, any phrase containing the word "up" is blocked.

In French, any phrase containing the word "comment" is blocked.

Previously, the word "how" was erroneously blocked in English. Because "comment" in french means "how", I'm guessing that "how" in the other languages is also blocked.

### Steps to Reproduce

![screen shot 2019-01-07 at 10 41 34 am](https://user-images.githubusercontent.com/567844/50777154-cdca5980-1268-11e9-859e-1d2005922e16.png)

![screen shot 2019-01-04 at 11 23 36 am](https://user-images.githubusercontent.com/567844/50698654-7b442f80-1013-11e9-8633-412a6db6aeff.png)

**Comment by apple502j** [comment]
![](https://screenshotscdn.firefoxusercontent.com/images/cf398abd-7097-44e7-81b9-68262b1ab4f9.png)
English, Japanese and Polish worked, but the others didn't.

**Comment by ericrosenbaum** [comment]
Fixed!
