### ISSUE TITLE
stop this script only

### ISSUE THREAD

**Issue by TravisWadeWilliamson** [LLK/scratch-vm#1896]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
What do you mean?

**Comment by TravisWadeWilliamson** [comment]
Sorrry, new to GitHub. Didn't mean to do this. Would delete but don't see a "delete" button!

**Comment by Kenny2github** [comment]
@TravisWadeWilliamson you can close the issue instead, it's the button next to the "Comment" button.

**Comment by TravisWadeWilliamson** [comment]
Thanks! Honestly, I don't even know where that came from. It's possible this happened when my cat walked on the keyboard. Fur realz!
