### ISSUE TITLE
Create A Github Wiki?

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#190]
It could include stuff like a roadmap, explaining more about putting it in your own NodeJS app, etc.

**Comment by tmickel** [comment]
That's a nice idea! I think that would be very helpful.

**Comment by thisandagain** [comment]
We have the beginnings of a Wiki here, but lots more to add!
https://github.com/LLK/scratch-blocks/wiki/

**Comment by TheBrokenRail** [comment]
No I mean a wiki for scratch-vm not scratch-blocks

**Comment by tmickel** [comment]
@thisandagain Started one here today!
