### ISSUE TITLE
Running Vernier sensor block during connection process causes an error

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1908]
### Expected Behavior

Using a Vernier extension block should not cause an error in the console.

### Actual Behavior

During the connection process, after you have clicked "connect" on your device, but before it has connected, if any block that accesses a sensor value runs, you'll get an error in the console:

```
Uncaught TypeError: Cannot read property 'getSensor' of null
    at GdxFor.getAccelerationX (index.js:270)
```

### Steps to Reproduce

- Add the GDX-FOR extension, and dismiss the connection modal
- Check the monitor checkbox for force (or add hat block to the workspace, or run a forever loop containing a sensor reporter)
- Connect to the device, and the error appears during the connection process

cc @spectranaut

**Comment by spectranaut** [comment]
Oh wow I wanted to test this but thought I'd never been able to click through the modal fast enough. Thanks for the steps, @ericrosenbaum :)

**Comment by ericrosenbaum** [comment]
Fixed by https://github.com/LLK/scratch-vm/pull/1914
