### ISSUE TITLE
Custom blocks issue

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#192]
When you drag reporter-defining hat, playground crashes

**Comment by tmickel** [comment]
Hmm, thanks for the report. I'm not seeing a crash - can you copy the output of the developer tools console, or take a screenshot?

**Comment by dekrain** [comment]
Yes, I can. Here:

```
blockly_compressed_vertical.js:1262 Uncaught TypeError: Cannot read property 'sourceBlock_' of null
```

**Comment by dekrain** [comment]
Oh, yes. Playground don't crash, only scripts window.

**Comment by tmickel** [comment]
I believe that's an issue with scratch-blocks, not a scratch-vm issue.

**Comment by tmickel** [comment]
I'll recreate it over there - thanks!
