### ISSUE TITLE
Create A Github Project?

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#193]
I have idea for use new Github feature, project.
For example: (project tree)

``` json
{
  "main_proect": {
    "procedures": [
      "Issue:A design for procedures",
      "PR:Implement procedures"
    ],
    "Layout": [ ... ]
    , ...
  }
}
```

**Comment by dekrain** [comment]
Um... Hello ?

**Comment by tmickel** [comment]
@dekrain Not exactly sure what you're proposing here. So far we've been using Github issues and milestones to track plans and progress, and that's worked pretty well.

**Comment by dekrain** [comment]
Next to the Pull Requests is Projects tab.

**Comment by tmickel** [comment]
We're not using that right now, we may or may not in the future.
