### ISSUE TITLE
Message and variable name including '&' destructs toolbox and blocks

### ISSUE THREAD

**Issue by yokobond** [LLK/scratch-vm#1939]
### Expected Behavior

'&' should be able to use in message or variable names. 

### Actual Behavior

When a message or variable contains '&', the message or variable blocks in the Toolbox has no name and blocks in the Code area is empty. 

This problem is reported in discussion forum. 
[When "&" is included in the message, the existing block disappears. - Discuss Scratch](https://scratch.mit.edu/discuss/topic/337375/?fbclid=IwAR2q-siYCFqzo62IeUhIcKTrNRM8_lhZG4EdGVeXRQEFZYPRNVO386myakM)

### Steps to Reproduce

1. Name a new message or variable with '&'.
2. Open 'Costume' tab and re-open 'Code' tab. 

### Operating System and Browser

MacOS 10.13.6
Chrome 71.0.3578.98

**Comment by apple502j** [comment]
Kind of #1077 and regression of #178

**Comment by kchadha** [comment]
Tracking this in #1077.
