### ISSUE TITLE
VM shows up as blank

### ISSUE THREAD

**Issue by ed-cooper** [LLK/scratch-vm#195]
Just did npm update, VM now shows up as blank on Chrome and Edge (no other browsers to test on)

![image](https://cloud.githubusercontent.com/assets/14095134/18640892/1444f59a-7e92-11e6-9f97-03fdbc6c851d.png)

Running Windows 10
Ran the VM several times before without any issues

Also, none of the buttons do anything

**Comment by tmickel** [comment]
Did you update your copy of scratch-render?

**Comment by ed-cooper** [comment]
Previously I hadn't installed scratch-render (I just followed the installation instructions in the readme for scratch-vm)

I installed it separately just now, re-ran npm update and tried again.

But I still get the same errors?

**Comment by tmickel** [comment]
Which commit are you on for both scratch-vm and scratch-render (`git rev-parse HEAD`)?

It looks like your VM playground is trying to load render-worker.js, but that was removed here: https://github.com/LLK/scratch-vm/pull/175

**Comment by ed-cooper** [comment]
Scratch-vm: 7caf8e588aa61f00b55525a31a50da3c9afae852

For scratch-render, "cd scratch-render" comes up with the system cannot find the file specified (and so I can't do git rev-parse HEAD)

**Comment by tmickel** [comment]
The scratch-render repo is in `node_modules/scratch-render`.

But anyway, that's a really old commit for `scratch-vm`. What's probably happened is that your scratch-vm is behind but your scratch-render is up-to-date.

Can you run `git pull` and then try again? Your scratch-vm should be on 470f686.

**Comment by tmickel** [comment]
@chooper100 I'm assuming this will be fixed by updating - please reopen if not :)
