### ISSUE TITLE
Point in the currently right direction for embedding scratch UI?

### ISSUE THREAD

**Issue by djMax** [LLK/scratch-vm#1951]
This is not an issue so much as a documentation pointer request, though perhaps it could result in some more docs. I am hoping to embed Scratch blocks/VM in a project aimed at kids writing "game playing" bots:

https://advent-game-lab.herokuapp.com/

Generally, each game will ask the student to write a function that takes the game state and returns the next move. I started to use Blockly, but it became clear it's not the answer so much as a tool the answer will use. SO, it seems like scratch-blocks is the right component, paired with scratch-vm. But I couldn't find an example that linked these up in an understandable way. Is it possible to use blocks/vm this way (where the execution is basically headless, though a step debugger would be super-great)?

**Comment by thisandagain** [comment]
Hi @djMax, we *just* released so we still have some documentation to catch up on. I would take a look at our old "VM playground" which simply merged together the VM and the blocks with a minimal wrapper:

https://griffpatch.github.io/scratch-vm/

This will probably require some updates to get it working with the latest VM, but should at least get you started. The other place I would look for "headless" execution are the VM's test suite which does quite a bit of loading a project and then running it without any connection to the rendering and audio engines.

**Comment by djMax** [comment]
Thanks, I'm poking my way around those things and getting a little further but not a lot. No expectation to respond, but for posterity, I'm just trying to get a value BACK out of the VM after a greenFlag and not finding any events that will be useful.

```
        const vm = new ScratchVM();
        window.blocklyWorkspace.addChangeListener(vm.blockListener);
        window.blocklyWorkspace.addChangeListener(vm.variableListener);
        vm.addListener('targetsUpdate', (...args) => {
          console.error('targetsUpdate', args);
        });
        vm.start();
```

Then I just have blocks that call move(10) or similar and look for any events firing out of the VM but there don't seem to be any other than PROJECT_START. If I add a fake renderer, I see lots of calls to draw, but I'm not sure that's the most efficient way to fish out a return value.
