### ISSUE TITLE
Needless BitMap Object when load more one project

### ISSUE THREAD

**Issue by TongDaDa** [LLK/scratch-vm#1955]
Scratch run out of memory frequently due to the bitMap Object of _allSkin in Scratch-render project when I load more one project,  I know that scratch is simply run once but I need to load it mutiple time. Perhaps this is not your bug, I just want to quest anwser that how to load multiple project in order and no memory-overflow? 

I have find out the bitMap Object of Scratch-Render is persisted in the memory and then I tried to clear the BitMap Object from the _allSkin, and later I did a lof of patching, It appear an another error when I repair a problem

**Comment by thisandagain** [comment]
I'm not sure if we can help you here as we only support loading one project at a time in Scratch. In general, we are working on some performance optimizations that should reduce overall memory and CPU/GPU utilization, but you'll need to investigate this yourself. Happy to review any specific suggestions you may have to reduce the memory footprint of skins (costumes).

**Comment by TongDaDa** [comment]
@thisandagain Thanks

**Comment by TongDaDa** [comment]
But, I find out the `clear` function of this project that seems not clear the _allSkin.

It just invoked the `clear` function and some Emit of Extension and penSkin to clear in Runtime module. I was thinking that is Incomplete,


@thisandagain

**Comment by TongDaDa** [comment]
> Scratch run out of memory frequently due to the bitMap Object of _allSkin in Scratch-render project when I load more one project, I know that scratch is simply run once but I need to load it mutiple time. Perhaps this is not your bug, I just want to quest anwser that how to load multiple project in order and no memory-overflow?
> 
> I have find out the bitMap Object of Scratch-Render is persisted in the memory and then I tried to clear the BitMap Object from the _allSkin, and later I did a lof of patching, It appear an another error when I repair a problem



> I'm not sure if we can help you here as we only support loading one project at a time in Scratch. In general, we are working on some performance optimizations that should reduce overall memory and CPU/GPU utilization, but you'll need to investigate this yourself. Happy to review any specific suggestions you may have to reduce the memory footprint of skins (costumes).

Please look at here. 🙋‍♂️🙋‍♂️

**Comment by TongDaDa** [comment]
It is your problem, whatever this project run once or more once, the _allSkin data should be cleared, but it has skin-data when the `runtime` run the clear function. How do you think?

This is a problem of VM,  I think the clear function means clear the data of all about VM Data, but the skin of `renderer` is also belong to VM

**Comment by TongDaDa** [comment]
Of course, I can create a pull request to repair it and maybe need a lot of time I inspect side-effects, so could you like to help me to find the side-effects when I repair it?

The side-effects are other problem when I run the `this.renderer._allSkin = []` in the clear Function in  `runtime` module, If you are interesting to inspect my changed code and give me some suggestions, I am willing to do that on a pull reaquest.
