### ISSUE TITLE
Drop `useRound` from Cast.toListIndex

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#202]
In Scratch 2.0, this block:
<img width="129" alt="screen shot 2016-09-20 at 10 55 23 am" src="https://cloud.githubusercontent.com/assets/120403/18675572/c5448c78-7f20-11e6-9270-6cc72dc14cb8.png">
Will delete the first item of the list. Because 0.5 is rounded to 1.

However,
<img width="246" alt="screen shot 2016-09-20 at 10 55 57 am" src="https://cloud.githubusercontent.com/assets/120403/18675586/d4bd2674-7f20-11e6-9ddb-13dacc6641dc.png">
will not do anything. Because it floors 0.5 to 0. (insert, item of also work this way).

Was this an intentional change in 2.0? In 1.4, delete works like "floor." Can we drop the round behavior and switch it to always floor without affecting compatibility of projects?

See: #187 for original discussion.

**Comment by ed-cooper** [comment]
imo I feel using round is more intuitive

eg. I would expect (item (1.99) of [list v]) to return item 2 of list rather than item 1

(Although this behaviour could easily be worked-around simply by using the "round" block)

**Comment by mrjacobbloom** [comment]
I'd be fine with either floor or round as long as it's consistent among all blocks that take integers. I guess I'd lean toward floor since C-based languages cast float to int with the floor function

**Comment by towerofnix** [comment]
> I'd be fine with either floor or round as long as it's consistent among all blocks that take integers. I guess I'd lean toward floor since C-based languages cast float to int with the floor function

Scratch ≠ C, and its lists are 1-based, so with that logic I say ceiling. :P

However I do agree with @chooper100, round is more intuitive.

**Comment by ed-cooper** [comment]
Going back to the example in the original post, I think what's really important here is that the casting function used is consistent between list blocks - I would consider the fact that the 2 blocks listed affect different items to be a bug with 2.0

**Comment by tmickel** [comment]
I think I agree, @chooper100 - having a consistent behavior seems better. We need to investigate if it will break projects...

**Comment by tmickel** [comment]
We've decided to use `floor` for all cases, since more projects are using the blocks that use that.
