### ISSUE TITLE
Renamed list doesn't show updated name

### ISSUE THREAD

**Issue by amylh** [LLK/scratch-vm#2047]
### Expected Behavior

Once a list is renamed, its graphic should display the updated name.

### Actual Behavior

When a list is renamed, the name displayed on the list's graphic is not updated.

### Steps to Reproduce

See this demo project: https://scratch.mit.edu/projects/293791473/
Or create your own project, make a list, and rename it.

### Operating System and Browser

LinuxMint 18.1, Mozilla Firefox 65.0.1
LinuxMint 18.1, Google Chrome 72.0.3626.109

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-gui#4098

**Comment by thisandagain** [comment]
Tracking in LLK/scratch-gui#4098
