### ISSUE TITLE
ERROR in Entry module not found: Error: Cannot resolve module 'expose'

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#206]
Getting this when I run `make serve`, and it appears that the playground no longer updates.

**Comment by tmickel** [comment]
ah- do I just need to run `npm install`?

**Comment by tmickel** [comment]
That says:
`├── UNMET PEER DEPENDENCY babel-core@^6.0.0`

`npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/tmickel/Sites/scratch-vm/node_modules/babel-core/node_modules/json5/lib/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.`

**Comment by tmickel** [comment]
Hmm, I solved this by deleting node_modules and reinstalling. Not sure what's up with that.

**Comment by rschamp** [comment]
`npm install` would be necessary to get the new `expose-loader` dependency. The babel-core error doesn't make sense to me. I don't know why you would have to delete node_modules and reinstall either.
