### ISSUE TITLE
BOOST extension: default motor speed should be 50%?

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#2089]
In the EV3 extension, we set the initial value for the power of the motors to 50%, instead of 100% (i.e. not the default value for the input of the block, but the actual value set internally when the extension loads). We should consider doing the same for the BOOST. 

This would make the initial experience of the motor moving a bit more gentle. It also gives you room for an increase, so that setting it to 100% actually causes it to change.

**Comment by knandersen** [comment]
aaah, that's a great point! I assumed that since the default value for the block input was 100, that the initial speed should follow that, but your reasoning makes a lot of sense, and I agree it's a great way of ensuring "something happens", the first time the block is used.
