### ISSUE TITLE
Use Scratch 3.0 GUI to play projects.

### ISSUE THREAD

**Issue by xiaolong2104** [LLK/scratch-vm#2094]
Thank you,but i want do like this ,run in scratch stage! Use left and right arrow to control sprite in html cancvas!

https://scratch.mit.edu/projects/298230520/

**Comment by towerofnix** [comment]
You'll want to look into embedding [scratch-gui](https://github.com/LLK/scratch-gui/) (see [this file](https://github.com/LLK/scratch-www/blob/develop/src/views/preview/presentation.jsx) for reference - specifically [these properties](https://github.com/LLK/scratch-www/blob/66df143bbc99274fc89541ae5ddea25e5e4e7302/src/views/preview/presentation.jsx#L328-L347)). scratch-gui can only be embedded in a controllable way by using React, but you could instead use an iframe with your project URL + "/embed", e.g. `<iframe src="https://scratch.mit.edu/projects/298230520/embed"></iframe>`.
