### ISSUE TITLE
"broadcast (expr) and wait" ends if value of (expr) changes

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-vm#2109]
### Expected Behavior

Broadcast and wait block should always wait until its receiver scripts finish.

### Actual Behavior

If the broadcast block contained an expression, changing the value of that expression (e.g. by changing a var it contains) causes the broadcast-and-wait block to end even if its receivers have not yet finished.

### Steps to Reproduce

Create a script along these lines:
`when GF clicked`
`say "hello"`
`set myvar to "test"`
`broadcast (myvar) and wait`
`say "goodbye"`

And a receiver script:
`when I receive "test"`
`wait 1 sec`
`set myvar to "changed"`
`forever {nothing}`

Click GF and note that it says "hello", then 1 sec later says "goodbye" – and yet the receiver script continues to run the forever loop.

Note if you add more work after the "b-a-w" in the first script, it means that *both* scripts are now running simultaneously. Interesting new feature, that...  :D

### Operating System and Browser

Presumably N/A

**Comment by mobluse** [comment]
Here is an unchanged Scratch 2 project that doesn't work in Scratch 3 due to this bug: https://scratch.mit.edu/projects/137676871/

I reported my project as broken in Scratch 3 3rd of January 2019:
https://scratch.mit.edu/discuss/topic/329513/?page=1#post-3378908

**Comment by mobluse** [comment]
It seems this bug was fixed now, because my old Scratch 2 project (see above) started to work in the right way.
