### ISSUE TITLE
BOOST extension: color reporter design?

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#2114]
Currently the BOOST extension includes a "color" reporter, which reports a string which is the name of the color the sensor currently sees, such as "red", "yellow", or "none".

If we keep this approach, we'll need to localize these color names. Then the problem would be that if I create code that checks value of the reporter, it will work for me but not for people using the editor in other languages:

![Screen Shot 2019-04-11 at 1 43 22 PM](https://user-images.githubusercontent.com/567844/55979323-e67b4e80-5c5f-11e9-8e32-afde5d6510bc.png)

For example, if I load this project with the editor set to Spanish, the reporter will report "rojo" instead of "red", and the condition will never be true.

So, we might consider instead creating a boolean reporter block with a menu listing the color names- something like:

<seeing color [red]?>

This would allow you to do the same thing as above, but more simply, in a way that works across languages. 

If we replace the color string reporter with the boolean, though, we will lose the ability to live monitor the color sensor's value, which is very useful.

**Comment by towerofnix** [comment]
This is a similar problem to LLK/scratch-blocks#1685 / #1836, btw! Although those discussions don't seem to have gone forward yet.

**Comment by ericrosenbaum** [comment]
Decisions from our meeting on this topic:
- Remove the `color` reporter
- Replace it with a boolean reporter: `<seeing [any color] brick?>`
- Change the wording on the hat block to: `when [any color] brick seen`
