### ISSUE TITLE
Blank bitmap costumes don't move correctly

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#2116]
### Expected Behavior

A blank bitmap costume is treated the same as a blank vector costume and moves appropriately. Its dimensions should be 2x2, just like blank vector costumes. In the demo project, both red circles should reach the black circles.

### Actual Behavior

Blank bitmap costumes move strangely: any position update fences it to Y >= 0. A blank bitmap costume's dimensions are 480x360. In the demo project, the empty bitmap costume ends up as though it veered off:

![Demo project. Two circles are supposed to move right 400 pixels, which would land them in indicated target circles. The circle which has a non-blank bitmap costume has been moved to the right. The circle which has a blank bitmap costume has been moved just halfway across the screen and is above the target circle.](https://user-images.githubusercontent.com/9948030/56079303-05e1bb00-5dc9-11e9-9a0d-a510f27c5685.png)

### Steps to Reproduce

Create an empty bitmap costume (create a blank vector costume then click "convert to bitmap"). Note its dimensions are 480x360. Move it around with motion blocks. Note the strange behavior, mostly related to fencing it seems.

See ihgfedcba's project which demonstrates this behavior: https://scratch.mit.edu/projects/301891022/ - Credits to them for finding out and investigating this weird bug.

### Operating System and Browser

I can repro this on both Firefox and Chromium.

**Comment by TheLogFather** [comment]
~This was already mentioned in https://github.com/LLK/scratch-gui/issues/4409 and is probably the same as https://github.com/LLK/scratch-gui/issues/4233 (which was closed, since that was a similar thing with vector, and was fixed).~
(see next comment!)

I was kinda surprised this hasn't yet been fixed, since it's been known about since only a few days after release of Scratch 3... Here's a demo project: https://scratch.mit.edu/projects/277240964/

**Comment by TheLogFather** [comment]
Agh, I'm getting references to the two issues mixed up...

The first one (https://github.com/LLK/scratch-gui/issues/4409) is probably the same thing, while the second (https://github.com/LLK/scratch-gui/issues/4233) was the same kind of thing with vector, but was fixed (which is why it's closed).

**Comment by towerofnix** [comment]
@TheLogFather Agreed that that's probably the issue here! It lines up with a comment on that project:

>From my 15 minutes of testing on this, it seems that, no matter the starting point, changing x by a positive or zero value or y by a negative or zero value will always move the sprite to the fixed point (-15, 15). I also found that if you change x by a negative value, it will move to (( x - ( n - 1 ), 15), starting from (-15, 15). Changing y by a positive value causes it to move to (-15, (y + (n - 1))), starting from (-15, 15). I'm definitely gonna have to test this some more :P
