### ISSUE TITLE
npm link problem

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-vm#2117]
I want to install scratch-gui and scratch-vm.
When I type npm link, there is an error happened.
It said "ENOENT: no such file or directory, open 'C:\Users\crouse\package.json'"
May I know how to solve this problem?
![image](https://user-images.githubusercontent.com/25700616/56105899-2ba9c400-5f71-11e9-8eff-709c8ca23855.png)

**Comment by apple502j** [comment]
Go to `C:\Users\crouse\AppData\Roaming\npm`, delete/rename `node_modules` there, and try again.
