### ISSUE TITLE
BOOST extension: setting speed continuously can result in motor being "stuck on"

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#2127]
### Expected Behavior

When you use the BOOST "turn motor on for seconds" block, the motor should always stop after the specified number of seconds.

### Actual Behavior

If you run a stack that sets the motor speed in a loop, and then click the "turn motor for 1 rotation" block, about a quarter of the time the motor does not stop, and gets "stuck on".

### Steps to Reproduce

Click the top stack to start the loop, then click the "turn motor for seconds" block:

![Screen Shot 2019-04-19 at 4 19 57 PM](https://user-images.githubusercontent.com/567844/56442504-0691ba00-62bf-11e9-814f-a170620d1385.png)

If you try this a few times, sometimes the motor will just stay on instead of stopping after a second.

**Comment by ericrosenbaum** [comment]
I believe this is a side effect of our rate limiting approach, combined with the fact that the "set motor speed" block, unlike other blocks, only yields for one tick. We should instead make it yield for     `BoostBLE.sendInterval`, like other commands.

**Comment by evhan55** [comment]
Should also useLimiter false for second part of 'on for'?
