### ISSUE TITLE
Yielding hats

### ISSUE THREAD

**Issue by harbaum** [LLK/scratch-vm#2129]
Currently there are several solutions for yield'ing reporters or command blocks as e.g. mentioned in #83. It's possible to use `util.yield` as well as promises.

But it seems these mechanisms all don't work for hats. I've tested promises as explained in the comments in #83 as well as util.yield. 

The following code does not trigger any action and after a while the framework even stops calling it:

```
when_test (args, util) {
   return new Promise(resolve => {
       if(this.toggle === undefined) this.toggle = true;
       this.toggle = !this.toggle;
       setTimeout(resolve.bind(this, this.toggle), 1000);
   });
}	
```

I'd expect this code to trigger the hats execution every two seconds.

The following code generates events a full rate which seems to show that yelding doesn't work at all:

```
when_test (args, util) {
	util.yield();
	return false;
    }
```

I'd expect this code to completely block.

I would like to use such a feature to request asynchronous input from some usb connected hardware and let the user run code e.g. when change on an input of the device (an ftDuino from http://ftduino.de) is detected as seen e.g. [in this video](https://www.youtube.com/watch?v=Hg4p8dhCaZ0).

**Comment by apple502j** [comment]
Currently, hats definition func is expected to return true/false (and if it's true the block runs).

**Comment by harbaum** [comment]
@apple502j No, it runs on the transition from false to true. 

I don't see why hats should work fundamentallly different than other blocks. 

But you are right and i could work around this. Although promises allow for much nicer solutions.

**Comment by harbaum** [comment]
It seems a workaround is the way to go.

**Comment by towerofnix** [comment]
@harbaum out of curiosity's sake why did close this issue? They may have just not gotten around to reviewing your suggestion yet; is there a reason besides this attention being as yet not commented on?

**Comment by hyansuper** [comment]
similar issue https://github.com/LLK/scratch-vm/issues/2244 and https://github.com/LLK/scratch-vm/issues/970

How do you work around this problem please? @harbaum
I have a customed HAT block that needs to sleep for 2 seconds and check a variable, how can I get around this problem? the below sleep code don't work:
```
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```
thank you!

**Comment by hyansuper** [comment]
Hi, @harbaum 
I have a customed HAT block that needs to sleep for 2 seconds and check a variable, how can I get around this problem? the below sleep code don't work:
```
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```
thank you!
