### ISSUE TITLE
BOOST extension: setting speed to 0 after motor is on results in it being stuck on

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#2136]
### Expected Behavior

A motor should never get stuck on: it should always be possible to stop all motors using the stop button, or to stop motors using the "turn motor off" block. 

### Actual Behavior

If you turn a motor on, then set its speed to 0, it will become stuck on. The stop all button does not stop it, and the "turn motor off" block does not stop it.

<img width="256" alt="Screen Shot 2019-04-23 at 12 20 22 PM" src="https://user-images.githubusercontent.com/567844/56598262-304e2800-65c2-11e9-8b9d-41cbde71175d.png">

Or, click the "turn motor on for 3 seconds" block, and then click the "set speed to 0" block. The motor will continue indefinitely, instead of stopping after three seconds (to stop it, you can change the value in the set speed block to something above 0, then click on it):

![Screen Shot 2019-04-24 at 5 36 46 PM](https://user-images.githubusercontent.com/567844/56695782-e0518d00-66b7-11e9-99e9-7c5a219035df.png)

and a third case ?:

<img width="317" alt="Screenshot 2019-04-26 at 17 27 12" src="https://user-images.githubusercontent.com/699840/56819696-48b78000-6818-11e9-9dbe-2b56f4b4414f.png">

**Comment by evhan55** [comment]
After speaking with @knandersen , here is a larger set of scenarios/examples to be testing for this bug:
- setting speed to **0 just once** while a motor is running
- setting it to **0 -> another value -> back to 0** continuously while a motor is running

<img width="602" alt="Screen Shot 2019-04-27 at 6 15 05 PM" src="https://user-images.githubusercontent.com/699840/56855636-7a177500-6918-11e9-924b-bd0e2ba0fa6b.png">

**Comment by knandersen** [comment]
Just to make sure it's recorded in git history, @evhan55 and I had a conversation about the functionality of the `resetState`-argument in the motor-functions.

It was introduced in https://github.com/LLK/scratch-vm/commit/3f0816bac8523551c97f8d3bc8688d9506d9db14 . Without it, running the program below, the `turn motor A for 20 rotations`-stack would lose it's highlight after clicking the `set motor ABCD speed to 20%`-block

<img width="440" alt="Screenshot 2019-04-28 at 21 18 42" src="https://user-images.githubusercontent.com/24595727/56869078-d0111900-69fb-11e9-8647-c781449c2ce3.png">
