### ISSUE TITLE
Error NPM Install

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#215]
OS: Ubuntu 9.04 (It's the only thing that will run on my old desktop)
Node.Js Version: LTS
Error:
npm ERR! git clone --template=/home/connor/.npm/_git-remotes/_templates --mirror https://git@github.com/LLK/scratch-blocks.git /home/connor/.npm/_git-remotes/https-git-github-com-LLK-scratch-blocks-git-43b046a2: fatal: destination directory '/home/connor/.npm/_git-remotes/https-git-github-com-LLK-scratch-blocks-git-43b046a2' already exists.
npm ERR! git clone --template=/home/connor/.npm/_git-remotes/_templates --mirror https://git@github.com/LLK/scratch-render.git /home/connor/.npm/_git-remotes/https-git-github-com-LLK-scratch-render-git-7d5313c7: fatal: destination directory '/home/connor/.npm/_git-remotes/https-git-github-com-LLK-scratch-render-git-7d5313c7' already exists.
npm ERR! Linux 2.6.28-19-generic
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/connor/.npm/_git-remotes/_templates --mirror https://git@github.com/LLK/scratch-blocks.git /home/connor/.npm/_git-remotes/https-git-github-com-LLK-scratch-blocks-git-43b046a2
npm ERR! fatal: destination directory '/home/connor/.npm/_git-remotes/https-git-github-com-LLK-scratch-blocks-git-43b046a2' already exists.

npm-log attached

**Comment by tmickel** [comment]
Can you try deleting your node_modules directory and then running `npm install`?
