### ISSUE TITLE
BOOST extension: Rename pendingPromiseFunction variable?

### ISSUE THREAD

**Issue by evhan55** [LLK/scratch-vm#2153]
The `pendingPromiseFunction` variable is used to track a Promise that resolves when a motor has reached a desired position after some rotations.  The variable name could be clearer to reflect that fact, perhaps `pendingRotationPromise` ? The comment on lines `#359-#360` also seems inaccurate, saying the variable is used to track duration and not rotation.  This might also require changing the setter/getter names on lines `#464` and `#471`. (This setter/getter pair might not be necessary since this variable is private, anyway).

**Comment by knandersen** [comment]
Thanks @evhan55, I think this makes a lot of sense! Would you mind creating the PR for it?

**Comment by evhan55** [comment]
@knandersen sure!

However, as I think about it more carefully, I can see further cleanup in general of these vars:

- `pendingTimeoutID`
- `pendingTimeoutStartTime`
- `pendingTImeoutDelay`
- `pendingPositionDestination`
- `pendingPromiseFunction`

3 of those are for duration commands, and 2 of those are for rotation commands.  So I can see all of those being renamed more cleanly to:

- `pendingDurationTimeoutID`
- `pendingDurationTimeoutStartTime`
- `pendingDurationTimeoutDelay`

and:

- `pendingRotationDestination`
- `pendingRotationFunction`

That feels much clearer to me, what do you think?

If that is clearer to you, then I would suggest this issue lumping all of those changes at once, and I can make a PR, and would even feel comfortable with it landing in the extension if it's tested during next Tuesday's QA session.
