### ISSUE TITLE
Can't load project's assets

### ISSUE THREAD

**Issue by Steve-xmh** [LLK/scratch-vm#2169]
I've installed `scratch-vm` by `npm`.
When I tried to run function `.loadProject()`, it says it couldn't find storage module and failed to load assets which inside project like this:
![image](https://user-images.githubusercontent.com/39523898/57700691-1073c680-768d-11e9-9203-3e8eab0a19b3.png)
It seems that it can't find module `scratch-storage`, but it still here in node_module folder:
![image](https://user-images.githubusercontent.com/39523898/57700823-4ca72700-768d-11e9-8b54-3231a1f9699b.png)
Example Code:
```javascript
const vm = require("scratch-vm");
let scVM = new vm();
scVM.loadProject(fs.readFileSync(filePath));
```

**Comment by towerofnix** [comment]
I believe you have to connect storage manually, by calling the `vm.attachStorage` function:

```js
const ScratchStorage = require('scratch-storage');
const storage = new ScratchStorage();
scVM.attachStorage(storage);
```

**Comment by benjiwheeler** [comment]
@steve-xmh did @towerofnix's answer solve your problem?

**Comment by Steve-xmh** [comment]
> @Steve-xmh did @towerofnix's answer solve your problem?

Solved, thanks for help!
