### ISSUE TITLE
"Say" and "Think" bubbles have different numeric precision

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-vm#2186]
### Expected Behavior

"Say" and "Think" bubbles should display the same output when given the same input, with the only difference being the shape of the bubble.

### Actual Behavior

~While visions of floating-point precision errors drift through Scratch Cat's thoughts, he is too shy to vocalize them~
"Say" bubbles are limited to 2 decimal digits of numeric precision, but "think" bubbles are not:
![image](https://user-images.githubusercontent.com/25993062/58531204-87da4780-81af-11e9-9cf3-1399f7474b25.png)

### Steps to Reproduce

1. Make a sprite "say" a number with more than 2 digits of precision
2. Make the sprite "think" the number

(Or see [this project](https://scratch.mit.edu/projects/313667447/editor/))

**Comment by fsih** [comment]
Decisions from design:
**Phase 1 - Say/Think/Ask Bubbles** 
We agree that all three of these bubbles should round (unlike 2.0 where Ask did not round) and that all three should to the same degree of precision (unlike current 3.0 implementation). 
Right now, it feels like the main tension between the following:
Biasing towards a lower floor by rounding to a lesser degree of precision. Thinking about the use case of reporting things like timer or more commonly used displays of values like money. 
Having a certain level of mathematical correctness and displaying more decimal places which would be closer to the actual value being returned / calculated

For Phase 1, we move forward with the original thinking of biasing towards the lower floor and keeping things consistent with 2.0:
IF the value was calculated by math operators or a returned value of a reported within a Say/Think/Ask block, THEN round to the degree of two decimal places and include a trailing `0` in cases where the value only has one value after the decimal place.
IF the value was directly input into a Say/Think/Ask block, THEN do not round and return the value as if it were a string.

In Phase 1, we get consistency in behavior across all bubbles and consistency with 2.0 behavior (or its intended behavior as Ask felt like an outlier).

**Future:**
Consider https://github.com/LLK/scratch-vm/issues/2342
