### ISSUE TITLE
GH-pages: icons missing

### ISSUE THREAD

**Issue by mrjacobbloom** [LLK/scratch-vm#219]
http://llk.github.io/scratch-vm/
The green-flag and repeat-arrow icons are showing for me as the "image missing" icon
![screen shot 2016-09-25 at 5 13 19 pm](https://cloud.githubusercontent.com/assets/2879020/18818944/6cfd406a-8343-11e6-89e5-be9b78abcc06.png)

**Comment by mrjacobbloom** [comment]
My console is full of 404 errors for image and sound files

**Comment by tmickel** [comment]
Likely that the URL for media is not quite right, I think...

**Comment by rschamp** [comment]
Thanks for the report @Airhogs777 — I'm going to close this as a part of PR #218 which hasn't been merged yet.
