### ISSUE TITLE
[feature] Group blocks by target type

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#220]

**Comment by CosmicWebServices** [comment]
Can you explain this a little more...

**Comment by tmickel** [comment]
@dekrain Hmm, yes, could you explain?

**Comment by dekrain** [comment]
For example, for stage is `change backdrop` and for sprite: `change costume`

**Comment by CosmicWebServices** [comment]
Ohhh

**Comment by tmickel** [comment]
That's one of the issues we're tracking here: https://github.com/LLK/scratch-blocks/issues/541 :)
