### ISSUE TITLE
Downloading and uploading a particular project with the pen extension to staging fails to re-load

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#2213]
### Expected Behavior

A project with the pen extension uploaded to staging should be able to be loaded after saving.

### Actual Behavior

The project https://scratch.mit.edu/projects/276932192 on production, when downloaded and uploaded again (as project https://scratch.ly/projects/1300004143) would not load.  It continued to load forever and looking in the console gave these errors:
![Screen Shot 2019-06-20 at 1 26 19 PM](https://user-images.githubusercontent.com/1088291/59868938-17fb4f00-9360-11e9-9f65-91c645f2a7bf.png)
![Screen Shot 2019-06-20 at 1 25 49 PM](https://user-images.githubusercontent.com/1088291/59868943-1a5da900-9360-11e9-93b3-d7dee6842e8b.png)

When it was first loaded (File>Load from your computer) it worked just fine in the editor. Upon reloading the page or any subsequent loads by other users, it would not load.

I suspect that it is an issue with saving as a result of https://github.com/LLK/scratch-vm/pull/2161 (and subsequent gui pr: https://github.com/LLK/scratch-gui/pull/4790) It likely has to do with the pen extension in that project.

It is possible to load the project back into production and reloading the page works fine there.

### Steps to Reproduce

Download the project 276932192 from production
On staging upload the project
Note: the project loads and you can run it.  Everything seems to work fine
Go to the project page
Note: it still works fine
Reload the page
Note: the project loads forever.  Check the console and see the errors.

The changes are being reverted, so it is likely that the 

### Operating System and Browser

Mac Chrome, Chromebook Chrome, Windows Firefox

**Comment by BryceLTaylor** [comment]
While loading the project into staging I got these errors in the console:
![Screen Shot 2019-06-20 at 2 08 01 PM](https://user-images.githubusercontent.com/1088291/59871212-f94b8700-9364-11e9-8fe6-9fe939291688.png)
![Screen Shot 2019-06-20 at 2 08 21 PM](https://user-images.githubusercontent.com/1088291/59871216-fc467780-9364-11e9-918c-eed9d8d6f556.png)

**Comment by BryceLTaylor** [comment]
Uploading another project that only has the blocks from the pen extension in it works fine.  it is the default project with one of each of the blocks from the pen extension added to it.
https://scratch.ly/projects/1300004171/

**Comment by BryceLTaylor** [comment]
After reverting the PRs mentioned above the error persists on staging.  It is most assuredly something else.

**Comment by rschamp** [comment]
This was an issue with our Fastly config, which was resolved on production but not in staging. We had a regex to recognize asset URLs but it did not recognize mp3 URLs. After resolving that and purging the 404ing asset URL, this project can be uploaded, saved and reloaded.
