### ISSUE TITLE
Replace Item "Last" Missing

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-vm#2219]
I have a small question about Scratch Lists.

In Scratch 3.0, the block of replaceitem last is no longer available. I cannot find any information about this and I actually need the block for the Scratch Wiki article of [Global Highscores](https://en.scratch-wiki.info/wiki/Global_High_Scores).

Any help would be appreciated.

ross

**Comment by apple502j** [comment]
well you can replace it with `(length of [list v])`
Duplicate of LLK/scratch-blocks#1335

**Comment by ghost** [comment]
Alright, thank you for the info.
