### ISSUE TITLE
The move speed is faster than Scratch GUI VM

### ISSUE THREAD

**Issue by alexwenbj** [LLK/scratch-vm#2281]
### Expected Behavior
The sprite's  "move x steps speed" in this "pure" VM is the same as the Scratch GUI VM

For example, 
```
forever  
    move 5 steps
```
program, the sprite should move at the same speed in this "pure" VM or in Scratch GUI VM.
### Actual Behavior
In this "pure" VM, the sprite moves faster than it in the Scratch GUI VM.

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/12047524/65437914-3ab56c00-de57-11e9-84e0-abd985caf656.png)

Run the above program in the scratch editor VM(`scratch.mit.edu`) and `llk.github.io/scratch-vm/`(disable the turbo mode), you can get the different speed.
### Operating System and Browser
Mac OS 10.14.6 +  Chrome 77.0.3865.90

**Comment by towerofnix** [comment]
scratch-vm runs at 60 frames per second by default. To match Scratch's 30fps, you'll need to call `vm.setCompatibilityMode(true)` in your own project.

**Comment by alexwenbj** [comment]
@towerofnix Thank you!
