### ISSUE TITLE
"Ask ... and wait" & "show variable" not work in scratch-vm VM

### ISSUE THREAD

**Issue by alexwenbj** [LLK/scratch-vm#2283]
### Expected Behavior
Show a prompt to accept user input for the block "Ask ... and wait",and show variable in the top-left side of canvas when check the variable.

### Actual Behavior

Does not show the prompt input and not show the variable in the canvas.

### Steps to Reproduce
1. Create a variable
2. Check the variable check-box.
3. Add "Ask what is your name and wait" block to a sprite.
4. Run it in this scratch-vm VM( not scratch-gui VM with editor),the variable is not shown and the prompt is not shown.

### Operating System and Browser

Mac OS 10.14.6  + Chrome 77.0.3865.90

But it is not affected by browser.

**Comment by apple502j** [comment]
This is because those things are handled in Scratch GUI.

**Comment by alexwenbj** [comment]
@apple502j Thank you.I know, but I don't understand, if the VM can't execute the project completely, what is the meaning of the existence of this standalone VM?

**Comment by apple502j** [comment]
VM runs project, send signals to GUI part and receives it. i.e. VM is blind.

**Comment by alexwenbj** [comment]
@apple502j Yeah,I know.What I want is just play the project, not need the editor GUI.The VM with GUI editor js file size is too large to me, so I think maybe I can use the VM only, but it doesnot support all the features.One more problem, see #2281 .

**Comment by alexwenbj** [comment]
@apple502j By the way,Where i can find all the VM APIs except review the source code?For example,how can I get the API for send "Ask...and Wait" signal and receive the answer, and so on.Thank you very much.

**Comment by apple502j** [comment]
@alexwenbj Why do you not review all the code?

**Comment by alexwenbj** [comment]
@apple502j I think maybe there is a simple way.

**Comment by apple502j** [comment]
Not really, and you can just search.
