### ISSUE TITLE
 How do I bind a block to a custom event? (that is how to parse the block)

### ISSUE THREAD

**Issue by King-hb** [LLK/scratch-vm#2290]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
![image](https://user-images.githubusercontent.com/14026774/66629649-f8e93b80-ec34-11e9-9aca-c634924edbd2.png)
How to read the workspace code block and bind custom events to make people move？
If we convert the block directly into an xml file, is it feasible to read the xml file to customize the event? If there is any good way? Or vm can provide a better way to help us achieve the functions shown in the figure above.

**Comment by benjiwheeler** [comment]
Looks like your project is cool! 

However, this issue does not seem to be a specific and answerable.

Please get more familiar with the code, and ask questions when there's something we or others could help answer.
