### ISSUE TITLE
Stage can stamp

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2297]
### Expected Behavior
Stage should do nothing for stamp block.

### Actual Behavior
It stamps.

### Steps to Reproduce
1. add a white background and black background
2.
```
switch backdrop to [black v]
stamp
switch backdrop to [white v]
```

### Operating System and Browser
Firefox 70 (x64) Windows 10

**Comment by BryceLTaylor** [comment]
Scratch 2 hangs when you try to stamp with the backdrop.  It does not stamp.

**Comment by BryceLTaylor** [comment]
It's also worth noting that in 2.0 the stamp block is not available to the stage and to try it you must "share the love" to it.

**Comment by apple502j** [comment]
WAI per https://github.com/LLK/scratch-gui/issues/2174#issuecomment-639068681
