### ISSUE TITLE
Cast - `isInt` method should attempt numeric conversion of strings

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#230]
The `isInt` method currently evaluates the string `"0.0"` as `false`.

From https://github.com/LLK/scratch-vm/pull/228

**Comment by tmickel** [comment]
It probably should be better documented and we could discuss, but the original point of `isInt` is to distinguish things like `0.0` from `0` when input by a user. Scratch will treat 0.0, 1.0, 2.0, 1.1, etc. as float values:

<img width="352" alt="screen shot 2016-10-03 at 5 35 04 pm" src="https://cloud.githubusercontent.com/assets/120403/19054987/ceebfa30-898f-11e6-9a1a-35943563c821.png">

In 2.0 this is determined by looking at if the string contains a decimal point, which is the same thing `isInt` does.

**Comment by thisandagain** [comment]
Got it. That seems reasonable.
