### ISSUE TITLE
BOOST extension "turn for rotations" block displays incorrectly in Spanish

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#2305]
### Expected Behavior

The BOOST extension's "turn for rotations" block should have a numeric input for rotations. 

### Actual Behavior

In Spanish, the input is broken:

![Screen Shot 2019-11-18 at 4 21 42 PM](https://user-images.githubusercontent.com/567844/69095122-aebb5d00-0a1f-11ea-9c6d-fbb88470b09a.png)

This appears to be due to a copy/paste error in the translation:
![Screen Shot 2019-11-18 at 4 23 59 PM](https://user-images.githubusercontent.com/567844/69095226-e2968280-0a1f-11ea-9fd1-36aa1e41d915.png)

cc @chrisgarrity

**Comment by chrisgarrity** [comment]
@ericrosenbaum I've changed the translations, so they should get picked up this week when I do an update of the blocks. There's an existing issue: https://github.com/LLK/scratch-l10n/issues/84 on scratch-l10n to add checking for extension placeholders.

**Comment by ericrosenbaum** [comment]
@chrisgarrity thanks!

**Comment by chrisgarrity** [comment]
Verified as fixed in the translation, closing.
