### ISSUE TITLE
touching mouse-pointer shoud not return true when mouse is outside stage

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2308]
It is possible to abuse this to make anti-remixer or something.

Pros:
* Prevents abusing it

Cons:
* Some project breaks - but who needs it?

**Comment by benjiwheeler** [comment]
@apple502j, do you have steps to replicate this? I tried, but `touching mouse pointer` seemed to only return false when the mouse was outside the stage.

![Dec-15-2019 03-02-51](https://user-images.githubusercontent.com/3431616/70873951-f0d3b200-1f7d-11ea-8eda-109a770a812c.gif)

**Comment by apple502j** [comment]
I'll contact-us you

**Comment by benjiwheeler** [comment]
Looks like this is already filed here, and I see how to repro it: https://github.com/LLK/scratch-gui/issues/5243
