### ISSUE TITLE
getListContents list.value.join('') 

### ISSUE THREAD

**Issue by errenxing** [LLK/scratch-vm#2310]
### Expected Behavior

contents joined together with no separator

### Actual Behavior
contents joined together with comma separator

**Comment by apple502j** [comment]
It's because you didn't put comma? If you pass empty string it will join without separator

**Comment by errenxing** [comment]
> It's because you didn't put comma? If you pass empty string it will join without separator

// Determine if the list is all single letters.
// If it is, report contents joined together with no separator.
 // If it's not, report contents joined together with a space.

above is the official notes

**Comment by errenxing** [comment]
> It's because you didn't put comma? If you pass empty string it will join without separator

thanks, 
var a = [1,2,3] 
var b = a.join('') // "123"
var c = a.join() // "1,2,3"
