### ISSUE TITLE
Why does code for starting `control_start_as_clone` hats live in initDrawable?

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-vm#2315]
### Expected Behavior

Code for starting `control_start_as_clone` hat blocks should live in a clone-related place in the codebase.

### Actual Behavior

Currently, `RenderedTarget.initDrawable`, whose documentation seems to indicate it is renderer-related ("Create a drawable with the this.renderer"), is [responsible for starting `control_start_as_clone` hat blocks](https://github.com/LLK/scratch-vm/blob/d47ea58bc3c1b8be6553a279ebfb4b4dc5e341a3/src/sprites/rendered-target.js#L177). Is there a reason for this?

**Comment by apple502j** [comment]
This code can be moved between L1007-L1008 of the same file (rendered-target.js)

**Comment by rschamp** [comment]
@tmickel Any idea?
