### ISSUE TITLE
Modules: 'fs' and 'child_process' are default modules in node.js. why compiled error as  "Module not found: Error: Can't resolve 'child_process' or 'fs' in '\Scratch3\scratch-vm\src\extensions\.."?

### ISSUE THREAD

**Issue by kevintu2007** [LLK/scratch-vm#2318]
[Issue Description] 

D:\Scratch3\scratch-vm\src\extensions\scratch3_test
 
[index.js]
  :
//add these default modules, as no required extra npm install
const fs = require('fs');
const childprocess = require('child_process');
 
after D:\Scratch3\scratch-vm\npm run watch

[got errors result]
   :
bytes {benchmark} [not cacheable] [built]
        + 504 hidden modules

    ERROR in ./src/extensions/scratch3_test/index.js
    Module not found: Error: Can't resolve 'child_process' in 'D:\Scratch3\scratch-vm\src\extensions\scratch3_test'
     @ ./src/extensions/scratch3_test/index.js 21:19-43
     @ ./src/extension-support/extension-manager.js
     @ ./src/virtual-machine.js
     @ ./src/index.js
     @ ./src/index.js
     @ ./src/playground/benchmark.js

    ERROR in ./src/extensions/scratch3_test/index.js
    Module not found: Error: Can't resolve 'fs' in 'D:\Scratch3\scratch-vm\src\extensions\scratch3_test'
     @ ./src/extensions/scratch3_test/index.js 19:9-22
     @ ./src/extension-support/extension-manager.js
     @ ./src/virtual-machine.js
     @ ./src/index.js
     @ ./src/index.js
     @ ./src/playground/benchmark.js
    Child worker:
         2 assets
        Entrypoint main = extension-worker.js extension-worker.js.map
           20 modules

Could any experienced fellows help to instruct this please? Thanks!

**Comment by apple502j** [comment]
Extensions are executed in your browser. Only compiling is done in Node.js.
If you want access to file, you may want to use `<input>` tag (in scratch-gui).

**Comment by kevintu2007** [comment]
Thanks! could you hint to use <input> tag (in scratch-gui) for the case?

why conduct to apply these two modules in extension block thus   
(1) 'fs': read data of a i.e. json file from a stored path.
(2) 'child_process': 
i.e.
var exec = require('child_process').exec;
var filename = 'test.py'
exec('python'+' '+filename, function(err,stdout,stderr){
  :
Thanks!
