### ISSUE TITLE
`goog` is not defined

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#232]
After merging #212 and our changes to the webpack/build system, there's an error:
https://llk.github.io/scratch-vm/#10015060 (go to the Pico sprite).

<img width="1248" alt="screen shot 2016-10-03 at 5 49 13 pm" src="https://cloud.githubusercontent.com/assets/120403/19055405/ba71b840-8991-11e6-9e82-7139cea3a677.png">

@rschamp

**Comment by tmickel** [comment]
it seems to be only `goog.array.equals` causing the problem

**Comment by tmickel** [comment]
I think it's that the procedure blocks expect access to `goog`, but that's not exposed to them under webpack. Considering this is just for experimenting, maybe I'll strip out the `goog` usage in scratch-blocks.

**Comment by rschamp** [comment]
If goog is required in the procedure blocks, we could provide it to them similarly. I think when I made the shim, the procedure blocks PR wasn't merged yet so I didn't notice it as a dependency.

**Comment by tmickel** [comment]
that makes sense-https://github.com/LLK/scratch-blocks/pull/656 :)
