### ISSUE TITLE
Is this still being actively maintained?

### ISSUE THREAD

**Issue by peabrainiac** [LLK/scratch-vm#2326]
This is more of a question than an actual issue with the code. Sorry if this isn't the right place to post this, but I don't know where else to ask.
I've been trying to see if I can help with a few optimizations here and there, but often noticed that these were already implemented as pull requests months ago but haven't been merged or updated ever since. Examples of this are #2239 and #2260 .

So, why haven't these been reviewed by now? I know these kinds of things can take quite a lot of time, but since these only change 1-2 lines of code each I would think that they shouldn't take too long to test and verify. Does that mean the developers aren't currently open to pull requests for small fixes and improvements like that?

Again, sorry if this isn't the right place to ask. I would really like to help with this project but am currently a little confused about how progress is being made here.

**Comment by brodycritchlow** [comment]
@peabrainiac 

Yes,

The project is still being actively maintained.  I hope. But when you have school, work, barely enough collaborators and 300+ issues. And more projects to work on that adds up to a busy work day. And it might be 1-2 lines of code for you, but they have to check if this could make a venerability, check their fix, make sure the fix didn't add any more bugs. 

I believe this was a good enough place to ask this question.
