### ISSUE TITLE
WeDo 2.0 isTilted-any function fails the threshold comparison

### ISSUE THREAD

**Issue by daikifukumori** [LLK/scratch-vm#2334]
### Expected Behavior

Only when the sensor steeply tilts (which means that the tilt sensor value is more than TILT_THRESHOLD=15), the following behaviors are expected:
- _isTilted function returns true
- "when tilted any"-block is triggered
- "tilted any ?"-block returns true

### Actual Behavior

Even when the tilt sensor value is less than TILT_THRESHOLD=15, the following behaviors happen:
- _isTilted function incorrectly returns true
- "when tilted any"-block is incorrectly triggered
- "tilted any ?"-block incorrectly returns true

### Steps to Reproduce

1. Add WeDo 2.0 extension on Scratch
2. Connect WeDo 2.0 Hub and tilt sensor
3. Put "when tilted any"-block and "tilted any ?"-block on Scratch
4. Change the tilt sensor's angle slightly like 1-5 degrees
5. See whether the "when tilted any"-block is triggered or not, and "tilted any ?"-block returns true or not

### Operating System and Browser

All Operating System and Browser with WeDo 2.0 tilt sensor

**Comment by fsih** [comment]
Related: https://github.com/LLK/scratch-vm/issues/2444 we are calling 256ths "angles"
I guess that explains why those constants weren't labeled; we didn't know what they were :p
