### ISSUE TITLE
Counter is not cleared by making new project

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2346]
### Expected Behavior
Counter (a hidden control block)'s value should be cleared when runtime is disposed.

### Actual Behavior
Counter is not cleared.

### Steps to Reproduce
You can get counter blocks by exporting the sprite on https://scratch.mit.edu/projects/45834258/editor/. After exporting it,
1) Import it.
2) Click increase counter block.
3) Click File->New.
4) Click counter block and see it says 1.

### Operating System and Browser
any

Related to #2340

**Comment by Kenny2github** [comment]
TIL Scratch 3.0 actually still implements those blocks
