### ISSUE TITLE
Proposal: Collision masks

### ISSUE THREAD

**Issue by cshaa** [LLK/scratch-vm#2350]
# The Problem
In professional game development, the **collision shapes of objects rarely exactly correspond to the rendered sprite**. There are many reasons for this, but most importantly it's to uncouple the gameplay from the artwork and animations. This way the animators have freedom to make the characters swing hands, for example, without having to worry they'll ruin the gameplay by making the collision mask too wide.

![image](https://user-images.githubusercontent.com/1671665/78978430-061ab080-7b1a-11ea-8f76-b76004607a6f.png) ![image](https://user-images.githubusercontent.com/1671665/78978554-45490180-7b1a-11ea-9384-85570a4a8ed7.png)

However, in Scratch the collision masks are hardwired to exactly match the sprites. Therefore it's **impossible to teach the students the concept** of collision masks without resorting to more complicated software (like [Godot](https://godotengine.org/)).

This causes real trouble when making platformers in Scratch, too. Animating a hero that extends their hand too far when walking presents a **real possibility of them getting stuck** on a platform.

![image](https://user-images.githubusercontent.com/1671665/78981609-93610380-7b20-11ea-9997-1d7c1985d600.png)

.

# The Proposed Solution
In most professional game studios, collision masks are entirely separate from sprites. They have their own UI and thier own file format. However, doing it this way would mean making Scratch much more complex and over-complicated for first-time users. In my opinion, this problem can be, _and should be_, solved without introducing significant changes to Scratch.

Ideally, we'd want to make the collision masks **entirely optional and as similar to the current collision checking as they can be**. Therefore I propose this mechanism:

* Every sprite has a _**current costume**_ property, which points to the costume it currently uses, and a _**current mask**_, which can point to a costume, or be `null`.
* In the renderer, only the _**current costume**_ is visible.
* The collision checker uses the costume from _**current mask**_, unless it's `null`, then it uses the _**current costume**_.
* The _**current mask**_ is `null` by default.
* There are two new blocks:
  * _**set mask to [costume]**_ – sets _**current mask**_ to the selected costume
  * _**reset mask**_ – sets _**current mask**_ to `null`

When a mask is set to “costume1”, collision checking works exactly as if the current costume was “costume1”, including color colisions. That means that if you have a **blue costume** and **purple mask**, the block _**color [blue] is touching [black]**_ will never be true, and _**color [purple] is touching [black]**_ is true if the mask touches something black.

Example code:

![image](https://user-images.githubusercontent.com/1671665/78979305-e1bfd380-7b1b-11ea-91a4-49af6c7ba6a1.png)

# Related issues
* #2076 **Collision Hitbox shrinks when sprite selected with mouse?**
* #2073 **Should Scratch 3 collisions be deterministic?**

**Comment by Kenny2github** [comment]
A lot of well-made platformers on Scratch currently use separate "hitbox" sprites, which have all the collision and game mechanics tied to them; then the animated, displayed sprite is just doing
```
forever
  go to [Hitbox v]
```
I don't think we necessarily need built in masks.

**Comment by BryceLTaylor** [comment]
There are a variety of solutions that you can do to implement this concept in Scratch right now, like the one @Kenny2github mentioned.  You can also make a hitbox costume and in a "run without screen refresh" block you can switch to that costume, check collisions, and then switch back.  You can also make AABBs using lists.
