### ISSUE TITLE
Placing a string beginning with "#" in a block's color input causes the VM to stop running scripts

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-vm#2355]
### Expected Behavior

You should never be able to cause the VM to error out and stop executing scripts simply by executing normal blocks

### Actual Behavior

If you drop any reporter returning a string beginning with the "#" character into a block's color input, and then execute that block, an error appears in the browser console and all scripts will stop executing until the green flag is pressed again.

### Steps to Reproduce

1. Drag a "touching color ()" block into the workspace
2. Drag a "join () ()" block into the "touching color" block's color input
3. Set the first text field of the "join" block to "#"
4. Set the second text field of the "join" block to some other string, e.g. "test" or "0"
5. Click the "touching color ()" block to execute it
6. Observe that any other running scripts no longer take effect, and an error appears in the browser console.

You can do this with any block that has a color input-- for instance, "touching color ()", "color () is touching color ()", and "set pen color to ()".

![image](https://user-images.githubusercontent.com/25993062/80831537-022dfb80-8bb9-11ea-94ad-1494857acd8a.png)

### Operating System and Browser

All

**Comment by BryceLTaylor** [comment]
While the console is filling up with errors, other loops stop running.  By clicking the block again, the other loops will start running again.

This test project shows that https://scratch.mit.edu/projects/391047180/

Clicking the green flag starts the cat spinning.  Then if you click the touching color block the cat stops and the console starts filling with errors.  If you click the block again, the errors stop and the cat starts spinning again.
