### ISSUE TITLE
Clones are not properly deleted when deleting sprite

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2357]
### Expected Behavior
If you delete a sprite, all of their clones would be deleted as well
### Actual Behavior
Some clones remain
### Steps to Reproduce
- Make a clone
- Delete the parent sprite
- The clone is still on the stage
### Operating System and Browser
Windows 10, Firefox 76

Thanks 4096bits for [reporting this](https://scratch.mit.edu/discuss/post/3990567/)!
My browser / operating system: Windows NT 10.0, Chrome Edge (the new one) 81.0.4044.129, No Flash version detected

**Comment by fsih** [comment]
@carljbowman @kathymakes what's the correct behavior here? In 2.0, when you delete a sprite, the clones remain. In 3.0, when you delete a sprite, we delete half of the clones (Can I use Thanos as a verb)

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-gui#2931
