### ISSUE TITLE
RenderedTarget.setSay is unused

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2414]
`RenderedTarget.setSay`, which only logs something, is currently unused. (Actual code for rendering the bubble is in `scratch3_looks` and scratch-render.)

**Comment by adroitwhiz** [comment]
This traces back to https://github.com/LLK/scratch-vm/commit/460760bd06cd5893e1a5f710a555e23316bf9e3e. Say/think bubbles were implemented in https://github.com/LLK/scratch-vm/pull/691 but that PR didn't remove the old stub `setSay`.
