### ISSUE TITLE
Help: detect motion from remote camera

### ISSUE THREAD

**Issue by hyansuper** [LLK/scratch-vm#2463]
I've roughly read the source code of [video sensing](https://github.com/LLK/scratch-vm/blob/develop/src/extensions/scratch3_video_sensing/) extension, [src/io/video.js](https://github.com/LLK/scratch-vm/blob/develop/src/io/video.js) and [scratch-gui/src/lib/video](https://github.com/LLK/scratch-gui/tree/develop/src/lib/video), to implement an extension that show remote camera video and detect motion in playground, I guess I need to write a "RemoteVideoProvider" like the [default video provider](https://github.com/LLK/scratch-gui/blob/develop/src/lib/video/video-provider.js) and use [setProvider()](https://github.com/LLK/scratch-vm/blob/develop/src/io/video.js#L74) method to set an instance of RemoteVideoProvider instead of the default local video provider, but where is the method [setProvider()](https://github.com/LLK/scratch-gui/blob/develop/src/lib/video/video-provider.js) called? I can't find it.

**Comment by apple502j** [comment]
Its public API is `VirtualMachine.setVideoProvider`, which is called [when the stage initializes](https://github.com/LLK/scratch-gui/blob/develop/src/containers/stage.jsx#L64)

**Comment by BryceLTaylor** [comment]
Thank you @apple502j
