### ISSUE TITLE
customized extensions failed to load

### ISSUE THREAD

**Issue by hyansuper** [LLK/scratch-vm#2473]
### Expected Behavior
I tried to add a customized extension:https://github.com/kebhr/scratch3-tello, it used to work a year ago. so I think maybe something has changed with the latest scratch3, that's why I am asking this here instead of the tello extension 
### Actual Behavior
when I click the customized extension, its blocks did not show, instead, an error in the console in chrome:
```
Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8601/tello' failed to load.
```
the error is different on firefox:
```
DataCloneError: The object could not be cloned.
```
### Steps to Reproduce
1. follow the last sections in https://github.com/LLK/scratch-gui/wiki/Getting-Started to install scratch-vm, scratch-gui and scratch-blocks
2. copy the [index.js](https://github.com/kebhr/scratch3-tello/blob/master/scratch-vm/src/extensions/scratch3_tello/index.js) into scratch-vm/src/extensions/scratch3_tello
3. add the line `tello: () => require('../extensions/scratch3_tello')` into scratch-vm/src/extension-support/extension-manager.js
4. add to scratch-gui/src/lib/libraries/extensions/index.jsx the following (https://github.com/kebhr/scratch3-tello/blob/master/scratch-gui/src/lib/libraries/extensions/index.jsx#L54):
```
import telloIconURL from './tello/tello.png';
import telloInsetIconURL from './tello/tello-small.png';
export default [
{
        name: (
            <FormattedMessage
                defaultMessage="Tello"
                description="Name for the 'Tello' extension"
                id="gui.extension.tello.name"
            />
        ),
        extensionId: 'tello',
        iconURL: telloIconURL,
        insetIconURL: telloInsetIconURL,
        description: (
            <FormattedMessage
                defaultMessage="Tello with Scratch 3.0"
                description="Description for the 'Tello' extension"
                id="gui.extension.tello.description"
            />
        ),
        featured: true
    },
...
...
```
5. also download [these image files](https://github.com/kebhr/scratch3-tello/tree/master/scratch-gui/src/lib/libraries/extensions/tello) to scratch-gui/src/lib/libraries/extensions/tello

### Operating System and Browser
ubuntu 18.04
Mozilla Firefox 77.0.1
chrome: Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by apple502j** [comment]
index.jsは呼び出されていますか。/is index.js executed?

**Comment by hyansuper** [comment]
thanks for your fast reply.
I put `console.log('*****')` at first line in index.js and it's not shown in console when I click the extension. I think index.js is not executed. why is that?

**Comment by apple502j** [comment]
try adding console.log to extension-manager.js L150 - does it run?

**Comment by hyansuper** [comment]
No, I add console.log at [here](https://github.com/LLK/scratch-vm/blob/develop/src/extension-support/extension-manager.js#L150) but I don't see the message printed in browser's console.
Other builtin extensions can work but also no printed message

**Comment by apple502j** [comment]
Are there any errors on the browser console?

**Comment by hyansuper** [comment]
yes, errors are as I described above 
> when I click the customized extension, its blocks did not show, instead, an error in the console in chrome:
> 
> ```
> Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8601/tello' failed to load.
> ```
> 
> the error is different on firefox:
> 
> ```
> DataCloneError: The object could not be cloned.
> ```
>

**Comment by apple502j** [comment]
So, no errors other than that? strange. try console.log in extension-manager but next time in line 157

**Comment by hyansuper** [comment]
I put console.log at line 157 and also at first line in the `loadExtensionURL (extensionURL)` function, still no coresponding output in browser console. seems like the function `loadExtensionURL (extensionURL)` is not called at all?
ps: I actually don't know if extension-manager.js is run on browser or on nodejs server side

**Comment by apple502j** [comment]
Any code will run on browser side.

**Comment by hyansuper** [comment]
Oh, I had some problem with npm linking, scratch-gui did not link to my scratch-vm folder but installed its own scratch-vm, somehow still shows the tello extension in the extensions page, making me think that npm linking is right, but it's not.
Thank your and really sorry to bother you
