### ISSUE TITLE
How to show peripheral connection status icon

### ISSUE THREAD

**Issue by hyansuper** [LLK/scratch-vm#2475]
I am making a customized extension for my robot connected via websocket. How do I show the connection status icon above all the extension blocks and change the icon according to peripheral connection status?
I read [io.ble.js#L63](https://github.com/LLK/scratch-vm/blob/develop/src/io/ble.js#L63), so I tried putting `runtime.emit(runtime.constructor.PERIPHERAL_CONNECTED);` in my extension block constructor, but the connection icon didn't show.
Thank you

**Comment by ericrosenbaum** [comment]
Hi @hyansuper! You may just need to set the `showStatusButton` property to true in your extension (like the one [here](https://github.com/LLK/scratch-vm/blob/b67ba75d8b1df4268a9d6727bbc4f32f153c9131/src/extensions/scratch3_microbit/index.js#L591)). Other changes may also be needed to get it fully working- feel free to re-open this issue or create a new one, but I will close this for now.
