### ISSUE TITLE
504 gateway timeout at text to speech extension

### ISSUE THREAD

**Issue by BoomerScratch** [LLK/scratch-vm#2485]
### Expected Behavior

TTS works.

### Actual Behavior

A 504 error occurs when using the text to speech tenor voice. I'm not sure if this needs to be reported, or this is a duplicate, but a lot of people are posting bug reports about the TTS extension on the bugs and glitches forum.
[log](https://github.com/LLK/scratch-vm/files/4799352/default.log)

### Steps to Reproduce

1. Add the TTS extension.
2. Switch to tenor voice.
3. Run the `speak []` block.

### Operating System and Browser

All

**Comment by ericrosenbaum** [comment]
thanks @BoomerScratch - we're investigating

**Comment by ericrosenbaum** [comment]
We've deployed a fix- looks like it's working fine now.
