### ISSUE TITLE
Add "stretch" graphic effect

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#249]
This would be really easy to implement cause it would just be changing the scale when rendering and adding a few blocks. (For Example Of Base Code See #261)
### Mockup

![capture](https://cloud.githubusercontent.com/assets/17478432/19403308/424e5476-9234-11e6-8759-b232201ea851.PNG)

![capture2](https://cloud.githubusercontent.com/assets/17478432/19410996/d6118178-92c6-11e6-8bfe-0ecdd5e39fa9.PNG)

**Comment by TheBrokenRail** [comment]
Should I make A PR on scratch-blocks that adds the blocks?

**Comment by tmickel** [comment]
@TheBrokenRail We can't take any PRs that add new feature-related blocks at this time without significant design discussion first.

**Comment by TheBrokenRail** [comment]
Any Discussion or updates about design and stuff?

**Comment by TheBrokenRail** [comment]
I added a mockup!

**Comment by CosmicWebServices** [comment]
[offtopic] @TheBrokenRail  what is your scratch username

**Comment by TheBrokenRail** [comment]
Comments, Questions, Design Questions, What do you think of my mockup (really just a fork of scratch-blocks)?

**Comment by TheBrokenRail** [comment]
Any Comments?

**Comment by CosmicWebServices** [comment]
Let me look for a minute or two...

**Comment by CosmicWebServices** [comment]
Does it stretch the whole x or the whole y up and down or just the top of the image or the bottom of the image... If that makes sense?

**Comment by CosmicWebServices** [comment]
Also, I think the mockup looks great and is understandable but could it be considered a motion block?

**Comment by TheBrokenRail** [comment]
The Whole Axis Stretches and I don't think it would be a motion block because it doesn't change position or rotation and it is a cosmetic effect

**Comment by TheBrokenRail** [comment]
@tmickel

**Comment by griffpatch** [comment]
You could even consider this an effects block named squeeze that multiplies the width. 100% being normal relative to current size, 50% being half width and 100% height still. The only reason for doing it like this is to try to reduce the number of new scratch blocks ;). You still want it to apply 'before' the rotation.

**Comment by griffpatch** [comment]
Maybe that's a silly idea... You wouldn't want the width to be reset when doing a reset all effects?

**Comment by TheBrokenRail** [comment]
It actually is not that bad, it would make things simpler to understand for new scratchers and you would think logically if a reset all effects block was used the sprite would return to normal and instead of stretch x/y reporters you could add graphics effects reporters which could be useful for other effects as well.


________________________________

**Comment by TheBrokenRail** [comment]
## Concept 2
![capture](https://cloud.githubusercontent.com/assets/17478432/21956720/6f17d8d4-da54-11e6-9a8d-26baf458773c.PNG)

**Comment by griffpatch** [comment]
I noticed that to be able to implement stretch blocks using this method was actually quite easy as all the work required is already done in scratch-render. So here is a branch with working 'scalex & scaley' blocks.

https://github.com/griffpatch/scratch-vm/tree/stretch

Running from this branch, try loading project: #185360912

I implemented a scalex & scaley graphics effect using the existing scale array that is used for flipping non rotating left right sprites. The functionality maintains the ability to use left right flipping sprites also and will still maintain their scalex & y proportions.

With these blocks we can now have rotating sprites that can face both ways without an extra costume, plus we can 'squish' and 'squeeze' sprites too :) - I guess we'd want to place a bound on the min / max size as we do with the 'size' block?

Anyhow, as you can see, it's a pretty simply change. All that needs doing to is to add the effect types to the effect block drop down?

Any thoughts?  I didn't create a PR as this was only a feature request in the backlog and not flagged as urgent or necessarily even going to be considered. However, here it is :)

Griffpatch

**Comment by TheBrokenRail** [comment]
Any Updates?

**Comment by TheBrokenRail** [comment]
Any News?

**Comment by thisandagain** [comment]
@TheBrokenRail We'll evaluate this and many other feature requests over the coming months. Please do not bump old requests.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/982
