### ISSUE TITLE
[PR-In-Progress] Custom Reporter Issue

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#250]
### Expected behavior

_It would work with yielding blocks and return values_
### Actual behavior

_It just gets stuck_
### Steps to reproduce

_Clone and build my fork and make a custom reporter and run it_
### Operating system and browser

_Windows 10 AU Microsoft Edge_
### Clone It At:

_https://github.com/TheBrokenRail/scratch-vm.git_

**Comment by tmickel** [comment]
We have to limit issues on this repository to those in the main codebase, not forks. Custom reporters haven't been implemented and any discussion/thoughts about implementation could happen in #79.
