### ISSUE TITLE
[bug] Lists reporters just report its name

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#251]
### Expected behavior

Lists should report its contents
### Actual behavior

Lists reports its name
### Steps to reproduce

Just drag list reporter to join block and click it
### Operating system and browser

Tested on Chrome on Windows and Android, but it should can reproduce on every device

**Comment by tmickel** [comment]
Thanks for the report, that's a good catch. I think it's because we named the `data_list` block to `data_listcontents`. Needs to be updated here:
https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_data.js#L20
