### ISSUE TITLE
 ArgumentType.MATRIX

### ISSUE THREAD

**Issue by sugar-tong** [LLK/scratch-vm#2515]
I find official microbit blocks has a ArgumentType.MATRIX.
image
Recently, I want to create extension blocks for MAX7219. MAX7219 has 8X8 led on it. May I know how to create a new ArgumentType.MATRIX for 8*8 led? Is it possible to create a new ArgumentType in Scratch3?
image

**Comment by ericrosenbaum** [comment]
We have PR's from a contributor for an 8x8 matrix, but I haven't had the chance to review and merge them yet. You can have a look and use them locally if you want:
https://github.com/LLK/scratch-blocks/pull/1977
https://github.com/LLK/scratch-vm/pull/2246
