### ISSUE TITLE
how to support chinese

### ISSUE THREAD

**Issue by yonghuming** [LLK/scratch-vm#252]
### Expected behavior

how to select different languages?
### Actual behavior

the scartch vm could not change different language
### Steps to reproduce

just run scratch-vm
### Operating system and browser

client:windows 10,chrome
server:ubuntu 14.04 x64

**Comment by CosmicWebServices** [comment]
scratch-vm is just a testing environment I think that language translations will be added when Scratch 3 is released.

**Comment by tmickel** [comment]
Exactly what @CosmicWebServices said. scratch-vm is intended to be the backend/core for running Scratch projects; we'll be adding languages to the Scratch Blocks and Scratch GUI projects when the time is right: https://github.com/LLK/scratch-blocks/issues/20
