### ISSUE TITLE
the latest google chrome version 84.0.4147.89 can't establish connection with scratch-link

### ISSUE THREAD

**Issue by MatataLab** [LLK/scratch-vm#2524]
### Expected Behavior

after I update google chrome version 84.0.4147.89 on my windows 10 version 1909.  I can't establish connection with scratch-link,
here is the log(I use microbit):

```
projects.bundle.js:31 Translation for "microbit.tiltDirectionMenu.any" in "en" is missing
(anonymous) @ projects.bundle.js:31
projects.bundle.js:150 WebSocket connection to 'wss://device-manager.scratch.mit.edu:20110/scratch/ble' failed: Error in connection establishment: net::ERR_SSL_OBSOLETE_VERSION
value @ projects.bundle.js:150

```

and then I tried it with Microsoft edge, It will not happen this error.
and I also tried google chrome version 83.0.4103.106, It also will not happen this error.

I’m not sure if this is a issue with Google Chrome or the vm socket is defective.

### Actual Behavior

the BLE Pop-up prompt is:

1. Make sure you have Scratch Link installed and running
2. Check that Bluetooth is enable

### Steps to Reproduce

just call BLE connect

### Operating System and Browser

OS: windows 10 version 1909
Browser: google chrome version 84.0.4147.89

**Comment by apple502j** [comment]
@MatataLab  Scratch Link was recently updated. Did you update it?
Cannot repro on Scratch Link 1.3.57 (949d6ed)

**Comment by YanMinge** [comment]
Yes, I have update the scratch-link version to 1.3.57. 
It seems that this issue is only related to the Google Chrome version.

This issue will not happen again if I used browser edge or roll back the Google Chrome version to  83.0.4103.106. It has nothing to do with the version of scratch-link

**Comment by apple502j** [comment]
Can repro now on Chrome 84, Scratch Link 1.3.57 - I think I messed something 7 hours ago
also @BryceLTaylor This is probably LLK/scratch-link issue

**Comment by cwillisf** [comment]
Tracking this in LLK/scratch-link#179
