### ISSUE TITLE
Request: Type definitions for extensions

### ISSUE THREAD

**Issue by Richienb** [LLK/scratch-vm#2533]
It would be useful for there to be Typescript definitions so that Intellisense would work when developing extensions.

**Comment by apple502j** [comment]
Currently Scratch does not use TypeScript. Maybe you can convert https://github.com/LLK/scratch-vm/blob/develop/src/extension-support/extension-metadata.js to TypeScript definitions?

**Comment by Richienb** [comment]
@apple502j Are there definitions for the `Scratch` variable exposed to global?

**Comment by Richienb** [comment]
Also, where should I put the type definitions?

**Comment by apple502j** [comment]
> Currently Scratch does not use TypeScript.

this is example:

```
/**
 * @typedef {object} Scratch
 * Scratch object exposed to extensions
 * @property {object.<string, string>} ArgumentType - represents what can be inserted to the argument
 * @property {pbject.<string, string>} BlockType - represents the block's shape
 * @property {object.<string, string>} TargetType - represents the targets the block will be displayed on the toolbox
 * @property {object.<ExtensionWorkerSubset>} extensions - represents extension worker subset

* @typedef {object} ExtensionWorkerSubset
* @property {function} register - function to register extensions
**/
```

**Comment by Richienb** [comment]
@apple502j And where should I put the typings?

**Comment by Richienb** [comment]
@apple502j [BlockType](https://github.com/LLK/scratch-vm/blob/develop/src/extension-support/extension-metadata.js#L18), [ReporterScope](https://github.com/LLK/scratch-vm/blob/develop/src/extension-support/extension-metadata.js#L23) and [ArgumentType](https://github.com/LLK/scratch-vm/blob/develop/src/extension-support/extension-metadata.js#L33) is not declared.

**Comment by apple502j** [comment]
@Richienb They are all string enums.
Again, **TypeScript is not supported, so there is no place to put typings.**

**Comment by Richienb** [comment]
@apple502j What are the possible values for the enums?

**Comment by apple502j** [comment]
See argument-type.js, block-type.js and target-type.js at https://github.com/LLK/scratch-vm/tree/develop/src/extension-support

**Comment by Richienb** [comment]
@apple502j Are `ArgumentType`, `BlockType` and `TargetType` all properties of `Scratch`?

**Comment by apple502j** [comment]
@Richienb yes.

**Comment by Richienb** [comment]
PR opened at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46522

**Comment by Richienb** [comment]
[`@types/scratch-env`](https://www.npmjs.com/package/@types/scratch-env) has been published! Thanks for all the help!
