### ISSUE TITLE
Video motion value for sprite is always zero until the sprite is interacted

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2541]
### Expected Behavior
As long as the user accepts video, video motion value is set correctly.

### Actual Behavior
Until the sprite is interacted, motion for the sprite is always 0 and direction is always -1. Values for stage are correct. There is no error on console.

"Interacting" includes:
- dragging, either on editor or on player (by set drag mode)
- clicking the sprite
- using say block, think block or ask block
- changing sprite selection from other sprite to the sprite
- using touching color/object block
- stamping

"Interacting" does not include:
- changing x/y
- changing direction
- changing draggability
- changing rotation style
- changing costume
- changing size
- changing graphic effect
- show/hide
- changing layer
- changing video transparency
- switching video on/off/flipped
- using pen extension (except stamp)

### Steps to Reproduce
1. Make a project using "when video motion > 0" block
2. Save and reload
3. Allow video permission
4. Dance (script not executed)
5. Interact with the sprite (script get executed)

### Operating System and Browser
Firefox 79 Windows 10

[original repro by Blue_Science](https://scratch.mit.edu/discuss/post/4276336/): My browser / operating system: Ubuntu Linux, Firefox 79.0, Flash 32.0 (release 0)

**Comment by ericrosenbaum** [comment]
e.g. my falling sprites project seems broken: https://scratch.mit.edu/projects/276660492/

**Comment by apple502j** [comment]
@ericrosenbaum @BryceLTaylor Can you bump this to priority 2? Search shows that [15 issues are marked with High Severity, Medium Impact and priority 2](https://github.com/search?q=org%3Allk+label%3A%22High+Severity%22+label%3A%22Medium+Impact%22+label%3A%22priority+2%22&type=Issues) while [9 issues are marked with priority 3](https://github.com/search?q=org%3Allk+label%3A%22High+Severity%22+label%3A%22Medium+Impact%22+label%3A%22priority+3%22&type=Issues) and this is not an environment-specific bug or anything that is hard to repro.
