### ISSUE TITLE
Events about variable updates

### ISSUE THREAD

**Issue by Ryuurock** [LLK/scratch-vm#2545]
https://github.com/LLK/scratch-vm/blob/5f101256434b21035e55183d4e0e4c2d1e5936fa/src/blocks/scratch3_data.js#L54-L65

Should the targetUpdate event or monitorUpdate event be triggered here? Variables that are not currently displayed cannot detect change events

**Comment by apple502j** [comment]
Monitor events are triggered in the monitor thread - at https://github.com/LLK/scratch-vm/blob/develop/src/engine/execute.js#L89

**Comment by Ryuurock** [comment]
> Monitor events are triggered in the monitor thread - at https://github.com/LLK/scratch-vm/blob/develop/src/engine/execute.js#L89

Undisplayed variable updates will not trigger events

**Comment by apple502j** [comment]
@Ryuurock  Yes, for performance reasons. Vanilla scratch does not need such events
