### ISSUE TITLE
Min/max scale doesn't match Scratch 2.0

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#255]
Currently it's set to 5%/500% respectively.

However, it appears to have been set based on a function of costume width/height:

https://github.com/LLK/scratch-flash/blob/a931df6ab30e34a1cb2d6f7288f99df1c8f7f49b/src/scratch/ScratchSprite.as#L253

To pull that off, I think we'll need to provide costume/width height from the renderer.

**Comment by tmickel** [comment]
Verification that this is based on costume size, not raster bounds size: https://scratch.mit.edu/projects/125172893/

**Comment by Tymewalk** [comment]
I don't really understand. What's the problem? Why can't we just cap the min/max to 5/500%?

**Comment by mrjacobbloom** [comment]
> I don't really understand. What's the problem? Why can't we just cap the min/max to 5/500%?

Imagine a 1x1px costume. If it could only grow to 500% of its original size it could only become 5x5px. If the scale limit was based on the size of the costume then you could make it 360x360 (3600%) and it would still fit on the stage, which is what we want.
Now imagine a 360x480px costume. It could become 5x as big as the stage (500%), which is also a problem.

Deciding the scale limits by costume size means that the sprite never gets small enough to disappear and never gets big enough to ruin everything. This helps new programmers never lose their sprites. And it means that they won't get confused by not being allowed to make their tiny-costumed sprites very big.

**Comment by Tymewalk** [comment]
I'm not sure about minimum size, but maximum can be calculated like so:

```
maxSize = math.min((stage.height / costume.height) * 100, (stage.width / costume.width) * 100)
```
