### ISSUE TITLE
"When I Receive" will stop execution of blocks initiated by message when a subsequent message is received

### ISSUE THREAD

**Issue by ronilan** [LLK/scratch-vm#2553]
### Expected Behavior

When a message is received all blocks below `When I Receive` should execute. When two messages are sent one after the other all blocks below `When I Receive` should execute twice. Same for any number of messages. 

Above should be independent of what the blocks are. 

Specifically, in cases where `When I Receive` has a `wait` block attached, a subsequent message may be received while blocks are still executing. That second message should not effect the execution of the blocks triggered by the first message. Same for any number of messages.

### Actual Behavior

In cases where `When I Receive` has a `wait` block attached, a subsequent message received while blocks are executing cancels the execution triggered by the first message. 

### Steps to Reproduce

See this: https://scratch.mit.edu/projects/416122680

Any click on the Sprite should increment both variables. This is not the case. "Fast clicks" will demonstrate that the blocks after the `wait` are not executed due to a subsequent message canceling execution of prior. Only last message will execute all.

### Operating System and Browser

Any (confirmed Mac OS Chrome, Windows 10 Chrome, iOS Safari)

**Comment by apple502j** [comment]
Potentially intended behavior since the block is set to "restart existing threads" - https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_event.js#L60

**Comment by ronilan** [comment]
I see how it can be deliberate since `When this sprite clicked` acts the same (see here: https://scratch.mit.edu/projects/416353576/) Not sure if this is the desirable behavior. It breaks user expectations (and limits some basic things). Was it same in Scratch 2.0?

**Comment by apple502j** [comment]
There is no option to run twice. It's either "stop and restart" or "don't run at all".

**Comment by ericrosenbaum** [comment]
This is the "expected" behavior (even if it seems unexpected!). it matches Scratch 2.0, so we need to keep it as-is to preserve compatibility with existing projects.
