### ISSUE TITLE
Feature Request: Inline JS

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-vm#2569]
Just like C can use the `__asm__` for inline assembly, we can have inline JS code as a block, in a new category, known as the technical category. This category can have inline code blocks that accept inputs. The only way that this code can report values is to use the return keyword. The block can be shaped like this:
<Run JS function [NAME] (Inputs)> if the return value is boolean, and 
(Run JS function [NAME] (Inputs)) if the return value is others.
```js
function inline_code(arg1,arg2) // If this part is changed, the inputs on the block will change. the inline_code determines the name
{
// Code...
return null; // Defaults to no return value
}
```

This is intended for those who write encryptions or other things with Scratch, so we can also have:
```js
encrypt("aes128","password","string"); // of course, a decryption function
guard(condition) else{};// This one is to allow the code to run only if the cond is satisfied.
```

**Comment by apple502j** [comment]
Scratch is designed to be a language that can be run safely - running JavaScript will not be safe. You can mod it but, be careful of the dangers of XSS!

**Comment by ghost** [comment]
> Scratch is designed to be a language that can be run safely - running JavaScript will not be safe. You can mod it but, be careful of the dangers of XSS!

Well, we can have potentially dangerous stuff like `document.write` removed.

**Comment by apple502j** [comment]
There are ways to bypass this. `safe-eval` has unpatched sandbox escape and I know others too.

**Comment by ghost** [comment]
> There are ways to bypass this. `safe-eval` has unpatched sandbox escape and I know others too.

I mean that we can have safe-eval removed as well.

**Comment by apple502j** [comment]
Hm what? I mean, there is no safe way to implement this because it's practically impossible to remove dangerous stuff.

**Comment by ericrosenbaum** [comment]
I agree that this is potentially unsafe for Scratch, no matter how it is implemented. For people who are interested in combining blocks with javascript, you can try the Snap! programming language, which has functionality much like what was suggested here: a block that lets you enter and run javascript functions, get their return values, etc. https://snap.berkeley.edu/search?query=javascript

**Comment by ericrosenbaum** [comment]
see also: https://snap.berkeley.edu/project?user=pkmnq&project=Why%20running%20arbitrary%20JavaScript%20is%20bad
