### ISSUE TITLE
Sequencer.retireThread is not erasing thead.stackFrames

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2574]
### Expected Behavior
Sequencer.retireThread erases `stackFrames`

### Actual Behavior
It does not, it sets `thread.stackFrame` (unused anywhere else) instead of actual attribute `stackFrames`. This may have caused some memory leaks, but I'm not sure.

### Steps to Reproduce
1. Read source code.
2. Debug thread code.
3. https://github.com/LLK/scratch-vm/blob/develop/src/engine/sequencer.js#L355

**Comment by BryceLTaylor** [comment]
If we find that this causes user facing problems we can reopen this issue, but until then, I'm closing it.
