### ISSUE TITLE
incorrect behavior of moveSteps and pointInDirection blocks

### ISSUE THREAD

**Issue by houcy** [LLK/scratch-vm#2583]
### Expected Behavior
Create a simple program with moveSteps and pointInDirection blocks, the full program looks as blow(pseudo code):

when click green flag
move to x(0) y(0)
loop forever:
     face to 90 degree
     move 100 steps
     face to 180 degree
     move 100 steps
     face to -90 degree
     move 100 steps
     face to 0 degree
     move 100 steps

The expected behavior is that the sprite can move 100 steps again and again to make a rectangle graph.
**Please see the program here:
https://scratch.mit.edu/projects/421480678**

### Actual Behavior
Actually, only the last block takes effect, the sprite moves 100 steps facing to 0 degree and stay in place. The sprite doesn't move 100 steps and turn around forever.

### Steps to Reproduce
Make a simple program like above pseudo code.

### Operating System and Browser
Windows desktop and online verion.

**Comment by apple502j** [comment]
It actually moves (is obvious when you have pen) - it's just so fast that it can finish in one frame.
I think this is working as intended. You can slow it down using "wait 0 seconds" block - so try it. Please do not make motion blocks wait for one tick, we sometimes need fast render too.

**Comment by houcy** [comment]
hmm, the behavior is weird, the sprite at best shows moving around very fast which is our expected behavior. Maybe you can add wait 0 second block at the background in hidden and show the expected behavior implicitly to user. Users don't care the internal implementation but the actual behavior. This way it can make sense.

**Comment by apple502j** [comment]
For me it does not make sense for motion blocks to yield, because the block does not say it waits. If you want to see sprites moving, pen can be used to track their trails.

**Comment by houcy** [comment]
Let's think this problem from users' point of view. Users want to see the sprite is moving instead of staying in place. Sometimes, users also dont' want to see the trails. In a word, moving, not in still and without trails. That's the users'  expectation. The second, from physics point of view, move x steps with some speed in a certain time. But in code implementation, the sprite moves to destination directly. 
As for wait 0 second block, its function is no need to wait, but actually it seems its behavior is not in line with its name.

**Comment by apple502j** [comment]
It actually moves, but does not appear as moving, because the blocks inside forever loop are executed in one frame. "the sprite moves to destination directly" is just visual thing.
This is a big breaking change and should not be introduced lightly.

(also, if i remember correctly, "wait 0 secs" does not actually wait for 0 seconds - it waits for one frame. you can wait for 1/30 secs if you want, and the result should be same)

**Comment by houcy** [comment]
Yes, this is a big change, I agree with you here. The best option is to keep everything remaining the same. Thanks for your kindly reply!
