### ISSUE TITLE
How can I start to contribute to the project?

### ISSUE THREAD

**Issue by champierre** [LLK/scratch-vm#260]
I developed some ScratchX extensions like Scratch2HTML(https://github.com/champierre/scratch2html), Scratch2MiP(https://github.com/champierre/scratch2mip).

I am interested in Scratch 3.0 very much and want to contribute.
Could you give me guideline or small advice about how I can start to contribute?

**Comment by TheBrokenRail** [comment]
I think there is a file called CONTRIBUTING.md that might help in the root of the project

**Comment by champierre** [comment]
Thank you very much. Sorry that I missed that. I will look through it.

**Comment by towerofnix** [comment]
Meta - should this have the question label? :)
