### ISSUE TITLE
Set size does not work if sprite is small (<10px width)

### ISSUE THREAD

**Issue by MarcusOtter** [LLK/scratch-vm#2643]
### Expected Behavior

I expect the sprite to be sized to X when I use the "Set size to X%" block.
This is not the case when the width of the sprite is small. I don't know exactly what width, but less than 10 px does the trick.
This seems like buggy behavior to me.

### Actual Behavior

It gets set to seemingly arbitrary values, for example, in my repro below, I try to resize the lowercase letter L to 25% size, but it gets resized to 78%.

![Screenshot of the problem](https://user-images.githubusercontent.com/35617441/96910391-ba20cf00-149f-11eb-88ed-669e2d43aab6.png)

### Steps to Reproduce

Here's a minimal repro trying to resize the lowercase letter L: ~~https://scratch.mit.edu/projects/439821699.~~ removed
You can also look at the screenshot above.

### Operating System and Browser

Windows 10, Firefox

**Comment by apple502j** [comment]
Works as intended. Sprites cannot be too small or too large.
There's a way to bypass this by switching costumes - but who needs a costume that small?

**Comment by MarcusOtter** [comment]
Thanks for the reply @apple502j
In my use case, I'm making a simple text renderer. I just made ~100 costumes (one for each character) with default text size, only to realize that some of the characters got different sizes than others. For example, i, L, and ! behaved differently than o, m, e, etc.
It took some debugging to figure out what the problem was. I will have to resize all 100 characters to be bigger now, and I don't really know how wide they need to be for me to be able to scale them down to any given number between 1-100 (maybe that's never possible?)

On second thought, I just tried manually setting the size of the letter to 25% which didn't work either, so I guess it shouldn't have been that hard to guess. Still feels like pretty buggy behaviour, what's the reason for this exactly? Risk of sprites/letters not being visible?

**Comment by MarcusOtter** [comment]
I think this is a related discussion, and as @apple502j says it seems intentional, so I'm closing this issue.
https://github.com/LLK/scratch-gui/issues/533

The workaround of changing the costume to a large one, changing the scale, and then changing to the desired sprite works well.
