### ISSUE TITLE
Performance degradation when moving sprite within non-refresh loop

### ISSUE THREAD

**Issue by RokCoder** [LLK/scratch-vm#2669]
### Expected Behavior

Movement of a sprite within a non-refresh loop should not impact upon performance

### Actual Behavior

Movement of a sprite within a non-refresh loop impacts upon performance. This is a fairly recent regression and is most noticeable in pen-based projects that move the pen many times per frame.

### Steps to Reproduce

This is a stripped down project that displays the behaviour - https://scratch.mit.edu/projects/445111877/

### Operating System and Browser

Windows 10 Enterprise - Version 1909
Chrome - Version 86.0.4240.183 (Official Build) (64-bit)

**Comment by BryceLTaylor** [comment]
@RokCoder  Can you describe the performance impact?  What is that project supposed to be showing me?  What does it show you?

**Comment by RokCoder** [comment]
<img width="483" alt="Screenshot 2020-11-05 at 23 28 21" src="https://user-images.githubusercontent.com/20208339/98307924-d3a53900-1fbe-11eb-8082-b6d5c9f97691.png">
It is expected that the animation should run at 30fps when updating the sprite's x coordinate in a non-refresh loop the same as it does when updating a variable in a non-refresh loop. This was the outcome in Scratch 2.0 and in the early days of Scratch 3.0. At a date between the middle of September and the middle of August the performance regressed noticeably. The screenshot displays that the updating of the x coordinate is much slower than the updating of the variable (10 seconds for 300 iterations as expected as opposed to over 12 seconds for 300 iterations). This is a very cut down project to demonstrate the performance hit is due to simply modifying the x coordinate. The fact it runs at far less than 30fps now is very clear on the original project that it is remixed from.

**Comment by RokCoder** [comment]
It's also worth noting the comment from @kriblo -

"Out of curiosity, I ran a quick test to see how other sprite-appearance-altering blocks would fare... For instance, setting the size of the sprite to a random number between 99 and 101, 2000 times each iteration, in a non-refresh block, yields a result similar to when updating a variable (around 10 seconds)."

I also noted that the performance regression is evident no matter what size of sprite is used or whether the sprite is hidden or not.

**Comment by apple502j** [comment]
Doesn't seem to be able to repro on Firefox 82, both are around 10sec

**Comment by RokCoder** [comment]
That is interesting! I just tested on Safari and it doesn't repro there either. It has a large impact in Chrome though.

**Comment by kriblo** [comment]
I tested it on Edge version 86.0.622.63 and it doesn't repro. My Windows Chrome version, were this issue is obvious, is 86.0.4240.183.

**Comment by RokCoder** [comment]
So it seems Chrome specific (also apparent on MBP Chrome Version 86.0.4240.75). Hopefully this is something that can be addressed as it's unfortunately not a nominal performance degradation.

**Comment by RokCoder** [comment]
This issue now appears to have been fixed. Is this a result of https://github.com/LLK/scratch-vm/pull/2203?

**Comment by BryceLTaylor** [comment]
Since it appears to have been fixed, I'm closing this issue.
