### ISSUE TITLE
Pen position (or size) has altered since the release of Scratch 3.0

### ISSUE THREAD

**Issue by RokCoder** [LLK/scratch-vm#2670]
### Expected Behavior

Projects displaying pen should display the same now as they did in Scratch 2.0 and, indeed, the same as they originally did with Scratch 3.0

### Actual Behavior

The positioning or size of the pen seems to have altered when drawing lines

### Steps to Reproduce

Apologies for the worst reproduction ever. Use this project (https://scratch.mit.edu/projects/360544527/), select "Just Driving" and while holding the up arrow to move forwards you will see many black lines appearing to the sides of the road that are new artifacts which have started occurring some time since the release of Scratch 3.0.

I'd be happy to create a better (far, far smaller) repro project but thought this might be a known issue in which case it should be mentioned in the wiki (https://github.com/LLK/scratch-vm/wiki/Compatibility).

### Operating System and Browser

Windows 10 Enterprise - Version 1909
Chrome - Version 86.0.4240.183 (Official Build) (64-bit)

**Comment by BryceLTaylor** [comment]
@RokCoder can you share a screenshot of what you're seeing?  It's either too subtle for me to notice or I'm not experiencing the same thing you are on my computer.

**Comment by RokCoder** [comment]
![Screenshot 2020-11-05 at 23 12 31](https://user-images.githubusercontent.com/20208339/98307059-e1f25580-1fbc-11eb-8b0c-bbe8416e0d09.png)

This is a screenshot taking on a MacBookPro (Chrome) after starting a "Just Driving" game without accelerating at all. Notice the green line across the track and all the black lines on the side above that. Originally these artefacts were not present. There should be no green visible across the road and no black lines visible at the edges. The rendered display was correct in Scratch 2.0 and in 3.0 at first. The issue has arisen some time since the release of 3.0.

**Comment by RokCoder** [comment]
Checking the project today the issue seems to have been resolved. I haven't closed this ticket because I'm curious as to which recent commit that might have fixed this? https://github.com/LLK/scratch-vm/pull/2203 ?

**Comment by BryceLTaylor** [comment]
Since it seems to be fixed, I am going to close this issue.
