### ISSUE TITLE
How to change extension block color

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-vm#2677]
In the previous version, I can change the menu color. I can create the block like this.
![image](https://user-images.githubusercontent.com/25700616/98439188-18e67980-212b-11eb-8113-d81e3e9eb288.png)
However, I found that the new block extension only has color1 and color.
![image](https://user-images.githubusercontent.com/25700616/98439221-5ea34200-212b-11eb-9f63-aad3151308bb.png)
I cannot change the menu color.
Can anyone tell me how to do it?

**Comment by apple502j** [comment]
This is because there are two types of menu input. Previous default was that you can drop a block inside. Default value was changed so that it no longer accepts blocks by default. See documentation.

**Comment by crouse12** [comment]
Thanks
