### ISSUE TITLE
Menu problem

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-vm#2678]
I'm building some blocks for scratch 3.0.
I want to have the following menu feature.
If one block's menu change selected option without clicking this block, the other block's menu items changed, too.
This menu feature is useful for microbit.
When we close microbit's led screen, we can use more pins.
I have try the dynamic menu.
However, it cannot do it.
May I know how to do it?

**Comment by apple502j** [comment]
Why not make two blocks, but make the other one non-functional?

**Comment by crouse12** [comment]
Just want to have better function for my extensions.
In the following video, I use the dynamic menu.
However, it needs to click the first one block, and then the other block's menu items change.

https://www.youtube.com/watch?v=8_aH2U2AtA0&feature=youtu.be

**Comment by BryceLTaylor** [comment]
We do not support blocks being affected by the state of another block.
