### ISSUE TITLE
Day since 2000 code?

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-vm#268]
This is the discussion talking about #272

**Comment by tmickel** [comment]
@CosmicWebServices Thanks. We'd be happy to take a PR that implements the block, or we'll get around to it eventually.

Please check out the scratch-flash implementation:
https://github.com/LLK/scratch-flash/blob/master/src/primitives/SensingPrims.as#L306

If possible, we should have the same behavior for timezones.

Regarding decimal precision: seems fine to me to have extra precision, but I haven't thought about it carefully.

**Comment by CosmicWebServices** [comment]
OK thanks maybe when I figure out how to do it I will

**Comment by CosmicWebServices** [comment]
Sorry for the late reply I will work o a pr soon

**Comment by towerofnix** [comment]
> seems fine to me to have extra precision

The more precise the days-since-2000 block, the better. It's already crazy (and for good reason - it's a super handy block), going farther isn't going overboard!

IMO.

By the way.. I haven't checked, but does scratch-blocks limit the rendered digits of a reporter block's result bubble?

**Comment by CosmicWebServices** [comment]
So I should leave the extra digets?

**Comment by tmickel** [comment]
@liam4 If I remember right, as far as scratch-blocks is concerned, the bubble isn't limited and can display arbitrary HTML.
@CosmicWebServices Yes, that seems fine to me.

**Comment by towerofnix** [comment]
I feel taken technically :)

I suppose that if it _does_ (or would) do anything, that's in scratch-vm? (i.e. snipping digits from number bubble returns)

**Comment by dekrain** [comment]
@CosmicWebServices You must rewrite https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_sensing.js#L26 adding comma and on next line, add

``` javascript
'sensing_dayssince2000': this.daysSince2000
```

Next add on end of file, before `module.exports` something like:

``` javascript
Scratch3SensingBlocks.prototype.daysSince2000 = function() {
  var start = new Date(2000, 1-1, 1); 
  var today =   new Date(); 
  return (today.valueOf() - start.valueOf()) / 1000 / 86400;
}
```

**Comment by CosmicWebServices** [comment]
Thanks @dekrain when I am done school I will do that.

**Comment by CosmicWebServices** [comment]
nvm I will do it now

**Comment by CosmicWebServices** [comment]
The pr is at #272

**Comment by CosmicWebServices** [comment]
@liam4 or anyone else do you think the extra few decimal places with hurt cross-compatibility?

**Comment by towerofnix** [comment]
Nah. I don't know why anybody would need to e.g. check the length of the return value of days since 2000..

**Comment by CosmicWebServices** [comment]
Actually some people used that in my pen challenge also the one line challenge but I think it is fine still.
