### ISSUE TITLE
How is Scratch-VM going to interact with audio?

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-vm#273]
I am not sure if audio is a thing yet in Scratch-VM but I would like to suggest the use of the library [HowlerJS ](https://howlerjs.com/) which include pretty much everything needed in scratch 2 and more. It is cross compatible and really easy to code. Also, it works with a whole lot of types of audio files (so no longer audio conversions like you see in 2.0).

I don´t know if audio is a discussion yet but I just wanted to point out an option that I found to be useful.

**Comment by ericrosenbaum** [comment]
Hi- we've started working with audio, but it is still at a very early stage. You can see watch our progress on the audio engine [here](https://github.com/LLK/scratch-audioengine).

Thanks for the tip- we're currently using [ToneJs](https://github.com/Tonejs/Tone.js) for prototyping, but that is likely to change.

**Comment by CosmicWebServices** [comment]
Thanks
