### ISSUE TITLE
VM clear method notes

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#274]
For the GUI, we'd like to be able to unload projects from the VM without deleting the whole VM object. Then new projects could be loaded at any time.

Roughly, `clear` method should dispose all the current targets, using `runtime.disposeTarget`. https://github.com/LLK/scratch-vm/blob/3bfd755e6005fcf528a544548e517dce6122c8b0/src/engine/runtime.js#L375 We could actually just do something like "for each target in `runtime.targets` (dispose target)`. 

Note that we should also update `clone.dispose`, to _allow_ disposing of original sprites:
https://github.com/LLK/scratch-vm/blob/3bfd755e6005fcf528a544548e517dce6122c8b0/src/sprites/clone.js#L420
And move that check to the "delete this clone" block instead.

We also have to stop all the currently running threads - I recommend `runtime.stopAll`.

**Comment by rschamp** [comment]
Thanks for writing this up @tmickel!
