### ISSUE TITLE
Ip camera

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-vm#2765]
Hi there,
Video sensing can show usb camera video. Is it possible to show  IP camera video?
Thanks a lot for a hint.

**Comment by ericrosenbaum** [comment]
You would need to make the IP camera show up as a webcam, which web browsers (I think) do not generally support.

As a workaround, you might be able to use software that can create a "virtual camera" from another input, such as OBS. It's a bit complex to set up. But then you would be able to select that virtual camera from the browser, and Scratch would use it for video sensing.

Please re-open this issue if you have updates or further questions. Thanks!
