### ISSUE TITLE
'if' and 'if-else' condition block run on loop when reject into start branch.

### ISSUE THREAD

**Issue by BrightLin** [LLK/scratch-vm#2776]
the program cannot stop.  see pictures below:
![image](https://user-images.githubusercontent.com/15828392/103117149-21c3e800-46a4-11eb-9bab-6945286c5f75.png)

modified the motion opcode: 
![image](https://user-images.githubusercontent.com/15828392/103116982-64d18b80-46a3-11eb-8f33-7fc1c2522e11.png)

why set thread status to running when reject?
![image](https://user-images.githubusercontent.com/15828392/103117201-491ab500-46a4-11eb-8023-05508953d87c.png)

**Comment by apple502j** [comment]
Promises returned should never reject.

**Comment by BryceLTaylor** [comment]
@BrightLin Can you provide reproduction steps?  Can you get this to happen in the current scratch editor?
