### ISSUE TITLE
Question: Why does the micro:bit extension have to route to Scratch link instead of using web-bluetooth-api directly?

### ISSUE THREAD

**Issue by JimEverest** [LLK/scratch-vm#2805]
I am confused with the micro:bit extension for why does it have to route to Scratch link instead of using web-bluetooth-api? I think most OS/Browser have released the capability to allow the Web Bluetooth API communicates with BLE devices directly. 

I am not sure if this is the right place to came up this question, Sorry if I am doing it not right, thanks.

**Comment by apple502j** [comment]
Not every browser supports WebBluetooth. Safari said no IIRC and Firefox does not.
Reminder: If it doesn't work on Firefox 57, we don't use.

**Comment by cwillisf** [comment]
Indeed: when we started implementing this stuff, no browsers fully supported Web Bluetooth yet as it was still experimental. As @apple502j mentioned, even now some of the browsers we support don't have Web Bluetooth support and it's unclear whether or not they will implement it any time soon.

In theory we could use Web Bluetooth in those cases where it's supported and fall back onto Scratch Link where it's not, or use Scratch Link if it's present and try Web Bluetooth as a fallback if it's not. We might consider that as a future change if there's enough call for it, but we'd have to carefully weigh the advantages against the disadvantages, such as complicating the support landscape with more browser-specific behavior and browser-specific UI for the Bluetooth connection flow.

Thanks for the question, @JimEverest!

**Comment by JimEverest** [comment]
Yah, it makes sense. Thanks for your explain, @cwillisf !
