### ISSUE TITLE
Only call `renderer.draw()` when necessary

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#281]
Currently we call `renderer.draw` on every tick. But, we can reduce these calls by a lot in some circumstances because we should know exactly when things on the stage have changed. This is at least when the "redraw" flag of the runtime has been set. But also when drawables have finished rendering/loading (which is why I didn't implement this already - not sure if we can do that yet).

**Comment by cwillisf** [comment]
Anyone who works on this should be careful to make sure that this doesn't negatively affect situations where the stage becomes exposed after being partially or fully obscured (by another window, being minimized, looking at another tab, etc.), computer coming out of sleep mode, etc.
