### ISSUE TITLE
JSON maximum size

### ISSUE THREAD

**Issue by ggenije** [LLK/scratch-vm#2839]
I don't know is this place for asking this , but anyways...

The maximum size of JSON in .sb3 is 5MB, is there a particular reason for that, why it's not 10 MB for example.
The 5MB is too small,
Also we know that assets can occupy much more server space , so that isn't the problem.

Also is there a chance for increasing it?

**Comment by rschamp** [comment]
We need some limit, and based on our analysis the current limit is sufficient for the vast majority of projects. We may consider increasing it in the future but aren't immediately planning to.
