### ISSUE TITLE
GH-pages playground is dead

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#284]
Dunno what causes the issue, but I had this very same issue earlier when working on another thing using scratch-vm after pulling. Removing node_modules and reinstalling unsurprisingly fixed it!

![screen shot 2016-10-17 at 6 21 54 pm](https://cloud.githubusercontent.com/assets/9948030/19456187/abfeacf4-9496-11e6-8952-273f08aeded8.png)

```
cannot read property getWorkspace of null (playground.js:75)
```

**Comment by thisandagain** [comment]
@rschamp Any ideas?

**Comment by CosmicWebServices** [comment]
Recompile it?

**Comment by towerofnix** [comment]
^ Basically the only known solution right now.. though it would also be nice to know what the issue is!

(But it probably wouldn't be a bad idea to rebuild it for now. You can always go back in time using git to figure out what's wrong with the old version, so you can avoid the issue in the future..)

**Comment by CosmicWebServices** [comment]
Is this a github issue? I know the playground is not broken

**Comment by towerofnix** [comment]
If you directly clone the gh-pages branch, and don't rebuild it, it'll probably be broken there as (though I haven't checked).

**Comment by CosmicWebServices** [comment]
It is broken

**Comment by rschamp** [comment]
The tool we're using to publish to gh-pages is not committing all the changes that happen for each build.  Debugging this now.

**Comment by CosmicWebServices** [comment]
Cool
