### ISSUE TITLE
Remove nets and use native fetch

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2890]
scratch-vm uses `nets` to fetch remote resources. However, all supported browsers support `fetch`, and there is no reason to add `nets` (besides [causing issues with Scratch Desktop](https://github.com/LLK/scratch-desktop/issues/157).)

Just like scratch-storage, nets should be removed and native `fetch()` should be used. If Node support is required for unittests, we can probably add `node-fetch` as devdeps.

**Comment by rschamp** [comment]
Which browsers were you considering as supported?

**Comment by adroitwhiz** [comment]
The ones listed on the [FAQ page](https://scratch.mit.edu/info/faq):

> Desktop
> 
>    * Chrome (63+)
>    * Edge (15+)
>    * Firefox (57+)
>    * Safari (11+)
>    * Internet Explorer is NOT supported.
> 
> Tablet
> 
>    * Mobile Chrome (63+)
>    * Mobile Safari (11+)

The [MDN page for the Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#browser_compatibility) lists all those browsers as supporting it:
![image](https://user-images.githubusercontent.com/25993062/108425569-a0eb1d80-7208-11eb-86d7-f8b55d03acaf.png)

**Comment by adroitwhiz** [comment]
Note that I [already removed `nets` from `scratch-storage` last June](https://github.com/LLK/scratch-storage/pull/113), leaving only the Fetch API, and thus far nothing seems to have broken, so it should be fine to remove it here as well.

**Comment by rschamp** [comment]
Great, thanks!
