### ISSUE TITLE
Uncaught DOMException when importing tf models

### ISSUE THREAD

**Issue by MarkKocherovsky** [LLK/scratch-vm#2914]
I'm trying to import a tensorflow model into my scratch extension using the instructions [here](https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md). Here is my code:

```
//<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.3.1/dist/tf.min.js"></script>
//<script src="https://cdn.jsdelivr.net/npm/@teachablemachine/image@0.8.3/dist/teachablemachine-image.min.js"></script>

import * as tf from '@tensorflow/tfjs';
import * as tmImage from '@teachablemachine/image';

const formatMessage = require('format-message');
const nets = require('nets');
const Video = require('../../io/video');
const Runtime = require('../../engine/runtime');
const ArgumentType = require('../../extension-support/argument-type');
const BlockType = require('../../extension-support/block-type');
const Cast = require('../../util/cast');
const MathUtil = require('../../util/math-util');
const Clone = require('../../util/clone');
const log = require('../../util/log');

/**
 * Icon svg to be displayed in the blocks category menu, encoded as a data URI.
 * @type {string}
 */
// eslint-disable-next-line max-len
const menuIconURI = 'Hand.png';

/**
 * Icon svg to be displayed at the left edge of each extension block, encoded as a data URI.
 * @type {string}
 */
// eslint-disable-next-line max-len
const blockIconURI = 'Hand.png';

//Model instantiation in global scope

//from https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md
let model, webcam, labelContainer, maxPredictions;

/**
 * Class for the test blocks.
 * @constructor
 */
class Scratch3PalmReaderBlocks {
    constructor (runtime) {
        /**
         * The runtime instantiating this block package.
         * @type {Runtime}
         */
        this.runtime = runtime;
    }
    getInfo() {
        return {
            id: 'PalmReader',
            name: formatMessage({
                id: 'palm.categoryName',
                default: 'Palm Reader',
                description: 'Palm Reader'
            }),
            blockIconURI: blockIconURI,
            menuIconURI: menuIconURI,
            blocks: [
                {
                    opcode: 'importModel',
                    text: formatMessage({
                        id: 'palm.import',
                        default: 'Import Model',
                        description: 'Import the Palm Reader Model'
                    }),
                    arguments: {

                    },
                    blockType: BlockType.COMMAND,
                    //filter: [TargetType.SPRITE]
                }
            ]
        };
    }
    importModel() {

        //from https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md
        const url = "<My Model URL>";
        const modelUrl = url + "model.json";
        const metadataUrl = url + "metadata.json";
        model = await tmImage.load(modelUrl, metadataUrl);
        maxPredictions = model.getTotalClasses();
    }
    //from videosensing/index.js
    videoToggle(args) {
        const state = args.VIDEO_STATE;
        this.globalVideoState = state;
        if (state === VideoState.OFF) {
            this.runtime.ioDevices.video.disableVideo();
        } else {
            this.runtime.ioDevices.video.enableVideo();
            // Mirror if state is ON. Do not mirror if state is ON_FLIPPED.
            this.runtime.ioDevices.video.mirror = state === VideoState.ON;
        }
    }
}
module.exports = Scratch3PalmReaderBlocks;
```

``toggleVideo`` is currently unused. When I load the extension in scratch, the console returns the following error (and the block does not appear): ``Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8601/PalmReader' failed to load.``

However, the code compiles correctly. I'm using ubuntu 20.04 focal and npm version@0.1.2.

**Comment by apple502j** [comment]
You are writing a "sandboxed extension" which does not have access to DOM.

**Comment by MarkKocherovsky** [comment]
> You are writing a "sandboxed extension" which does not have access to DOM.

That matches what I've found online. Is there a way to do what I'm trying to do with a sandboxed extension, or should I unsandbox it? If so, how would I go about it?

**Comment by apple502j** [comment]
Sandboxed extensions cannot access most of the APIs - I mean, you can do calculations and fetch() calls but that's it - you can't access runtime or camera.

"Unsandboxed extension" is just "modding Scratch". Clone scratch-gui and this repo, add files, and see how things work. (Files to check include src/lib/libraries/extensions/index.jsx on GUI and src/extensions/extension-manager.js on VM, the source code provided looks fine other than mixing ESM and CommonJS require(), and using async & await (use promise).)

**Comment by MarkKocherovsky** [comment]
> Sandboxed extensions cannot access most of the APIs - I mean, you can do calculations and fetch() calls but that's it - you can't access runtime or camera.
> 
> "Unsandboxed extension" is just "modding Scratch". Clone scratch-gui and this repo, add files, and see how things work. (Files to check include src/lib/libraries/extensions/index.jsx on GUI and src/extensions/extension-manager.js on VM, the source code provided looks fine other than mixing ESM and CommonJS require(), and using async & await (use promise).)

So, as I understand, I should just create a github repo and push my ``index.jsx`` and this index.js to it, and then call the github url in my local ``extension-manager``?

**Comment by apple502j** [comment]
No. You have to clone this repo & scratch-gui then mod them (basically do what other extensions do)

**Comment by MarkKocherovsky** [comment]
> No. You have to clone this repo & scratch-gui then mod them (basically do what other extensions do)

I'm not sure I understand; That's what I was already doing when I got this error.

**Comment by apple502j** [comment]
You have to include the extension itself in the clone. You can't load from URL.

**Comment by MarkKocherovsky** [comment]
> You have to include the extension itself in the clone. You can't load from URL.

That's already what I'm doing. I have the following files made or edited on my local build: ``scratch-vm/src/extensions/scratch3_palmreader/index.js``, ``scratch-vm/src/extension-manager/index.jsx``, and ``Scratch-gui\src\lib\libraries\extensions\index.jsx``.

The extension appears in the menu in localhost:8061, but loading it returns the error in the original post. 

I just want to know how I can host my extension in such a way that I can use runtime and the webcam without having this error. Presently, I have the cloned repos (gui, blocks, and vm) that loads in localhost. To my understanding, this was a sandboxed extension.

**Comment by apple502j** [comment]
importScripts should never be called. Are you sure you modified `extension-manager` to load the extension from the clone?

**Comment by MarkKocherovsky** [comment]
> importScripts should never be called. Are you sure you modified `extension-manager` to load the extension from the clone?

This is what I have:

```
const builtinExtensions = {
    // This is an example that isn't loaded with the other core blocks,
    // but serves as a reference for loading core blocks as extensions.
    coreExample: () => require('../blocks/scratch3_core_example'),
    // These are the non-core built-in extensions.
    pen: () => require('../extensions/scratch3_pen'),
    wedo2: () => require('../extensions/scratch3_wedo2'),
    music: () => require('../extensions/scratch3_music'),
    microbit: () => require('../extensions/scratch3_microbit'),
    text2speech: () => require('../extensions/scratch3_text2speech'),
    translate: () => require('../extensions/scratch3_translate'),
    videoSensing: () => require('../extensions/scratch3_video_sensing'),
    ev3: () => require('../extensions/scratch3_ev3'),
    makeymakey: () => require('../extensions/scratch3_makeymakey'),
    boost: () => require('../extensions/scratch3_boost'),
    gdxfor: () => require('../extensions/scratch3_gdx_for'),
    MarkKocherovskyTest: () => require('../extensions/scratch3_testextension'),
    PalmReader: () => require('../extensions/scratch3_palmreader')
};
```

Right, now, I am trying to work with ``PalmReader``.

**Comment by apple502j** [comment]
What is in index.jsx then?

**Comment by MarkKocherovsky** [comment]
> What is in index.jsx then?
```
    {
        name: (
            <FormattedMessage
                defaultMessage="Palm Reader"
                description="Name for the 'palm reader' extension"
                id="gui.extension.PalmReader.name"
            />
        ),
        extensionId: 'PalmReader',
        iconURL: videoSensingIconURL,
        insetIconURL: videoSensingInsetIconURL,
        description: (
            <FormattedMessage
                defaultMessage="Test to see if the Palm Reader works"
                description="Description for the 'Palm Reader' extension"
                id="gui.extension.PalmReader.description"
            />
        ),
        featured: true
    }
```

**Comment by apple502j** [comment]
Hmm, not sure why it's not working. If you put console.log in random places in extension-manager, do they fire? (could be npm link issue)

**Comment by MarkKocherovsky** [comment]
> Hmm, not sure why it's not working. If you put console.log in random places in extension-manager, do they fire? (could be npm link issue)

They do not return anything. If this is an npm link issue, what would be best way of checking?

**Comment by apple502j** [comment]
Okay, let's redo linking.

1) Run `npm install` on both clones
2) Run `npm link` on VM
3) Run `npm link scratch-vm` on GUI

**Comment by MarkKocherovsky** [comment]
> Okay, let's redo linking.
> 
> 1. Run `npm install` on both clones
> 2. Run `npm link` on VM
> 3. Run `npm link scratch-vm` on GUI

I've done this and am getting an error, but it's possible I may have broken it. I accidentally ran ``npm link`` in GUI instead of ``npm link scratch-vm`` and it became stuck, so I cancelled the command and continued as normally. Now, when I run ``npm start``, I get this error:

```
mkocherov@R9301986:/mnt/c/Users/mkocherov/Documents/Scratch/SrPrj2/scratch-gui$ npm start

> scratch-gui@0.1.0 start
> webpack-dev-server

node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'import-local'
Require stack:
- /mnt/c/Users/mkocherov/Documents/Scratch/SrPrj2/scratch-gui/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/mnt/c/Users/mkocherov/Documents/Scratch/SrPrj2/scratch-gui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:10:21)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/Users/mkocherov/Documents/Scratch/SrPrj2/scratch-gui/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```

I have also tried ``npm install import-local``, which did not fix the error.

**Comment by apple502j** [comment]
Try deleting node_modules on both then do it again.

**Comment by MarkKocherovsky** [comment]
> Try deleting node_modules on both then do it again.

Alright, the DOM exception is gone (I think), meaning that it was a link problem. However, I've now got this error: ``lib.min.js:411104 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'" with the line ``module.exports = Scratch3PalmReaderBlocks;``. Presumably, I should replace that with code for an "unsandboxed" extension?

**Comment by apple502j** [comment]
@MarkKocherovsky That line is correct, but there are some more that I pointed out:

- You need to use CJS require not ESM
- Async function is not supported in this repo, use Promise

**Comment by MarkKocherovsky** [comment]
> @MarkKocherovsky That line is correct, but there are some more that I pointed out:
> 
> * You need to use CJS require not ESM
> * Async function is not supported in this repo, use Promise

I've fixed the CJS and ESM, but I'm having a bit of trouble with my Promise function:

```
    importModel() {
        console.log("import model start");
        //from https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md
        //also https://medium.com/jspoint/javascript-promises-and-async-await-as-fast-as-possible-d7c8c8ff0abc
        const url = "<URL>;
        const modelUrl = url + "model.json";
        const metadataUrl = url + "metadata.json";
        const promiseModel = new Promise(resolve => {
            model = tmImage.load(modelUrl, metadataUrl);
            console.log(typeof model);
            maxPredictions = model.getTotalClasses();
        });
        promiseModel.then((result) => {
            console.log("Import Model Success.")
        });
        promiseModel.catch((error) => {
            console.log("Error in promiseModel.")
        });
        promiseModel.finally((result) => {
            console.log("promiseModel done?")
        })
```
This returns ``Uncaught (in promise) TypeError: model.getTotalClasses is not a function``. It also does this outside of the promise. If this isn't a general problem with my JS, then I can ask in the tensorflow repo instead.

**Comment by dalelane** [comment]
I think it's because `tmImage.load(modelUrl, metadataUrl);` returns a promise, not a model.
```js
tmImage.load(modelUrl, metadataUrl)
   .then((model) => {
      // now you can use your model, and call getTotalClasses
   });   

```

**Comment by dalelane** [comment]
I think creating promises is over-complicating it a little. If I was you, I would rewrite your original code:

```js
    importModel() {

        //from https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md
        const url = "<My Model URL>";
        const modelUrl = url + "model.json";
        const metadataUrl = url + "metadata.json";
        model = await tmImage.load(modelUrl, metadataUrl);
        maxPredictions = model.getTotalClasses();
    }
```

as something more like this:

```js
importModel() {
    const url = "<My Model URL>";
    const modelUrl = url + "model.json";
    const metadataUrl = url + "metadata.json";
    return tmImage.load(modelUrl, metadataUrl)
        .then((model) => {
            maxPredictions = model.getTotalClasses();
        });
}
```

(and btw, I think that last `return` is important, because you don't want the invocation of your block to complete until the promise resolves, otherwise Scratch will immediately do to the next code block in your script, potentially before the model has finished loading)

**Comment by MarkKocherovsky** [comment]
> I think creating promises is over-complicating it a little. If I was you, I would rewrite your original code:

That seems to be working without error. I'd like to thank @dalelane and @apple502j for their help!

**Comment by DolevArtzi** [comment]
> Okay, let's redo linking.
> 
> 1. Run `npm install` on both clones
> 2. Run `npm link` on VM
> 3. Run `npm link scratch-vm` on GUI

I experienced the same error as op, and this also fixed the error for me. To clarify, I believe that `scratch-vm` and `scratch-gui` were what was being referred to as
> both clones

as those are the directories that I ran `npm install` in.
