### ISSUE TITLE
Block caching/optimization tech debt

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-vm#2925]
### Expected Behavior

The codebase should be easy to understand, and should not contain any dead code

### Actual Behavior

The 2017-2018 optimization work done across many PRs to speed up block execution has introduced a lot of technical debt into the codebase. There's a lot of dead code of the worst kind: code where you really have to think about whether it's *really* dead. This increases the mental burden on those trying to trace through code paths in order to reason about the VM, because they will quickly run into either code that does something but appears to do nothing, or vice versa, code that does nothing but appears to do something.

**Comment by fsih** [comment]
The triage team is having a hard time prioritizing this issue since it's a bit too broad. Can you make more specific issues for the PRs, e.g. "remove x dead code path" or "refactor y for clarity"?

**Comment by adroitwhiz** [comment]
I didn't want to clutter up the issue tracker but I can. The issues will basically just be copies of the PR descriptions, though.

**Comment by fsih** [comment]
I think that's ok
