### ISSUE TITLE
Implement sound blocks

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-vm#293]
### Expected behavior

The sound "meow" or a drum plays.
### Actual behavior

No sound plays.
### Steps to reproduce

Insert any sound block into a script. For this I used "play sound (meow v)" and "play drum (1) for (10) beats".
### Operating system and browser

Ubuntu Linux 14.04 LTS, Firefox 49 and Google Chrome 53.0.2785.143 (Official Build) (64-bit)

**Comment by CosmicWebServices** [comment]
That is because it was not implemented yet.
You can see the progress of the sound engine [here](https://github.com/LLK/scratch-audioengine)

**Comment by dekrain** [comment]
@CosmicWebServices you're faster than me.

**Comment by CosmicWebServices** [comment]
:)

**Comment by tmickel** [comment]
We will hopefully have some demo sound blocks in the VM soon!

**Comment by CosmicWebServices** [comment]
Yay!

**Comment by Tymewalk** [comment]
@tmickel Sounds great!

As I don't think they'd be fundamentally redesigned, would it be possible to add sound seeking blocks like [these](https://scratch.mit.edu/discuss/topic/182656/?page=1)?

**Comment by tmickel** [comment]
@Tymewalk That's interesting. @ericrosenbaum might have comments/ideas. We can't really know whether particular blocks will be added for 3.0, because we have a long design process, but we are playing with some new sound ideas.

**Comment by tmickel** [comment]
A reminder that this requires implementing "volume of _" in the "of" sensing block.
