### ISSUE TITLE
Make the Makey Makey "when key pressed" block into an event block

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-vm#2944]
### Expected Behavior

The Makey Makey extension's "when key pressed" block should function like the one in the Events category--it should fire immediately when you press a key, and match the key-repetition behavior of the host system (i.e. if you hold down a key, it will fire once, then after a short delay, begin firing repeatedly).

### Actual Behavior

The Makey Makey "when key pressed" block is "edge-activated", meaning that it is evaluated every frame and activates if some state differs from the previous frame. In order to make this work, there's a bit of a hack that means it's only capable of activating once every other frame, resulting in a delay.

In addition, because it is *always* activated once every other frame, it is extremely easy to accidentally activate it multiple times simply by holding the key(s) down for too long.

@ericrosenbaum tried to fix this in https://github.com/ericrosenbaum/scratch-vm/commit/4984b32c0d7ce3fb04ba59759bbb301a3745a497, but the VM doesn't currently support evaluating dynamic inputs on "event"-based hat blocks.

### Steps to Reproduce

1. Add the Makey Makey extension
2. Create scripts using both the extension's "when key pressed" block and the normal "when key pressed" block. Note that because the Makey Makey is a regular USB keyboard, you do not require a Makey Makey and can use *any* keyboard to test the Makey Makey block.
3. Compare the differences in behavior between the two hat blocks.

### Operating System and Browser

All

**Comment by mxmou** [comment]
The difference between the blocks is quite well known so removing it would change the behavior of existing projects that expect it.

**Comment by BryceLTaylor** [comment]
Since some people's projects rely on the current behavior, we will not fix this.
