### ISSUE TITLE
Uncaught reference to defined model within extension class.

### ISSUE THREAD

**Issue by MarkKocherovsky** [LLK/scratch-vm#2958]
I'm trying to use predict() to return predictions from my tensorflow model. within a scratch extension My code is as follows:

```
importModel() {
        console.log("import model start");
        //from https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md
        //also https://medium.com/jspoint/javascript-promises-and-async-await-as-fast-as-possible-d7c8c8ff0abc
        const url = <URL>;
        const modelUrl = url + "model.json";
        const metadataUrl = url + "metadata.json";
        //https://github.com/LLK/scratch-vm/issues/2914#issuecomment-791514353
        return tmImage.load(modelUrl, metadataUrl)
            .then((model) => {
                console.log(model);
                maxPredictions = model.getTotalClasses();
            });
    }
    getXCoord() {
        //A1 or A2 returns 0
        //B1 or B2 returns 1
        const prediction = model.predict(this.runtime.renderer._allDrawables[target.drawableID]);
    }
```

``model`` and ``maxPredictions`` are global variables defined by ``let model, labelContainer, maxPredictions;``. However, when I run my code, getXCoord throws the following error: ``Uncaught TypeError: Cannot read property 'predict' of undefined``. 

If I try the following:

```
getXCoord() {
        //A1 or A2 returns 0
        //B1 or B2 returns 1
        model = importModel();
        const prediction = model.predict(this.runtime.renderer._allDrawables[target.drawableID]);
    }
```

It returns ``index.js:117 Uncaught ReferenceError: importModel is not defined``. However, importModel is in the class and is clearly defined.

**Comment by adroitwhiz** [comment]
Try `this.importModel()`

**Comment by dalelane** [comment]
I think there are a couple of problems here:

1) the `importModel` function isn't returning a model object. 
Currently it's returning a promise that resolves to nothing. If you want to return the model, you need to add a `return model` in your final `then` method.
e.g.
```js
return tmImage.load(modelUrl, metadataUrl)
            .then((model) => {
                console.log(model);
                maxPredictions = model.getTotalClasses();
                return model;
            });
```

2) the `importModel` function is asynchronous
The `model` variable in your `getXCoord` function is a promise. That means the only methods you can use on it are `.then()` and `.catch()` 
You need to use an asynchronous pattern:
e.g.
```js
getXCoord() {
    this.importModel()
        .then(function (model) {
            const prediction = model.predict(this.runtime.renderer._allDrawables[target.drawableID]);
        });
}
```



_Updated to include the third problem that @adroitwhiz pointed out above_

**Comment by MarkKocherovsky** [comment]
Alright, that's working, but I'm now getting this error:

``index.js:120 Uncaught (in promise) TypeError: Cannot read property 'renderer' of undefined``

```
importModel() {
        console.log("import model start");
        //from https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md
        //also https://medium.com/jspoint/javascript-promises-and-async-await-as-fast-as-possible-d7c8c8ff0abc
        const url = "https://teachablemachine.withgoogle.com/models/3RBPI6zKN/";
        const modelUrl = url + "model.json";
        const metadataUrl = url + "metadata.json";
        //https://github.com/LLK/scratch-vm/issues/2914#issuecomment-791514353
        return tmImage.load(modelUrl, metadataUrl)
            .then((model) => {
                console.log(model);
                maxPredictions = model.getTotalClasses();
                return model;
            });
    }
    getXCoord() {
        //A1 or A2 returns 0
        //B1 or B2 returns 1
        this.importModel()
            .then(function (model) {
                const prediction = model.predict(this.runtime.renderer._allDrawables[target.drawableID]);
                console.log(prediction);
            });
    }
```

**Comment by MarkKocherovsky** [comment]
> I think there are a couple of problems here:
> 
> 1. the `importModel` function isn't returning a model object.
>    Currently it's returning a promise that resolves to nothing. If you want to return the model, you need to add a `return model` in your final `then` method.
>    e.g.
> 
> ```js
> return tmImage.load(modelUrl, metadataUrl)
>             .then((model) => {
>                 console.log(model);
>                 maxPredictions = model.getTotalClasses();
>                 return model;
>             });
> ```
> 
> 1. the `importModel` function is asynchronous
>    The `model` variable in your `getXCoord` function is a promise. That means the only methods you can use on it are `.then()` and `.catch()`
>    You need to use an asynchronous pattern:
>    e.g.
> 
> ```js
> getXCoord() {
>     this.importModel()
>         .then(function (model) {
>             const prediction = model.predict(this.runtime.renderer._allDrawables[target.drawableID]);
>         });
> }
> ```
> 
> _Updated to include the third problem that @adroitwhiz pointed out above_

Alright, that's working, but I'm now getting this error:

``index.js:120 Uncaught (in promise) TypeError: Cannot read property 'renderer' of undefined``

```
importModel() {
        console.log("import model start");
        //from https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md
        //also https://medium.com/jspoint/javascript-promises-and-async-await-as-fast-as-possible-d7c8c8ff0abc
        const url = "https://teachablemachine.withgoogle.com/models/3RBPI6zKN/";
        const modelUrl = url + "model.json";
        const metadataUrl = url + "metadata.json";
        //https://github.com/LLK/scratch-vm/issues/2914#issuecomment-791514353
        return tmImage.load(modelUrl, metadataUrl)
            .then((model) => {
                console.log(model);
                maxPredictions = model.getTotalClasses();
                return model;
            });
    }
    getXCoord() {
        //A1 or A2 returns 0
        //B1 or B2 returns 1
        this.importModel()
            .then(function (model) {
                const prediction = model.predict(this.runtime.renderer._allDrawables[target.drawableID]);
                console.log(prediction);
            });
    }
```

**Comment by adroitwhiz** [comment]
[In JavaScript, anonymous functions (like the one in your promise callback) bind the `this` value to `window`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this).

If you want `this` to refer to the extension class, you need to use an [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), which does not bind `this`:
```js
            .then(model => {
                const prediction = model.predict(this.runtime.renderer._allDrawables[target.drawableID]);
                console.log(prediction);
            });
```

**Comment by adroitwhiz** [comment]
(While the bug lies in code provided by @dalelane, and JavaScript's behavior here is definitely confusing, this seems to be veering off of "help interfacing with the scratch-vm API" into "help understanding how JavaScript works in general"--are there others at LTU who may be able to better assist you?)

**Comment by MarkKocherovsky** [comment]
> (While the bug lies in code provided by @dalelane, and JavaScript's behavior here is definitely confusing, this seems to be veering off of "help interfacing with the scratch-vm API" into "help understanding how JavaScript works in general"--are there others at LTU who may be able to better assist you?)

As I understood, part of the issue is in my call to the webcam through scratch, so I figured this would be the best place about that. I'm using code from the video sensing extension, but I'm getting ``Uncaught (in promise) ReferenceError: target is not defined``. in the line ``const prediction = model.predict(this.runtime.renderer._allDrawables[target.drawableID]);``, where the argument in predict is the webcam. I'm using the video sensing extension to manage the webcam.

**Comment by adroitwhiz** [comment]
The error is indeed correct-- the `target` variable is not defined. Look a bit closer at the function you copy-pasted the code from, and the functions which call it.

**Comment by MarkKocherovsky** [comment]
> The error is indeed correct-- the `target` variable is not defined. Look a bit closer at the function you copy-pasted the code from, and the functions which call it.

Alright, I've got this:
```
getXCoord(util) {
        //A1 or A2 returns 0
        //B1 or B2 returns 1
        this.importModel()
            .then(model=> {
                const prediction = model.predict(this.runtime.renderer._allDrawables[util.target.drawableID]);
                console.log(prediction);
            });
    }
```
``util`` is still undefined, but I'm not sure where it's defined in the first place, based on the other extensions. Do I need to pass ``args, util`` and leave the arguments empty?

**Comment by adroitwhiz** [comment]
> Do I need to pass `args, util` and leave the arguments empty?

In JavaScript, function arguments are passed by position--it doesn't matter what you name them. So yes, the first argument, which you've named "util", will be what other blocks name `args`. You need the function signature to be `args, util`.

Note that this will only work if `getXCoord` is a function corresponding to a block. If `getXCoord` is a utility function called by *other* block functions, then you'll need to pass the proper arguments yourself.

Once again, if you need help understanding more general JavaScript behavior like how function arguments work, you should probably look to other JavaScript learning resources rather than asking open-source maintainers to teach you JavaScript on a bug tracker.

**Comment by MarkKocherovsky** [comment]
> > Do I need to pass `args, util` and leave the arguments empty?
> 
> In JavaScript, function arguments are passed by position--it doesn't matter what you name them. So yes, the first argument, which you've named "util", will be what other blocks name `args`. You need the function signature to be `args, util`.
> 
> Note that this will only work if `getXCoord` is a function corresponding to a block. If `getXCoord` is a utility function called by _other_ block functions, then you'll need to pass the proper arguments yourself.
> 
> Once again, if you need help understanding more general JavaScript behavior like how function arguments work, you should probably look to other JavaScript learning resources rather than asking open-source maintainers to teach you JavaScript on a bug tracker.

Alright, the function is nearly working. I'm still getting a JS error, but I'm not sure it's due to Scratch. Again, I'd like to thank everyone for their assistance; it means a lot to me!
