### ISSUE TITLE
make a simpler default project. (at least, stop making new ones)

### ISSUE THREAD

**Issue by edward789121** [LLK/scratch-vm#296]
### Expected behavior

either one of these:
- make the default project nyan cat or ship it squirrel (:shipit:) repeatedly changing color.
- just stick with any of them for a few months.
### Actual behavior

showing you a new one every time you visit.
### Steps to reproduce

go to https://scratch.mit.edu/projects/119615668 , or view S3 on the web.
### Operating system and browser

Chrome on Windows 7

**Comment by towerofnix** [comment]
Actually the testing project is just for, well, testing. It's kind of fun to have a new project there every once in a while, to see what's new with the VM.

In any case obviously that won't be the default project in the future when Scratch 3.0 is released!

**Comment by edward789121** [comment]
Good. But I just don't like having 5 minutes to play around with S3, and the next time, it's something else. I think development would be faster if they stuck with the same default project for a while. 'Cause I bet they would have changing sprite names/deleting sprites/etc.!

**Comment by dekrain** [comment]
Always you can load non-working empty project :P

**Comment by thisandagain** [comment]
We switch out the project depending on what we are testing, which helps out with development quite a bit. If you would like something else you can load it yourself by adding `/#someprojectid` to the end of the URL.
