### ISSUE TITLE
Playground not working?

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-vm#2969]
### Expected Behavior
Playground runs projects

### Actual Behavior
Pressing run doesn't seem to do anything
Here are the console errors
<img width="328" alt="Screen Shot 2021-03-16 at 16 58 08" src="https://user-images.githubusercontent.com/2855464/111378922-e4567180-8678-11eb-8563-90a46804ed4d.png">

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by adroitwhiz** [comment]
Try http://127.0.0.1:8073/playground/

EDIT: I think it's the trailing slash that does it

**Comment by kchadha** [comment]
@fsih Could you confirm what @adroitwhiz mentioned above and close this issue if it works?

**Comment by fsih** [comment]
Yup it works!
