### ISSUE TITLE
On Empty Project Renderer Not Attached

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#297]
### Expected behavior

_The renderer should be attached and the sprite should display._
### Actual behavior

_The renderer is not attached._
### Steps to reproduce

_Create Empty Project_
### Operating system and browser

_Google Chrome On Windows 10 AU_

**Comment by thisandagain** [comment]
We are handling this in the new GUI repo that we will be releasing soon. I'm going to keep this open as a feature request.

**Comment by dekrain** [comment]
When you publish this? Next week or month?

**Comment by tmickel** [comment]
Hi,

I'm closing empty project issues for now since they'll be addressed in our upcoming scratch-gui release. @dekrain No promises but it seems this is more likely to be next week than next month (@rschamp).

**Comment by dekrain** [comment]
Yay
