### ISSUE TITLE
Errors in scratch-vm travis build: in-publish not found

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-vm#2983]
### Expected Behavior
Scratch-vm should build

### Actual Behavior
We install a version of npm that is not compatible with our version of node on Travis, and it causes build errors
<img width="1011" alt="Screen Shot 2021-03-23 at 16 52 43" src="https://user-images.githubusercontent.com/2855464/112216788-4aeb0a80-8bf8-11eb-94f1-ce7044f28f6e.png">

See https://travis-ci.org/github/LLK/scratch-vm/jobs/764141205
This is blocking development

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by cwillisf** [comment]
Looking into this, it turns out it's because npm 7.7.0 no longer works with Node 8. We need to either stop building on Node 8, or stop installing `npm@latest`
