### ISSUE TITLE
Add motion fence

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#301]
### Expected behavior

Sprites should be bounded to the edges of the stage, as in Scratch 2.0's "keep on stage."
### Actual behavior

Sprites can go on forever, with no default bounds.
### Steps to reproduce

Place a sprite and do "forever move 10." It should stop when it is partially off the stage.

**Comment by towerofnix** [comment]
A toggle constant (or whatever) for this in the source might be nice.

**Comment by tmickel** [comment]
@liam4 We have thought about adding {MOTION_STYLE_FENCE, MOTION_STYLE_WRAP, MOTION_STYLE_FREE} in the source. Not clear if we'll actually expose these in the Scratch editor, but would be useful for future experimentation. However, definitely not the highest priority.

**Comment by towerofnix** [comment]
> MOTION_STYLE_WRAP

..This is interesting!

**Comment by ed-cooper** [comment]
Yes, wrap and free motion would be useful features in the editor.

I suspect a design discussion might be needed for how wrap should work though

**Comment by tmickel** [comment]
Created this back in November when taking a look for the first time:

https://scratch.mit.edu/projects/132069625/
https://llk.github.io/scratch-vm/#132069625

Just in case that might be helpful in the future :)

**Comment by griffpatch** [comment]
Oh please please expose a free motion option! :)

**Comment by mrjacobbloom** [comment]
"wrap" motion style would be super handy! If you decided to expose that to the user, would motion styles apply to one sprite or the whole project?

**Comment by rschamp** [comment]
Fixed by #459
