### ISSUE TITLE
Implement "of" block in sensing

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#303]
This block is unimplemented, but could be implemented right away.

**Comment by towerofnix** [comment]
Here's a test project: https://scratch.mit.edu/projects/127295747/

..Though it depends on smaller feature I'm not 100% sure has been implemented, switching to a costume using the index of that costume.

EDIT: Also there's lots of vector graphics, but I don't think the lack of proper vector graphics rendering ATM _really_ messes up anything.

**Comment by towerofnix** [comment]
The argument name for "() of" is `OBJECT`. I wonder if that should be `TARGET`?

Also, on the topic of this block, I'd find a "myself" option quite useful, though I'd like to know whether or not that has even a sliver of a chance of being used before implementing it.. no need for unnecessary hype :)

EDIT: "useful" as in "get (variable) of myself", "get [costume name] of myself", and so on.

**Comment by tmickel** [comment]
@liam4 We could switch that to TARGET to be more consistent with the language of the VM. However I wouldn't consider it highest priority.

The thinking with the "myself" is that you could programmatically switch which attributes you're getting, right? With clones, would it return the values for the target clone or the original sprite? Personally I wouldn't be opposed to it but we'll have to have a bit of design discussion here. @carljbowman

**Comment by towerofnix** [comment]
@tmickel Yeah, that's the idea.

The dropdown for the attribute would need to be "opened", but I can't really see why not -- the only possibly confusing thing that could happen, I suppose, would be dropping an attribute-getter block (such as "x position") into the dropdown. But it probably wouldn't take anybody longer than ten seconds to figure out that "x position" means (0, 240, 15, etc - visual value bubbles are great!), and that's what the dropdown is seeing, which obviously doesn't work. (What's "27 of Sprite1" supposed to mean?)
