### ISSUE TITLE
Implement video motion sensing

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#304]
We need to do at least two things:
- Display the video on the stage (do this in scratch-render?)
- Implement the sensing primitives. Reference: https://github.com/LLK/scratch-flash/blob/master/src/primitives/VideoMotionPrims.as. Personally I might lean toward a direct reproduction of this if possible, i.e., a translation AS3->JavaScript. More documentation at https://llk.media.mit.edu/papers/tony-hwang-thesis.pdf

**Comment by thisandagain** [comment]
> Personally I might lean toward a direct reproduction of this if possible, i.e., a translation AS3 -> JavaScript

Agreed.

**Comment by CosmicWebServices** [comment]
Well @thisandagain there are some really good javascript libraries that can do what you want and more...

**Comment by AmazingMech2418** [comment]
There are only 2 blocks currently, but on some of my projects that use pen and video, a video transparency block like what's in Scratch 2 would be very helpful.
