### ISSUE TITLE
Implement loudness detection

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#305]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

We'll need to map microphone values to a value 0-100, like Scratch.

**Comment by towerofnix** [comment]
Don't forget that if no microphone is detected, or it doesn't have permission to use a microphone, the microphone value is -1.

**Comment by ericrosenbaum** [comment]
closed by https://github.com/LLK/scratch-vm/pull/513
