### ISSUE TITLE
Implement "username" block

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#306]
Can we get this data without being embedded on a *.scratch.mit.edu page, or will it have to read a cookie there?

**Comment by thisandagain** [comment]
We'll have to either grab it from the session directly or pass the session to the API which means we'll need to limit it to a `*.scratch.mit.edu` domain unfortunately.

**Comment by TheBrokenRail** [comment]
It could be included in creating the VM object to it to function on more than just *.scratch.mit.edu domains

**Comment by TheBrokenRail** [comment]
It could also be stored on a SQL database and the link could be stored on a cookie or variable (it could be changed), you could also open source the stuff on the SQL server so people could run there own.
