### ISSUE TITLE
Implement monitor manager, show/hide variable/list blocks

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#308]
Needs to interact with the scratch-blocks flyout checkboxes and https://github.com/LLK/scratch-render/issues/19 to display monitors when appropriate. Also need to update the SB2 importer to know when to display monitors by default.

**Comment by towerofnix** [comment]
This is closed, but the `data_showvariable` (etc) blocks are not actually implemented? LLK/scratch-blocks#1276 tracks showing the blocks when they're implemented in the VM, but I don't think there's an issue (besides this one, but it's closed) for tracking the VM code itself.
