### ISSUE TITLE
Not The Full Toolbox on Scratch-GUI

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#325]
### Expected behavior

_You see the default toolbox._
### Actual behavior

_You only see 5 categories of the default toolbox._
### Steps to reproduce

_Go to: llk.github.io/scratch-gui_

**Comment by rschamp** [comment]
This is a prototype for a "microworld" usage of the gui so the limited toolbox is expected.

**Comment by dekrain** [comment]
When `scratch-gui` will published?

**Comment by jeandrek** [comment]
@dekrain I think I remember @tmickel saying "soon".

**Comment by dekrain** [comment]
Ok, I will don't ask anymore for this.

**Comment by dekrain** [comment]
I created program:

```
[Flag clicked]
forever {
play sound (3) until done
}

[Flag clicked]
wait (0.2) secs
forever {
repeat (4) {
play sound (10)
wait (0.4) secs
}
repeat (5) {
play sound (10)
wait (0.2) secs
}
wait (0.55) secs
}
```

**Comment by towerofnix** [comment]
Sounds like the type of thing to share on the Scratch 3.0 [discussion thread](https://scratch.mit.edu/discuss/topic/199574/)! (Along with a screenshot of the program, might be nice.)

**Comment by dekrain** [comment]
Ok, sorry
