### ISSUE TITLE
Custom extension fails to load in production

### ISSUE THREAD

**Issue by sinanthottan** [LLK/scratch-vm#3267]
Hi all, 

Can someone help me solve this issue? 
I have created an extension for our hardware, it fails to load in production (hosted using Docker). Referred Microbit extension file to create the extension. Error in console shows: "DataCloneError: The object could not be cloned."

Extension works well in local machine, connecting successfully to the hardware and everything works as expected. 

To reproduce the error, 
- goto http://codebricks.junkbot.co
- Load Junkbot extension. 

But on the other hand, microbit and all the other extensions load just fine.

**Comment by apple502j** [comment]
This is due to an error in central-dispatch.js L130; we need to pop twice and the condition is different

**Comment by sinanthottan** [comment]
Thank you, but I am not so good with this. How do we fix it?
Also found error at extension-worker.js L24.
To debug I cloned microbit and renamed it to microbit2. Even that does not work on production, but works perfect in locally

**Comment by apple502j** [comment]
Well, there are two extensions: unsandboxed and sandboxed. All built-in ones are unsandboxed.

Extension implementers can implement both of them. Sandboxed extensions can be loaded on any mod that supports custom extensions. Unsandboxed extensions are just hard-coded mods. Sandboxed extensions cannot use many of the features, such as DOM or access to the full virtual machine of Scratch.

Dispatch and worker stuff do not apply to unsandboxed extensions; so you can probably make that one instead. Clone gui and vm, npm link, copy-paste vanilla files (try translate extension), edit `src/extension-support/extension-manager.js` in VM and `src/lib/libraries/extensions/index.jsx` in GUI, npm start on GUI

**Comment by sinanthottan** [comment]
@apple502j  thank you for the detailed explanation. I did not know about these things

I think, I did the same as you mentioned above. Cloned gui and vm. updated extension-manager.js
`junkbot: () => require('../extensions/scratch3_junkbot')`
Also updated extensions/index.jsx at GUI to list the extensions. 
What I additionally did was, like you see above, copied scratch3_microbit/index.js and updated to fit my needs. 
This works like a charm locally with `npm start` on GUI. 
For production using docker, I did `npm run build`

my code can be reviewed at http://github.com/sinanthottan/scratch-vm and scratch-gui

**Comment by sinanthottan** [comment]
@apple502j 
- cloned `scratch-vm` and run command `npm link` 
- cloned `scratch-gui` and run command `npm link scratch-vm`
- added `junkbot: () => require('../extensions/scratch3_junkbot')` to `src/extension-support/extension-manager.js` at `scratch-vm`
- copied and updated `scratch3_microbit/index.js` to `scratch3_junkbot/index.js` at `scratch-vm`
- added the extension name to  `src/lib/libraries/extensions/index.jsx`
- run command `npm run build` from `scratch-gui`

https://github.com/sinanthottan/scratch-gui/blob/develop/Dockerfile
I know I am doing something wrong, but I have no clue about it. I would really appreciate if you could help me. This happens only in production. I have no trouble loading and connecting the hardware to the extension on my local machine. :(

**Comment by apple502j** [comment]
Can you send the full error traceback?

**Comment by sinanthottan** [comment]
Sure, but where do I find it?

**Comment by apple502j** [comment]
On browser console?

**Comment by sinanthottan** [comment]
ExtensionWorker/</< http://codebricks.junkbot.co/extension-worker.js:140:24

**Comment by apple502j** [comment]
Okay, two things:
- you are using unsandboxed extensions, and
- Scratch must be served under HTTPS.

**Comment by sinanthottan** [comment]
@apple502j thank you so much for your support. Finally it's working. Discarded the docker deployment. 
Deployed at aws ec2 server on nginx. setup ssl certificate. 
assume the issue was something related to `npm build`, so deployed with `npm start` on aws ec2 server. Luckily it worked. 
`npm install` on docker was throwing an unknown error which I was not able to fix. 

https://code.junkbot.co - Created extension to control Junkbot core (basically Arduino compatible) board using ble
