### ISSUE TITLE
switch backdrop to [next backdrop/previous backdrop] doesn't work as expected

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#327]
Demo project: https://llk.github.io/scratch-gui/#128185170

**Comment by towerofnix** [comment]
I'm guessing "[previous/next] backdrop" is getting evaluated to 0, which is wrapping to the last backdrop..

**Comment by tmickel** [comment]
@liam4 Yep I bet that is close to right. https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_looks.js#L97 This code is looking at the calculated `costumeIndex`, but I bet it should be checking the string.

**Comment by towerofnix** [comment]
You've got 7 days to fix this critical issue. Good luck.
