### ISSUE TITLE
A broadcast bug

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#328]
Something has broken with broadcast, causing it to behave unexpectedly in loops (and possibly other situations).
<img width="443" alt="screen shot 2016-11-09 at 10 51 29 am" src="https://cloud.githubusercontent.com/assets/120403/20144404/8c1ae1ec-a66a-11e6-910f-4703f1b616cc.png">
In the above, I expect it to behave like "forever turn right", but it doesn't seem to execute the broadcast until the left script stops.

**Comment by ed-cooper** [comment]
More specifically, the issue demonstrated here is that when the same message is broadcast, the script execution starts back at the top of the script, even if it is already running.

(Just some proof:)
Swapping the broadcast block for a broadcast and wait block works:

![screen 1](https://cloud.githubusercontent.com/assets/14095134/20147090/8f417848-a69e-11e6-9636-08ec7c509bb1.png)

This example, where the script restarting means that we never see the sprite turn anti-clockwise (until you stop the forever loop sending the broadcast)

![screen 2](https://cloud.githubusercontent.com/assets/14095134/20147109/afe8cfe2-a69e-11e6-95f9-c88e7a912739.png)

**Comment by tmickel** [comment]
@chooper100 Thanks for writing that up. I'm not sure if that's quite the issue, but it's definitely on the right track.

In Scratch 2.0 for example, when you make this script:
<img width="358" alt="screen shot 2016-11-10 at 11 39 17 am" src="https://cloud.githubusercontent.com/assets/120403/20185514/5adc6a30-a73a-11e6-913a-eae3addcad0c.png">
If the broadcast doesn't restart the script on the right, we would expect that the sprite never changes color. In fact, it does - broadcasts restart scripts. The script above will also have the sprite turn, but it turns forever because of the script on the left, not the script on the right. It is actually equivalent to this:
<img width="372" alt="screen shot 2016-11-10 at 11 41 00 am" src="https://cloud.githubusercontent.com/assets/120403/20185575/94f921b8-a73a-11e6-8383-09eb8ac4beae.png">

**Comment by tmickel** [comment]
Here is a test project:
https://scratch.mit.edu/projects/130183108/
