### ISSUE TITLE
Dosn't Load On IE And MS Edge

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#334]
### Expected behavior

_It should load and work perfectly fine._

### Actual behavior

_Only the HTML Elements Load_

### Steps to reproduce

_Go To Scratch-VM On IE Or MS Edge_

### Operating system and browser

_MS Edge And IE_

**Comment by CosmicWebServices** [comment]
UGH IE and Edge

**Comment by TheBrokenRail** [comment]
Edge Is Actually A Really Good Browser

Posted With MS Edge

**Comment by TheBrokenRail** [comment]
On edge it looks like it has something to do with the default toolbox

**Comment by TheBrokenRail** [comment]
Has PR to fix this in scratch-blocks repository.

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-blocks/pull/762

**Comment by thisandagain** [comment]
Blocks issue resolved. Bug with rendering engine filed here:
https://github.com/LLK/scratch-render/issues/85
