### ISSUE TITLE
Effect not correctly copied to clones

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#337]
Demo: https://llk.github.io/scratch-gui/#125767391

In Scratch 2.0, you end up with squares of all different colors.

**Comment by tmickel** [comment]
A simpler demo:
https://llk.github.io/scratch-gui/#132285226
vs. https://scratch.mit.edu/projects/132285226/ (correct)

**Comment by TheBrokenRail** [comment]
Since this is fixed, shouldn't it be closed?

**Comment by thisandagain** [comment]
Resolved in #401
