### ISSUE TITLE
Code Connectivity with Scratch

### ISSUE THREAD

**Issue by Saket-hub-ui** [LLK/scratch-vm#3429]
How to connect this code to scratch? @question

**Comment by BryceLTaylor** [comment]
I'm not entirely sure what you mean. Scratch-vm is a dependency of [Scratch-gui](https://github.com/LLK/scratch-gui), which is the code for the editor code.  So it is deeply connected to Scratch already.

**Comment by Saket-hub-ui** [comment]
Yes but they are not getting added.

**Comment by adroitwhiz** [comment]
I think [`npm link`](https://docs.npmjs.com/cli/v8/commands/npm-link) may be what you're after.
