### ISSUE TITLE
Global custom blocks

### ISSUE THREAD

**Issue by ggenije** [LLK/scratch-vm#3436]
### History
This feature hasn't been discussed since [_scratch-flash_](https://github.com/LLK/scratch-flash/issues/782) , and my personal opinion is that it is worthy to reconsider it again.
I will try my best to represent you my vision how it should be implemented.
Also it's important to mention that this feature isn't only my personal desire, it have [decent number of supporters](https://scratch.mit.edu/discuss/topic/12015/) among scratchers (up to 200 followers on the forum, and perhaps many more who do not use the forums).

### Introduction
Global custom block are scripts which can be called outside the sprite which is created in. 
In the following paragraphs I will describe to you how I imagine it , how to make it intuitive enough , how to avoid potential _pitfalls_.

### Creating global custom blocks
The first and most important thing is separating **global** from **local** custom blocks.
I would achieve this, as people before me have suggest, by adding a checkbox with label **for all sprites** , which will make the custom block available for using for the other sprites.

### How the global block is called
In order to call it should be required to add new block type. Instead of listing every global custom block in the blocks bar, it would be done like following:
That new block  which I would call here GCC block _(Global Custom Caller block)_ , will contain two dropdowns.

1. The name of sprite which global custom block is called from
2. The name of the global custom block which should be called

For example you have global custom block "Draw Rectangle" in sprite "Draw" with arguments position and size (x,y,w,h), if you want to call that global custom block block you will add that new custom block GCC and first set the first 2 drop downs, first to "Draw" and when you do that the second dropdown would change to first element it is available (or to nothing if there was no global custom blocks in that sprite), also the default value of GCC is the first sprite and the first global custom block, with empty argument fields.

Then as you change the second dropdown the argument input fields appears , every time you change the dropdowns and input fields aren't corresponding , that inputs would be _kicked out_ the same way it should when you change inputs in local custom block.
It could be also possible to kick out them every time you change any of the first two dropdowns, or to keep the maximally possible input fields in case you made two functions with similar parameters, and you don't want to reinput them all over again.

The name of the global custom block located in the second dropdown will represent the all "text" field combined in the custom block,
For example if you have two custom blocks one Draw line (x1) (y1) (x2) (y2) and second  Draw line (x1) (y1) (x2) (y2) rotated (a), the first custom block will be shown as "Draw line" while other "Draw line rotated". This is only my suggestion , maybe somebody else can come up with a better one.

It would visually look this: [Call from sprite [Draw v] custom block [Draw Rectangle v] (x) (y) (w) (h)]

Each sprite including backdrop would have option to add this new GCC block.

### Where , how and why the global custom block is actually called

As previously discussed , there are problems like what if you call global custom block which change costume in sprite to "cat1" but the other sprite which calls it doesn't have that costume , or if you call global custom block from stage and the global custom block have motion block in it.

Because of that I think the best solution is to have script to be executed in the sprite it is called. That means that custom block would behave like a **function** and not like a **method** (in OOP context). Practically that means if e.g. you are drawing a rectangle using global custom block "Draw Rectangle" from sprite "Draw" the movement which be applied to the sprite "Draw" ,not to the caller sprite.

Now the question arises , what is point/usage for global custom blocks if you cannot modify movement or looks of the another sprite.

And answer is for **organizing , easier way of collaborating/remixing**,
For example one scratcher creates sprite "Draw Library" which contains functions draw rectangle, line, 3D line , rotated line , fill triangle etc. then the other scratcher doesn't need to know what how are exactly implemented those functions when they use it.
Other examples would be , 3D engine, Text engine, UI engine, Cloud engine(multiplayer, leaderboards , saving), Save/Load engine , Animation engine etc.. _I could explain those engines more detailed if you want so._

This way we will help young scratchers to understand how it importance of libraries , i.e. how you don't need to know everything about some scripts in order to use them (but they can still see the implementation in case they want to learn to make something similar too). Fortunately, there are plenty of older / experienced  scratchers (like me) who would be more than happy to make engines for others to use. Even the older students could benefit from this by fact they would learn how to create their own libraries, and learn to write the documentation for that engine.
Another example is easier collaboration, for example team wants to create a game, one scratcher wants to create the game logic, another scratcher User Interface, another to implement rendering. It would be much easier when you divide jobs by sprites and call other's scripts from your sprite, you don't need to know how they implement their sprites' scripts, and you don't need to explain how your sprite scripts works.

### Solving pitfalls
Here I will explain my vision how I would solve the possible obstacles which will occur while implementing this feature:

> Does every clone then run its global custom block independently when it's called (once) from somewhere, using its own local variables? Or should it just be the ‘original’ sprite that runs it?

I would solve this by adding another dropdown next to second one, which label would be **Run for** , and options would be **original sprite** and **clones**, that way you can have choice.

> How they would differ from the existing broadcasts blocks.

You could call them multiply times per frame, for example for draw rectangle, you would be able to draw multiply rectangle, which isn't possible by using broadcast, also the big problem is that you have to wait a frame before scripts executes which can be devastating.

> Is this feature simple enough for the kids / inexperienced people.

It is nothing more difficult than existing local/global variables feature. Also as I mentioned the point is not to make kids create global custom block but to use them.  For example you can create lesson for kids which is to teach them how to use the global custom blocks which are made by either teacher, another student or another scratcher.
For example the snap version is super complex compared to the implementation I am suggesting currently. Everything is basically the same expect there is a new GCC block. If you're still doubting it you could even make a extension "better blocks" or something which will have this option , that way it wouldn't confuse scratchers (with assumption it would even confuse somebody).

> What will happen to the global custom blocks usages when that global custom block is deleted (or unchecked being global).

Similarly to current implementation of regular custom block, you cannot delete the custom block until you delete all usage occurrences, I cannot see why it shouldn't be the same way for the global version.
About unchecking being global they are two solution, once is disabling converting custom block to local once it's created , and the other is make it only available when there are no occurrences.

### Visual example
[Global custom block presentation](https://scratch.mit.edu/projects/604460350/)

![Example](https://user-images.githubusercontent.com/50455160/143680277-15b9fddc-83b4-4808-b36a-7dc7276c8333.png)

### Conclusion
That would be it if you have any additional issues you can mention them here, and I will try to find to solution.

**Comment by ShipmasterKyle** [comment]
Scratch would 100% benefit from having this feature. I hope they add it soon.

**Comment by lucid-boop** [comment]
this seems interesting, but i think instead of a "from (sprite) call (func)" block, scratch would add a feature where you can see global custom blocks in other sprites(just the custom block, none of that fancy "call" stuff)

**Comment by ggenije** [comment]
> this seems interesting, but i think instead of a "from (sprite) call (func)" block, scratch would add a feature where you can see global custom blocks in other sprites(just the custom block, none of that fancy "call" stuff)

That is an alternative solution, but main problem with that implementation is possible ambiguity between custom blocks, i.e. when you're trying to define two same global custom block in different sprites.
Additionally, I think my solution is more concise, which mean user don't have to search for the desired global custom block in each other sprite when target script is in known sprite. 
Also my way you can choose would the custom block be executed at the "main sprite" or for each clone which could be useful.

On the other hand your suggestion is much simpler. Scratch already have problem when you're defining same custom block twice(or more), you would be able to call only single of them, and when you edit the one which couldn't be called, the one which would be called is actually changed , not the one selected.
When you think about it , why scratch even allow to create two same custom blocks (with exactly same name and argument types), they should've fixed this problem before implementing this. The same solution could be with this second solution, especially because it's much simpler and doesn't require the new block. Only problems would be lack of option to choose would be script be executed at the "main sprite" or at the each clone.

**Comment by BryceLTaylor** [comment]
Thanks for your suggestion and your thorough writeup, but we are not likely to add this feature.
