### ISSUE TITLE
Add Thread tests

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#345]
Currently, there are no tests for Thread. There are a bunch of methods in there that could be easily unit-tested and are pretty critical for managing execution.

**Comment by SillyInventor** [comment]
I'm interested in adding some thread testing, would you like a hand?

**Comment by thisandagain** [comment]
@SillyInventor Yeah! That would be great.

**Comment by thisandagain** [comment]
We are still not at 100% coverage for `engine/thread` but https://github.com/LLK/scratch-vm/pull/445 gets us close enough to close this for now.
