### ISSUE TITLE
Move sprite to top layer

### ISSUE THREAD

**Issue by Norbiros** [LLK/scratch-vm#3498]
I was creating addon for scratch, and i found 1 problem:
**How U can change sprite's layer?**
I didn't found anything or any examples, only `https://github.com/LLK/scratch-vm/tree/develop/src/engine/stage-layering.js`

**Comment by apple502j** [comment]
https://github.com/LLK/scratch-vm/blob/develop/src/sprites/rendered-target.js#L846

**Comment by Norbiros** [comment]
Thanks you very much 😺 
`Apple here, apple there, apple can help everywhere!`
