### ISSUE TITLE
Turn down intervals

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#35]
Until we can implement the VM in a WebWorker, running as much computation as we are seems to be hanging the main UI thread...this is mostly visible when dragging blocks around. It won't make it as perfect as we can, but we could improve it slightly by making the blocks execute for less ms.

**Comment by takaokouji** [comment]
## 作業予定

Issue#35の対応として、翻訳拡張機能のサーバーURLを変更します。

### 修正内容
- **ファイル**: 
- **修正箇所**: 27行目の定数
- **修正前**: 
- **修正後**: 

### 作業手順
1. ✅ 翻訳拡張機能のindex.jsファイルを読み込んで現在のserverURLを確認
2. ✅ serverURLをhttps://api.smalruby.app/scratch-api-proxy/に変更  
3. 🔄 Docker環境でlintを実行して問題がないことを確認
4. 🔄 Docker環境で既存の自動テストがパスすることを確認

これにより、翻訳機能がSmalrubyのAPIプロキシサーバーを経由するようになります。
