### ISSUE TITLE
how to add a custom block ?

### ISSUE THREAD

**Issue by makerclass** [LLK/scratch-vm#350]
### Expected behavior

i want to add a custom block on movtion category

**Comment by dekrain** [comment]
The flyout category of CBs is broken

**Comment by CosmicWebServices** [comment]
Yeah unforchantly that is the case hopefully it will be fixed soon enogth

**Comment by makerclass** [comment]
i can add a custom block, But i dont knot how to write the code generate code. In Blockly i can create a new js file. but in scratch vm 

in playground.js: i add a block like this

window.Blockly.Blocks['test'] = {
    init: function() {
    this.appendDummyInput()
        .appendField("test");
    this.setInputsInline(false);
    this.setPreviousStatement(true, null);
    this.setColour(210);
    this.setTooltip('');
    this.setHelpUrl('http://www.example.com/');
  }


in Scratch3MotionBlocks i add the block config

Scratch3MotionBlocks.prototype.getPrimitives = function () {
    return {
        motion_test: this.smove,
        motion_movesteps: this.moveSteps,
        motion_gotoxy: this.goToXY,
        motion_goto: this.goTo,
        motion_turnright: this.turnRight,
        motion_turnleft: this.turnLeft,
        motion_pointindirection: this.pointInDirection,
        motion_pointtowards: this.pointTowards,
        motion_glidesecstoxy: this.glide,
        motion_ifonedgebounce: this.ifOnEdgeBounce,
        motion_setrotationstyle: this.setRotationStyle,
        motion_changexby: this.changeX,
        motion_setx: this.setX,
        motion_changeyby: this.changeY,
        motion_sety: this.setY,
        motion_xposition: this.getX,
        motion_yposition: this.getY,
        motion_direction: this.getDirection
    };
};

Scratch3MotionBlocks.prototype.test = function (args, util) {
    var steps = Cast.toNumber(args.STEPS);
    var radians = MathUtil.degToRad(90 - util.target.direction);
    var dx = steps * Math.cos(radians);
    var dy = steps * Math.sin(radians);
    util.target.setXY(util.target.x + dx, util.target.y + dy);
    };


but when i running the server ,when i run the block, console debug display:

vm.js:3545 vm Could not get implementation for opcode: test

so i dont' know what happen, need i modify the scratch-block' code?
so could you give some suggestion about it ?   million of thx

**Comment by tmickel** [comment]
Hi @makerclass:

You've given the block the name "test" here: `window.Blockly.Blocks['test']`. If you change that code to look like `window.Blockly.Blocks['motion_test']`, the VM should know where to look for it. Note also that you'll probably want to add the block to the scratch-blocks toolbox XML, if you haven't already.

**Comment by makerclass** [comment]
got it, thank you very much!! it works well

**Comment by dekrain** [comment]
And here: `motion_test: this.TEST`
