### ISSUE TITLE
Question: How do you make those huge gaps between blocks like in Motion?

### ISSUE THREAD

**Issue by RixInGithub** [LLK/scratch-vm#3506]
Hello, coding and Scratching guys,

I want to know ( because I didn't found it in the source code ) how do you do those huge gaps like below:

![That huuuge gap](https://user-images.githubusercontent.com/87478581/153747018-e76ea581-aa95-4cda-a535-dcd41c8df94c.png)

I really wonder how, because I want to make a gap between:

![The normal gappy](https://user-images.githubusercontent.com/87478581/153747106-eea3df17-fb35-4011-95ef-056c701c31c1.png)

**Comment by apple502j** [comment]
See https://github.com/LLK/scratch-vm/blob/f5cb041cba940e3f10903409e963162a37e65bb5/src/extensions/scratch3_microbit/index.js#L625

**Comment by RixInGithub** [comment]
> See https://github.com/LLK/scratch-vm/blob/f5cb041cba940e3f10903409e963162a37e65bb5/src/extensions/scratch3_microbit/index.js#L625

Thanks!

![That another big gappy by @apple502j](https://user-images.githubusercontent.com/87478581/153752571-39651c3f-a3c0-4f4e-b530-6be2394c1523.png)
