### ISSUE TITLE
Sprite movement is jerky

### ISSUE THREAD

**Issue by BookOwl** [LLK/scratch-vm#352]
I hope that this is the right repo to report this in.
### Expected behavior

The ship sprite's movement should be smooth, just like in Scratch 2.0

### Actual behavior

The sprite's jerks around when trying to rotate or move it.

### Steps to reproduce

1. Load project 133736970 in the VM
2. Hit the green flag button. Since Scratch 3.0 doesn't support when this sprite clicked yet, I modified the project to automatically pick the ship.
3. Use the arrow keys move the ship around. 

### Operating system and browser

I'm running OSX 10.11.6 and Firefox 50.0

I'm also including the project as a .sb2 file to let you guys test it in Scratch 2.0 easily (just change the file extension from .zip to .sb2)
[Asteroids for Scratch 3.0.zip](https://github.com/LLK/scratch-vm/files/624812/Asteroids.for.Scratch.3.0.zip)

**Comment by dekrain** [comment]
Report this to LLK/Scratch-Render

**Comment by tmickel** [comment]
If I'm observing the same problem you are, my guess is that this is related to https://github.com/LLK/scratch-render/issues/62. The movement of the ship appears "jerky" to me when it switches costume: it seems to "jump" to a different location - which I think means something is likely up with the coordinates of the rotation centers with one of the costumes...

**Comment by thisandagain** [comment]
Related to #391

**Comment by paulkaplan** [comment]
This seems to have been fixed by some of the recent optimization work. Runs smooth for me. Closing.
