### ISSUE TITLE
how to create a custom extension for scratch that can get a response from the REST API

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [LLK/scratch-vm#3526]
Hi all
I am using scratch for teaching kids,
I  had developed some REST API that returns some numbers. I  would Like to know how can I add an extension or a new block that accesses the REST API and returns the value.

**Comment by apple502j** [comment]
Translate Extension does exactly that: https://github.com/LLK/scratch-vm/blob/develop/src/extensions/scratch3_translate/index.js

**Comment by ericrosenbaum** [comment]
thanks @apple502j ! I agree that the translate extension is a good example. Please open a new issue if you have further questions.
