### ISSUE TITLE
[sharing] using scratch-vm to list all blocks

### ISSUE THREAD

**Issue by Domiii** [LLK/scratch-vm#356]
Thank you so much for your earlier help!

In my opinion, learning coding requires working with code and "playing around with it". Of course, the most straight-forward way to do that would be to actually use Scratch to create cool stuff! But sadly that does not work very well for everyone, especially initially.

That is why I am currently producing a bunch of mini apps (some with Firebase as a backend, some front-end only) to let my students play around with Scratch blocks in different ways.

For example, [this simple codepen](http://codepen.io/Domiii/pen/NbJogP?editors=0010) uses React to:

1. List all blocks on one page
2. Let you randomly swipe through all Scratch blocks

Maybe other teachers or Scratch users can use it for "Scratch flashcards" or use it in some other way to toy around with Scratch on a whole different level :)

PS: I assume that the github issue page is not an appropriate place for sharing this. Maybe you can point me to a better place?

**Comment by thisandagain** [comment]
Hi @domiii thanks for sharing! Our Facebook and Twitter accounts or simply "help" [at] scratch.mit.edu are all great places to share things you are experimenting with. :-)
