### ISSUE TITLE
blocks with menu are not reload correctly from old project

### ISSUE THREAD

**Issue by mbonani** [LLK/scratch-vm#3631]
### Expected Behavior

old project that have blocks with menu are not reloaded correctly in extension

### Actual Behavior

it loads all menu with the first item of the menu 

### Steps to Reproduce

this happens in our Thymio extension, scratch project made in our ThymioSuite 2.1.5 are not load correctly in Thymio 2.2.0.
We made a big update to follow your development between this two version. 
We pointed out that it is related to the acceptReporters definition of the menu. We never change our menu definition and was something like that:

```
 menus: {
                leftrightall: [
                    {text: messages.menus.leftrightall.left, value: 'left'},
                    {text: messages.menus.leftrightall.right, value: 'right'},
                    {text: messages.menus.leftrightall.all, value: 'all'}
                ],
                leftright: [
                    {text: messages.menus.leftright.left, value: 'left'},
                    {text: messages.menus.leftright.right, value: 'right'}
                ],
```

So without the definition of "acceptReporters"

In our version 2.1.5 
menu of blocs are saved in the json file like that:
```
{"4olB@nR+xD0]JR%`cQuG":{"opcode":"thymio_proximity","next":null,"parent":null,"inputs":{"N":[1,"yIw%L[PGuB8:{.Gm[T^6"]},"fields":{},"shadow":false,"topLevel":true,"x":593,"y":334},"yIw%L[PGuB8:{.Gm[T^6":{"opcode":"thymio_menu_horizontalSensors","next":null,"parent":"4olB@nR+xD0]JR%`cQuG","inputs":{},"fields":{"horizontalSensors":["2",null]},"shadow":true,"topLevel":false},
```
it seems that the menu was saved seperatly as it is made when now `acceptReportes = true`

in our 2.2.0 version

```
{"rOXk%3cKsILpz+HweCVx":{"opcode":"thymio_proximity","next":null,"parent":null,"inputs":{},"fields":{"N":["2",null]},"shadow":false,"topLevel":true,"x":613,"y":311},
```

like it is now for a menu that `acceptReporters = false`

So we didn't see that for a while and we have now for our user some old projects that are saved with the old format and are open in a wrong way, we have new ones that are saved in a new format that make us not possible to define our menu with `acceptReporter=true` that make it works for old project but not for new ones,

Do you have a suggestion? 

[scratchbug.zip](https://github.com/LLK/scratch-vm/files/8663003/scratchbug.zip)

**Comment by apple502j** [comment]
Since you are modding the VM anyway I recommend adding a hackfix to the loading logic - src/serialization/sb3.js if I remember correctly.

**Comment by ericrosenbaum** [comment]
Sorry you're having trouble with this. We did change the default behavior, and that requires a small change to each extension in order to keep their behavior the same. I'm not sure we have a way to help you load your users' old projects correctly - but @apple502j 's suggestion to check for the problem when loading the project and fix it at that stage might work for you.
