### ISSUE TITLE
Concepts: Data + List categories are confusing

### ISSUE THREAD

**Issue by Domiii** [LLK/scratch-vm#365]
I just realized that you now separate the original `Data` category into `Data` and `Lists`. In terms of computational thinking concepts, lists are also a family of variables and any sort of variable is used to store data. Having a category called `Lists` that is separate from `Data` can quickly become confusing.

I would propose naming the two: `Data: simple` and `Data: lists` instead (...or something like that...?)
I understand that you want to keep names simple and short, but especially when considering that we want to use Scratch for on-boarding to general computational thinking concepts and use it as a precursor to more general programming languages, Scratch should still keep things accurate and not too ambiguous.

Helping students getting a better, a more accurate idea of a concept as abstract and complex as `data` would be an amazing feat! :)

[NOTE: Sorry about a discussion in the issues section. I hope, it is not too off-topic!]

Thanks for your great work! Keep it up! I love using your new web-based stuff for creating more tools to reflect and better understand Scratch and computational concepts! :)

**Comment by thisandagain** [comment]
We will be merging `Variables` and `Lists` back together into `Data` (just as we have for Scratch 2.0). We have them split right now just to help with development. Sorry for any confusion!

**Comment by Domiii** [comment]
Thanks a lot! Really awesome! :)
