### ISSUE TITLE
"Show" requests a redraw but "hide" does not

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-vm#3663]
### Expected Behavior

The "show" and "hide" blocks would behave as in Scratch 2:
* "show" would always request a redraw;
* "hide" would request a redraw if the sprite was not already hidden.

### Actual Behavior

"Hide" never requests a redraw.

### Steps to Reproduce

Run "program 5" from [this forum topic](https://scratch.mit.edu/discuss/topic/607096/) in both Scratch 2 and Scratch 3. Scratch 3 behaves incorrectly.

### System Details

Scratch app, version 3.29.1 on Windows

**Comment by mxmou** [comment]
If there are existing Scratch 3 project that rely on this behavior, it might be better to not change this. It has existed since `requestRedraw` was implemented (#280).

**Comment by cwillisf** [comment]
Thanks for reporting this! Since it has been this way for so long and might affect existing projects, like you said, we'd like to leave it as it is.
