### ISSUE TITLE
Dynamic Variable Creation Works, Sort Of

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#370]
### The Sort Of Part

_It doesn't appear in the variable menu, I understand this is unintended behavior but it is cool for more advanced projects._

### How

_I did this by replacing the data.variable menu shadow with text._

### Drawbacks
- It does not appear in scratch block menus.
- You need to mess with variable getter's shadow to get the value.
- You can set a dynamic variable by dropping a reporter into a variable set block (this might be a bug)

### Question

_So is this going to stay in here hidden, removed, or is it going to be fully implemented?_

### Screenshot

![capture](https://cloud.githubusercontent.com/assets/17478432/21705184/5e39b3a8-d38c-11e6-954f-57cced9fd59c.PNG)

### Note

_I modified the set blocks shadow for convenience you can just drop a reporter into it and it will work._

**Comment by mrjacobbloom** [comment]
If you try to access a variable that doesn't exist, it'll be created: https://github.com/LLK/scratch-vm/blob/56ef01745fbb0cc65262438ab27864b435822dd5/src/engine/target.js#L66 This is the same as in Scratch 2.0, probably to make sure that old projects still run correctly. I don't think they're going to remove that, but just like in Scratch 2.0 it's up to the user to figure out how to create hacked blocks

**Comment by TheBrokenRail** [comment]
Wait, I did some more testing and you can get a custom variables without messing with the shadow and just by dropping in a reporter, since that is kind of not hacked blocks, will that be removed, patched, or implemented fully? And why doesn't it show up in scratch-blocks menus?

**Comment by TheBrokenRail** [comment]
Currently, unlike the variable getter or set, sensing will not create a variable if it is non-existent, is this intended or not?

**Comment by TheBrokenRail** [comment]
My personal opinion on this is to fully implement a proper dynamic variable system.
