### ISSUE TITLE
`project.json` reference

### ISSUE THREAD

**Issue by BD103** [LLK/scratch-vm#3718]
Hello! Is there a reference for `project.json`'s format? I'm designing a programming language that compiles to an SB3 file, but I have been struggling on figuring out what everything means in `project.json`.

If there isn't a reference, are there any places in the code that would be a good place to look? (Especially for blocks, since there are some confusing things with them.)

Thanks,
~BD103

**Comment by cwillisf** [comment]
That sounds like a cool project! There's no formal documentation on the `project.json` format, but you can use `src/serialization/sb3.js` to help explain some of its details. For example, check out the comment on the `compressInputTree` function!

Also, you might have figured this out already, but some of the strange-looking strings in the file are just randomized identifiers. As long as the identifier of each block is unique within the project, uses only valid characters, and is the same in the place where the block is stored and any other place it's referenced, the project file should work correctly even if you don't match the exact format that Scratch 3.0 uses when saving a project.

**Comment by BD103** [comment]
Thank you! I found [Scratch Parser](https://github.com/LLK/scratch-parser), which provided a very helpful schema for `project.json`. The info about unique identifiers is incredibly useful, as now I won't have to recreate an MD5 hash.

My last question is what happens when you try to load a malformed SB3 file? Will I get an error message for debugging, or will I need to try something else?

**Comment by RixInGithub** [comment]
> Thank you! I found [Scratch Parser](https://github.com/LLK/scratch-parser), which provided a very helpful schema for `project.json`. The info about unique identifiers is incredibly useful, as now I won't have to recreate an MD5 hash.
> 
> My last question is what happens when you try to load a malformed SB3 file? Will I get an error message for debugging, or will I need to try something else?

I have tried running multiple not-in-format .SB3 files, and in all of them Scratch just loaded the project indefinitely

**Comment by BD103** [comment]
> I have tried running multiple not-in-format .SB3 files, and in all of them Scratch just loaded the project indefinitely

Have you tried looking at the DevTools console for any error messages?
