### ISSUE TITLE
"set size to" block does not work under a "when I start as a clone" hat

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#372]
### Expected behavior

Clone will be sized to the specified size.

### Actual behavior

The clone is reset to 100% size regardless of the original sprites size, and the subsequent resize is ignored (also during cloning a large squirrel sprite sometimes flashes on the screen!)

### Steps to reproduce

When Green Flag Clicked
  set size to 10
  repeat 50
    create clone of [this sprite]
    create clone of [this sprite]     <-- The more of these we repeat, the more squirrels we see!
    create clone of [this sprite]
    create clone of [this sprite]
  end loop

when I start as clone
  go to [random position]
  set size to [random 10 to 100]    <-- FAILS

### Operating system and browser

Windows 10, chrome 55.0

**Comment by tmickel** [comment]
Regarding the squirrels: I believe that is a problem we will see fixed soon. Creating a clone adds an object to the renderer, which initially renders with the default costume/texture (squirrel), until the correct costume is downloaded asynchronously (if cached by the browser, probably 1 frame). We've reworked that whole system, so the costume will be available before the frame is rendered.

The set size one is quite interesting :)

It seems to me like the set size after clone actually works when sizes are > 100%. But values under 100 are forced to 100...

Here is a trace of the internal size-clamping code, run immediately after a clone is created:

<img width="587" alt="screen shot 2017-01-06 at 12 39 21 pm" src="https://cloud.githubusercontent.com/assets/120403/21727012/2babaea6-d40d-11e6-9e43-363ccce47940.png">

It seems before the correct costume is rendered for the clone, the renderer reports the size of the costume as 0x0: for the same reason as the squirrel problem, the actual costume size is unknown when this code is run. The math above works out so values are clamped to 100%, causing the problem you observe. As further evidence, this works just fine:
<img width="305" alt="screen shot 2017-01-06 at 12 42 12 pm" src="https://cloud.githubusercontent.com/assets/120403/21727071/76d4356a-d40d-11e6-8ed0-b371491587aa.png">

I imagine fixing the "squirrel rendering problem" will also fix this "set size to" problem: if the renderer knows the correct dimensions of the costume at the time the "set size to" code is run, the value will be clamped to the expected dimensions.

**Comment by cwillisf** [comment]
Yep -- it all basically comes down to making sure the renderer has an image before it tries to use that image for rendering, answering size questions, etc. Both the squirrel and the "set size" issue should be fixed once LLK/scratch-render#67 is merged.
