### ISSUE TITLE
NFT Collection Extension (Automated Canvas Image Download)

### ISSUE THREAD

**Issue by functionsio** [LLK/scratch-vm#3739]
### Expected Behavior

Requesting automated canvas image download block for student use in generating NFT collections on web application. (Pull Request incoming soon.)

### Actual Behavior

Automated canvas image download block does not exist.

### Steps to Reproduce

Unable to find block via extensions.

### Operating System and Browser

Ubuntu 20.04

### Other

I've tried creating a new topic on the suggestions forums, but I am getting a 403. See attachment. Posting here until I have the ability there.

![Screenshot from 2022-09-15 16-14-50](https://user-images.githubusercontent.com/59425276/190518165-18c6ecb6-d177-4558-ab59-036d5733aa40.png)

Here is what I have developed so far. Any feedback is much appreciated! Thank you!

[screen-capture (1).webm](https://user-images.githubusercontent.com/59425276/190518378-6306870b-9bbd-45e2-ab48-f0933c06add4.webm)

**Comment by cwillisf** [comment]
Hi there! I'm excited to see another person experimenting with extensions! I don't think we're likely to add this feature to Scratch, but you're certainly welcome to work on it in your own fork!

We have a very high bar when it comes to adding features to Scratch, including extensions. We try to follow the principles listed here: https://scratch.mit.edu/developers#principles

In the case of this extension and its feature, I think it does well with the low floor principle, but not as well with wide walls, many paths, and tinkerability. But like I said, I encourage you to continue this work on your own fork if it's an interest of yours. If you're Passionate about NFTs, the extension itself can be a Project of yours where you Play with these ideas, and you can use GitHub to share it with your Peers! ;)

**Comment by functionsio** [comment]
Thanks for the feedback!

Are there any plans to develop a core canvas image download block (for the
web) anytime in the near future?

**Comment by functionsio** [comment]
More discussion on this on the Scratch forums: https://scratch.mit.edu/discuss/topic/631160/?page=1#post-6623288. Thanks.

**Comment by functionsio** [comment]
Bump. More discussion here. https://scratch.mit.edu/discuss/topic/631160/?page=1#post-6623288. cc @cwillisf 
[screen-capture (3).webm](https://user-images.githubusercontent.com/59425276/192832108-65029ae2-f78b-4ea6-8ab5-010a830b4345.webm)
