### ISSUE TITLE
What are the purpose of these branches?

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#374]
The names of these branches don't exactly explain there purpose.
- feature/audio (Wasn't audio blocks just implemented?
- feature/ios
- bugfix/wedo (bug fix for what?)

**Comment by thisandagain** [comment]
- `feature/audio` is / was the staging ground for the new audio features. No longer required as of today.
- `feature/ios` is a staging ground for prototypes of Scratch for iOS
- `bugfix/wedo` is a staging ground for implementing the LEGO WeDo 2.0 extension

**Comment by TheBrokenRail** [comment]
Is there eventually going to be a ```feature/android``` branch?
