### ISSUE TITLE
Add JSON blocks

### ISSUE THREAD

**Issue by PPPDUD** [LLK/scratch-vm#3759]
One block would be called "encode list [insert list here]. It would be a reporter block that reports the JSON equivalent of the list. Then there would be a stack block known as "decode JSON list (var) to [insert list here]", which would clear the selected list, and then convert (var) to a list, the results going into the selected list.

Sorry for any confusion :) !

**Comment by benjiwheeler** [comment]
Closing this as needing a more thorough description. @PPPDUD if you'd like to reopen it, please add more detail!

**Comment by PPPDUD** [comment]
One block would be called "encode list [insert list here]. It would be a reporter block that reports the JSON equivalent of the list. Then there would be a stack block known as "decode JSON list (var) to [insert list here]", which would clear the selected list, and then convert (var) to a list, the results going into the selected list.

Sorry for any confusion :) !
