### ISSUE TITLE
Touching edge sensing block freezes project

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#380]
### Expected behavior

Touching edge sensing block freezes project

### Actual behavior

Running default shark project freezes up instantly - Have tracked it down to the 'touching edge' block. Removing the touching edge boolean block from the project flow fixes the freeze. Adding it in at any point on any sprite appears to freeze it again (when it evaluate it).

### Steps to reproduce

Load the default shark project and click green flag. Remove the touching edge block from the bouncing ball sprite and click green flag again to see it work again.

### Operating system and browser

PC win 10 / Chrome 55.0.2883.87 m.

n.b. I know this is an early build - would you prefer me not to raise issues at this point? Just let me know - thanks.

**Comment by thisandagain** [comment]
These are all incredibly helpful. Thank you for reporting and please keep it up! We still have a ton of work to do so it might take us a little time to get to these, but having all of these bugs reported with a repro is more helpful that you know. :-)

**Comment by griffpatch** [comment]
Excellent ;) - Really enjoying watching your progress! Hope you guys are
having fun building the future of Scratch *grin*

**Comment by rasmushaglund** [comment]
Where can I find the shark project?

**Comment by paulkaplan** [comment]
The shark project was the old default vm playground project. It has since changed, but testing the touching-edge block seems to work ok now. Closing.
