### ISSUE TITLE
How to display a part of a costume?

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-vm#3822]
Is there any way to display a section of a costume onto the stage by making an extension?

**Comment by RixInGithub** [comment]
*Can* be possible if you know how un-sandbox extensions to access the deep Scratch API (is what I call)

**Comment by cwillisf** [comment]
Hi @Praquron! Extensions can do a lot of things, but the current extension system isn't really designed to alter a costume. If you want to explore features like that, you'll probably need to modify `scratch-vm` and maybe `scratch-render` in your own fork.
