### ISSUE TITLE
Pen Blocks Request

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#383]
### Pen blocks aren't yet implemented

I assume this is already on the todo list. However, per the new contribution guidelines, I wanted to bring up the need for pen block implementation before I went any farther in playing around. My intention is to mock up a concept, so that people over here can play. If the mock up is to your liking, I can make a pull request.

The implementation I was thinking about has trails as a drawable just above the stage, and then have pen blocks modify the skin of said drawable.

**Comment by thisandagain** [comment]
Thanks for the question! Luck would have it that @cwillisf is actually wrapping up the implementation of pen right now which we are tracking here:
https://github.com/LLK/scratch-render/issues/6
