### ISSUE TITLE
Pen size restricted to 255?

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#385]
### Expected Behavior

_It can get bigger than 255 because there is no longer a flash player limitation_

### Actual Behavior

_It get locked at 255._

### Steps to Reproduce

_Place a 255 size dot, then place a 1000 sized dot, no difference._

### Operating System and Browser

_Windows 10 Google Chrome_

**Comment by mrjacobbloom** [comment]
#97
