### ISSUE TITLE
3D projects run slower

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#386]
### Expected Behavior

_It runs smooth as it did in 2.0 (25-30 FPS)_

### Actual Behavior

_It runs at 2-3 FPS._

### Steps to Reproduce

_Go to https://llk.github.io/scratch-vm/#118602500 and note the FPS (I did not make this project)_

### Operating System and Browser

_Windows 10 Google Chrome_

**Comment by tmickel** [comment]
pretty cool that it sort of runs though! :) The nice thing about JavaScript is there are some really neat tools to figure out where things are slow.

In Chrome Developer Tools->Timeline, for 5s:
<img width="590" alt="screen shot 2017-01-21 at 10 35 50 pm" src="https://cloud.githubusercontent.com/assets/120403/22179717/f8716f0c-e029-11e6-80ad-95bcace9feaf.png">

Seems like there are lots of optimizations to be made around procedure calls and look-ups, which makes sense (the 3d project above uses tons of procedures). Scratch 2.0 has some interesting optimizations for that sort of thing built-in, like here:
https://github.com/LLK/scratch-flash/blob/develop/src/interpreter/Interpreter.as#L647
Where links to procedure blocks are stored on the sprite itself. I wonder if similar optimizations might help in scratch-vm :)

**Comment by ed-cooper** [comment]
lol - so I wasn't the only person who thought that project would be a fun test? 😆 

Note that the only reason the project actually works is that I handle clearing the screen myself - otherwise clearing the screen doesn't seem to work?

Is that issue being tracked anywhere as I couldn't see it myself

**Comment by griffpatch** [comment]
For a performance test just try creating a single loop that increments a
variable and see how the execution time compares in scratch 2 & 3... I
think scratch 2 is currently around 10 times faster? Yet I agree, scratch 3
is really taking shape! It's very satisfying to see complex projects
running :)

**Comment by TheBrokenRail** [comment]
I tested a less intense 3D project this time a recreation of portal, also has extremely bad FPS unlike 2.0:

https://llk.github.io/scratch-vm/#16158656

**Comment by TheBrokenRail** [comment]
Portal also doesn't seem to render right in 3.0.

**Comment by TheBrokenRail** [comment]
This runs better but still slow, also the world designer pixels look odd.

https://llk.github.io/scratch-vm/#67575180

**Comment by thisandagain** [comment]
Closing in favor of performance meta bug available here:
https://github.com/LLK/scratch-vm/issues/391

Future performance examples should be added there as comments or new issues created with very specific optimizations / bottleneck descriptions.
