### ISSUE TITLE
If a variable is created in the lookupOrCreateVariable function it is not created on the scratch-blocks side.

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#387]
### Expected Behavior

_It is created on scratch-blocks as well as on VM._

### Actual Behavior

_It is only created on the scratch-vm side of things._

### Steps to Reproduce

_Create a set variable block that has a text shadow and set the text to a nonexistent variable and run it, the variable will be created on the scratch-vm side but will not appear in any menus._

### Operating System and Browser

_Windows 10 Google Chrome_

### How this could be fixed

_This could be fixed by adding a check when creating a variable in the lookupOrCreateVariable function to check if it is in scratch-blocks, if not add it to the workspace._

**Comment by thisandagain** [comment]
We are aware that significant work is still needed for variables and lists.

**Comment by TheBrokenRail** [comment]
Should I make a PR to fix this?


________________________________

**Comment by thisandagain** [comment]
No thanks. We have a bunch of work from upstream blockly that we are trying
to land now that will impact this.
