### ISSUE TITLE
Turbo mode is way slower in 3.0 than 2.0.

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#389]
### Expected Behavior

_3.0 turbo mode is as fast or faster than 2.0._

### Actual Behavior

_It is way slower._

### Steps to Reproduce

_Go to https://scratch.mit.edu/projects/67575180/ and https://llk.github.io/scratch-vm/#67575180 and play them in turbo mode and see which one takes longer to generate the drawing board._

### Operating System and Browser

_Windows 10 Google Chrome_

**Comment by thisandagain** [comment]
Tracking in #391
