### ISSUE TITLE
The hats for my Scratch extension don't work...

### ISSUE THREAD

**Issue by RixInGithub** [LLK/scratch-vm#3899]
So, I am currently making an unofficial Scratch extension called GlobalComm. GlobalComm is an extension that works like the messages thing, but ***across every project*** (and sprites, of course) that uses GlobalComm.

I'm trying to make a hat that looks like this:

![when message [hello] gotten :: hat #00bfff](https://user-images.githubusercontent.com/87478581/221866322-64575435-09ea-4787-8bdf-aeb2c943a54d.svg)

Pretty self-explanatory, I'd say. When I click the block in the toolbar, these two appear:

```diff
- vm cannot compile script Sprite1 Error: Not compiling an edge-activated hat: GlobalComm_onMsg
- 	at h.generate (irgen.js:1460:23)
- 	at e.exports.generateScriptTree (irgen.js:1514:34)
- 	at e.exports.generate (irgen.js:1550:28)
- 	at e.exports (compile.js:6:28)
- 	at a.tryCompile (thread.js:468:26)
- 	at H._pushThread (runtime.js:1813:20)
- 	at H.toggleScript (runtime.js:1920:14)
- 	at g.blocklyListen (blocks.js:411:26)
- 	at e.exports.flyoutBlockListener (virtual-machine.js:1383:35)
- 	at Blockly.Workspace.fireChangeListener (blockly_compressed_vertical.js:346:240)
```
```diff
- Custom extension block error TypeError: Cannot read properties of undefined (reading 'startHats')
```
And the running border doesn't disappear unless I click the stop button or click the hat again.

Here's some more information:
- [Turbowarp](https://turbowarp.org/editor) link: https://turbowarp.org/editor?extension=https://globalcomm.rixthetyrunt.repl.co/globalComm.js

And, that's it... Feel free to ask me info I missed out on, and maybe I'll be able to answer ya!

**[FULL SOURCE CODE INCOMING]**
```js

class GlobalComm {
	getHats() {
		return {
			GlobalComm_onMsg: {
				restartExistingThreads: false,
				edgeActivated: true
			}
		}
	}
	getInfo() {
		return {
			color1: "#00bfff",
			id: "GlobalComm",
			name: "GlobalComm",
			description: "A yet another Scratch extension",
			blocks: [
				{
					opcode: "sendMsg",
					blockType: Scratch.BlockType.COMMAND,
					text: "send message [MSG]",
					arguments: {
						MSG: {
							type: Scratch.ArgumentType.STRING,
							defaultValue: "hello"
						}
					}
				},
				{
					opcode: "latestMsg",
					blockType: Scratch.BlockType.REPORTER,
					text: "latest message"
				},
				"---",
				{
					opcode: "onMsg",
					blockType: Scratch.BlockType.HAT,
					text: "when message [MSG] gotten",
					arguments: {
						MSG: {
							type: Scratch.ArgumentType.STRING,
							defaultValue: "hello"
						}
					}
				},
				{
					opcode: "didGetMsg",
					blockType: Scratch.BlockType.BOOLEAN,
					text: "did get message [MSG]?",
					arguments: {
						MSG: {
							type: Scratch.ArgumentType.STRING,
							defaultValue: "hello"
						}
					}
				}
			]
		}
	}
	sendMsg(args) {
		var xhr = new XMLHttpRequest()
		xhr.open("GET", "https://globalcomm.rixthetyrunt.repl.co/api/send/" + (args.MSG != "" ? "?msg=" + encodeURIComponent(args.MSG) : ""), false)
		xhr.send()
	}
	didGetMsg(args) {
		return this.latestMsg() == args.MSG // I'm a big brainer and like one-liners
	}
	latestMsg() {
		var xhr = new XMLHttpRequest()
		xhr.open("GET", "https://globalcomm.rixthetyrunt.repl.co/api/get/", false)
		xhr.send()
		return xhr.responseText
	}
	onMsg(args) {
		if (this.didGetMsg(args) == true) {
			this.runtime.startHats("GlobalComm_onMsg", args)
		}
	}
}

Scratch.extensions.register(new GlobalComm())
```

PS: Some of this code is borrowed from the [Events](https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_event.js) blocks

**Comment by cwillisf** [comment]
Hi, @RixInGithub! This sounds like a pretty fun project! It looks like the trouble you're seeing is related to TurboWarp, though, rather than Scratch. Maybe you could ask about it over in https://github.com/TurboWarp ?

**Comment by RixInGithub** [comment]
> Hi, @RixInGithub! This sounds like a pretty fun project! It looks like the trouble you're seeing is related to TurboWarp, though, rather than Scratch. Maybe you could ask about it over in https://github.com/TurboWarp ?

You see, it's the extension's problem, not TurboWarp's :)

**Comment by adroitwhiz** [comment]
This issue tracker is primarily for problems with `scratch-vm`. You seem to be looking for help with writing your own code.

There are a couple issues with your extension:
- There is no constructor. That's where `this.runtime` should be initialized. Take, for instance, the video extension:
```js
class Scratch3VideoSensingBlocks {
    constructor (runtime) {
        /**
         * The runtime instantiating this block package.
         * @type {Runtime}
         */
        this.runtime = runtime;
        [...]
    }
```
- Edge-activated hat blocks are run once per frame, in order to check if their condition has become true. That means that any project using the "when message gotten" block will be making *30 HTTP requests per second* to your server.

Do note, however, that in general it is considered poor forum etiquette to simply post your code and ask other people to fix it for you. When asking for help, even in places that are meant for it, it's beneficial to include information about the debugging steps you have taken so far, and what you've already tried to fix the issue.
