### ISSUE TITLE
Clear Block Doesn't Work

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#390]
### Expected Behavior

The clear screen block should remove all stamps and pen trails. Discussed in #384 and #386 

### Actual Behavior

Doesn't remove them.

### Steps to Reproduce

Stamp, move, clear.

### Operating System and Browser

Windows 7, chrome 55.0.2883.87 m

### Suggested solution
Add the following or similar to block code:
this.runtime.renderer._allSkins[penSkinId]._canvasDirty=true;

**Comment by thisandagain** [comment]
@SillyInventor Thanks for reporting! Did you want to take this one?

**Comment by TheBrokenRail** [comment]
has patch (#394)
