### ISSUE TITLE
"Set tempo", "change tempo", and "tempo" blocks don't work

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#392]
### Expected Behavior

The [global tempo](https://github.com/LLK/scratch-flash/blob/9fbac92ef3d09ceca0c0782f8a08deaa79e4df69/src/primitives/SoundPrims.as#L59-L67) is set or returned.

### Actual Behavior

In the case of the set/change blocks, an error is thrown in the console; the getter block does not return anything.

```js
Uncaught TypeError: util.target.audioPlayer.setTempo is not a function
    at Scratch3SoundBlocks.setTempo (scratch3_sound.js:119)
```

The source code of scratch-vm and scratch-audio explain the issue:

```js
Scratch3SoundBlocks.prototype.setTempo = function (args, util) {
    var value = Cast.toNumber(args.TEMPO);
    util.target.audioPlayer.setTempo(value);
};
```

There simply is not a `setTempo` method on a sprite's `audioPlayer` (which is an `AudioPlayer`). That's a method on `AudioEngine`:

```js
AudioEngine.prototype.setTempo = function (value) {
    this.currentTempo = value;
};
```

The `audioEngine` is [stored](https://github.com/LLK/scratch-vm/blob/bdabe2efa37eeb9c053d4a8dbe5e85ba051cc34c/src/engine/runtime.js#L322-L328) on the `Runtime`.

Since `runtime` is [stored](https://github.com/LLK/scratch-vm/blob/bdabe2efa37eeb9c053d4a8dbe5e85ba051cc34c/src/blocks/scratch3_sound.js#L4-L10) on the various `Scratch3<..>Blocks` classes, simply changing the appropriate references from `util.target.audioPlayer` to `this.runtime.audioEngine` should fix the issue (though I don't know if you'd rather have a method on `runtime` to manipulate the audio engine).

### Steps to Reproduce

Open scratch-vm and run the "change tempo", "set tempo" or "tempo" blocks.

### Operating System and Browser

macOS 10.12, Google Chrome 55

**Comment by thisandagain** [comment]
Thanks for reporting! We still have lots of work to do with the audio engine, but these bugs are great to have tracked!

**Comment by ericrosenbaum** [comment]
The tempo blocks were fixed in https://github.com/LLK/scratch-audio/pull/14. thanks!
