### ISSUE TITLE
Make a Block Button

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#396]
### Expected Behavior

Under More Blocks, there should be a make a new block button. Said button should open a view to create a C-block or reporter with optional inputs. It should then either generate a 'define' block as in Scratch or open a window for editing blocks as in Snap!. There should there after be a block of that name / type that calls that in More Blocks.

### Actual Behavior

There is a block called 'undefined.'

This would be a useful step for our play test -- though not critical. Is anyone working on this?

**Comment by thisandagain** [comment]
Yeah, we are working on this with the team at Google right now. You can see specs / discussion here:
https://github.com/LLK/scratch-blocks/issues/607
