### ISSUE TITLE
Runtime does not exit warp mode if at end of loop

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#398]
### Expected Behavior

When a custom block (with run without screen refresh) is called as the last block within a loop (that is not running in warp mode) then you would expect the runtime to yield at the end of the loop and the screen to update.

### Actual Behavior

The runtime continues in warp mode around the outer loop and the screen is not updated in line with the project.

### Steps to Reproduce

http://llk.github.io/scratch-vm/#141944442

* Run this project and it hits around 2 fps while just drawing a single pen down.
* Add any new block (like a set var to 0) as the last statement in the loop after the call to the custom block draw and run it again to see 60fps.

I have created a fix here: e849c7576cd0cb7b2bf9ddda62653c6fef6a142f

Here it is running at 60fps on my forked branch: https://griffpatch.github.io/scratch-vm/#141944442

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
Resolved in #406
