### ISSUE TITLE
Firefox 48 - If on edge bounce broken

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#399]
This block is intended to make the sprite turn in the opposite direction when it hits an edge.

What actually happens is that the sprite just keeps moving into the edge of the screen.

To view the error, just make a script saying: 'When green flag clicked, forever, move 10 steps. If on edge bounce.'

This error was viewed in Firefox on Mac OS X 10.6

---
Moved from LLK/scratch-gui#47
/cc @chicken3600

**Comment by thisandagain** [comment]
Cannot replicate in Chrome or latest Firefox. This seems to be specific to an old version of Firefox (see OS version). Moving to backlog.

**Comment by thisandagain** [comment]
@chicken3600 What version of Firefox are you using?

**Comment by ghost** [comment]
Version 48.0.2

**Comment by ghost** [comment]
Note: This bug was in scratch-gui and not scratch-vm

**Comment by towerofnix** [comment]
Wait, does that mean that it works fine in scratch-vm but doesn't work in scratch-gui (for you)?

**Comment by ghost** [comment]
Yes. Whatever is going I really have no idea(JavaScript is not one of my strengths).

**Comment by ghost** [comment]
Actually, I was wrong. It's also broken in scratch-vm for me.

**Comment by ghost** [comment]
Please close the issue because it's fixed now.

**Comment by thisandagain** [comment]
@chicken3600 Did you update your browser?
