### ISSUE TITLE
Pixely images rendered

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-vm#405]
### Expected Behavior

Image should not be pixely. 

### Actual Behavior

![screenshot 2017-01-27 at 8 57 49 pm](https://cloud.githubusercontent.com/assets/10731781/22393391/82ab595a-e4d3-11e6-9d71-571bb6a748be.png)

### Steps to Reproduce

1. In this case, I opened Scratch GUI but I think it is a rendering issue...
2. Observe the already place scratch cat

### Operating System and Browser

Chromebook latest version

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#77
