### ISSUE TITLE
Avoid negative index lookups

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#407]
### Run-time Optimisation

The thread.stackFrames array is accessed all the time to retrieve the 'parent' stack frame. This is done using as index of [this.stack.length - 1]. However, a lot of the time this evaluated to [-1]. Although this results in null, which is fine, to get to this javascript actually defers from a numeric array lookup to an object lookup using the string "-1". This is roughly 100 times slower to compute and so a simple catch for negative indexes is well worth the extra check.

**Comment by thisandagain** [comment]
Related to #391

**Comment by griffpatch** [comment]
Am I doing this wrong raising an issue log as well as a pull request? - Do I just need the one? and it will be linked back to your 391 issue?

**Comment by thisandagain** [comment]
Nope! This is perfect.

**Comment by thisandagain** [comment]
Resolved in #408
