### ISSUE TITLE
Variable / List Monitors

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#417]
### Expected Behavior

Checking the box next to variable should cause the value to appear on screen.

### Actual Behavior

It doesn't.

### Steps to Reproduce

Click box.

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.76 

I am sure you're already working on this, just adding an issue so I can share our first play test findings / complaints.

**Comment by thisandagain** [comment]
@rschamp This is probably going to involve work in the blocks, VM, and GUI. Do you want to track it here for now?

**Comment by rschamp** [comment]
Tracking here makes sense for now I think.

**Comment by paulkaplan** [comment]
I'm going to close this one in favor of the first iteration milestone in this new issue: https://github.com/LLK/scratch-vm/issues/545
