### ISSUE TITLE
Stamping hidden sprite doesn't do anything

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#425]
### Expected Behavior

The sprite's costume should be stamped (with graphic effects).

In [the demo project](http://llk.github.io/scratch-vm/#143013722), this should be visible:

![Stage](https://cloud.githubusercontent.com/assets/9948030/22522254/51f3b124-e891-11e6-8197-eca79d32f51f.png)

### Actual Behavior

Nothing is stamped. In the demo project, this is visible:

![Stage (3.0)](https://cloud.githubusercontent.com/assets/9948030/22522360/b5d5ebd0-e891-11e6-8d32-71064bcf4071.png)

Note the demo project renders the top row while the sprite is visible, and the bottom row while hidden.

### Steps to Reproduce

1. Attempt to stamp a hidden sprite by using the `stamp` block after the `hide` block. Alternatively, open and run [this project](http://llk.github.io/scratch-vm/#143013722).

[Here's the project opened in 2.0, for reference.](https://scratch.mit.edu/projects/143013722/)

### Operating System and Browser

macOS 10.12, Google Chrome 56.0.2924.76

**Comment by thisandagain** [comment]
@liam4 Nice catch!

**Comment by joshlory** [comment]
No longer repros?

<img width="1263" alt="screen shot 2017-08-30 at 8 36 07 pm" src="https://user-images.githubusercontent.com/413693/29905321-ea2fc8ac-8dc2-11e7-8d23-e476188d214f.png">

**Comment by rschamp** [comment]
I wonder what fixed this... good work mystery PR!
