### ISSUE TITLE
Use scratch-storage

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-vm#427]
### Expected Behavior

The VM should use the [scratch-storage](/LLK/scratch-storage) module for loading files. Ideally we should do this in such a way that the storage module could be replaced with a different implementation if necessary.

### Actual Behavior

The VM (actually `playground.js` [here](https://github.com/LLK/scratch-vm/blob/fec9e5b91a1a72f78bc9b860ec6784f2641a4600/playground/playground.js#L9)) loads project files itself, relies on the renderer to load costumes, etc.

**Comment by towerofnix** [comment]
Ohhh, more repositories! Modularized code is the best.

Any plan on publishing this repo?

**Comment by cwillisf** [comment]
@liam4 yep! It needs a little bit of work to make it "official" and then scratch-storage will become public like the rest.
