### ISSUE TITLE
Sound Effects Pitch and Pan Don't Effect Instruments

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#430]
### Expected Behavior

Pitch and pan effects should change the frequency and speaker side intensity of instruments respectively.

### Actual Behavior

No noticeable change.

### Steps to Reproduce

Play noise or note, change pitch, replay noise or note.

### Operating System and Browser

Ubuntu 16.0.4, Chrome 56.0.2924.87

**Comment by ericrosenbaum** [comment]
moved to https://github.com/LLK/scratch-audio/issues/18
