### ISSUE TITLE
Broadcasts are case sensitive

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#433]
### Expected Behavior

A broadcast in scratch 2 is case insensitive. Some projects (not sure how) broadcast and receive in different case. You would expect these to still trigger. 

### Actual Behavior

They do not trigger. 

### Steps to Reproduce

You need a project with a broadcast and receiver with the same name, but different case.

See: http://llk.github.io/scratch-vm/#144148381

### Operating System and Browser

Any

**Comment by thisandagain** [comment]
Resolved in #440
