### ISSUE TITLE
src/engine/sequencer.js bug?

### ISSUE THREAD

**Issue by greenSnot** [LLK/scratch-vm#44]
What's this in row 68 of src/engine/sequencer?
`activeThread.status === Thread.STATUS_RUNNING;`

**Comment by tmickel** [comment]
That is a very good question and looks like a bug to me as well.

We wrote this code very quickly to prepare for a prototype demo, hopefully we'll get it fixed up :)

**Comment by tmickel** [comment]
Permalink: https://github.com/LLK/scratch-vm/blob/2d834de76603756038b46d693c1840f7fd13253d/src/engine/sequencer.js#L68

**Comment by greenSnot** [comment]
also: https://github.com/LLK/scratch-vm/blob/2d834de76603756038b46d693c1840f7fd13253d/src/engine/sequencer.js#L63  The condition will always be false because of line 55.

**Comment by tmickel** [comment]
I believe this is addressed in the refactor we just merged. Thanks again for the report!
