### ISSUE TITLE
Skin Measurements Error

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#441]
### Expected Behavior

Scratch VM should run without errors.

### Actual Behavior

Got the error:

![image](https://cloud.githubusercontent.com/assets/8440451/22754478/a5a2c22a-ee0d-11e6-9198-fd28c4310eab.png)

### Steps to Reproduce

Navigate to https://llk.github.io/scratch-vm/ (currently running project 119615668), and press green flag.

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.87

Seems that the costume is loading after call to measurements. Perhaps you should use a get method that will return width and height of 0 for SVGRenderer.measurements if none. Although simply assigning to _measurements on creation can also solve this problem.

**Comment by SillyInventor** [comment]
Do you want a PR?

**Comment by thisandagain** [comment]
@cwillisf any thoughts on this one?

**Comment by cwillisf** [comment]
I think this will stop being an issue once we get the renderer out of the business of loading costumes: after that, every `Skin` will always have a valid logical size. That said, I think initializing `_measurements` would make sense even without this bug, so I'd definitely be OK with that as a fix here :)

@SillyInventor, thanks for investigating! If you want to put together a PR for a fix I'd be happy to review & merge it.
