### ISSUE TITLE
toUperCase Error

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#443]
### Expected Behavior

Scratch VM should run without error

### Actual Behavior

Get error:

![image](https://cloud.githubusercontent.com/assets/8440451/22795137/93614756-eec3-11e6-8924-7e2efbd16e6c.png)

### Steps to Reproduce

Press a key not recognized by scratch (like control) while scratch is focused.

### Operating System and Browser

Ubuntu 16.04, Chrome 56.0.2924.87

**Comment by ericrosenbaum** [comment]
I noticed this error as well. It is triggered by typing a key that is not in the Scratch key events menu. So for example, focus scratch by clicking on the stage or blocks area and then press tab, caps lock, shift, control, option, or command (and probably others).

**Comment by SillyInventor** [comment]
You could just change it so that keyboard returns an empty string instead of null for unused values.

**Comment by SillyInventor** [comment]
Do you want a PR for this?

**Comment by thisandagain** [comment]
@SillyInventor Yes please! 😄
