### ISSUE TITLE
Throws Error When IsTouching and Stamp Hidden Sprite

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#453]
### Expected Behavior

No error. Continues to play.

### Actual Behavior

Stops and gives error:
![image](https://cloud.githubusercontent.com/assets/8440451/22856235/aeb69e4a-f05b-11e6-9d39-31ca50fd6791.png)

### Steps to Reproduce

Navigate to https://llk.github.io/scratch-vm/ , remove show block from start as clone script, press green flag.

### Operating System and Browser

Windows 7, Chrome 56.0.2924.87

Is touching generates bounds at infinity if sprite hidden, stamp tries to use infinite bounds and crashes. Perhaps bounds should be initialized at 0, all drawables should have finite bounds, or a check should be put in getBounds.

**Comment by SillyInventor** [comment]
So the easiest way to fix this is to add an item in drawable.needsConvexHullPoints() for _convexHullPoints is empty, and to use drawable.getFastBounds() in rengerGL.getBounds(). Also fixes #450. Let me know if you want such a change.

**Comment by cwillisf** [comment]
@SillyInventor, thanks! Any time you feel like you can fix an issue please feel free to put together a pull request. This goes double for any issue with the "help wanted" label, which means we feel it's especially well suited for contributors outside the Scratch team. Also, if an item is in the "Backlog" milestone it usually means that nobody on the team is working on it yet.

Thanks again - we really appreciate the help!

**Comment by SillyInventor** [comment]
Oh, I see. I just read the Contributor Guidelines and figured I shouldn't make a pull request unless specifically asked.
