### ISSUE TITLE
SVG costumes don't stamp after "if on edge, bounce" runs

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-vm#455]
https://llk.github.io/scratch-vm/#145257756 SVG behavior (broken)
https://llk.github.io/scratch-vm/#145258263 Bitmap behavior (works)

This may be in the renderer but putting here in case it's a combination of the VM + renderer

**Comment by SillyInventor** [comment]
This is because _getConvexHullPointsForDrawable doesn't handle non-integer skin sizes.
