### ISSUE TITLE
Execution bug: can't escape from conditional branches that end with a Promise-resolution-terminating command block

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#464]
### Expected Behavior

Some command blocks use Promises to indicate when they're finished. When the Promise resolves, execution should proceed to the next block.

I think the current set of blocks uses this in two places: playing sounds, and say/think (as a demo). But it's conceivable this could be used for extensions and other network-accessing blocks.

If one of these blocks is inside a conditional branch (the `if` or `if-else` C-block), at the end, execution should pop out of the branch (to whatever's connected to the bottom of the if/if-else).

### Actual Behavior

If you place a Promise-using command block at the end of a conditional branch (i.e., as the last block inside the C), the branch will loop forever!

I haven't looked into why this happens. It seems to be exclusive to conditionals (if and if-else) but could affect other things.

### Steps to Reproduce

2.0 demo: https://scratch.mit.edu/projects/145800579/ (the if conditional executes once instantaneously, and then the green checkmark should appear).
3.0: https://llk.github.io/scratch-vm/#145800579 (red X forever. Because "say" terminates with a Promise resolution. You can replace the "say" with any sound-playing block to achieve the same).

### Operating System and Browser

OS X 10.12.1 Beta, Chrome Version 56.0.2924.87 (64-bit)

**Comment by rasmushaglund** [comment]
This is fixed, right?

**Comment by rschamp** [comment]
Yes, thanks.
