### ISSUE TITLE
Current playground URL is confusing / error prone

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#466]
The current local development URL for the VM playground is:
`http://localhost:8073/playground/`

Navigating to (what is normative for local development) `http://localhost:8073` leads to:
![image](https://cloud.githubusercontent.com/assets/747641/23094744/8dd29b68-f5cc-11e6-84a5-4e5c06f3cffe.png)

Navigating to `http://localhost:8073/playground` (note the lack of trailing `/`) leads to:
![image](https://cloud.githubusercontent.com/assets/747641/23094750/a69b6ab2-f5cc-11e6-8bc3-b2bb64878c6f.png)

I would expect one of these paths to work. The current path seems to be convenient from a technical perspective, but not necessarily from a human one.

---
Moved from LLK/scratch-blocks#799
/cc @thisandagain

**Comment by rschamp** [comment]
I agree. I tried making this work with the single webpack config, but I think the way to accomplish the playground being available at `/` is to use separate configs for running the dev server and building.
