### ISSUE TITLE
Any block with branch(es) will loop depending on the last block in the branch

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#467]
### Expected Behavior

Block execution behaves as normal.

### Actual Behavior

In a block formation such as this, the "play sound" block will loop over on itself:

![Demo 1](https://cloud.githubusercontent.com/assets/9948030/23095860/de0ce62c-f5e7-11e6-873c-2ae74f873156.png)

In this script, the "play drum" block loops:

![Demo 2](https://cloud.githubusercontent.com/assets/9948030/23095863/f3ce6eea-f5e7-11e6-9b77-ee2fd68f3528.png)

In this script, no blocks loop – it behaves as you'd expect (play sound, wait 0.25 seconds, end):

![Demo 3](https://cloud.githubusercontent.com/assets/9948030/23095878/1ffe02e6-f5e8-11e6-91fb-a5666dff8926.png)

In this script, however, the two blocks do loop:

![Demo 4](https://cloud.githubusercontent.com/assets/9948030/23095896/4d047b94-f5e8-11e6-9ba1-f4f86bbbfda6.png)

Note that the parent block (i.e., the one with branches) is looping. This script will play a single meow and then constantly run the "play drum" block:

![Demo 5](https://cloud.githubusercontent.com/assets/9948030/23095910/72c44ab2-f5e8-11e6-86d2-f0be8e83d0fb.png)

A few other blocks I noticed that caused these issues when put at the end of a branch – "rest for beats", "say"/"think", but *not* "wait 1 secs". I imagine this is probably an issue in how a block is marked as "finished running"..?

### Steps to Reproduce

Create scripts as described in "actual behavior" and run them.

### Operating System and Browser

macOS 10.12, Chrome 56

**Comment by thisandagain** [comment]
Hi @liam4. I believe that this may be a dupe of https://github.com/LLK/scratch-vm/issues/464, but the screenshots and additional tests are most appreciated. I'm going to keep this open for now, but may close should we decide that this is a duplicate.

**Comment by griffpatch** [comment]
I think this issue is fixed in PR #472

**Comment by SillyInventor** [comment]
Should be closed?

**Comment by towerofnix** [comment]
I believe so, yes; the issue isn't happening anymore. Thanks for reminding!
