### ISSUE TITLE
Extend Test Coverage

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#471]
### Expected Behavior

It's usually best if you have test coverage >90%

### Actual Behavior

Currently around 81%.

Does anyone mind if I add some tests?

**Comment by rschamp** [comment]
More tests are always welcome!

**Comment by rasmushaglund** [comment]
What kind of tests are needed? Are we looking for more detailed integration tests perhaps?

**Comment by rschamp** [comment]
@rasmushaglund If you run `npm run coverage` you will get a coverage report that looks like this:
![image](https://cloud.githubusercontent.com/assets/1512021/24805701/b5051be6-1b80-11e7-85d0-b652f4e96112.png)

You can use that as a guide to find which parts of the project are not covered by tests.

**Comment by rschamp** [comment]
Both unit and integration tests are helpful, but unit tests are the easiest for us to verify.

**Comment by SillyInventor** [comment]
I have been busy on other projects. Thank you for picking up the torch. What I did is in #527.

**Comment by thisandagain** [comment]
Closing this in favor of more focused issues addressing specific test coverage areas.
