### ISSUE TITLE
The Backdrop Doesn't Change

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#478]
### Expected Behavior

After launch the backdrop should change from launch pad to stars ~ 30 seconds in.

### Actual Behavior

It doesn't, and persists until the moon.

### Steps to Reproduce

Navigate to https://llk.github.io/scratch-gui/#104024967/ and press the green flag.

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.87

**Comment by cwillisf** [comment]
The backdrop is changing for me on Windows 10 with Chrome 56.0.2924.87.
I am seeing some problems with text, probably related to #479.

**Comment by SillyInventor** [comment]
I think this was a result of not all the images loading or not loading quickly enough. It happened a few times in a row, but I can't reproduce it anymore.
