### ISSUE TITLE
Sprites not displaying

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#479]
### Expected Behavior

Lutin 1, 2, & 3 should have pink images of bubbles, "ok!!!", and "Hazzard!!!" respectively in https://llk.github.io/scratch-gui/#144880441/ 

### Actual Behavior

All missing.

### Steps to Reproduce

Navigate to https://llk.github.io/scratch-gui/#144880441/ 

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.87

Not sure if this should be in render, but I'm putting here for now.

**Comment by cwillisf** [comment]
I think this is a problem with text handling in our SVG code, so I'm moving it to scratch-render. Thanks for the report, @SillyInventor!
