### ISSUE TITLE
Clones don't inherit pen color

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#481]
Reported by a Scratcher in the forums:
> I found a bug: clones don't inherit pen colour from their parents. It can be seen in [this project](http://llk.github.io/scratch-vm/#24900838), where the drips and spray will always be the default blue regardless of the main paint colour.

### Expected Behavior

- Clones should inherit pen color from the sprite which created them

### Actual Behavior

- They inherit the default "blue" pen color

### Operating System and Browser

Mac OS 10.12.3  |  Chrome Version 56.0.2924.87 (64-bit)

**Comment by SillyInventor** [comment]
This can be fixed by copying _customState and _events from renderedTarget to newClone in makeClone.

**Comment by rasmushaglund** [comment]
Fixed in https://github.com/LLK/scratch-vm/pull/525. For some reason it wasn't automagically referenced in this ticket.

**Comment by cwillisf** [comment]
Partially resolved by #555, tracking remained in #557
