### ISSUE TITLE
npm install- not working on windows

### ISSUE THREAD

**Issue by Vanrao** [LLK/scratch-vm#482]
Please help me get this running. Working fine on Ubuntu.
### Operating System and Browser

Windows 10

**Comment by bates64** [comment]
You're going to have to actually give us the error or it's gonna be _pretty_ hard to help you :)

**Comment by benajaero** [comment]
Have you installed node and npm?

**Comment by Vanrao** [comment]
npm install fails by throwing error in line number:471 in module.js
Error: Cannot find module 'copy-webpack-plugin'

@Blaze349 I have installed both. Set up the path variables also.

**Comment by thisandagain** [comment]
Hi @Vanrao ! Could you please share the complete contents on the `npm-debug` log?

**Comment by benajaero** [comment]
Try this.
`npm install --save-dev copy-webpack-plugin`

Or:
`sudo npm install --global webpack`

**Comment by Vanrao** [comment]
Thank you. It worked :)
