### ISSUE TITLE
Hidden sprites don't stamp (they do in 2.0)

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#492]
Reported via internal playtest 3/3/17.

### Expected Behavior

A hidden sprite should stamp, as it does in 2.0, unless we intentionally want to change that behaviour in 3.0?

### Actual Behavior

A hidden sprite doesn't stamp, while it does in 2.0 (e.g. Project ID 77009574).

### Steps to Reproduce

Use Project ID 77009574 to view the behaviour.

### Operating System and Browser

_Mac & Chrome_

---
Moved from LLK/scratch-gui#188
/cc @jwzimmer

**Comment by mrjacobbloom** [comment]
I vote to definitely keep this behavior the way it was in 2.0
