### ISSUE TITLE
Can't import/export XML in Playground

### ISSUE THREAD

**Issue by rasmushaglund** [LLK/scratch-vm#523]
### Expected Behavior

Should be able to import/export XML

### Actual Behavior

Importing/exporting XML in playground result in an error

### Steps to Reproduce

Navigate to http://llk.github.io/scratch-vm/ or http://localhost:8073/playground/ (latest master) and pressing "Export to XML" or "Import from XML".

Both actions result in `Uncaught ReferenceError: workspace is not defined`

### Operating System and Browser

Linux/Mint on Google Chrome 56.0.2924.87 (64-bit)

**Comment by TheBrokenRail** [comment]
Now that ```workspace``` is no longer a global variable it needs to go to ```Scratch.workspace``` instead.

**Comment by rasmushaglund** [comment]
Sounds good, I can fix it and create a pull request.

**Comment by cwillisf** [comment]
Resolved by #524 -- thanks, @rasmushaglund!
