### ISSUE TITLE
No Glow on blocks (I do not mean stack glow)

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#532]
### Expected Behavior

_Blocks should glow when running._

### Actual Behavior

_They just stack glow._

### Steps to Reproduce

_Make a forever loop with wait blocks in it and run it._

#### What Should Happen
![glow1](https://cloud.githubusercontent.com/assets/17478432/24981838/814386aa-1fac-11e7-960e-11f7f874becd.PNG)
#### What Does Happen
![glow2](https://cloud.githubusercontent.com/assets/17478432/24981850/8a34ac30-1fac-11e7-9002-cdecb6586c80.PNG)

**Comment by Grinthy** [comment]
I don't see any difference, other than the 2nd image's background being black, but that not related.

Can you elaborate?
