### ISSUE TITLE
Figure out how to translate labels for monitors

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-vm#565]
### Expected Behavior

Monitor labels should change based on the language that the rest of Scratch is in. The decimal point in number monitors should change to a comma in some countries. Also we should truncate the numbers after the decimal.

### Actual Behavior

Things are in English

### Steps to Reproduce

Check the check box next to a reporter block, say x position
Relevant code: https://github.com/LLK/scratch-vm/pull/560/files#diff-c2e52c759bccc44bfc3789bbfe5d9b2eR303

**Comment by paulkaplan** [comment]
The monitor labels are now translated
