### ISSUE TITLE
Crash on sending too many commands via Lego WeDo extension

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#572]
### Expected Behavior

When using the Lego WeDo 2.0 extension, I should be able to safely run a stack that sends commands in a forever loop, such as this one:

<img width="314" alt="screen shot 2017-05-17 at 2 09 17 pm" src="https://cloud.githubusercontent.com/assets/567844/26169119/89919882-3b0a-11e7-8143-c129c9ccb71c.png">

### Actual Behavior

In the case of the stack above, the code ran correctly for a half second or so, then the WeDo disconnected, the computer became unresponsive, and the OS crashed with a "gray screen of death," forcing a restart.

### Steps to Reproduce

Save your work first!

Use the extensions prototyping branches of [scratch-vm](https://github.com/llk/scratch-vm/tree/feature/extensions-prototype) and [scratch-gui](https://github.com/llk/scratch-gui/tree/feature/extension-prototype).

Add a WeDo extension sprite.

Run the stack shown above, set light color in a forever loop.

Crash!

### Operating System and Browser

Mac OS 10.11.6 Chrome 58.0

**Comment by ericrosenbaum** [comment]
I have a workaround for this- just adding a short wait time (200ms) to each block that sends a message to the wedo seems to prevent it. Even with that, though, it's probably still possible to trigger this bug and the resulting OS crash. I'll file another bug for scratch device manager, where maybe we should be throttling messages somehow.

**Comment by thisandagain** [comment]
This should probably *also* be handled by the device manager.

**Comment by ericrosenbaum** [comment]
fixed!
