### ISSUE TITLE
Pixel Quest Game fails: Messages not received

### ISSUE THREAD

**Issue by AnmAtAnm** [LLK/scratch-vm#592]
### Expected Behavior

Load https://llk.github.io/scratch-gui/#62306380
When I click the "Start" button, the main menu should go away, music should play, etc.

### Actual Behavior

 * Variable StartGame does gets set (click was registered)
 * "musicbleh" and "startlevel" messages not received by clouds, background, etc. (verified by an edited version)

### Steps to Reproduce

 * Load https://llk.github.io/scratch-gui/#62306380
 * Click Green flag until resources load
 * Click start

### Operating System and Browser

Chrome 58 on Mac 10.12

**Comment by SillyInventor** [comment]
Click is selecting 'white screen' rather than start button. Perhaps because pick is ignoring ghost effect.

**Comment by paulkaplan** [comment]
Start button seems to work now
