### ISSUE TITLE
Dragging a sprite doesn't bring it to front layer

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-vm#603]
### Expected Behavior

In 2.0, when you drag a sprite, it goes to the front/ top layer.

I'm not sure if we want the 2.0 behaviour in 3.0 or not, since it can be annoying to re-layer your sprite if you just want to adjust the position a bit to see how it looks.

### Actual Behavior

Reported by Shruti during the Catch Game Internal Playtest II (6/12/17):
> When you drag the sprite on the stage, it doesn't come in front of other sprites. Only the one that's added later remains in front.

### Steps to Reproduce

Add a 2nd sprite to the project. Drag Scratch Cat (1st sprite), then let it go when it overlaps with the 2nd sprite. Note it's behind that sprite.

### Operating System and Browser

_Chrome, Mac_

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/161
