### ISSUE TITLE
Uncaught TypeError: Cannot read property 'variables' of undefined

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-vm#604]
This has the same symptom as https://github.com/LLK/scratch-blocks/issues/842, so I'm not sure if it should be tracked separately, but I went ahead and filed it since it had a different error in the console.

### Expected Behavior

I should see a different set of blocks for each sprite/ backdrop.

### Actual Behavior

My scripting area doesn't re-render when I switch between sprites. I had no sprites in the project initially, with these blocks in the scripting area, then added the two sprites in the screenshot.

```
Uncaught TypeError: Cannot read property 'variables' of undefined
    at VirtualMachine.emitWorkspaceUpdate (gui.js:22627)
    at VirtualMachine.setEditingTarget (gui.js:22590)
    at TargetPane.handleSelectSprite (gui.js:92511)
    at Object.wrapper [as onClick] (gui.js:2861)
    at SpriteSelectorItem.handleClick (gui.js:50101)
    at wrapper (gui.js:2861)
    at Object.r (lib.min.js:6)
    at a (lib.min.js:6)
    at Object.s [as executeDispatchesInOrder] (lib.min.js:6)
    at f (lib.min.js:6)
```

<img width="926" alt="screen shot 2017-06-12 at 3 24 45 pm" src="https://user-images.githubusercontent.com/1320456/27051404-f9c0e440-4f83-11e7-820a-76bffa3051ed.png">
<img width="912" alt="screen shot 2017-06-12 at 3 24 39 pm" src="https://user-images.githubusercontent.com/1320456/27051405-f9c13896-4f83-11e7-97c5-658e2a0728e0.png">
<img width="642" alt="screen shot 2017-06-12 at 3 21 04 pm" src="https://user-images.githubusercontent.com/1320456/27051406-f9cd9ce4-4f83-11e7-8f86-5d0a310debb4.png">

### Operating System and Browser

_Mac OS El Capitan, Chrome 59_

**Comment by thisandagain** [comment]
@paulkaplan Can you investigate?

**Comment by paulkaplan** [comment]
I haven't been able to reproduce this. @jwzimmer could I get some help finding a repeatable way to get this?

**Comment by SillyInventor** [comment]
Could not replicate on Mac OS Sierra 10.12, Chrome 59.0.3071.115.

**Comment by jwzimmer-zz** [comment]
@paulkaplan I'll try to repro it 👍

**Comment by jwzimmer-zz** [comment]
### Unable to repro

The closest I got to repro'ing was when I encountered the errors here: https://github.com/LLK/scratch-gui/issues/544#issuecomment-315391007. I added some blocks to the project - to the backdrop & to a sprite - but they were not (visible) in the scripting pane when I switched back between those assets to check if they were saved. When I checked the console, I saw the errors in the linked comment. Two monitors were visible on the stage from the previous project (pre-page-refresh).

Closing for lack of repro, if we encounter this again we can re-open.

### Repro attempts
_Mac OS El Capitan, Chrome 59_
- Added multiple sprites to a 2.0 project, put blocks in the various sprites
- Added very large value for the variable
- Noticed https://github.com/LLK/scratch-gui/issues/544
- Added blocks to every sprite
- Switched between active sprites & backdrop very often/ quickly
- Played & edited project
- Deleted some sprites
- Switched between active sprites & backdrop very often/ quickly
- Switched to other tabs then back to 3.0 tab
- Switched to other applications like Sublime, Safari
- Edited sprites using the sprite info pane
- Dragged sprites on stage to change which sprite is active (rather than clicking thumbnails)
- Scrolled around scripting area
- Used zoom in scripting area
- Switched through multiple tabs before returning to 3.0 tab
- Refreshed another tab before returning to 3.0 tab
- I refreshed the 3.0 tab and noticed that the project vanished except for the variable monitors: https://github.com/LLK/scratch-gui/issues/544#issuecomment-315391007
  - **I added some blocks to the project but they were not in the scripting pane when I switched back to that asset to check**
    - This is the closest I have come to repro'ing this issue so far
  - There were errors seemingly related to the variable monitors in the console
- Adding numerous sprites, backdrops, scripts
  - Then deleting them
  - And refreshing the page
  - Adding variables, refreshing page
