### ISSUE TITLE
Uncaught SyntaxError: Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-vm#605]
### Actual Behavior

I saw this error at the same time as I saw https://github.com/LLK/scratch-vm/issues/604. This error appeared in the console first, followed by the error in 604 (multiple times). I'm not sure how my project got into this state.

```
Uncaught SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at VirtualMachine.fromJSON (scratch-vm.js:14820)
    at FileReader.reader.onload (load-button.jsx:19)
```

<img width="1280" alt="screen shot 2017-06-12 at 3 31 11 pm" src="https://user-images.githubusercontent.com/1320456/27051460-32d2985a-4f84-11e7-8655-c5eea49f482b.png">

### Operating System and Browser

_Mac OS El Capitan, Chrome 59_

**Comment by SillyInventor** [comment]
Unable to reproduce as with #604

**Comment by rschamp** [comment]
Thanks @SillyInventor. I will close for now. We can re-open if this gets reported again.
