### ISSUE TITLE
Browser locks up on sending speech synthesis commands too fast

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#607]
### Expected Behavior

It should be possible to call the speech extension block "speak" many many times very fast without locking up the browser. 

### Actual Behavior

A stack like this one causes the browser to lock up:

<img width="212" alt="screen shot 2017-06-13 at 6 34 36 pm" src="https://user-images.githubusercontent.com/567844/27107724-a73cbf0c-5067-11e7-9ee1-f6596a36030e.png">

### Steps to Reproduce

Visit [https://ericrosenbaum.github.io/scratch-gui/](https://ericrosenbaum.github.io/scratch-gui/)

Run the above stack

You'll be forced to restart your browser

### Operating System and Browser

Mac OS 10.11.6 Chrome 59.0

**Comment by paulkaplan** [comment]
Closing this since speech extension will have a different backend from when this bug was reported.
