### ISSUE TITLE
WeDo 2 not connecting - briefly connects, then disconnects

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-vm#615]
Reported during Extensions Internal Playtest (6/16/17).

### Expected Behavior

The WeDo should be able to connect to the SDM & Scratch. It should remain connected while the user is active.

### Actual Behavior

Several people were unable to connect. At least one of them was eventually able to connect, but two others were not.

The behaviour we observed was that the SDM would briefly show that it had connected, the WeDo blue light would not come on, and then the SDM would show it was not connected - the SDM would also sometimes show the step where it wants you to open scratch & add an extension (when Scratch was already opened) - within quick succession. 

The step where you should open scratch & add an extension
<img width="301" alt="screen shot 2017-06-16 at 4 43 36 pm" src="https://user-images.githubusercontent.com/1320456/27244091-0301bd22-52b3-11e7-8caf-10f7c414a7c3.png">

### Steps to Reproduce

Unclear. 

### Operating System and Browser

_We were all looking at https://ericrosenbaum.github.io/scratch-gui/ via Chrome, Mac._

**Comment by cwillisf** [comment]
If you're able to get this to happen again, please check for messages in the JS console window of the browser running the editor. My current suspicion is that this is a CORS problem, related to editing the SDM config file, but seeing the console output should confirm/reject that.

**Comment by cwillisf** [comment]
Also, I just filed LLK/scratch-device-manager#76 since I think CORS issues will continue to grow in importance as we continue work on Scratch 3.0
