### ISSUE TITLE
can it support react-native?

### ISSUE THREAD

**Issue by jiangbo2015** [LLK/scratch-vm#625]
### Expected Behavior

work well when use in react-native

### Actual Behavior
can't resoleve scratch-vm
![image](http://www.jiangbobo.cn/bug.png)
You can open this link [https://github.com/jiangbo2015/DD/blob/master/src/img.png](https://github.com/jiangbo2015/DD/blob/master/src/img.png)
 

### Steps to Reproduce

**use it in react-native, if I don't use vm in reducers/gui.js, that work well**
```
const {combineReducers} = require('redux');

module.exports = combineReducers({
    modals: require('./modals'),
    monitors: require('./monitors'),
    targets: require('./targets'),
    // vm: require('./vm')
});
```
### Operating System and Browser
Windows10, react-native[last]

**Comment by rschamp** [comment]
@jiangbo2015 It looks like you're attempting to use `scratch-gui` in React Native?  Would you please re-post the image in "Actual Behavior"? It looks like GitHub lost it, so I can't tell what the error is.  While we aren't explicitly supporting React Native, we're interested in knowing what issues there are right now.

**Comment by jiangbo2015** [comment]
**Yes, thanks for your comments. I want to use scratch-gui in React Native**
**But, React Native can't resoleve scratch-gui, because RN not run on browser environment**

**Comment by rschamp** [comment]
For now, scratch-gui will not be supporting React Native and is intended for a browser environment. If there are places in scratch-gui where we could improve compatibility with React Native without changing the functionality, please make suggestions and/or pull requests on the scratch-gui repo.

**Comment by joseeph** [comment]
could we just include vm&scratch-blocks in UIwebview
