### ISSUE TITLE
Sounds selected by reporter should be 1-indexed

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#627]
### Expected Behavior

When you select a sound in the "play sound" or "play sound until done" block by dropping a reporter onto the menu, it should treat the sprite's sounds a 1-indexed list, and wrap-clamp appropriately.

This bug is similar to https://github.com/LLK/scratch-vm/issues/626.

### Actual Behavior

The sounds are selected using 0-indexing.

### Steps to Reproduce

Create a sprite with two or more sounds. This code should play the first sound:

<img width="171" alt="screen shot 2017-06-27 at 11 28 09 am" src="https://user-images.githubusercontent.com/567844/27595848-ceabdd7e-5b2b-11e7-80a1-0a77033ea4b1.png">

Instead it plays the second sound in the list.

### Operating System and Browser

Mac OS 10.11.6 Chrome 59.0

**Comment by paulkaplan** [comment]
@ericrosenbaum do you think this should be done for the sound playtest milestone?
