### ISSUE TITLE
Loaded Project's have broken variable assignments

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#638]
### Expected Behavior

Loading an existing project in Scratch 3 should have working variable assignment blocks.

### Actual Behavior

Existing variable assignments [set (var) = "value"] do not assign their values, whereas newly created ones, and duplicated versions (of the bad ones) do work.

### Steps to Reproduce

> Load a project: https://llk.github.io/scratch-gui/#168754184
> Make the two variables visible (if they are not)
> Run the project
Both variables stay at 0 rather than being assigned any values.
> Duplicate the two assignment blocks
> Run the new blocks
Both values are assigned correctly.

### Operating System and Browser

Chrome on windows 10.

**Comment by paulkaplan** [comment]
@marisaleung do you happen to have any ideas about this?

**Comment by paulkaplan** [comment]
This appears to be a bug in the way the VM imports the `VARIABLE` field. Looking at the block representation in the vm playground, the imported block has a variable field with value as the name.
![image](https://user-images.githubusercontent.com/654102/28269273-7a0510c0-6acf-11e7-9eba-97d2f52ff475.png)

The block representation of a newly added block looks like this 
![image](https://user-images.githubusercontent.com/654102/28269336-a9af04fc-6acf-11e7-95f5-a3498f2602f0.png)

**Comment by paulkaplan** [comment]
And there is another problem: when you click the checkbox, the monitor that is created is not associated with the variable. It creates a new variable.

**Comment by jwzimmer-zz** [comment]
There still seems to be a bug here, where the variable-setting blocks in an imported project don't work properly (Chrome 60, Mac OS El Capitan, GUI).

**To repro:**
- Load 147710357 in the GUI editor
- Check the monitors in Data so the variables are displayed on the stage
- Add a stack that changes the value of one of the variables, effect1, to 10 in the backdrop scripting area
- Click the main stack on the cat sprite to start it
- Note that even though there's a block in there to reset the value of effect1 to 0, the monitor stays at 10
- Note that if you add a new "set effect1 block to 0" to that stack, the value will reset to 0
- Play the project in 2.0
- Note that the values of the variables are frequently changed by the main stack
- Play the project in 3.0
- Note that the values of the variables don't change

<img width="1280" alt="screen shot 2017-08-23 at 10 51 08 am" src="https://user-images.githubusercontent.com/1320456/29629284-4a80ca0c-8806-11e7-96b7-589df4dac89f.png">
<img width="1280" alt="screen shot 2017-08-23 at 10 50 37 am" src="https://user-images.githubusercontent.com/1320456/29629283-4a80b1de-8806-11e7-9294-36949dd4d2fa.png">
<img width="1280" alt="screen shot 2017-08-23 at 10 50 22 am" src="https://user-images.githubusercontent.com/1320456/29629282-4a7edf08-8806-11e7-8e10-f5197576edf3.png">

![out](https://user-images.githubusercontent.com/1320456/29628756-612c2000-8804-11e7-8602-c94f4a880171.gif)



Discussed with @paulkaplan.

**Comment by paulkaplan** [comment]
@jwzimmer can you try your repro case on develop again to make sure this is still a problem?

**Comment by paulkaplan** [comment]
I tried following the instructions for your repro case but in the 4th step (activate the main cat sprite) the monitors do in fact update. I believe this was fixed by a vm change that was previously "recreating" local variables as global variables when you switched sprites.

**Comment by jwzimmer-zz** [comment]
I duplicated part of the stack from the screenshot and tried to re-create the repro described above, and don't see the described behaviour.  The value of the monitor does seem to update correctly whether I alter the value under another asset or drag stacks into the stack when it's active.
<img width="1274" alt="screen shot 2017-11-01 at 3 41 41 pm" src="https://user-images.githubusercontent.com/1320456/32294021-52cb6662-bf1b-11e7-9d86-d2ca0e7c0656.png">

I could not repro the issue with the original project, either.
