### ISSUE TITLE
Clicking a variable should show it's current value

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#639]
### Expected Behavior

If you single click a variable, a reporter bubble should appear containing its current value.

### Actual Behavior

No value bubble appears (this used to work, but I think may have been lost when the double border around variables was removed?)

### Steps to Reproduce

> Create a variable.
> Assign it a value.
> Place the variable on the scripting area.
> Click the variable once with the mouse.

Nothing happens.

> Place the variable inside a JOIN block and click the join block.

It's value is reported in a bubble.

### Operating System and Browser

Chrome win 10

**Comment by rschamp** [comment]
Tracking in LLK/scratch-gui#519
