### ISSUE TITLE
(Playground) Watchers don't appear

### ISSUE THREAD

**Issue by CatsAreFluffy** [LLK/scratch-vm#661]
### Expected Behavior

Variable watchers work in Scratch GUI ([click](https://llk.github.io/scratch-gui/#170945846) and enable watcher)

### Actual Behavior

But they don't in the playground (add a variable and enable watcher)

### Steps to Reproduce

See above

### Operating System and Browser

Mac OS 10.11.6 Chrome 59

**Comment by thisandagain** [comment]
Variable monitors are implemented in the GUI. You will need to use the GUI to use them.

**Comment by CatsAreFluffy** [comment]
So what does the VM playground use for rendering? An old version of Scratch
GUI?

**Comment by rschamp** [comment]
The VM playground is a bare bones implementation of hooking up the VM to the blocks (scratch-blocks) and the stage (scratch-render). It only exists as a developer tool for building features into the VM before they are exposed to the GUI.  Originally it served as a demonstration of the VM, before the GUI existed.

The GUI provides reusable components that hook up the VM to the renderer, blocks etc. and serves as our recommended way for doing so. The GUI is also where additional features are implemented like monitors, the sprite, costume and sound libraries, sprite, costume and sound pickers (within a project), etc.

**Comment by CatsAreFluffy** [comment]
That makes sense.
