### ISSUE TITLE
Text in costumes from 1.4 SBs converted to SB2s is not loaded

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#672]
(This is related to #128, but is partially specific to 1.4 SBs which were imported to 2.0, then loaded in 3.0.)

### Expected Behavior

The costume's text displays; for example:

![2.0 screenshot](https://user-images.githubusercontent.com/9948030/30006800-80803258-90d7-11e7-99f5-6708963ec556.png)

### Actual Behavior

The costume's text does not display:

![3.0 screenshot](https://user-images.githubusercontent.com/9948030/30006796-7380c2ca-90d7-11e7-8bc4-bc9f3e3b0aec.png)

### Steps to Reproduce

1. Create and upload a 1.4 project that has a costume containing text, and have this project be saved as an SB2 (on the Scratch servers). I've already created [a project](https://scratch.mit.edu/projects/173088631) you can use to test (so you don't need to go through all these steps).
    1. Open Scratch 1.4. Edit (or add) a costume so that [it has a text in it](http://i.cubeupload.com/1URnWF.png).
    2. Save the project (it'll be a `.sb` file).
    3. Import the project into the online Scratch 2.0 editor.
    4. Make a note of the URL, and load the project into Scratch 3.0 (`#<project ID>`).
2. Look at the costume with the text in it. Note that the text doesn't appear.

### Operating System and Browser

Linux / Debian (testing), Firefox 52.2.0.

---

#### 2.0 Implementation

If a costume has a 1.4 text in it, Scratch 2.0 actually gives the costume *two* images: the `baseLayer` and the `textLayer`. That means there's four respective JSON fields:

```
{
  "baseLayerID": <id>,
  "baseLayerMD5": <md5>,
  "textLayerID": <id>,
  "textLayerMD5": <md5>
}
```

In the Scratch 2.0 editor, this makes it act as a vector image. For example, given this 1.4 costume:

![Screenshot of 1.4 paint editor](https://user-images.githubusercontent.com/9948030/30006873-04169b74-90d9-11e7-8dc4-77b6f3794456.png)

..the costume displays as this vector image, in 2.0's costume editor:

![Screenshot of 2.0 vector editor](https://user-images.githubusercontent.com/9948030/30006877-0b802e20-90d9-11e7-85c0-ab620f9de2c2.png)

Note that the text is displayed in Helvetica in the paint editor, but in the actual player it's displayed as it looks in Scratch 1.4:

![Screenshot of entire 2.0 UI, with vector editor open](https://user-images.githubusercontent.com/9948030/30006903-5d786418-90d9-11e7-9865-5baf9bfddc06.png)

However, as soon as it's changed, the player shows it in Helvetica (that is, exactly as it appears in the vector editor):

![Screenshot after changing the content of the text](https://user-images.githubusercontent.com/9948030/30006920-af95fe0e-90d9-11e7-898c-5afcea3c977c.png)

#### Flattening

However, *flattening* the vector image -- that is, clicking on "bitmap editor" -- *without editing it*, converts it to how it looks in 1.4:

![Screenshot after converting the unmodified image to a bitmap](https://user-images.githubusercontent.com/9948030/30006943-2c4a5418-90da-11e7-9888-e665dcbbb5da.png)

Flattening is really just concatenating the base layer and text layer images (as gotten from the project JSON) together.

#### Intended behavior?

Perhaps the image should be flattened as soon as 3.0 sees it, rather than imported as a "pseudo-vector" costume. It's confusing for the image to display as a vector in 2.0, and for the font to change as soon as you edit the text. It's also complex to implement; there'd need to be a separate way of rendering these pseudo-vector costumes, since they're actually two bitmap images. (Rendering two images could also be slower performance-wise?)

I'd argue that flattening the images should be the behavior of 2.0 as well, but scratch-flash is now deprecated/frozen.

This is, of course, only a problem for 1.4 projects which were uploaded to and edited in the 2.0 editor, but those do exist; epninja's projects come to mind. For example, in [Extreme Ninja Parkour](https://scratch.mit.edu/projects/11858411/), the text at the bottom of the first screen is from 1.4 and [does not display in 3.0](https://llk.github.io/scratch-gui/develop/#11858411).

**Comment by thisandagain** [comment]
@towerofnix Thanks for reporting. This is a 1.X edge case that is good to have tracked.

**Comment by towerofnix** [comment]
(Note, mainly to self: I've put a little work into starting a bug fix [here](https://github.com/towerofnix/scratch-vm/tree/old-text-costumes); I can't continue much more without design/implementation discussion, though.)

**Comment by LiFaytheGoblin** [comment]
Also visible in 2327569

**Comment by towerofnix** [comment]
Another case where this is particularly noticeable (e.g. in the buttons at the main menu, and during some slides): https://scratch.mit.edu/projects/257694182/

**Comment by fsih** [comment]
We've decided that since 1.4 projects would have been created so long ago, it's more important to preserve what they looked like than keep them editable, so we agree with your intended behavior of pre-flattening.

That said @towerofnix it looks like you've made really good progress on the fix for this. Would you like to make a pull request for it, and I'll help review it? I can also pick up where you left off if you prefer.

**Comment by towerofnix** [comment]
@fsih I actually made a PR for this a while ago, #915. It was closed due to the codebase not being 110% stable back then (e.g. scratch-svg-renderer was just being made), and it would have taken some fairly significant steps to move forward at the time (e.g. changes to scratch-storage). But since it's been a while it's probably worth re-investigating. The code might be reusable. Definitely should check out the comments and input from @cwillisf and me.

That said, I'm going to be on a vacation for a while through early November, and I won't be able to work on programming for Scratch (or really anything) then, so I probably wouldn't be able to go anywhere very immediately. @cwillisf especially, maybe you could take a look at this and consider what direction to implement this? (And you too fsih, of course!)

PS :jack_o_lantern:

**Comment by fsih** [comment]
Thanks @towerofnix, I will work on this then!
