### ISSUE TITLE
Import Doesn't Display Variable Monitors

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#683]
### Expected Behavior

A visible monitor in a saved Scratch 2 project should remain visible.

### Actual Behavior

It doesn't load.

### Steps to Reproduce

- Make any project with a visible variable monitor in 2.0
- Load said project into 3.0
- Note that the monitor is missing

### Operating System and Browser

Ubuntu 17.03, Chrome 61.0.3163.100

### Cause

The parseScratchObject function doesn't handle the stage monitor object when loading correctly. Specifically:
The stage monitor object looks like:
```
cmd:"getVar:"
color:15629590
isDiscrete:true
label:"test"
mode:1
param:"test"
sliderMax:100
sliderMin:0
target:"Stage"
visible:true
x:5
y:5
```
The parseScratchObject looks for a name, since there is none, it discards the object
Furthermore, it doesn't handle command events, labels, etc.

### Suggested Solution

1. Add a new function 'parseScratchCommand'
2. Before calling parseScratchObject on children, check if child is command, if it is, call parseScratchCommand instead of parseScratchObject.

**Comment by rschamp** [comment]
Thanks for the report and suggested solution @SillyInventor!
