### ISSUE TITLE
Monitors for extension reporters

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-vm#693]
### Expected Behavior

It should be possible to monitor the value of an extension reporter.

### Actual Behavior

It's not possible to monitor the value of an extension reporter.

### Steps to Reproduce

1. Load an extension with at least one reporter.
2. Try to activate a monitor for a reporter provided by that extension.
3. ![can't](http://i0.kym-cdn.com/photos/images/original/000/451/651/823.gif)

**Comment by thisandagain** [comment]
@ericrosenbaum @cwillisf Does this feel like a blocker for you?

**Comment by ericrosenbaum** [comment]
Monitors are helpful for e.g. playing with WeDo sensors etc, but we can definitely run a workshop without them- so, not a blocker.
