### ISSUE TITLE
Extension hat blocks not working

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#705]
### Expected Behavior

Extension blocks that are hats should activate on an edge as expected. 

### Actual Behavior

The Lego WeDo 2.0 extension hats "When distance < 50" and "When tilted any" do not activate.

### Steps to Reproduce

- Load the current extension prototype: https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/
- Add the Lego WeDo extension
- Connect a Lego WeDo (note that this requires an edit to the Scratch Device Manager config file)
- Make a stack such as "when distance < 50, play sound meow" 
- Note that it does not trigger when the distance drops below 50

**Comment by larjohn** [comment]
I am currently building an extension for Raspberry Pi. I  bypassed the still unresolved issues with the GUI and tried remote communcation, somehow like WeDo. So far things go well, except I couldn't make a HAT block work, no matter what I have tried. Here is a very simple extension that I think should have the HAT blocked activated somehow but it doesn't:
```js
let  HatRack = function () {
    
};

HatRack.prototype.getInfo = function () {
    return {
        id: 'hat_rack',
        name: 'hat rack',
        blocks: [
            {
                opcode: 'tipped',
                blockType: Scratch.BlockType.HAT,
                func: "isTipped",
                text: 'hat tipped',
                arguments: {
                    DIRECTION: {
                        type: Scratch.ArgumentType.STRING,
                        defaultValue: "any"
                    }
                }
            },
        ]
    };
};

HatRack.prototype.isTipped = function (args) {
    return Math.random() >= 0.5;
};

Scratch.extensions.register(new HatRack());

```
I can see the isTipped function being polled continuously but nothing else happens - movement blocks under the HAT never execute.
I load this extension by modifying Scratch GUI's extensions/index.js export, like this:
```javascript
...
  {
        name: 'Hat Rack',
        extensionURL: 'http://localhost/rpi/hatrack.js',
        iconURL: musicImage,
        description: 'A common rack for hats.',
        featured: true
   }
...
```
Am I missing something?
