### ISSUE TITLE
Let extensions make non-droppable menus

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-vm#709]
### Expected Behavior

Any Scratch 3.0 block should be possible to build in an extension.

### Actual Behavior

It's currently not possible to make a drop-down menu which cannot be overridden by inserting a reporter. That is, all extension menus currently accept reporters.

Note that another way to fix this would be to make all Scratch 3.0 menus accept reporters...

**Comment by towerofnix** [comment]
>Note that another way to fix this would be to make all Scratch 3.0 menus accept reporters...

Should there be a central issue for this? (Probably in scratch-blocks or scratch-gui.) I've brought up whether or not *all* menus should be droppable several times on various issues; it's a bit of a pain to search through each Scratch repository to find them. (Also, there's no convenient place for anybody to join in on discussion about the topic at the moment.)

**Comment by thisandagain** [comment]
We had a long conversation about this today after a play test. We believe it is important for some blocks to have non-droppable menus to avoid confusion and error states.

**Comment by MegaApuTurkUltra** [comment]
>We had a long conversation about this today after a play test. We believe it is important for some blocks to have non-droppable menus to avoid confusion and error states.

Can this be a feature that advanced users are allowed to disable? It's a pain to manually edit JSON
