### ISSUE TITLE
Custom procedure deletion

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-vm#715]
Deleting a custom procedure should remove it from the VM.

Removing the block from the VM should also remove the corresponding custom command block from the toolbox.

The scratch-blocks work for custom procedure deletion is tracked in https://github.com/LLK/scratch-blocks/issues/1130

**Comment by rachel-fenichel** [comment]
Scratch-blocks will decide whether a procedure can be deleted, and will delete all necessary blocks in the workspace.

Scratch-vm will delete the procedure when its corresponding `procedure_callnoreturn_internal` block is deleted.

**Comment by thisandagain** [comment]
Related to https://github.com/LLK/scratch-blocks/issues/1287

**Comment by paulkaplan** [comment]
No more vm work is needed to support this. Closing.
