### ISSUE TITLE
Custom procedure category in the toolbox

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-vm#717]
In Scratch 2.0:
![image](https://user-images.githubusercontent.com/13686399/31566265-a3e07b84-b01e-11e7-8eb2-a9b28f3c1330.png)

This category contains one custom command block per defined procedure, and a "Make a Block" button.

**Comment by towerofnix** [comment]
Scratch 2.0 doesn't really do any sorting on the list of custom blocks in this category - it tends to be finicky, sometimes putting the most recently dragged block at the top of the list and sometimes seeming to order the list based on the positions of the procedure definitions in the workspace. I recommend sorting this list alphabetically, so it's easy to find the custom block you're looking for just by scrolling to the right letter, like a dictionary.
