### ISSUE TITLE
Missing Scratch.Storage in Playground

### ISSUE THREAD

**Issue by rasmushaglund** [LLK/scratch-vm#719]
### Expected Behavior

It should be possible to run Playground

### Actual Behavior

It's not possible to run Playground because of the javascript error 'Uncaught TypeError: Scratch.Storage is not a constructor'

### Steps to Reproduce

Open Playground in a browser

### Operating System and Browser

61.0.3163.100 (Official Build) (64-bit) on Linux

**Comment by rasmushaglund** [comment]
I think this is an issue related to Webpack. If someone give me a pointer I can try fixing it.

**Comment by msintov** [comment]
I wonder if there a workaround available to get past this issue before it's fixed? Thanks so much in advance for advice.

**Comment by paulkaplan** [comment]
@cwillisf it looks like this is due to the change in https://github.com/LLK/scratch-storage/commit/c1f66ce1322b0b07d8581067055d815ae9c8b3b. Can you look into this?
