### ISSUE TITLE
After renaming a variable on the workspace, exported JSON doesn't reflect blocks on workspace

### ISSUE THREAD

**Issue by msintov** [LLK/scratch-vm#723]
### Expected Behavior

After renaming a variable on the workspace then exporting to JSON, importing that JSON on a new workspace should show the new variable name.

### Actual Behavior

The old variable name shows after importing the JSON.

### Steps to Reproduce

1. Load playground in browser
2. Create new variable "TestVariable"
3. Drag new "TextVariable" oval block as well as "set x to 0" data block to workspace
4. Change variable dropdown in set block to "TestVariable"
5. In set block, select "Rename variable..."
6. In dialog, enter "NewTestVariable" and tap OK
7. Export to JSON
8. Refresh page and import the JSON

Note: Notice that in blocks.js, _getBlockParams receives an undefined block parameter and then a TypeError is encountered in that method: 
TypeError: Cannot read property 'fields' of undefined
    at Blocks._getBlockParams (http://localhost:8073/playground/scratch-vm.js:6376:35)
    at RenderedTarget.renameVariable (http://localhost:8073/playground/scratch-vm.js:31890:44)
    at Blocks.blocklyListen (http://localhost:8073/playground/scratch-vm.js:6074:27)
    at VirtualMachine.blockListener (http://localhost:8073/playground/scratch-vm.js:35526:43)
    at Blockly.WorkspaceSvg.Blockly.Workspace.fireChangeListener (http://localhost:8073/playground/vendor.js:18037:432)
    at Blockly.Events.fireNow_ (http://localhost:8073/playground/vendor.js:18128:467)

### Operating System and Browser

Mac OS 10.11.6 Chrome 61

**Comment by paulkaplan** [comment]
Thanks for this thorough report.

The problem with the `_getBlockParams` not working seems to be caused by the regression of this PR https://github.com/LLK/scratch-blocks/pull/1002 in scratch blocks, which got lost in a merge/refactor shuffle. I'll submit a PR to scratch blocks reimplementing that shortly. (Update: here https://github.com/LLK/scratch-blocks/pull/1182)

The actual import/export problem seems to be an issue with the change event not handling the variable id/name distinction correctly. I'll try to submit a fix for that shortly as well. (Update: issue tracked https://github.com/LLK/scratch-blocks/issues/1183)

**Comment by paulkaplan** [comment]
I'm going to check with the blockly team about the change event problem, it seems to be an upstream bug as well.

**Comment by paulkaplan** [comment]
@msintov Here is a the patch I referred to in the scratch-blocks issue. It fixes the issue and I'll make a PR out of it if the timeline for the upstream fix is long.

```
From 8383d8f90af0724363e379de0eb98f9633d7ee04 Mon Sep 17 00:00:00 2001
From: Paul Kaplan <pkaplan@media.mit.edu>
Date: Wed, 25 Oct 2017 11:16:42 -0400
Subject: [PATCH] Patch behavior of variable rename change event

---
 src/engine/blocks.js | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/src/engine/blocks.js b/src/engine/blocks.js
index f25827b..a70618a 100644
--- a/src/engine/blocks.js
+++ b/src/engine/blocks.js
@@ -226,6 +226,7 @@ class Blocks {
                 id: e.blockId,
                 element: e.element,
                 name: e.name,
+                oldValue: e.oldValue,
                 value: e.newValue
             }, optRuntime);
             break;
@@ -310,6 +311,14 @@ class Blocks {
                 if (variable) {
                     block.fields[args.name].value = variable.name;
                     block.fields[args.name].id = args.value;
+                } else {
+                    // If args.value isn't an ID, this is a change resulting from a rename
+                    // and args.value is the new name and args.oldValue is the id.
+                    const newName = args.value;
+                    const variableId = args.oldValue;
+                    const renamingVariable = optRuntime.getEditingTarget().lookupVariableById(variableId);
+                    block.fields[args.name].value = newName;
+                    block.fields[args.name].id = variableId;
                 }
             } else {
                 block.fields[args.name].value = args.value;
-- 
2.12.0

```

**Comment by msintov** [comment]
@paulkaplan Thank you so much!! I'll try it.
