### ISSUE TITLE
Pen blocks not included in runtime

### ISSUE THREAD

**Issue by regcole** [LLK/scratch-vm#726]
### Expected Behavior

When user uses pen blocks, the pen vm should use the functions as described in `scratch-vm/src/blocks/scratch3_pen.js`

### Actual Behavior

Console error is thrown as op_codes are not wired through any sort of `getPrimitives` method and the `scratch3_pen` is not included as a default package in `runtime.js`
```js
const defaultBlockPackages = {
    scratch3_control: require('../blocks/scratch3_control'),
    scratch3_event: require('../blocks/scratch3_event'),
    scratch3_looks: require('../blocks/scratch3_looks'),
    scratch3_motion: require('../blocks/scratch3_motion'),
    scratch3_operators: require('../blocks/scratch3_operators'),
    scratch3_sound: require('../blocks/scratch3_sound'),
    scratch3_sensing: require('../blocks/scratch3_sensing'),
    scratch3_data: require('../blocks/scratch3_data'),
    scratch3_procedures: require('../blocks/scratch3_procedures')
};
```

### Steps to Reproduce

Use the following blocks:
```
set pen color
set pen size
pen down
move 30 steps
```

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/792
