### ISSUE TITLE
Extension menus are too Bright

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#732]
### Expected Behavior

_They are darker than the outside block_

### Actual Behavior

_They pop out way too much_

### Steps to Reproduce

_Load Pen Extension in Scratch-GUI_

### Operating System and Browser

_Chrome_

### Screenshot
![motion](https://user-images.githubusercontent.com/17478432/32083305-c09f8988-ba8f-11e7-9afa-7786bbfaf89a.PNG)
![extesnion](https://user-images.githubusercontent.com/17478432/32083311-c5d75b88-ba8f-11e7-864a-79257797475b.PNG)

**Comment by cwillisf** [comment]
Tracking in #704.
@TheBrokenRail, I added your extra comparison screenshot over there. Thanks!
