### ISSUE TITLE
Auto-load pen extension

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#734]
### Expected Behavior

Some extensions, including pen and others to come soon, include blocks that were not extensions in Scratch 2.0. We need to detect that a project includes these blocks and load the extension automatically.

(This is distinct from https://github.com/LLK/scratch-vm/issues/692)

### Actual Behavior

The extension is not loaded.

### Steps to Reproduce

Load a pen project from Scratch 2.0 into Scratch 3.0, like this one:

https://scratch.mit.edu/projects/53931894/
https://llk.github.io/scratch-gui/develop/#53931894

**Comment by curlyz** [comment]
Fyi, I ran into this problem and come up with a dirty approach.
Step 1: Scan all the blocks to determine what extension is needed ( eg: 'music')
Step 2: Modify the constructor of ExtensionManager to get that object ( window.ExtensionManager = this; )
Step 3: call this anywhere to add extension : window.ExtensionManager.loadExtensionURL('music')

I hope that someone will come up with a more secure approach.
