### ISSUE TITLE
Naming of "stack", "substack", "thread.stack", etc.

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#74]
Some of these names are not like the other. Notably, the "thread stack" is a very different thing from the "block stack." This naming situation has led to awkward situations, like pushing the stack to the stack.

We couldn't immediately decide on what better name to use (original discussion: https://github.com/LLK/scratch-vm/pull/72/files#r66675817) - continuing the discussion here.

**Comment by rachel-fenichel** [comment]
"substack" -> "branch"?

**Comment by tmickel** [comment]
I actually like the name "branch" quite a bit - especially with the VM metaphor :)

For the record, here are all the option we've mentioned:
1. block stacks and substacks (called this in 2.0)
2. "connected statement input" like blockly
3. "block statement" like JS (loaded terms...)
4. "compound statement"
5. "connected statement"
6. "sequence" and "subsequence"
7. and "branch"

another one we could consider is
8. "strips" and "substrips" like ScratchJr...

**Comment by tmickel** [comment]
@cwillisf @thisandagain Any more thoughts on this? I'm leaning toward "branches."

**Comment by thisandagain** [comment]
👍  for "branches".

**Comment by tmickel** [comment]
Cool - I think it still makes sense to me. Will do that refactor.
