### ISSUE TITLE
Saturation slider sets its position to 0 when hitting 100

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-vm#742]
When setting the saturation slider on a color dropdown to 99, it will jump back to 0, while still saying it's set to 99 or 100 (and the color appearing as such.)

### Expected Behavior

The slider should remain at the right side of the bar, as it is set to 99.

### Actual Behavior

The slider jumps to the left side of the bar, but still is set to and reports 99.

### Steps to Reproduce

* Grab any block with a color dropdown, for example, `touching color []?`.
* Click the color dropdown, and set "Saturation" to 99.
* Close the dropdown and re-open it.

The slider will appear to be set to 0, when it is actually set to 99. It will also sometimes report 100. I don't know if this is related.

### Operating System and Browser

Ubuntu Linux, Firefox 55.0

**Comment by Kenny2github** [comment]
Cannot reproduce on Chrome 61 on Windows 8. Are you using https://llk.github.io/scratch-gui or https://llk.github.io/scratch-gui/develop ? The latter has the most updated changes.

**Comment by towerofnix** [comment]
Yeah, it looks like https://llk.github.io/scratch-gui/ is what you're using, since I can reproduce the bug there. It's been fixed, though, in the develop version @Kenny2github linked.
