### ISSUE TITLE
Travis Deployment Error

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#748]
Hi, I wanted to publish my optimised version of the Scratch-vm to make it easy to compare with the official development release. I followed the steps from https://github.com/LLK/scratch-gui/wiki/Publishing-to-GitHub-Pages, but although my build was successful in travis, it they reported that it failed to deploy:

![image](https://user-images.githubusercontent.com/6737342/32328591-54935088-bfd2-11e7-8f02-e0a00ba28e78.png)

The error appears to be with:
`error: option '-r, --repo <repo>' argument missing`

Any ideas anyone on this?

Thanks,

Griffpatch

**Comment by thisandagain** [comment]
@griffpatch Are you still having trouble with this? We've made a number of changes to the way the VM builds that I hope will help here.
