### ISSUE TITLE
Consider creating a scratch-vm performance benchmark

### ISSUE THREAD

**Issue by boazsender** [LLK/scratch-vm#750]
To help track performance improvement or regressions, a tool that can run a project in a browser and record information from #749 will give us regular recorded information that can be stored and used to compare performance between different versions of the vm, renderer, and gui.

It could be useful to run a project with a renderer but without rendering to test how many steps a second it can perform as a metric.

**Comment by mzgoddard** [comment]
Here is a spreadsheet with some devices I'm testing with and there respective scores in the (deprecated) Google Octane benchmark and (2015) Unity 3D's WebGL benchmark. I'm using these to have a relative handle on the performance of the devices in regards to JavaScript performance and WebGL (and JavaScript) performance.

https://docs.google.com/spreadsheets/d/1Jo3wyZw6l3ey9-FKX87FGgpqPAkz8NCVhmA6zl980xs/edit#gid=0
