### ISSUE TITLE
Rework pushReportedValue for performance

### ISSUE THREAD

**Issue by mzgoddard** [LLK/scratch-vm#781]
### Expected Behavior

Run faster than it does now.

### Actual Behavior

While not itself slow, `Thread.pushReportedValue` is called a lot in Scratch projects so they can return a value to a higher level of the Thread stack. This makes it a prime opportunity to have a large performance gain from a fairly small amount of code distributed in `thread.js` and `execute.js`.

`Thread.pushReportedValue` and related codes and structures can be rewritten to decrease assignments to and reading from computed member expressions (e.g. `currentStackFrame.reported[inputName]`. These aren't slow operations, but it is used frequently enough that using faster operations will provide a measurable bump in performance.

One way this might be replaced would be using a dedicated member on currentStackFrame and assigning to it, and having a argValues object cached here that execute can assign to. If execute can build all the args synchronously it'll be able to build argValues and continue normally. If asynchronous, it can store argValues (kind of like how reported is on the currentStackFrame) and read from the dedicated reporting member next time. The saved time here is from assigning to a known currentStackFrame member that JS vms can speed up compared to computed member assignments. Another simple change is to remove the if statement in `pushReportedValue` by assigning to a fake stack frame if there isn't a parent. Assuming there is always a stack frame and assigning to a dedicated member instead of needing to test first has an opportunity to also provide a boost.

It will still be important to measure and make sure these possible changes and other changes around pushReportedValue actually do so.

### Steps to Reproduce

Measure performance with a performance inspector like Chrome's Performance DevTools tab. pushReportedValue will have a larger presentation as scratch features are used like reading variables, math operators, and other blocks that return values to a higher stack member of the Thread.

**Comment by rschamp** [comment]
Fixed in https://github.com/LLK/scratch-vm/pull/1065
