### ISSUE TITLE
Loudness doesn't work on Firefox

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-vm#796]
### Expected Behavior

Checking and unchecking the loudness monitor shows and hides the monitor.

### Actual Behavior

Checking the loudness monitor gets a console error:

```
TypeError: this.mic.mediaStream is undefined
[Learn More]
lib.min.js:52:12017
value
https://llk.github.io/scratch-gui/develop/lib.min.js:52:12017
value
https://llk.github.io/scratch-gui/develop/lib.min.js:6:228082
value self-hosted:954:17 e
https://llk.github.io/scratch-gui/develop/lib.min.js:6:255200
value
https://llk.github.io/scratch-gui/develop/lib.min.js:6:276417
value
https://llk.github.io/scratch-gui/develop/lib.min.js:6:275579
value
https://llk.github.io/scratch-gui/develop/lib.min.js:6:268969
value/this._steppingInterval<
https://llk.github.io/scratch-gui/develop/lib.min.js:6:273106
TypeError: undefined has no properties
[Learn More]
lib.min.js:52:12017
```

Subsequent unchecking has no effect.

### Operating System and Browser

_e.g. Mac OS 10.12.6 Firefox Quantum 57.0 (64-bit)

**Comment by apple502j** [comment]
Me too. Also Recording Sound is not working.
"needing permission", but I HAVE agreed.
microphone is not broken.
firefox quantu 57.0.3 with win7 home premium 64bit SP1
![Another website is OK](https://screenshots.firefoxusercontent.com/images/41b4b52f-c8f2-4ca5-9bd8-ec54df3861f8.png)

**Comment by towerofnix** [comment]
This issue is older but I made [a more detailed issue](https://github.com/LLK/scratch-audio/issues/67) in scratch-audio a little while ago.

**Comment by ericrosenbaum** [comment]
resolved by https://github.com/LLK/scratch-audio/pull/70
