### ISSUE TITLE
Seems To Glitch

### ISSUE THREAD

**Issue by radioblahaj** [LLK/scratch-vm#812]
### Expected Behavior

To Work Perfectly
_Please describe what should happen_

### Actual Behavior
Glitched While Using, I Was Trying to use it, but it won't let me
_Describe what actually happens_
Glitched when i was using and wasn't working
### Steps to Reproduce
Fix Glitch
_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser
Chrome Os, Chrome
_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
Can you please be more descriptive? Unfortunately, this is not enough information to be useful.
