### ISSUE TITLE
Can't escape from conditional branches that condition contains a promise reporter

### ISSUE THREAD

**Issue by felix2ch** [LLK/scratch-vm#827]
<img width="320" alt="screen shot 2017-11-29 at 9 44 18 am" src="https://user-images.githubusercontent.com/6711220/33353743-4c34b31e-d4ea-11e7-8622-9b2bd0e3eec3.png">

Show as upon image, replace volume with a reporter return promise and let the condition be true, then the if block will execute repeatedly.
If_else block has same behaviour.

As @mrjacobbloom said, It maybe related with #464.

**Comment by felix2ch** [comment]
It looks so like #658

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/688
