### ISSUE TITLE
TypeError: Cannot read property 'isConnected' of null

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#834]
### Actual Behavior

Loading project #176077569 and switching to the "Maze Runner" sprite causes a type error:

![image](https://user-images.githubusercontent.com/1786240/33443166-e674f382-d5c4-11e7-9249-6b453ce9d2a7.png)

### Steps to Reproduce

Load https://llk.github.io/scratch-gui/develop/#176077569
Click on the "Maze Runner" sprite
See error logged in console.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by paulkaplan** [comment]
This is actually a scratch-blocks issue: the block definitions have been commented out, they should be reinstated and then not shown in the toolbox until ready.
