### ISSUE TITLE
Drum and instrument blocks load from sb2 with numbers instead of strings

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#835]
### Expected Behavior

Drum and instrument menus should have a consistent appearance.

### Actual Behavior

The music extension blocks "play drum" and "set instrument" have menus with strings containing the instrument names that looks like this ("strings only"):

<img width="274" alt="screen shot 2017-11-30 at 3 02 29 pm" src="https://user-images.githubusercontent.com/567844/33452242-924a992c-d5df-11e7-8ac9-2b8e4c28daa0.png">

But when you import an SB2 with play drum and play instrument blocks, the blocks look like this ("numbers only"):

<img width="206" alt="screen shot 2017-11-30 at 3 04 47 pm" src="https://user-images.githubusercontent.com/567844/33456423-6304848a-d5ed-11e7-9153-02f7733e036e.png">

In 2.0, "play drum" and "set instrument" blocks are a hybrid type (like the current 3.0 "point in direction" block) like this ("number input with menu"): 

<img width="257" alt="screen shot 2017-11-30 at 4 46 18 pm" src="https://user-images.githubusercontent.com/567844/33456652-04f87df0-d5ee-11e7-9f60-c3916874b105.png">

So what should we do in 3.0?

1) Change the 3.0 blocks to behave like 2.0, using a "number input with menu". This would require creating a new field type for extensions to use I think?

2) Keep the "strings only" style, and convert sb2 blocks to this type on import. Might require a hacky fix.

3) Leave as is: imported sb2 blocks have "number only" inputs, and new blocks have "string only" inputs.

I lean toward #2 but I'm not sure how to implement it. Curious what others think. @carljbowman @thisandagain @cwillisf

**Comment by thisandagain** [comment]
We had talked at some length about trying our best to remove the style of menu from 1 from Scratch. My leaning is towards option 2 as well.
