### ISSUE TITLE
Saved tempo in sb2 is not used

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#837]
### Expected Behavior

When we load an sb2 file, we should load the tempo setting stored in the project. 

It appears that the Stage object in the sb2 has a tempoBPM property. On loading the sb2, we can store this value in the stage, and then the music extension loads, when can check for this property in the stage and set it in the music extension's custom state.

### Actual Behavior

The tempo stored in the project is ignored.

### Steps to Reproduce

This project should play the cowbell at 500 BPM when you press the green flag, but it plays at 60 BPM:

https://llk.github.io/scratch-gui/develop/#190025063

**Comment by ericrosenbaum** [comment]
Notes on this:

There's a related problem for "set instrument", thought tempo is global and instrument is custom state per-sprite.

We will need to load the tempo and instrument from sb2 files, store them in the VM somewhere, and then load them at the time the music extension loads

We also need to consider how to save these properties in SB3.

**Comment by towerofnix** [comment]
>Some options:
>(end of message)

Ah, good!

**Comment by ericrosenbaum** [comment]
oops (fixed)
