### ISSUE TITLE
Make sure "go to front" is a no-op for the stage

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#839]
### Expected Behavior

The "go to front" block should not have any effect when used on the stage.

### Actual Behavior

Right now, the master branch does not have toolbox filtering for the stage, so it still has the "go to front" block. It actually causes the backdrop to go in front of the sprites, which is very confusing.

This is a weird bug that will basically go away for a long time (because we will soon merge the toolbox filtering to master, and there will be no way to use "go to front" on the stage), and then it will re-appear once we have "share the love" or the backpack, which will again make it possible. 

### Steps to Reproduce

- On the [master](https://llk.github.io/scratch-gui/) branch (while you still can!) select the stage
- Add a backdrop
- Click the "go to front" block and see the cat vanish

**Comment by fsih** [comment]
What if we keep this feature but when you do it all the places that say "backdrop" change to "frontdrop"
