### ISSUE TITLE
Sound blocks

### ISSUE THREAD

**Issue by isabela-angelo** [LLK/scratch-vm#843]
Hello!
I was using an old version of VM and some days ago I got errors when trying to play sound blocks. Then I tried to use the latest version and now it is a log warning like "vm warn Could not get implementation for opcode: sound_playdrumforbeats". 

### Expected Behavior
The expected behavior is playing the sound :)

### Actual Behavior

A get this in the console "vm warn Could not get implementation for opcode: sound_playdrumforbeats" for the play drum block.

### Operating System and Browser

Tested in UBUNTU 16.04 and 14.04.
In older versions of VM I don't get errors when using the old versions of firefox in UBUNTU 14.04. 
But in the new version of firefox and in UBUNTU 16.04, I get error when using old version of vm.
In the latest vm it is just this warning in both cases.

**Comment by ericrosenbaum** [comment]
We have moved the music blocks (including play drum, play note, rest, set instrument, set tempo) into an extension. In the GUI, you load it from the extension library (go [here](https://llk.github.io/scratch-gui/develop/) and click on "extensions" at the bottom left). The music extension is auto-loaded when a project is loaded that uses any of the music blocks. Depending on what you're doing, you might be able to directly get the music extension to load on startup by doing something like `vm.extensionManager.loadExtensionURL('music')`.

**Comment by isabela-angelo** [comment]
Hi Eric!
Thanks for the help!
I will try to load the extension on startup.
