### ISSUE TITLE
vm Could not get implementation for opcode: sound_playdrumforbeats

### ISSUE THREAD

**Issue by wenyiweb** [LLK/scratch-vm#846]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by ericrosenbaum** [comment]
Sorry about that- we've moved the music blocks into an extension. Please see my comment here: https://github.com/LLK/scratch-vm/issues/843#issuecomment-349044192

**Comment by wenyiweb** [comment]
thank you,
