### ISSUE TITLE
Can't load saved json file

### ISSUE THREAD

**Issue by felix2ch** [LLK/scratch-vm#847]
I got exception below when open it.

Uncaught (in promise) TypeError: Cannot read property 'shadow' of undefined
    at Blocks.blockToXML (gui.js:20679)
    at Blocks.blockToXML (gui.js:20697)
    at Blocks.blockToXML (gui.js:20693)
    at gui.js:20663
    at Array.map (<anonymous>)
    at Blocks.toXML (gui.js:20662)
    at VirtualMachine.emitWorkspaceUpdate (gui.js:41903)
    at gui.js:41423
    at <anonymous>

[Archive.zip](https://github.com/LLK/scratch-vm/files/1529559/Archive.zip)
Saved json file has broken object link. It is named origin.json.
I open it in editor and fix it manually, then open it successfully.
Manual fixed file is named fixed.json

It contains our custom block, the blocks show as below:
<img width="503" alt="screen shot 2017-12-05 at 10 53 49 am" src="https://user-images.githubusercontent.com/6711220/33588099-0cc557e4-d9ac-11e7-99dc-9d07b4e89eb3.png">

I can not repeat it certainly. 
But it's happen quite frequently.

**Comment by thisandagain** [comment]
Tracking in #194
