### ISSUE TITLE
"Go to" and "glide to" block menus should default to "random position"

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#848]
### Expected Behavior

The "go to" and "glide to" blocks have a menu that includes each other sprite, the mouse pointer, and random position. The default value on the block should be "random position", because that does something visible and different each time you click on it, so it helps people learn by tinkering. 

### Actual Behavior

Currently the menu defaults to "mouse pointer".

**Comment by sjhuang26** [comment]
I agree. I don't see any drawbacks to this change, but it would help beginners learn the mechanics of the block faster.

**Comment by ericrosenbaum** [comment]
Moved to https://github.com/LLK/scratch-gui/issues/1009
