### ISSUE TITLE
"Switch backdrop to" block is missing next and previous items

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#849]
### Expected Behavior

In Scratch 2.0, The block "switch backdrop to" (available to stage and sprites) has a menu that includes the current backdrops, plus "next backdrop" and "previous backdrop":

<img width="265" alt="screen shot 2017-12-05 at 4 27 18 pm" src="https://user-images.githubusercontent.com/567844/33631839-b3f00d0c-d9d9-11e7-97fa-20bb7b1dafa4.png">

### Actual Behavior

The Scratch 3.0 "switch backdrop to" block does not have these menu items.

**Comment by paulkaplan** [comment]
Implemented, with bonus "random backdrop"!
