### ISSUE TITLE
Changing a string variable by 1 assumes the string is zero

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-vm#851]
In Scratch 2.0 if you set a variable to a string then try to change the value by 1 the monitor shows `NaN`.

Currently in Scratch 3.0 it seems to convert the string to 0 and add 1.

**Comment by mrjacobbloom** [comment]
related to https://github.com/LLK/scratch-vm/pull/187#discussion_r79498341 https://github.com/LLK/scratch-vm/wiki/Compatibility

**Comment by chrisgarrity** [comment]
👍 , closing as this is an expected difference from 2.0
