### ISSUE TITLE
How should color sensing work when the sprite is hidden?

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#852]
(Moved to LLK/scratch-render#212)

### Expected (2.0) Behavior

"Touching color" returns true when the sprite overlaps the given color, regardless of whether or not the sprite is hidden. "Touching sprite" returns true if the sprite overlaps the other sprite, *and* the sprite is shown; if it is hidden, "touching sprite" returns false.

### Actual Behavior

"Touching color" returns false when the sprite is hidden. "Touching sprite" behaves as described in 2.0.

### Steps to Reproduce

Demo project: [2.0](https://scratch.mit.edu/projects/191930440/#editor), [3.0](https://llk.github.io/scratch-gui/#191930440). Move the sprite around using the mouse, and use the space bar to toggle the sprite between being shown and hidden. Observe the contents of the speech bubble while dragging.

(Note - in the speech bubble that shows up, you can see that, next to "touching (sprite)", sometimes "undefined" is being said instead of "false".. undefined is a falsey value, so this is okay, but maybe something to look into if it's not already reported somewhere..)

I don't know what the expected behavior is, but I would think that this incompatibility could be a source of issues in platformer projects?

Demo project 2: [2.0](https://scratch.mit.edu/projects/191931857/#editor), [3.0](https://llk.github.io/scratch-gui/#191931857). Notice how, in Scratch 3.0, when you hide the sprite, it falls through the floor! :hole:

### Operating System and Browser

Firefox Nightly (59) on Debian Testing. I'm fairly certain this same bug was reported [here](https://scratch.mit.edu/discuss/topic/285123/).

**Comment by towerofnix** [comment]
Funnily enough this seems in the same vein of Scratch's development as the just-made PR https://github.com/LLK/scratch-render/pull/211 (which I didn't see until now). Ping @paulkaplan since you'll probably have an idea on this?

**Comment by paulkaplan** [comment]
Going to close and reopen this on scratch render. Thanks @towerofnix
