### ISSUE TITLE
Projects with old 1.4 "midiInstrument:" block fail to open

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#861]
### Expected Behavior

Project opens and editor loads. (Behavior for `midiInstrument:` is not 100% certain yet - see LLK/scratch-audio#13.)

### Actual Behavior

Editor crashes, with this error in the console:

```
vm warn Couldn't find SB2 block:  midiInstrument:
```

I recall projects with this block opening at some point in the past? That might be my bad memory, though.

### Steps to Reproduce

Open a project which uses the `midiInstrument:` 1.4 block, such as https://scratch.mit.edu/projects/138256836/ ([3.0](https://llk.github.io/scratch-gui/develop/#138256836)).

### Operating System and Browser

Firefox 58.0, Debian (Testing).

**Comment by apple502j** [comment]
Ok, just edited specmap!

**Comment by apple502j** [comment]
#883
Here. added to specmap.
