### ISSUE TITLE
Scroll Wheel runtime detection is broken

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#865]
### Expected Behavior

Moving the scroll wheel while a project is running should trigger the "when up and down arrow pressed?"
hat blocks (but not the <key up/down pressed?> detection blocks. (See: https://scratch.mit.edu/projects/229142/ or https://llk.github.io/scratch-gui/develop/#193724034).

This functionality was also recently broken in the Scratch 2 (most likely when the keyboard code was changed around to support the edge browser).

### Actual Behavior

The  "when up and down arrow pressed?" hat block does not fire.

### Steps to Reproduce

Fire up this project: https://llk.github.io/scratch-gui/develop/#193724034 and try it out. (I remixed: https://scratch.mit.edu/projects/229142/ as it was a Scratch 1.3 project so doesn't load in scratch 3 yet). 

### Operating System and Browser

Windows PC running Chrome

**Comment by cwillisf** [comment]
Good news: this will be fixed in version 459 and above, which we are planning to release very soon.

Edit: oops, I didn't realize this was in the 3.0 VM repository. Anyway, the Scratch 2.0 bug will be fixed very soon ;)
