### ISSUE TITLE
Empty repeat (for values more than 0) runs forever

### ISSUE THREAD

**Issue by jeandrek** [LLK/scratch-vm#88]
Repeat blocks with values more than zero always run forever, the loopCounter never goes down:
![screenshot from 2016-07-03 19-12-44](https://cloud.githubusercontent.com/assets/13597222/16544234/348d0a90-4152-11e6-9e4d-416d716360cf.png)
My browser / operating system: Linux, Firefox 50.0, Flash 11.2 (release 202)

**Comment by tmickel** [comment]
Specifically seems to be empty loops - thanks for the report.

**Comment by tmickel** [comment]
Now fixed.
