### ISSUE TITLE
Mouse X and mouse Y report incorrect coordinates in full screen mode

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#905]
### Expected Behavior

Mouse X and mouse Y reporters should report consistently across stage modes.

### Actual Behavior

In full screen mode, the mouse x and mouse y values are incorrect.

**Comment by towerofnix** [comment]
This was just yesterday fixed by #889 (which is not in the master/non-develop branch yet).

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-vm/pull/889
