### ISSUE TITLE
Music extension stops playing notes on Safari

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#910]
### Expected Behavior

The music extension should be able to play an unlimited number of drum and instrument sounds.

### Actual Behavior

On Safari, after you've played about 30 sounds, it stops working.

This is due to the concurrency counter never getting decremented, because the audioBufferSourceNode's onended event (usually) does not fire. 

### Steps to Reproduce

- Add the music extension
- This stack works for a a few seconds, then stops playing:

![screen shot 2018-01-22 at 11 31 47 am](https://user-images.githubusercontent.com/567844/35231877-f1804cfa-ff67-11e7-816a-158da4ac681e.png)

### Operating System and Browser

Mac OS 10.13.2 Safari 11.0.2

**Comment by kyleplo** [comment]
I can't recreate this in Chrome on Windows 10.
