### ISSUE TITLE
Should clones be able to start their own copy of a sound?

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#919]
This [PR](https://github.com/LLK/scratch-vm/pull/891), “Audio effects state for clones,” introduced a new behavior that need discussion and possible changes. 

It is related to the behavior of a clone starting a sound when another clone or the parent sprite has already started that same sound. In 2.0, the sound restarts. After the above PR, a new copy of the sound starts playing (with the clone's effects settings applied). 

Example:
If you have a sprite with the sound "happy song", and you run "forever [start sound happy song]", it will restart the sound every frame, creating a stuttering sound. This is true in both 2.0 and 3.0. However, in 3.0, if you create a bunch of clones, and run "when I start as a clone [start happy song]", the clones will all separately start their own copy of the song. 

Upside: you can make music using clones that play the same sound at overlapping times with different audio effect settings (pitch, pan, volume). 

Downside: you get a potentially very loud sound instead of a stuttering sound if you make a lot of clones that play a sound simultaneously.

We should consider how often this downside case would occur in existing projects, if possible.

**Comment by CatsAreFluffy** [comment]
I'd say that the old behavior is less intuitive, since why would all clones share one speaker?

**Comment by thisandagain** [comment]
Discussed! @ericrosenbaum will follow-up with changes. :-)
