### ISSUE TITLE
Regression introduced in SB2 Minecraft project

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#924]
### Expected Behavior

Running project #10128407 should start the character off on the ground. This is working correctly in preview.scratch.mit.edu but not working in the current state of develop.

### Actual Behavior

Character starts off in the sky and falls to the ground. 
This is a recently introduced regression by [this commit](https://github.com/LLK/scratch-vm/commit/6b7582f1c70ce4f90a0ca5eb986d96771414d86b).

There are no errors reported in the console, so not exactly sure what the problem is or what is causing it.

### Steps to Reproduce

1. [Load project #10128407 in Scratch 3.0](https://llk.github.io/scratch-gui/develop/#10128407).
2. Click the green flag to start the project, start the game via the menu (click 'New Game', followed by 'Done' on the next screen).
3. Observe that the game starts to load (on the ground), but then a loading screen similar to the following image pops up. The character then starts off in the sky and falls to the ground (in most cases immediately dying).

![image](https://user-images.githubusercontent.com/1786240/35593527-1fdd71f0-05de-11e8-8b7a-30d4cf7a1816.png)

4. Try steps 1-3 on preview.scratch.mit.edu, and observe that the same thing does not happen.

**Comment by kchadha** [comment]
cc @mzgoddard

**Comment by kchadha** [comment]
This project has a regression as well that might be related.
Compare:
[Correct Behavior] https://preview.scratch.mit.edu/#10761768
vs.
[Broken Behavior] https://llk.github.io/scratch-gui/develop/#10761768

**Comment by kchadha** [comment]
Also this?

[Correct behavior] https://preview.scratch.mit.edu/#56667360
vs.
[Broken behavior] https://llk.github.io/scratch-gui/develop/#56667360

**Comment by kchadha** [comment]
[Correct Behavior] https://preview.scratch.mit.edu/#21554369
vs.
[Broken Behavior] https://llk.github.io/scratch-gui/develop/#21554369

**Comment by thisandagain** [comment]
Pushing to March milestone for when @mzgoddard returns. :-)

**Comment by kchadha** [comment]
The push reported work, including the commit that seems to be causing this regression, was reverted in #928. Tracking this issue in #929.
