### ISSUE TITLE
Green Flag seems to clear out sound effects

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#927]
### Expected Behavior

Pressing the green flag should not clear out existing sound effects. 

### Actual Behavior

It does (example below).

### Steps to Reproduce

1. Open a new project in 3.0
2. Drag out a `play sound (Meow v) until done` block and click to execute it.
3. Drag out a `set volume to (100) %` block, and change the input to `10`. Enable the monitor for the volume reporter.
4. Click on the `set volume to (10) %` block. Observe that the volume monitor reads `10`.
5. Click on the `play sound (Meow v) until done` block again. Observe that the volume did, in fact reduce.
6. Now place the `play sound (Meow v) until done` block under a `when <green flag> clicked` hat.
7. Click the green flag and observe that the sound seems to be playing at 100% even though the volume monitor still reads `10`.
8. Placing the `set volume to (10) %` block under a green flag hat and clicking the green flag should have the expected behavior of playing the sound at 10% volume.

Similar results can be observed with the `pitch` and `pan left/right` effects as well.

### Operating System and Browser

macOS 10.13.2, Chrome Version 64.0.3282.119 (Official Build) (64-bit)

**Comment by kchadha** [comment]
Related question that should perhaps be a separate issue. Should setting the volume to 10% and then clearing sound effects result in the volume reporter re-setting its value to 100?

**Comment by mrjacobbloom** [comment]
They should probably parallel the graphic effects? (Limited) discussion of when to clear graphic effects happened in #139 and LLK/scratch-gui#198

**Comment by kchadha** [comment]
In Scratch 2.0, both the green flag button and the stop button clear out graphic effects, but the same is not true for sound effects like volume and tempo. The behavior described above is an inconsistency between Scratch 2.0 and 3.0.

**Comment by ericrosenbaum** [comment]
Closing this because we agreed that all that's necessary is the change here: https://github.com/LLK/scratch-audio/issues/75
