### ISSUE TITLE
SB2 with sprite called "Stage" loads blocks with menus showing "_stage_"

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#932]
### Expected Behavior

It's possible to have a sprite called "Stage" in Scratch 2.0. Projects that use blocks that refer to this sprite in a menu should display its name correctly as "Stage."

### Actual Behavior

In an SB2 with a sprite called "Stage", the blocks with menus referring to it load displaying its name as `_stage_`:

![screen shot 2018-02-12 at 3 51 27 pm](https://user-images.githubusercontent.com/567844/36118978-b706fc94-100c-11e8-85c8-cd802033c962.png)

### Operating System and Browser

Mac OS 10.13.2 Chrome 64.0

**Comment by picklesrus** [comment]
I'm not sure where along the way this got fixed... but it is.

![screen shot 2018-12-20 at 1 23 34 pm](https://user-images.githubusercontent.com/15675877/50303310-b3b40d00-045a-11e9-848b-af94d712c163.png)
![screen shot 2018-12-20 at 1 23 14 pm](https://user-images.githubusercontent.com/15675877/50303341-cc242780-045a-11e9-9447-fb29f3506fbb.png)
