### ISSUE TITLE
Not on npm?

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-vm#95]
![screen shot 2016-07-14 at 5 22 30 pm](https://cloud.githubusercontent.com/assets/10731781/16856354/af2d47ae-49e7-11e6-91fc-88782d24abcd.png)

**Comment by tmickel** [comment]
Correct - the project is a major work in progress :) We'll probably add it once we have more features implemented.

**Comment by CosmicWebServices** [comment]
OK!

**Comment by thisandagain** [comment]
I updated the `README.md` instructions to reflect the proper path for installing the VM until it is released.
