### ISSUE TITLE
Implement doForLoop block

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-vm#959]
### Expected Behavior

As [per](https://scratch.mit.edu/users/thisandagain/#comments-43174070) @thisandagain, the "doForLoop" block should be implemented.

!["The "doForLoop" will probably continue to be supported."](https://user-images.githubusercontent.com/9948030/36974659-cadd8890-204d-11e8-9134-9b6c238f01c1.png)

### Actual Behavior

There is no code to handle how the for loop block.

### Steps to Reproduce

Load a project that has the doForLoop block. Note that, in 2.0, doForLoop is an obsolete block; it cannot be found in the block palette. The only projects which use them are "hacked" projects (that is, their JSON has been modified to include doForLoop). However, the block does exist and function (mostly) as expected.

(I'd make an example project, but Flash isn't running well on my computer lately!)

---

[Here is the relevant code in scatch-flash.](https://github.com/LLK/scratch-flash/blob/9fbac92ef3d09ceca0c0782f8a08deaa79e4df69/src/interpreter/Interpreter.as#L503-L540) The main takeaway points:

* If listArg is a string, and `Number(listArg)` is not NaN, then treat listArg as if it is a number (per below). (Test case: passing "join [1] [2]", a string, to doForLoop should behave the same way as passing (10 + 2), a number.)
* If listArg is a number (or the above case), use the range from 1 to listArg (inclusive) as the list. (For example, if listArg is 5, list is [1, 2, 3, 4, 5]).
* doForLoop otherwise works exactly like a normal "for" loop: On each tick, set the value of the passed loop variable to the item of the list at the current index and increment the index by one, then run the substack.

This will probably also take implementation in the -gui and -blocks repositories.

**Comment by thisandagain** [comment]
Related to https://github.com/LLK/scratch-vm/issues/355
