### ISSUE TITLE
External extensions HAT blocks not running

### ISSUE THREAD

**Issue by larjohn** [LLK/scratch-vm#970]
### Expected Behavior

As reported [here](https://github.com/LLK/scratch-vm/issues/705#issuecomment-371179733), I have created a sample extension:
```js
let  HatRack = function () {
    
};

HatRack.prototype.getInfo = function () {
    return {
        id: 'hat_rack',
        name: 'hat rack',
        blocks: [
            {
                opcode: 'tipped',
                blockType: Scratch.BlockType.HAT,
                func: "isTipped",
                text: 'hat tipped',
                arguments: {
                    DIRECTION: {
                        type: Scratch.ArgumentType.STRING,
                        defaultValue: "any"
                    }
                }
            },
        ]
    };
};

HatRack.prototype.isTipped = function (args) {
    return Math.random() >= 0.5;
};

Scratch.extensions.register(new HatRack());

```

I would expect, that as `true` and `false` alternate, the commands below the HAT block would execute.

### Actual Behavior

No commands execute.

### Steps to Reproduce

1. Load the provided extension
2. Place the 'hat tipped' HAT block into the scene
3. Place a movemnt command under the 'hat tipped' block
4. See if anything moves

### Operating System and Browser

Windows 10, Chrome 65 beta

### Context
I tried to debug the code behind loading and executing the extension and its blocks. I am not really aware what each thing does there, but I can make the following remarks:
Plain extensions like mine, are loaded in a different way than the WeDo extension. The loading process creates a worker that is then used to determine for each block if it is a 'remote' service block.
This leads to replacing the function name with a function returning a promise, instead of returning the block function itself. The promise is resolved but the thread state is not updated to RUNNING. 
```js
else if (thread.status === Thread.STATUS_PROMISE_WAIT) {
                    // A promise was returned by the primitive. Yield the thread
                    // until the promise resolves. Promise resolution should reset
                    // thread.status to Thread.STATUS_RUNNING.
                    return;
                }
```

I tried to manually update the thread state to RUNNING just after the promise resolution, but this did not work:

```js
 primitiveReportedValue.then(function (resolvedValue) {
            handleReport(resolvedValue, sequencer, thread, currentBlockId, opcode, isHat);
            thread.status = Thread.STATUS_RUNNING;
```
I am not really sure how to make the execution check the thread again and let it continue with the rest of the commands below. Any ideas?

**Comment by thisandagain** [comment]
Hi @larjohn, the extension worker stuff isn't quite finished yet so running into some issues is to be expected. In the short-term I recommend forking the VM and integrating your extension as "internal" until we are ready to share our full plans for 3rd party extensions later this year.
