### ISSUE TITLE
In Say, decimal shows where param is number (not string)

### ISSUE THREAD

**Issue by maxiostro** [LLK/scratch-vm#971]
Simple, when I use Say(text) it works. With Say(1) it works too. But when the input is a real number, not a number to string, it adds two decimal to the number.s

**Comment by towerofnix** [comment]
This is a duplicate of #960, which has a PR fixing it (#965).

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-vm/pull/965

**Comment by thisandagain** [comment]
(Thanks @towerofnix !)
