### ISSUE TITLE
Creating clones of sprites is different with strings and integers

### ISSUE THREAD

**Issue by 77Tigers** [LLK/scratch-vm#974]
## Expected Behavior
_**Create clone of (pick random (1) to (1))**_
should be the same as:
_**Create clone of (join (1) ())**_

## Actual Behavior

Opposite of above.

## Steps to Reproduce
Run the above code in a sprite named 1. Only one will create a clone.
Here's a demo project:
https://scratch.mit.edu/projects/209226817/#editor
https://llk.github.io/scratch-gui/develop/#209226817

## Operating System and Browser

Windows NT 10.0, Chrome 64.0.3282.186

**Comment by Clark-E** [comment]
To add images, just drag and drop an image into the issue text editor. Github will automatically create an image.

**Comment by 77Tigers** [comment]
Thanks!
