### ISSUE TITLE
Translation extension feature request: add viewer's language

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-vm#983]
Here is my beautiful mspaint mock:
![image](https://user-images.githubusercontent.com/2855464/37532082-63850af4-2914-11e8-80c7-2f46cc501dcc.png)

For instance, if you made a game with a "start" button, you could put "translate to viewer's language" around it, and then people from France would see the word "start" in French, and more people would be able to enjoy your game.

It might be hard for people to understand what this option did, since it wouldn't look like it does anything...

**Comment by ericrosenbaum** [comment]
We added a reporter block for the viewer's language, which can be dropped into the language menu, in https://github.com/LLK/scratch-vm/pull/1178
