### ISSUE TITLE
Translation extension feature request: Bring my default language to top

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-vm#984]
The translate extension would be a bit easier to use if my language were at the top of the list, since it's pretty likely that I'll pick my language. Maybe it could be at 2 places in the list, the top and where it should be alphabetically.

So if my language is set to Russian on the Scratch website, Russian would appear at the top of the translate list, instead of me having to scroll to the bottom to select it.

**Comment by ericrosenbaum** [comment]
We made the viewer's language the default value for the menu, but leave it in its current location in the list. I think this addresses the concern well enough.
