### ISSUE TITLE
Translation extension: order when translated?

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-vm#985]
If the translate block is translated, what order will the languages appear in? If they're in the English order that could be a really weird order in another language.
The native alphabet of the language? What if the language doesn't have an alphabet, like Chinese?

**Comment by ericrosenbaum** [comment]
@fsih here's how it currently looks in Chinese (language code zh). Does this seem okay?

Top of the list:
![screen shot 2018-05-30 at 2 23 25 pm](https://user-images.githubusercontent.com/567844/40739842-3b3dcd06-6415-11e8-8faa-07c83449bfa5.png)

Bottom of the list (with the word for "Chinese" selected):
![screen shot 2018-05-30 at 2 23 31 pm](https://user-images.githubusercontent.com/567844/40739854-444ebbee-6415-11e8-80ab-59875c8b108c.png)

**Comment by fsih** [comment]
I don't really have a sense of what order would feel right. Maybe try asking Tracy?

**Comment by ericrosenbaum** [comment]
At @fsih's suggestion, I was able to visually compare our list of languages in japanese to the list provided by google translate in japanese (at https://translate.google.co.jp/). The first letters were in the same order in each- so far so good!

update: I checked chinese the same way, and it also matches.

update: hebrew and russian also look fine, so I'm going to close this issue.
