### ISSUE TITLE
Translation extension feature request: line wrapping?

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-vm#986]
It seems reasonably likely that you will want to translate a long message, and in that case the block becomes really unwieldy. It's hard to move without accidentally deleting and hard to read all of, and the tooltip that shows what the result was can be offscreen.

![image](https://user-images.githubusercontent.com/2855464/37533482-5889a214-2918-11e8-83d9-48dbe0af41a7.png)
![image](https://user-images.githubusercontent.com/2855464/37533553-8c8f85a6-2918-11e8-9474-b14ac552b1a5.png)

**Comment by towerofnix** [comment]
Potentially related to LLK/scratch-blocks#400 and LLK/observations#34 (though that's a private issue so I don't know how much discussion has gone on there).

**Comment by thisandagain** [comment]
Tracking feature request in LLK/scratch-blocks#400
