### ISSUE TITLE
Translate extension: block image should not be from other website

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#989]
### Expected Behavior
src/extensions/scratch3_translate/index.js
Line 7,8 should be internal links
### Actual Behavior
external links
### Steps to Reproduce
see source code
### Operating System and Browser
Firefox 59.0.1 Windows 7 Home Premium 64bit sp1

**Comment by thisandagain** [comment]
Those icons are temporary (as per the comment above). We will move them into the repo when the final icons are designed.
