### ISSUE TITLE
Many individual blocks fail to glow when clicked

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#993]
### Expected Behavior

When you click on an individual block, it should glow at least for a single frame.

### Actual Behavior

Many individual blocks do not glow when clicked.

Note that it's not clear to me whether reporters and hats should have this behavior, but it's inconsistent among those as well, i.e. there are some reporters and some hats that do glow when clicked individually.

Here are the blocks that do not glow when clicked:

- x position
- y position
- direction
- costume number
- backdrop number
- size
- play sound until done (see also https://github.com/LLK/scratch-audio/issues/19)
- volume
- when green flag clicked
- when space clicked
- when this sprite clicked
- when backdrop switches
- when I receive message1
- when I start as a clone
- answer
- mouse down?
- mouse x
- mouse y
- loudness
- timer
- current year
- days since 2000
- and
- or
- not
- variable reporter
- list reporter
- length of list
- custom block

**Comment by tmickel** [comment]
I suggest addressing this by reworking/rewriting the "stack glow" logic :) Currently it's pretty overcomplicated and clearly misses cases -- IIRC a result of going through a few different iterations.......
