### ISSUE TITLE
Translate Extension Bug: the API should support CORS

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#998]
### Expected Behavior
https://translate-service.scratch.mit.edu
should support CORS (Access-Control-Allow-Origin)
### Actual Behavior
Not so, so we cannot use it now
### Steps to Reproduce
open https://llk.github.io/scratch-gui/extensions/
### Operating System and Browser
windows 7 64bit sp1 HomePremium
Firefox 59.0.1

**Comment by thisandagain** [comment]
I'm confused. The server does support CORS:
https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Ftranslate-service.scratch.mit.edu%2Fsupported%2F&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

Can you please clarify what errors you are seeing in the cosole? Testing in Chrome and Firefox latest.
